[tools] perf scripts python: exported-sql-viewer.py: Fix error when shrinking / enlarging font
Message-id: <20191110211921.28070-92-mpetlan@redhat.com>
Patchwork-id: 285095
O-Subject: [RHEL8.2 BZ1743208 091/158] perf scripts python: exported-sql-viewer.py: Fix error when shrinking / enlarging font
Bugzilla: 1743208
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1743208
https://bugzilla.redhat.com/show_bug.cgi?id=1743208

upstream
========
commit 4b2084537e5f3b58337bce894391fb63bf3b0e28
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Fri May 3 15:08:23 2019 +0300

description
===========
Fix the following error if shrink / enlarge font is used with the help
window.

  Traceback (most recent call last):
    File "tools/perf/scripts/python/exported-sql-viewer.py", line 2791, in ShrinkFont
      ShrinkFont(win.view)
  AttributeError: 'HelpWindow' object has no attribute 'view'

Committer testing:

Before, matches above output:

  $ python ~acme/libexec/perf-core/scripts/python/exported-sql-viewer.py ~/c/adrian.hunter/simple-retpoline.db
  Traceback (most recent call last):
    File "/home/acme/libexec/perf-core/scripts/python/exported-sql-viewer.py", line 2780, in EnlargeFont
      EnlargeFont(win.view)
  AttributeError: 'HelpWindow' object has no attribute 'view'
  $

After:

No more tracebacks, but the fonts don't get enlarged, which is kinda
frustrating...

Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>