[platform] platform/x86: intel_pmc_core: avoid unused-function warnings
Message-id: <20200915163536.136845-22-darcari@redhat.com>
Patchwork-id: 326420
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1783140 21/21] platform/x86: intel_pmc_core: avoid unused-function warnings
Bugzilla: 1783140
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1783140

commit 01f259f3720c3965443109d82a0f12611ea8bb58
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Apr 28 23:36:38 2020 +0200

    platform/x86: intel_pmc_core: avoid unused-function warnings

    When both CONFIG_DEBUG_FS and CONFIG_PM_SLEEP are disabled, the
    functions that got moved out of the #ifdef section now cause
    a warning:

    drivers/platform/x86/intel_pmc_core.c:654:13: error: 'pmc_core_lpm_display' defined but not used [-Werror=unused-function]
      654 | static void pmc_core_lpm_display(struct pmc_dev *pmcdev, struct device *dev,
          |             ^~~~~~~~~~~~~~~~~~~~
    drivers/platform/x86/intel_pmc_core.c:617:13: error: 'pmc_core_slps0_display' defined but not used [-Werror=unused-function]
      617 | static void pmc_core_slps0_display(struct pmc_dev *pmcdev, struct device *dev,
          |             ^~~~~~~~~~~~~~~~~~~~~~

    Rather than add even more #ifdefs here, remove them entirely and
    let the compiler work it out, it can actually get rid of all the
    debugfs calls without problems as long as the struct member is
    there.

    The two PM functions just need a __maybe_unused annotations to avoid
    another warning instead of the #ifdef.

    Fixes: aae43c2bcdc1 ("platform/x86: intel_pmc_core: Relocate pmc_core_*_display() to outside of CONFIG_DEBUG_FS")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>

Signed-off-by: David Arcari <darcari@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>