[netdrv] net: aquantia: fix undefined devm_hwmon_device_register_with_info reference
Message-id: <1558707223-29275-54-git-send-email-irusskik@redhat.com>
Patchwork-id: 260745
O-Subject: [RHEL8.1 BZ 1706905 53/53] net: aquantia: fix undefined devm_hwmon_device_register_with_info reference
Bugzilla: 1706905
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1706905

commit 70610c922bae2f3f974eef955ef254defb7755ce
Author: Kefeng Wang <wangkefeng.wang@huawei.com>
Date:   Thu May 9 23:32:35 2019 +0800

    net: aquantia: fix undefined devm_hwmon_device_register_with_info reference

    drivers/net/ethernet/aquantia/atlantic/aq_drvinfo.o: In function `aq_drvinfo_init':
    aq_drvinfo.c:(.text+0xe8): undefined reference to `devm_hwmon_device_register_with_info'

    Fix it by using #if IS_REACHABLE(CONFIG_HWMON).

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Signed-off-by: Kefeng Wang <wangkefeng.wang@huawei.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>