[tools] perf cs-etm: Add missing case value
Message-id: <20191104222454.10863-295-mpetlan@redhat.com>
Patchwork-id: 282936
O-Subject: [RHEL8.2 BZ1715508 294/327] perf cs-etm: Add missing case value
Bugzilla: 1715508
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715508
https://bugzilla.redhat.com/show_bug.cgi?id=1715508

upstream
========
commit c8fa7a807f3c5f946bd92076fbaf7826edb650dc
Author: Solomon Tan <solomonbobstoner@gmail.com>
Date: Fri Mar 22 13:22:55 2019 +0800

description
===========
The following error was thrown when compiling `tools/perf` using OpenCSD
v0.11.1. This patch fixes said error.

    CC       util/intel-pt-decoder/intel-pt-log.o
    CC       util/cs-etm-decoder/cs-etm-decoder.o
  util/cs-etm-decoder/cs-etm-decoder.c: In function
  cs_etm_decoder__buffer_range:
  util/cs-etm-decoder/cs-etm-decoder.c:370:2: error: enumeration value
  OCSD_INSTR_WFI_WFE not handled in switch [-Werror=switch-enum]
    switch (elem->last_i_type) {
    ^~~~~~
    CC       util/intel-pt-decoder/intel-pt-decoder.o
  cc1: all warnings being treated as errors

Because `OCSD_INSTR_WFI_WFE` case was added only in v0.11.0, the minimum
required OpenCSD library version for this patch is no longer v0.10.0.

Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>