[tools] perf diff: Use llabs() with 64-bit values
Message-id: <20200514101858.720-264-mpetlan@redhat.com>
Patchwork-id: 307827
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 263/300] perf diff: Use llabs() with 64-bit values
Bugzilla: 1818838
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1818838
https://bugzilla.redhat.com/show_bug.cgi?id=1818838

upstream
========
commit 2b1ac6403f8800babed0f16ab1d29ee3300be122
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Nov 27 09:58:22 2019 -0300

description
===========
To fix this build error on a debian mipsel cross build environment:

  builtin-diff.c: In function 'compute_cycles_diff':
  builtin-diff.c:649:10: error: absolute value function 'labs' given an argument of type 's64' {aka 'long long int'} but has parameter of type 'long int' which may cause truncation of value [-Werror=absolute-value]
    649 |    val = labs(pair->block_info->cycles_spark[i] -
        |          ^~~~

Fixes: cebf7d51a6c3 ("perf diff: Report noisy for cycles diff")
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>