wireless/nl80211: fix wdev_id may be used uninitialized
Bugzilla: http://bugzilla.redhat.com/1937053

commit 239729a21e528466d02f5558936306ffa9314ad1
Author: Jarod Wilson <jarod@redhat.com>
Date:   Fri Mar 12 11:36:51 2021 -0500

    wireless/nl80211: fix wdev_id may be used uninitialized

    Build currently fails with -Werror=maybe-uninitialized set:

    net/wireless/nl80211.c: In function '__cfg80211_wdev_from_attrs':
    net/wireless/nl80211.c:124:44: error: 'wdev_id' may be used
    uninitialized in this function [-Werror=maybe-uninitialized]

    Easy fix is to just initialize wdev_id to 0, since it's value doesn't
    otherwise matter unless have_wdev_id is true.

    Fixes: a05829a7222e ("cfg80211: avoid holding the RTNL when calling the driver")
    CC: Johannes Berg <johannes@sipsolutions.net>
    CC: "David S. Miller" <davem@davemloft.net>
    CC: Jakub Kicinski <kuba@kernel.org>
    CC: linux-wireless@vger.kernel.org
    CC: netdev@vger.kernel.org
    Signed-off-by: Jarod Wilson <jarod@redhat.com>
    Link: https://lore.kernel.org/r/20210312163651.1398207-1-jarod@redhat.com
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>

Signed-off-by: Jarod Wilson <jarod@redhat.com>