[x86] x86/boot: Fix cmdline_find_option() prototype visibility
Message-id: <20190724030321.7638-20-bhe@redhat.com>
Patchwork-id: 267145
O-Subject: [RHEL8.1 PATCH v2 19/27] x86/boot: Fix cmdline_find_option() prototype visibility
Bugzilla: 1564822
RH-Acked-by: Kairui Song <kasong@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1564822
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=22757594
Upstream: Merged in linus's tree.
Test: Passed on my kvm guest.

This is back ported from upstream directly, no conflict.

commit 82f9ed3a93307089242ff8a5c694e82c8c93f522
Author: Borislav Petkov <bp@suse.de>
Date:   Tue Feb 5 12:05:45 2019 +0100

    x86/boot: Fix cmdline_find_option() prototype visibility

      ac09c5f43cf6 ("x86/boot: Build the command line parsing code unconditionally")

    enabled building the command line parsing code unconditionally but it
    forgot to remove the respective ifdeffery around the prototypes in the
    misc.h header, leading to

      arch/x86/boot/compressed/acpi.c: In function ‘get_acpi_rsdp’:
      arch/x86/boot/compressed/acpi.c:37:8: warning: implicit declaration of function \
              ‘cmdline_find_option’ [-Wimplicit-function-declaration]
        ret = cmdline_find_option("acpi_rsdp", val, MAX_ADDR_LEN);
              ^~~~~~~~~~~~~~~~~~~

    for configs where neither CONFIG_EARLY_PRINTK nor CONFIG_RANDOMIZE_BASE
    was defined.

    Drop the ifdeffery in the header too.

    Fixes: ac09c5f43cf6 ("x86/boot: Build the command line parsing code unconditionally")
    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: Chao Fan <fanc.fnst@cn.fujitsu.com>
    Cc: x86@kernel.org
    Link: https://lkml.kernel.org/r/5c51daf0.83pQEkvDZILqoSYW%lkp@intel.com
    Link: https://lkml.kernel.org/r/20190205131352.GA27396@zn.tnic

Signed-off-by: Baoquan He <bhe@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>