[tools] selftests: use LDLIBS for libraries instead of LDFLAGS
Message-id: <20201119094111.1486275-22-haliu@redhat.com>
Patchwork-id: 340126
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net 22/27] selftests: use LDLIBS for libraries instead of LDFLAGS
Bugzilla: 1898813
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Andrea Claudi <aclaudi@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1898813
Upstream Status: net.git commit 3e8393630e92

commit 3e8393630e928767aeb23f4744518de4ea5cc35a
Author: Dmitry Safonov <dima@arista.com>
Date:   Wed Feb 12 14:00:40 2020 +0000

    selftests: use LDLIBS for libraries instead of LDFLAGS

    While building selftests, the following errors were observed:
    > tools/testing/selftests/timens'
    > gcc -Wall -Werror -pthread  -lrt -ldl  timens.c  -o tools/testing/selftests/timens/timens
    > /usr/bin/ld: /tmp/ccGy5CST.o: in function `check_config_posix_timers':
    > timens.c:(.text+0x65a): undefined reference to `timer_create'
    > collect2: error: ld returned 1 exit status

    Quoting commit 870f193d48c2 ("selftests: net: use LDLIBS instead of
    LDFLAGS"):

    The default Makefile rule looks like:

    $(CC) $(CFLAGS) $(LDFLAGS) $@ $^ $(LDLIBS)

    When linking is done by gcc itself, no issue, but when it needs to be passed
    to proper ld, only LDLIBS follows and then ld cannot know what libs to link
    with.

    More detail:
    https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

    LDFLAGS
    Extra flags to give to compilers when they are supposed to invoke the linker,
    ‘ld’, such as -L. Libraries (-lfoo) should be added to the LDLIBS variable
    instead.

    LDLIBS
    Library flags or names given to compilers when they are supposed to invoke the
    linker, ‘ld’. LOADLIBES is a deprecated (but still supported) alternative to
    LDLIBS. Non-library linker flags, such as -L, should go in the LDFLAGS
    variable.

    While at here, correct other selftests, not only timens ones.

    Reported-by: Shuah Khan <skhan@linuxfoundation.org>
    Signed-off-by: Dmitry Safonov <dima@arista.com>
    Tested-by: Shuah Khan <skhan@linuxfoundation.org>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>