[net] sched: taprio: fix build without 64bit div
Message-id: <20190610212005.12299-170-ivecera@redhat.com>
Patchwork-id: 264157
O-Subject: [RHEL-8.1 net PATCH 169/194] net/sched: taprio: fix build without 64bit div
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 23bddf692d369c6415d570f16ae40d9165eaaa9a
Author: Jakub Kicinski <jakub.kicinski@netronome.com>
Date:   Wed Apr 17 13:51:57 2019 -0700

    net/sched: taprio: fix build without 64bit div

    Recent changes to taprio did not use the correct div64 helpers,
    leading to:

    net/sched/sch_taprio.o: In function `taprio_dequeue':
    sch_taprio.c:(.text+0x34a): undefined reference to `__divdi3'
    net/sched/sch_taprio.o: In function `advance_sched':
    sch_taprio.c:(.text+0xa0b): undefined reference to `__divdi3'
    net/sched/sch_taprio.o: In function `taprio_init':
    sch_taprio.c:(.text+0x1450): undefined reference to `__divdi3'
    /home/jkicinski/devel/linux/Makefile:1032: recipe for target 'vmlinux' failed

    Use math64 helpers.

    Fixes: 7b9eba7ba0c1 ("net/sched: taprio: fix picos_per_byte miscalculation")
    Signed-off-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Reviewed-by: Dirk van der Merwe <dirk.vandermerwe@netronome.com>
    Acked-by: Vinicius Costa Gomes <vinicius.gomes@intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>