[net] bpf: Fix build in minimal configurations, again
Message-id: <20200529062245.152030-208-yauheni.kaliuta@redhat.com>
Patchwork-id: 315420
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 208/235] bpf: Fix build in minimal configurations, again
Bugzilla: 1813370
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813370

commit 4c80c7bc583a87ded5f61906f81256b57c795806
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Dec 10 21:35:46 2019 +0100

    bpf: Fix build in minimal configurations, again

    Building with -Werror showed another failure:

    kernel/bpf/btf.c: In function 'btf_get_prog_ctx_type.isra.31':
    kernel/bpf/btf.c:3508:63: error: array subscript 0 is above array bounds of 'u8[0]' {aka 'unsigned char[0]'} [-Werror=array-bounds]
      ctx_type = btf_type_member(conv_struct) + bpf_ctx_convert_map[prog_type] * 2;

    I don't actually understand why the array is empty, but a similar
    fix has addressed a related problem, so I suppose we can do the
    same thing here.

    Fixes: ce27709b8162 ("bpf: Fix build in minimal configurations")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Martin KaFai Lau <kafai@fb.com>
    Link: https://lore.kernel.org/bpf/20191210203553.2941035-1-arnd@arndb.de

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>