[tools] perf scripts python: export-to-postgresql.py: Fix invalid input syntax for integer error
Message-id: <20191104222454.10863-208-mpetlan@redhat.com>
Patchwork-id: 282850
O-Subject: [RHEL8.2 BZ1715508 207/327] perf scripts python: export-to-postgresql.py: Fix invalid input syntax for integer error
Bugzilla: 1715508
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715508
https://bugzilla.redhat.com/show_bug.cgi?id=1715508

upstream
========
commit 07c5ebead85f507271fb8e2a8b5814e486702518
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Thu Feb 28 15:00:26 2019 +0200

description
===========
Fix SQL query error "invalid input syntax for integer":

  Traceback (most recent call last):
    File "tools/perf/scripts/python/export-to-postgresql.py", line 465, in <module>
      do_query(query, 'CREATE VIEW calls_view AS '
    File "tools/perf/scripts/python/export-to-postgresql.py", line 274, in do_query
      raise Exception("Query failed: " + q.lastError().text())
  Exception: Query failed: ERROR:  invalid input syntax for integer: ""
  LINE 1: ...ch_count,call_id,return_id,CASE WHEN flags=0 THEN '' WHEN fl...
                                                               ^
  (22P02) QPSQL: Unable to create query
  Error running python script tools/perf/scripts/python/export-to-postgresql.py

Fixes: f08046cb3082 ("perf thread-stack: Represent jmps to the start of a different symbol")
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>