[scsi] scsi: qla2xxx: Fix compilation issue in PPC systems
Message-id: <20201209070031.29153-6-njavali@redhat.com>
Patchwork-id: 343672
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 BZ 1905493 05/14] scsi: qla2xxx: Fix compilation issue in PPC systems
Bugzilla: 1905493
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1905493

Tree: git://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git

commit 6589b2ca6a538c6f5b9eb7792930327b44181ed5
Author: Arun Easi <aeasi@marvell.com>
Date:   Wed Dec 2 05:23:03 2020 -0800

    scsi: qla2xxx: Fix compilation issue in PPC systems

    Fix compile time errors reported on PPC systems,

    qla_gbl.h:991:20: error: inlining failed in call to always_inline
         ‘qla_nvme_abort_set_option’: function body not available

    Link: https://lore.kernel.org/r/20201202132312.19966-7-njavali@marvell.com
    Signed-off-by: Arun Easi <aeasi@marvell.com>
    Signed-off-by: Nilesh Javali <njavali@marvell.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Cc: Nilesh Javali <njavali@redhat.com>
Cc: Arun Easi <aeasi@redhat.com>
Cc: "Ewan D. Milne" <emilne@redhat.com>
Signed-off-by: Nilesh Javali <njavali@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>