[mm] x86/init: fix build with CONFIG_SWAP=n
Message-id: <20200619015957.14656-1-longman@redhat.com>
Patchwork-id: 320659
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH] x86/init: fix build with CONFIG_SWAP=n
Bugzilla: 1839415
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>
RH-Acked-by: Aristeu Rozanski <aris@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1839415
BuildInfo: https://brewweb.devel.redhat.com/taskinfo?taskID=29507148

commit 792adb90fa724ce07c0171cbc96b9215af4b1045
Author: Vlastimil Babka <vbabka@suse.cz>
Date:   Tue, 14 Aug 2018 20:50:47 +0200

    x86/init: fix build with CONFIG_SWAP=n

    The introduction of generic_max_swapfile_size and arch-specific versions has
    broken linking on x86 with CONFIG_SWAP=n due to undefined reference to
    'generic_max_swapfile_size'. Fix it by compiling the x86-specific
    max_swapfile_size() only with CONFIG_SWAP=y.

    Reported-by: Tomas Pruzina <pruzinat@gmail.com>
    Fixes: 377eeaa8e11f ("x86/speculation/l1tf: Limit swap file size to MAX_PA/2")
    Signed-off-by: Vlastimil Babka <vbabka@suse.cz>
    Cc: stable@vger.kernel.org
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>