ASoC: soc-component: fix undefined reference to __ffssi2
microblaze-linux-gcc (GCC) 9.3.0 complains about missing __ffssi2
symbol while using __builtin_ffs at runtime.

This is because arch/h8300 is compiled with -fno-builtin option.

so fallback and use kernel ffs() instead to all the arch builds happy!

    Fixes: 1da0b9899abd ("ASoC: soc-component: add snd_soc_component_read/write_field()")
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
    Link: https://lore.kernel.org/r/20210129100539.23459-1-srinivas.kandagatla@linaro.org
    Signed-off-by: Mark Brown <broonie@kernel.org>

Author: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Date: Fri Jan 29 10:05:39 2021 +0000

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 8ac9e476b86851c94e0f33bea758e0a00e3f875e)
Bugzilla: https://bugzilla.redhat.com/1917388