[include] raid6/test: fix a compilation error
Message-id: <1585655207-3634-16-git-send-email-bhsharma@redhat.com>
Patchwork-id: 298818
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH v2 RESEND 15/15] raid6/test: fix a compilation error
Bugzilla: 1817524
RH-Acked-by: Jeremy Linton <jlinton@redhat.com>
RH-Acked-by: Mark Salter <msalter@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1817524
Upstream Status: 6b8651aac1dca6140dd7fb4c9fec2736ed3f6223
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27567118
Tested: On 'cav-thunderx2s-cn88xx' machine
Conflicts: None

commit 6b8651aac1dca6140dd7fb4c9fec2736ed3f6223
Author: Zhengyuan Liu <liuzhengyuan@kylinos.cn>
Date:   Fri Dec 20 10:21:26 2019 +0800

    raid6/test: fix a compilation error

    The compilation error is redeclaration showed as following:

            In file included from ../../../include/linux/limits.h:6,
                             from /usr/include/x86_64-linux-gnu/bits/local_lim.h:38,
                             from /usr/include/x86_64-linux-gnu/bits/posix1_lim.h:161,
                             from /usr/include/limits.h:183,
                             from /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed/limits.h:194,
                             from /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed/syslimits.h:7,
                             from /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed/limits.h:34,
                             from ../../../include/linux/raid/pq.h:30,
                             from algos.c:14:
            ../../../include/linux/types.h:114:15: error: conflicting types for ‘int64_t’
             typedef s64   int64_t;
                           ^~~~~~~
            In file included from /usr/include/stdint.h:34,
                             from /usr/lib/gcc/x86_64-linux-gnu/8/include/stdint.h:9,
                             from /usr/include/inttypes.h:27,
                             from ../../../include/linux/raid/pq.h:29,
                             from algos.c:14:
            /usr/include/x86_64-linux-gnu/bits/stdint-intn.h:27:19: note: previous \
            declaration of ‘int64_t’ was here
             typedef __int64_t int64_t;

    Fixes: 54d50897d544 ("linux/kernel.h: split *_MAX and *_MIN macros into <linux/limits.h>")
    Signed-off-by: Zhengyuan Liu <liuzhengyuan@kylinos.cn>
    Signed-off-by: Song Liu <songliubraving@fb.com>
    (cherry picked from commit 6b8651aac1dca6140dd7fb4c9fec2736ed3f6223)

Signed-off-by: Bhupesh Sharma <bhsharma@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>