[sound] ALSA: ASoC: SOF: nocodec: fix undefined reference
Message-id: <15693081207948942-280-patchset-jkysela@redhat.com>
Patchwork-id: 273391
O-Subject: [RHEL 8.2 PATCH 0279/1298] ALSA: ASoC: SOF: nocodec: fix undefined reference
Bugzilla: 1738610
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

The nocodec option can be selected individually, leading to the following
issue:

sound/soc/sof/core.o: In function `snd_sof_device_probe':
core.c:(.text+0x4af): undefined reference to `sof_nocodec_setup'

Fix by selecting the SND_SOF_NOCODEC option as needed.

Reported-by: Hulk Robot <hulkci@huawei.com>
Reported-by: YueHaibing <yuehaibing@huawei.com>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 8d01c3c73cefbb5bacffe804427daed3e6051435)
Bugzilla: 1738610
Signed-off-by: Phillip Lougher <plougher@redhat.com>