[tools] perf metric: Add cache_miss_cycles to metric parse test
Message-id: <20201214095352.11924-135-mpetlan@redhat.com>
Patchwork-id: 344349
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 134/248] perf metric: Add cache_miss_cycles to metric parse test
Bugzilla: 1811839 1731571 1838555 1838896 1873271
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1873271
https://bugzilla.redhat.com/show_bug.cgi?id=1873271

upstream
========
commit 55f30d68397df7d67367a0643d9dea7cbbcda061
Author: Jiri Olsa <jolsa@kernel.org>
Date: Sun Jul 19 20:13:14 2020 +0200

description
===========
Adding test that compute metric with other metrics in it.

  cache_miss_cycles = metric:dcache_miss_cpi + metric:icache_miss_cycles

Committer notes:

Fixed up initializer to cope with:

  tests/parse-metric.c:242:7: error: missing field 'val' initializer [-Werror,-Wmissing-field-initializers]
                  { 0 },

Signed-off-by: Michael Petlan <mpetlan@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>