[netdrv] net/mlx5e: Fix build break when CONFIG_XPS is not set
Message-id: <20201209085358.12844-27-ahleihel@redhat.com>
Patchwork-id: 343732
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1858561 v2 026/180] net/mlx5e: Fix build break when CONFIG_XPS is not set
Bugzilla: 1858561
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1858561
Upstream: v5.9-rc1
Conflicts:
 - drivers/net/ethernet/mellanox/mlx5/core/en_accel/ktls_rx.c
   Diff due to temporarly dropped patch:
   76c1e1ac2aae ("net/mlx5e: kTLS, Add kTLS RX stats")

commit 8b5ec43d73dbdb427651caac5b76610ec0f5f298
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Tue Jul 14 18:54:46 2020 -0700

    net/mlx5e: Fix build break when CONFIG_XPS is not set

    mlx5e_accel_sk_get_rxq is only used in ktls_rx.c file which already
    depends on XPS to be compiled, move it from the generic en_accel.h
    header to be local in ktls_rx.c, to fix the below build break

    In file included from
    ../drivers/net/ethernet/mellanox/mlx5/core/en_main.c:49:0:
    ../drivers/net/ethernet/mellanox/mlx5/core/en_accel/en_accel.h:
    In function ‘mlx5e_accel_sk_get_rxq’:
    ../drivers/net/ethernet/mellanox/mlx5/core/en_accel/en_accel.h:153:12:
    error: implicit declaration of function ‘sk_rx_queue_get’ ...
      int rxq = sk_rx_queue_get(sk);
                ^~~~~~~~~~~~~~~

    Fixes: 1182f3659357 ("net/mlx5e: kTLS, Add kTLS RX HW offload support")
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>