[tools] perf tools: Fix maps__find_symbol_by_name()
Message-id: <46ae9ed2459a0e2460c82a347160b59908aa11bd.1558604935.git.mpetlan@redhat.com>
Patchwork-id: 259879
O-Subject: [RHEL8.1 BZ1709242 174/190] perf tools: Fix maps__find_symbol_by_name()
Bugzilla: 1709242
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1709242
https://bugzilla.redhat.com/show_bug.cgi?id=1709242

upstream
========
commit 03db8b583d1c3c84963e08e2abf6c79081da5c31
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Fri Sep 7 11:51:16 2018 +0300

description
===========
Commit 1c5aae7710bb ("perf machine: Create maps for x86 PTI entry
trampolines") revealed a problem with maps__find_symbol_by_name() that
resulted in probes not being found e.g.

	$ sudo perf probe xsk_mmap
	xsk_mmap is out of .text, skip it.
	Probe point 'xsk_mmap' not found.
	   Error: Failed to add events.

maps__find_symbol_by_name() can optionally return the map of the found
symbol. It can get the map wrong because, in fact, the symbol is found
on the map's dso, not allowing for the possibility that the dso has more
than one map. Fix by always checking the map contains the symbol.

Fixes: 1c5aae7710bb ("perf machine: Create maps for x86 PTI entry trampolines")
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>