[netdrv] mlxsw: spectrum_flower: Forbid to offload mirred redirect on egress
Message-id: <20200601180237.4179948-4-ivecera@redhat.com>
Patchwork-id: 315778
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 PATCH 003/290] mlxsw: spectrum_flower: Forbid to offload mirred redirect on egress
Bugzilla: 1821646
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1821646

Upstream commit(s):
commit 185556f092491120ea2bd7eab6f9f78ff6c4d6d0
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Sat Jul 27 20:32:55 2019 +0300

    mlxsw: spectrum_flower: Forbid to offload mirred redirect on egress

    Spectrum ASIC does not support redirection on egress, so refuse to
    insert such flows:

    $ tc qdisc add dev ens16np1 clsact
    $ tc filter add dev ens16np1 egress protocol all pref 1 handle 101 flower skip_sw action mirred egress redirect dev ens16np2
    Error: mlxsw_spectrum: Redirect action is not supported on egress.

    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>