[tools] tools lib api fs: Fix gcc9 stringop-truncation compilation error
Message-id: <20200522095131.24335-21-mpetlan@redhat.com>
Patchwork-id: 313652
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 20/98] tools lib api fs: Fix gcc9 stringop-truncation compilation error
Bugzilla: 1818841
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1818841
https://bugzilla.redhat.com/show_bug.cgi?id=1818841

upstream
========
commit 6794200fa3c9c3e6759dae099145f23e4310f4f7
Author: Andrey Zhizhikin <andrey.z@gmail.com>
Date: Wed Dec 11 08:01:09 2019 +0000

description
===========
GCC9 introduced string hardening mechanisms, which exhibits the error
during fs api compilation:

error: '__builtin_strncpy' specified bound 4096 equals destination size
[-Werror=stringop-truncation]

This comes when the length of copy passed to strncpy is is equal to
destination size, which could potentially lead to buffer overflow.

There is a need to mitigate this potential issue by limiting the size of
destination by 1 and explicitly terminate the destination with NULL.

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>