[fs] ceph: quota: fix null pointer dereference in quota check
Message-id: <20191108140453.73236-53-jlayton@redhat.com>
Patchwork-id: 284351
O-Subject: [BZ#1767959 RHEL8.2 PATCH 052/264] ceph: quota: fix null pointer dereference in quota check
Bugzilla: 1767959
RH-Acked-by: Zheng Yan <zyan@redhat.com>
RH-Acked-by: Ilya Dryomov <idryomov@redhat.com>

From: Luis Henriques <lhenriques@suse.com>

This patch fixes a possible null pointer dereference in
check_quota_exceeded, detected by the static checker smatch, with the
following warning:

fs/ceph/quota.c:240 check_quota_exceeded()
error: we previously assumed 'realm' could be null (see line 188)

Fixes: b7a2921765cf ("ceph: quota: support for ceph.quota.max_files")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Luis Henriques <lhenriques@suse.com>
Reviewed-by: "Yan, Zheng" <zyan@redhat.com>
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit 71f2cc64d027d712f29bf8d09d3e123302d5f245)
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>