[uapi] iommu/virtio: Fix sparse warning
Message-id: <20210116012107.726851-136-jsnitsel@redhat.com>
Patchwork-id: 349542
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 135/449] iommu/virtio: Fix sparse warning
Bugzilla: 1887546
RH-Acked-by: Mark Salter <msalter@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1887546
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=34307190

commit 3f84b96c9779c8c2c8f4215a9d08cc6af1d45fdb
Author: Jean-Philippe Brucker <jean-philippe@linaro.org>
Date:   Thu Mar 26 10:35:56 2020 +0100

    iommu/virtio: Fix sparse warning

    We copied the virtio_iommu_config from the virtio-iommu specification,
    which declares the fields using little-endian annotations (for example
    le32). Unfortunately this causes sparse to warn about comparison between
    little- and cpu-endian, because of the typecheck() in virtio_cread():

    drivers/iommu/virtio-iommu.c:1024:9: sparse: sparse: incompatible types in comparison expression (different base types):
    drivers/iommu/virtio-iommu.c:1024:9: sparse:    restricted __le64 *
    drivers/iommu/virtio-iommu.c:1024:9: sparse:    unsigned long long *
    drivers/iommu/virtio-iommu.c:1036:9: sparse: sparse: incompatible types in comparison expression (different base types):
    drivers/iommu/virtio-iommu.c:1036:9: sparse:    restricted __le64 *
    drivers/iommu/virtio-iommu.c:1036:9: sparse:    unsigned long long *
    drivers/iommu/virtio-iommu.c:1040:9: sparse: sparse: incompatible types in comparison expression (different base types):
    drivers/iommu/virtio-iommu.c:1040:9: sparse:    restricted __le64 *
    drivers/iommu/virtio-iommu.c:1040:9: sparse:    unsigned long long *
    drivers/iommu/virtio-iommu.c:1044:9: sparse: sparse: incompatible types in comparison expression (different base types):
    drivers/iommu/virtio-iommu.c:1044:9: sparse:    restricted __le32 *
    drivers/iommu/virtio-iommu.c:1044:9: sparse:    unsigned int *
    drivers/iommu/virtio-iommu.c:1048:9: sparse: sparse: incompatible types in comparison expression (different base types):
    drivers/iommu/virtio-iommu.c:1048:9: sparse:    restricted __le32 *
    drivers/iommu/virtio-iommu.c:1048:9: sparse:    unsigned int *
    drivers/iommu/virtio-iommu.c:1052:9: sparse: sparse: incompatible types in comparison expression (different base types):
    drivers/iommu/virtio-iommu.c:1052:9: sparse:    restricted __le32 *
    drivers/iommu/virtio-iommu.c:1052:9: sparse:    unsigned int *

    Although virtio_cread() does convert virtio-endian (in our case
    little-endian) to cpu-endian, the typecheck() needs the two arguments to
    have the same endianness. Do as UAPI headers of other virtio devices do,
    and remove the endian annotation from the device config.

    Even though we change the UAPI this shouldn't cause any regression since
    QEMU, the existing implementation of virtio-iommu that uses this header,
    already removes the annotations when importing headers.

    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Jean-Philippe Brucker <jean-philippe@linaro.org>
    Link: https://lore.kernel.org/r/20200326093558.2641019-2-jean-philippe@linaro.org
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit 3f84b96c9779c8c2c8f4215a9d08cc6af1d45fdb)
Cc: Myron Stowe <myron.stowe@redhat.com>
Cc: Alex Williamson <alex.williamson@redhat.com>
Cc: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>