[powerpc] powerpc/test_emulate_sstep: Fix build error
Message-id: <20201109235448.21980-2-drosario@redhat.com>
Patchwork-id: 338683
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 BZ1883975 PATCH 1/2] powerpc/test_emulate_sstep: Fix build error
Bugzilla: 1883975
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

BUGZILLA: https://bugzilla.redhat.com/show_bug.cgi?id=1883975
UPSTREAM STATUS: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=70cc062c47e7851335ff4c44ba9b362174baf7d4
BUILD INFO: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=32982881

DESCRIPTION
commit 70cc062c47e7851335ff4c44ba9b362174baf7d4
Author: Michael Ellerman <mpe@ellerman.id.au>
Date: Fri, 24 Jul 2020 09:02:26 +1000

    ppc64_book3e_allmodconfig fails with:

      arch/powerpc/lib/test_emulate_step.c: In function 'test_pld':
      arch/powerpc/lib/test_emulate_step.c:113:7: error: implicit declaration of function 'cpu_has_feature'
        113 |  if (!cpu_has_feature(CPU_FTR_ARCH_31)) {
            |       ^~~~~~~~~~~~~~~

    Add an include of cpu_has_feature.h to fix it.

    Fixes: b6b54b42722a ("powerpc/sstep: Add tests for prefixed integer load/stores")
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20200724004109.1461709-1-mpe@ellerman.id.au
    (cherry picked from commit 70cc062c47e7851335ff4c44ba9b362174baf7d4)

Signed-off-by: Desnes A. Nunes do Rosario <drosario@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>