[tools] perf tests: Factor check_parse_id function
Message-id: <20201214095352.11924-46-mpetlan@redhat.com>
Patchwork-id: 344266
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 045/248] perf tests: Factor check_parse_id function
Bugzilla: 1811839 1731571 1838555 1838896 1873271
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1873271
https://bugzilla.redhat.com/show_bug.cgi?id=1873271

upstream
========
commit 34bacc9578de2893ab6301cea89ea001d8e4cf5b
Author: Jiri Olsa <jolsa@kernel.org>
Date: Tue Jun 2 23:47:31 2020 +0200

description
===========
Separating the generic part of check_parse_id function,
so it can be used in following changes for the new test.

Committer notes:

Fix this error:

  tests/pmu-events.c:413:40: error: missing field 'idx' initializer [-Werror,-Wmissing-field-initializers]
        struct parse_events_error error = { 0 };

Signed-off-by: Michael Petlan <mpetlan@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>