[x86] x86/purgatory: Fail the build if purgatory.ro has missing symbols
Message-id: <20200729075116.10882-7-lijiang@redhat.com>
Patchwork-id: 322953
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 6/7] x86/purgatory: Fail the build if purgatory.ro has missing symbols
Bugzilla: 1857528
RH-Acked-by: Pingfan Liu <piliu@redhat.com>
RH-Acked-by: Baoquan He <bhe@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1857528
Brew build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=30336198
Tested machine: intel-wildcatpass-06.khw.lab.eng.bos.redhat.com
Conflicts: None

commit e4160b2e4b02377c67f8ecd05786811598f39acd
Author: Hans de Goede <hdegoede@redhat.com>
Date:   Tue Mar 17 14:08:41 2020 +0100

    x86/purgatory: Fail the build if purgatory.ro has missing symbols

    Linking purgatory.ro with -r enables "incremental linking"; this means
    no checks for unresolved symbols are done while linking purgatory.ro.

    A change to the sha256 code has caused the purgatory in 5.4-rc1 to have
    a missing symbol on memzero_explicit(), yet things still happily build.

    Add an extra check for unresolved symbols by calling ld without -r
    before running bin2c to generate kexec-purgatory.c.

    This causes a build of 5.4-rc1 with this patch added to fail as it should:

        CHK     arch/x86/purgatory/purgatory.ro
      ld: arch/x86/purgatory/purgatory.ro: in function `sha256_transform':
      sha256.c:(.text+0x1c0c): undefined reference to `memzero_explicit'
      make[2]: *** [arch/x86/purgatory/Makefile:72:
          arch/x86/purgatory/kexec-purgatory.c] Error 1
      make[1]: *** [scripts/Makefile.build:509: arch/x86/purgatory] Error 2
      make: *** [Makefile:1650: arch/x86] Error 2

    Also remove --no-undefined from LDFLAGS_purgatory.ro as that has no
    effect.

    Signed-off-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Link: https://lkml.kernel.org/r/20200317130841.290418-2-hdegoede@redhat.com

Signed-off-by: Lianbo Jiang <lijiang@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>