[tools] bpf: Use local copy of headers including uapi/linux/filter.h
Message-id: <b7cc76e3e9a790ae40a3ef256c06855a0a7f49ee.1608036136.git.jbenc@redhat.com>
Patchwork-id: 344716
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net 02/90] tools: bpf: Use local copy of headers including uapi/linux/filter.h
Bugzilla: 1882709
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Eelco Chaudron <echaudro@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1882709

commit f143c11bb7b924403ea2d5b5c990717772293620
Author: Will Deacon <will@kernel.org>
Date:   Thu Nov 21 12:41:40 2019 +0000

    tools: bpf: Use local copy of headers including uapi/linux/filter.h

    Pulling header files directly out of the kernel sources for inclusion in
    userspace programs is highly error prone, not least because it bypasses
    the kbuild infrastructure entirely and so may end up referencing other
    header files that have not been generated.

    Subsequent patches will cause compiler.h to pull in the ungenerated
    asm/rwonce.h file via filter.h, breaking the build for tools/bpf:

      | $ make -C tools/bpf
      | make: Entering directory '/linux/tools/bpf'
      |   CC       bpf_jit_disasm.o
      |   LINK     bpf_jit_disasm
      |   CC       bpf_dbg.o
      | In file included from /linux/include/uapi/linux/filter.h:9,
      |                  from /linux/tools/bpf/bpf_dbg.c:41:
      | /linux/include/linux/compiler.h:247:10: fatal error: asm/rwonce.h: No such file or directory
      |  #include <asm/rwonce.h>
      |           ^~~~~~~~~~~~~~
      | compilation terminated.
      | make: *** [Makefile:61: bpf_dbg.o] Error 1
      | make: Leaving directory '/linux/tools/bpf'

    Take a copy of the installed version of linux/filter.h  (i.e. the one
    created by the 'headers_install' target) into tools/include/uapi/linux/
    and adjust the BPF tool Makefile to reference the local include
    directories instead of those in the main source tree.

    Cc: Masahiro Yamada <yamada.masahiro@socionext.com>
    Acked-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Alexei Starovoitov <ast@kernel.org>
    Suggested-by: Daniel Borkmann <daniel@iogearbox.net>
    Reported-by: Xiao Yang <ice_yangxiao@163.com>
    Signed-off-by: Will Deacon <will@kernel.org>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>