ath11k: fix undefined reference to 'ath11k_debugfs_htt_ext_stats_handler'
Bugzilla: http://bugzilla.redhat.com/1937053

commit bc8befe6f950264f2f4f6cbe267a3e934a15e26b
Author: Kalle Valo <kvalo@codeaurora.org>
Date:   Fri Sep 25 11:57:21 2020 +0300

    ath11k: fix undefined reference to 'ath11k_debugfs_htt_ext_stats_handler'

    kbuild bot reported than link fails when CONFIG_ATH11K_DEBUGFS is disabled:

    drivers/net/wireless/ath/ath11k/dp_rx.c:1662: undefined reference to `ath11k_debugfs_htt_ext_stats_handler'

    This was because I had missed to move the static inline version of the function
    (which are used when CONFIG_ATH11K_DEBUGFS is disabled) to debufs_htt_stats.h.
    Also move ath11k_debugfs_htt_stats_req() at the same time. And create a stub
    also for ath11k_debugfs_htt_stats_init() for consistency, even if it's not
    needed.

    Reported-by: kernel test robot <lkp@intel.com>
    Fixes: 568f06036ee2 ("ath11k: debugfs: move some function declarations to correct header files")
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/1601024241-16594-1-git-send-email-kvalo@codeaurora.org

Signed-off-by: Jarod Wilson <jarod@redhat.com>