[thermal] thermal: processor_thermal_device: Fix build warning
Message-id: <20191024223900.3192-25-aberegal@redhat.com>
Patchwork-id: 281111
O-Subject: [RHEL8.2 BZ 1732604 24/26] drivers: thermal: processor_thermal_device: Fix build warning
Bugzilla: 1732604
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1732604

commit 6c395f66e98c895cf3ebf87c0b2fc63b6a57a196
Author: Zhang Rui <rui.zhang@intel.com>
Date:   Tue Jul 9 21:19:12 2019 +0800

    drivers: thermal: processor_thermal_device: Fix build warning

    As a system sleep callback, proc_thermal_resume() should be defined only
    if CONFIG_PM_SLEEP is defined.

    This fixes a build warning when CONFIG_PM_SLEEP is not set,
    drivers/thermal/int340x_thermal/processor_thermal_device.c:446:12: error: 'proc_thermal_resume' defined but not used [-Werror=unused-function]
     static int proc_thermal_resume(struct device *dev)

    Fixes: aaba9791fbb4 ("drivers: thermal: processor_thermal: Read PPCC on resume")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Zhang Rui <rui.zhang@intel.com>

Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>