[netdrv] net/mlx5e: xsk: dynamically allocate mlx5e_channel_param
Message-id: <20200510145245.10054-3-ahleihel@redhat.com>
Patchwork-id: 306542
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1789378 v2 02/82] net/mlx5e: xsk: dynamically allocate mlx5e_channel_param
Bugzilla: 1789378
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1789378
Upstream: v5.4-rc1

commit 658688ce6c936254c34ea1f31549ec62439574aa
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jul 23 12:02:26 2019 +0000

    net/mlx5e: xsk: dynamically allocate mlx5e_channel_param

    The structure is too large to put on the stack, resulting in a
    warning on 32-bit ARM:

    drivers/net/ethernet/mellanox/mlx5/core/en/xsk/setup.c:59:5: error: stack frame size of 1344 bytes in function
          'mlx5e_open_xsk' [-Werror,-Wframe-larger-than=]

    Use kvzalloc() instead.

    Fixes: a038e9794541 ("net/mlx5e: Add XSK zero-copy support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Maxim Mikityanskiy <maximmi@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>