[tools] libbf: Fix uninitialized pointer at btf__parse_raw()
Message-id: <20210113140908.457588-211-yauheni.kaliuta@redhat.com>
Patchwork-id: 348557
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 v2 211/291] libbf: Fix uninitialized pointer at btf__parse_raw()
Bugzilla: 1874005
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874005

commit 932ac54a3e59335a847f7682b5124a788ab3c798
Author: Daniel T. Lee <danieltimlee@gmail.com>
Date:   Thu Aug 6 07:33:59 2020 +0900

    libbf: Fix uninitialized pointer at btf__parse_raw()

    Recently, from commit 94a1fedd63ed ("libbpf: Add btf__parse_raw() and
    generic btf__parse() APIs"), new API has been added to libbpf that
    allows to parse BTF from raw data file (btf__parse_raw()).

    The commit derives build failure of samples/bpf due to improper access
    of uninitialized pointer at btf_parse_raw().

        btf.c: In function btf__parse_raw:
        btf.c:625:28: error: btf may be used uninitialized in this function
          625 |  return err ? ERR_PTR(err) : btf;
              |         ~~~~~~~~~~~~~~~~~~~^~~~~

    This commit fixes the build failure of samples/bpf by adding code of
    initializing btf pointer as NULL.

    Fixes: 94a1fedd63ed ("libbpf: Add btf__parse_raw() and generic btf__parse() APIs")
    Signed-off-by: Daniel T. Lee <danieltimlee@gmail.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: John Fastabend <john.fastabend@gmail.com>
    Link: https://lore.kernel.org/bpf/20200805223359.32109-1-danieltimlee@gmail.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>