[tools] selftests/bpf: fix compile errors due to unsync linux/in6.h and netinet/in.h
Message-id: <20191018135423.24316-148-yauheni.kaliuta@redhat.com>
Patchwork-id: 280291
O-Subject: [RHEL8.2 148/268] selftests/bpf: fix compile errors due to unsync linux/in6.h and netinet/in.h
Bugzilla: 1747615
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747615

commit 5de35e3ae9d01796a4909fd0dd8c3660d9316a77
Author: Wang YanQing <udknight@gmail.com>
Date:   Fri Apr 19 02:05:13 2019 +0800

    selftests/bpf: fix compile errors due to unsync linux/in6.h and netinet/in.h

    I meet below compile errors:
    "
    In file included from test_tcpnotify_kern.c:12:
    /usr/include/netinet/in.h:101:5: error: expected identifier
        IPPROTO_HOPOPTS = 0,   /* IPv6 Hop-by-Hop options.  */
        ^
    /usr/include/linux/in6.h:131:26: note: expanded from macro 'IPPROTO_HOPOPTS'
                                    ^
    In file included from test_tcpnotify_kern.c:12:
    /usr/include/netinet/in.h:103:5: error: expected identifier
        IPPROTO_ROUTING = 43,  /* IPv6 routing header.  */
        ^
    /usr/include/linux/in6.h:132:26: note: expanded from macro 'IPPROTO_ROUTING'
                                    ^
    In file included from test_tcpnotify_kern.c:12:
    /usr/include/netinet/in.h:105:5: error: expected identifier
        IPPROTO_FRAGMENT = 44, /* IPv6 fragmentation header.  */
        ^
    /usr/include/linux/in6.h:133:26: note: expanded from macro 'IPPROTO_FRAGMENT'
    "
    The same compile errors are reported for test_tcpbpf_kern.c too.

    My environment:
    lsb_release -a:
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.6 LTS
    Release:        16.04
    Codename:       xenial

    dpkg -l | grep libc-dev:
    ii  libc-dev-bin              2.23-0ubuntu11           amd64        GNU C Library: Development binaries
    ii  linux-libc-dev:amd64      4.4.0-145.171            amd64        Linux Kernel Headers for development.

    The reason is linux/in6.h and netinet/in.h aren't synchronous about how to
    handle the same definitions, IPPROTO_HOPOPTS, etc.

    This patch fixes the compile errors by moving <netinet/in.h> to before the
    <linux/*.h>.

    Signed-off-by: Wang YanQing <udknight@gmail.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>