[tools] perf tools: Free 'printk' string in parse_ftrace_printk()
Message-id: <d701b9204281292ad6a2744ad30c173162c7710b.1559304074.git.mpetlan@redhat.com>
Patchwork-id: 261496
O-Subject: [RHEL8.1 BZ1709243 139/217] perf tools: Free 'printk' string in parse_ftrace_printk()
Bugzilla: 1709243
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1709243
https://bugzilla.redhat.com/show_bug.cgi?id=1709243

upstream
========
commit 9c8a182e5a73e01afd11742a2ab887bf338fdafd
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:12 2018 -0400

description
===========
parse_ftrace_printk() tokenizes and parses a line, calling strdup() each
iteration.  Add code to free this temporary format string duplicate.

Fixes the following coverity complaints:

  Error: RESOURCE_LEAK (CWE-772):
  tools/perf/util/trace-event-parse.c:158: overwrite_var: Overwriting
  "printk" in "printk = strdup(fmt + 1)" leaks the storage that "printk"
  points to.

  tools/perf/util/trace-event-parse.c:162: leaked_storage: Variable
  "printk" going out of scope leaks the storage it points to.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>