[tools] selftests/bpf: fix a compilation error
Message-id: <20191018135423.24316-146-yauheni.kaliuta@redhat.com>
Patchwork-id: 280231
O-Subject: [RHEL8.2 146/268] selftests/bpf: fix a compilation error
Bugzilla: 1747615
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747615

commit ba02de1aa04e392e15ef503c6dd5166915d9d4de
Author: Yonghong Song <yhs@fb.com>
Date:   Wed Apr 17 22:23:30 2019 -0700

    selftests/bpf: fix a compilation error

    I hit the following compilation error with gcc 4.8.5.

      prog_tests/flow_dissector.c: In function test_flow_dissector:
      prog_tests/flow_dissector.c:155:2: error: for loop initial declarations are only allowed in C99 mode
        for (int i = 0; i < ARRAY_SIZE(tests); i++) {
        ^
      prog_tests/flow_dissector.c:155:2: note: use option -std=c99 or -std=gnu99 to compile your code

    Let us fix the issue by avoiding this particular c99 feature.

    Fixes: a5cb33464e53 ("selftests/bpf: make flow dissector tests more extensible")
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>