[netdrv] net/mlx5e: Unblock setting vid 0 for VFs through the uplink rep
Message-id: <20190611125818.20321-198-ahleihel@redhat.com>
Patchwork-id: 264885
O-Subject: [RHEL8.1 BZ 1691236 v2 197/238] net/mlx5e: Unblock setting vid 0 for VFs through the uplink rep
Bugzilla: 1691236
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1691236
Upstream: v5.0-rc5

commit 6ce966fd2671899a48037abe7bf1df80a5adf029
Author: Or Gerlitz <ogerlitz@mellanox.com>
Date:   Tue Jan 1 12:44:52 2019 +0200

    net/mlx5e: Unblock setting vid 0 for VFs through the uplink rep

    It turns out that libvirt uses 0-vid as a default if no vlan was
    set for the guest (which is the case for switchdev mode) and errs
    if we disallow that:

    error: Failed to start domain vm75
    error: Cannot set interface MAC/vlanid to 6a:66:2d:48:92:c2/0 \
                    for ifname enp59s0f0 vf 0: Operation not supported

    So allow this in order not to break existing systems.

    Signed-off-by: Or Gerlitz <ogerlitz@mellanox.com>
    Reported-by: Maor Dickman <maord@mellanox.com>
    Reviewed-by: Gavi Teitz <gavi@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>