[infiniband] IB/core: Fix build failure without hugepages
Message-id: <20200407085502.253987-23-kheib@redhat.com>
Patchwork-id: 299526
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 PATCH 022/104] IB/core: Fix build failure without hugepages
Bugzilla: 1786604
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1786604

commit 74f75cda754eb69a77f910ceb5bc85f8e9ba56a5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jan 9 09:47:30 2020 +0100

    IB/core: Fix build failure without hugepages

    HPAGE_SHIFT is only defined on architectures that support hugepages:

    drivers/infiniband/core/umem_odp.c: In function 'ib_umem_odp_get':
    drivers/infiniband/core/umem_odp.c:245:26: error: 'HPAGE_SHIFT' undeclared (first use in this function); did you mean 'PAGE_SHIFT'?

    Enclose this in an #ifdef.

    Fixes: 9ff1b6466a29 ("IB/core: Fix ODP with IB_ACCESS_HUGETLB handling")
    Link: https://lore.kernel.org/r/20200109084740.2872079-1-arnd@arndb.de
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Jason Gunthorpe <jgg@mellanox.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>