[s390] s390/mm: Fix ERROR: "__node_distance" undefined!
Message-id: <20190322173354.8197-11-emilne@redhat.com>
Patchwork-id: 247380
O-Subject: [RHEL8.1 PATCH 10/21] s390/mm: Fix ERROR: "__node_distance" undefined!
Bugzilla: 1690940
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Mike Snitzer <snitzer@redhat.com>

Fixes:
ERROR: "__node_distance" [drivers/nvme/host/nvme-core.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:92: __modpost] Error 1
make: *** [Makefile:1275: modules] Error 2
+ exit 1

Signed-off-by: Justin M. Forbes <jforbes@fedoraproject.org>
Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>
Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>
(cherry picked from commit a541f0ebcc08ed8bc0cc492eec9a86cb280a9f24)
Signed-off-by: Ewan D. Milne <emilne@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>