[net] net: core: Fix build with CONFIG_IPV6=m
Message-id: <20190604085256.3304-303-yauheni.kaliuta@redhat.com>
Patchwork-id: 262299
O-Subject: [RHEL8.1 PATCH v2 303/627] net: core: Fix build with CONFIG_IPV6=m
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit d71019b54bff4b8f52903e354bf3b8cb2b4dfa75
Author: Joe Stringer <joe@wand.net.nz>
Date:   Tue Oct 2 22:32:26 2018 -0700

    net: core: Fix build with CONFIG_IPV6=m

    Stephen Rothwell reports the following link failure with IPv6 as module:

      x86_64-linux-gnu-ld: net/core/filter.o: in function `sk_lookup':
      (.text+0x19219): undefined reference to `__udp6_lib_lookup'

    Fix the build by only enabling the IPv6 socket lookup if IPv6 support is
    compiled into the kernel.

    Signed-off-by: Joe Stringer <joe@wand.net.nz>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>