[include] include/asm-generic/topology.h: guard cpumask_of_node() macro argument
Message-id: <20200922205532.30550-2-darcari@redhat.com>
Patchwork-id: 327633
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1860387 1/5] include/asm-generic/topology.h: guard cpumask_of_node() macro argument
Bugzilla: 1860387
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1860387

commit 4377748c7b5187c3342a60fa2ceb60c8a57a8488
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 27 22:20:55 2020 -0700

    include/asm-generic/topology.h: guard cpumask_of_node() macro argument

    drivers/hwmon/amd_energy.c:195:15: error: invalid operands to binary expression ('void' and 'int')
                                            (channel - data->nr_cpus));
                                            ~~~~~~~~~^~~~~~~~~~~~~~~~~
    include/asm-generic/topology.h:51:42: note: expanded from macro 'cpumask_of_node'
        #define cpumask_of_node(node)       ((void)node, cpu_online_mask)
                                                   ^~~~
    include/linux/cpumask.h:618:72: note: expanded from macro 'cpumask_first_and'
     #define cpumask_first_and(src1p, src2p) cpumask_next_and(-1, (src1p), (src2p))
                                                                           ^~~~~

    Fixes: f0b848ce6fe9 ("cpumask: Introduce cpumask_of_{node,pcibus} to replace {node,pcibus}_to_cpumask")
    Fixes: 8abee9566b7e ("hwmon: Add amd_energy driver to report energy counters")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Acked-by: Guenter Roeck <linux@roeck-us.net>
    Link: http://lkml.kernel.org/r/20200527134623.930247-1-arnd@arndb.de
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: David Arcari <darcari@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>