selftests/bpf: Make selftest compilation work on clang 11
Bugzilla: http://bugzilla.redhat.com/1874007

commit 41003dd0241c2ceb2461a88a18ff461795f2af57
Author: Jiri Olsa <jolsa@kernel.org>
Date:   Wed Dec 9 15:29:12 2020 +0100

    selftests/bpf: Make selftest compilation work on clang 11

    We can't compile test_core_reloc_module.c selftest with clang 11, compile
    fails with:

      CLNG-LLC [test_maps] test_core_reloc_module.o
      progs/test_core_reloc_module.c:57:21: error: use of unknown builtin \
      '__builtin_preserve_type_info' [-Wimplicit-function-declaration]
       out->read_ctx_sz = bpf_core_type_size(struct bpf_testmod_test_read_ctx);

    Skipping these tests if __builtin_preserve_type_info() is not supported
    by compiler.

    Signed-off-by: Jiri Olsa <jolsa@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Andrii Nakryiko <andrii@kernel.org>
    Link: https://lore.kernel.org/bpf/20201209142912.99145-1-jolsa@kernel.org

Signed-off-by: Jiri Olsa <jolsa@redhat.com>