[netdrv] net: atlantic: fix out of range usage of active_vlans array
Message-id: <1604687916-15087-65-git-send-email-irusskik@redhat.com>
Patchwork-id: 338491
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1857861 064/139] net: atlantic: fix out of range usage of active_vlans array
Bugzilla: 1857861
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1857861

commit 5a292c89a84d49b598f8978f154bdda48b1072c0
Author: Dmitry Bogdanov <dbogdanov@marvell.com>
Date:   Fri Feb 14 18:44:58 2020 +0300

    net: atlantic: fix out of range usage of active_vlans array

    fix static checker warning:
     drivers/net/ethernet/aquantia/atlantic/aq_filters.c:166 aq_check_approve_fvlan()
     error: passing untrusted data to 'test_bit()'

    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Fixes: 7975d2aff5af: ("net: aquantia: add support of rx-vlan-filter offload")
    Signed-off-by: Dmitry Bogdanov <dbogdanov@marvell.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Igor Russkikh <irusskik@redhat.com>

Cc: David Arcari <darcari@redhat.com>
Cc: Igor Russkikh <irusskik@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>