[kernel] bpf: Fix build error without CONFIG_NET
Message-id: <20200529062245.152030-61-yauheni.kaliuta@redhat.com>
Patchwork-id: 315460
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 061/235] bpf: Fix build error without CONFIG_NET
Bugzilla: 1813370
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813370

commit 1f5343c0ae9673543055e9794362766e1f0ed163
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Fri Oct 18 17:03:44 2019 +0800

    bpf: Fix build error without CONFIG_NET

    If CONFIG_NET is n, building fails:

    kernel/trace/bpf_trace.o: In function `raw_tp_prog_func_proto':
    bpf_trace.c:(.text+0x1a34): undefined reference to `bpf_skb_output_proto'

    Wrap it into a #ifdef to fix this.

    Fixes: a7658e1a4164 ("bpf: Check types of arguments passed into helpers")
    Reported-by: Hulk Robot <hulkci@huawei.com>
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/bpf/20191018090344.26936-1-yuehaibing@huawei.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>