[tools] perf metric: Add DCache_L2 to metric parse test
Message-id: <20201214095352.11924-136-mpetlan@redhat.com>
Patchwork-id: 344350
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 135/248] perf metric: Add DCache_L2 to metric parse test
Bugzilla: 1811839 1731571 1838555 1838896 1873271
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1873271
https://bugzilla.redhat.com/show_bug.cgi?id=1873271

upstream
========
commit 5a606f3b9c85ea024a8071765a523c85df93c454
Author: Jiri Olsa <jolsa@kernel.org>
Date: Sun Jul 19 20:13:15 2020 +0200

description
===========
Adding test that compute DCache_L2 metrics with other related metrics in it.

Committer notes:

Fixed up this:

  tests/parse-metric.c:285:7: error: missing field 'val' initializer [-Werror,-Wmissing-field-initializers]
                  { 0 },
                      ^

Signed-off-by: Michael Petlan <mpetlan@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>