[netdrv] mlxsw: spectrum_router: avoid uninitialized variable access
Message-id: <20190607192438.30003-30-ivecera@redhat.com>
Patchwork-id: 263225
O-Subject: [RHEL-8.1 PATCH 029/486] mlxsw: spectrum_router: avoid uninitialized variable access
Bugzilla: 1680241
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1680241

Upstream commit(s):
commit be9c64b19b8131459dd7107dc0ae209eeeaa9ce8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 6 14:44:45 2018 +0200

    mlxsw: spectrum_router: avoid uninitialized variable access

    When CONFIG_BRIDGE_VLAN_FILTERING is disabled, gcc correctly points out
    that the 'vid' variable is uninitialized whenever br_vlan_get_pvid
    returns an error:

    drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c: In function 'mlxsw_sp_rif_vlan_fid_get':
    drivers/net/ethernet/mellanox/mlxsw/spectrum_router.c:6881:6: error: 'vid' may be used uninitialized in this function [-Werror=maybe-uninitialized]

    This changes the condition check to always return -EINVAL here,
    which I guess is what the author intended here.

    Fixes: e6f1960ae6c7 ("mlxsw: spectrum_router: Allocate FID according to PVID")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>