[netdrv] net: phy: at803x: add missing dependency on CONFIG_REGULATOR
Message-id: <e6b8e1e3e54d675973aa27e9b02b8d683ac71f39.1590674883.git.poros@redhat.com>
Patchwork-id: 315027
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 142/298] net: phy: at803x: add missing dependency on CONFIG_REGULATOR
Bugzilla: 1816982
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1816982

Upstream commit(s):
commit dddb318b9f989acba9ccca9babc4715a9075eae8
Author: Madalin Bucur <madalin.bucur@nxp.com>
Date:   Thu Nov 7 15:03:44 2019 +0200

    net: phy: at803x: add missing dependency on CONFIG_REGULATOR

    Compilation fails on PPC targets as CONFIG_REGULATOR is not set and
    drivers/regulator/devres.c is not compiled in while functions exported
    there are used by drivers/net/phy/at803x.c. Here's the error log:

      LD      .tmp_vmlinux1
    drivers/net/phy/at803x.o: In function `at803x_rgmii_reg_set_voltage_sel':
    drivers/net/phy/at803x.c:294: undefined reference to `.rdev_get_drvdata'
    drivers/net/phy/at803x.o: In function `at803x_rgmii_reg_get_voltage_sel':
    drivers/net/phy/at803x.c:306: undefined reference to `.rdev_get_drvdata'
    drivers/net/phy/at803x.o: In function `at8031_register_regulators':
    drivers/net/phy/at803x.c:359: undefined reference to `.devm_regulator_register'
    drivers/net/phy/at803x.c:365: undefined reference to `.devm_regulator_register'
    drivers/net/phy/at803x.o:(.data.rel+0x0): undefined reference to `regulator_list_voltage_table'
    linux/Makefile:1074: recipe for target 'vmlinux' failed
    make[1]: *** [vmlinux] Error 1

    Fixes: 2f664823a470 ("net: phy: at803x: add device tree binding")
    Signed-off-by: Madalin Bucur <madalin.bucur@nxp.com>
    Reviewed-by: Florian Fainelli <f.fainelli@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>