[mm] mm, compaction: fully assume capture is not NULL in compact_zone_order()
Message-id: <ba695300cd86bb5365cc2ffc36cce5f8acd9ee5c.1597412633.git.aquini@redhat.com>
Patchwork-id: 323943
Patchwork-instance: patchwork
O-Subject: [RHEL8 BZ#1862175 PATCH 37/43] mm, compaction: fully assume capture is not NULL in compact_zone_order()
Bugzilla: 1862175
RH-Acked-by: Aristeu Rozanski <aris@redhat.com>
RH-Acked-by: Waiman Long <longman@redhat.com>
RH-Acked-by: Chris von Recklinghausen <crecklin@redhat.com>

This patch is a backport of the following upstream commit:
commit 6467552ca64c4ddd2b83ed73192107d7145f533b
Author: Vlastimil Babka <vbabka@suse.cz>
Date:   Wed Apr 1 21:10:35 2020 -0700

    mm, compaction: fully assume capture is not NULL in compact_zone_order()

    Dan reports:

    The patch 5e1f0f098b46: "mm, compaction: capture a page under direct
    compaction" from Mar 5, 2019, leads to the following Smatch complaint:

        mm/compaction.c:2321 compact_zone_order()
         error: we previously assumed 'capture' could be null (see line 2313)

    mm/compaction.c
      2288  static enum compact_result compact_zone_order(struct zone *zone, int order,
      2289                  gfp_t gfp_mask, enum compact_priority prio,
      2290                  unsigned int alloc_flags, int classzone_idx,
      2291                  struct page **capture)
                                          ^^^^^^^

      2313          if (capture)
                        ^^^^^^^
    Check for NULL

      2314                  current->capture_control = &capc;
      2315
      2316          ret = compact_zone(&cc, &capc);
      2317
      2318          VM_BUG_ON(!list_empty(&cc.freepages));
      2319          VM_BUG_ON(!list_empty(&cc.migratepages));
      2320
      2321          *capture = capc.page;
                    ^^^^^^^^
    Unchecked dereference.

      2322          current->capture_control = NULL;
      2323

    In practice this is not an issue, as the only caller path passes non-NULL
    capture:

    __alloc_pages_direct_compact()
      struct page *page = NULL;
      try_to_compact_pages(capture = &page);
        compact_zone_order(capture = capture);

    So let's remove the unnecessary check, which should also make Smatch happy.

    Fixes: 5e1f0f098b46 ("mm, compaction: capture a page under direct compaction")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Suggested-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Vlastimil Babka <vbabka@suse.cz>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Reviewed-by: Andrew Morton <akpm@linux-foundation.org>
    Acked-by: Mel Gorman <mgorman@techsingularity.net>
    Link: http://lkml.kernel.org/r/18b0df3c-0589-d96c-23fa-040798fee187@suse.cz
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

RHEL BACKPORT NOTES:
* KABI diff from upstream: pointer to capture_control is placed
  into struct task_struct->task_struct_rh

Signed-off-by: Rafael Aquini <aquini@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>