[net] ipv4: Return error for RTA_VIA attribute
Message-id: <5d4bdcecb7558098c4f19f440d56f7ad36ff936c.1572283823.git.gnault@redhat.com>
Patchwork-id: 281254
O-Subject: [RHEL8.2 net PATCH 2/8] ipv4: Return error for RTA_VIA attribute
Bugzilla: 1765639
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Hangbin Liu <haliu@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1765639
Upstream Status: linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24264781
Tested: LNST + CKI net + iproute2 command sequence provided in commit
        description.

commit b6e9e5df4ecf100f6a10ab2ade8e46d47a4b9779
Author: David Ahern <dsahern@gmail.com>
Date:   Tue Feb 26 09:00:02 2019 -0800

    ipv4: Return error for RTA_VIA attribute

    IPv4 currently does not support nexthops outside of the AF_INET family.
    Specifically, it does not handle RTA_VIA attribute. If it is passed
    in a route add request, the actual route added only uses the device
    which is clearly not what the user intended:

      $ ip ro add 172.16.1.0/24 via inet6 2001:db8:1::1 dev eth0
      $ ip ro ls
      ...
      172.16.1.0/24 dev eth0

    Catch this and fail the route add:
      $ ip ro add 172.16.1.0/24 via inet6 2001:db8:1::1 dev eth0
      Error: IPv4 does not support RTA_VIA attribute.

    Fixes: 03c0566542f4c ("mpls: Netlink commands to add, remove, and dump routes")
    Signed-off-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Guillaume Nault <gnault@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>