[arm64] arm64: kexec_file: include linux/vmalloc.h
Message-id: <1555358844-13856-20-git-send-email-bhsharma@redhat.com>
Patchwork-id: 249965
O-Subject: [RHEL8.1 PATCH v2 19/21] arm64: kexec_file: include linux/vmalloc.h
Bugzilla: 1666078
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Mark Salter <msalter@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1666078
Upstream Status: 732291c4fab8b790847aa572703c01ad483b14d0
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21172579
Tested: On 'hpe-apollo' arm64 machine
Conflicts: None

commit 732291c4fab8b790847aa572703c01ad483b14d0
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Dec 11 11:05:46 2018 +0100

    arm64: kexec_file: include linux/vmalloc.h

    This is needed for compilation in some configurations that don't
    include it implicitly:

    arch/arm64/kernel/machine_kexec_file.c: In function 'arch_kimage_file_post_load_cleanup':
    arch/arm64/kernel/machine_kexec_file.c:37:2: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]

    Fixes: 52b2a8af7436 ("arm64: kexec_file: load initrd and device-tree")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Will Deacon <will.deacon@arm.com>
    (cherry picked from commit 732291c4fab8b790847aa572703c01ad483b14d0)

Cc: Jeremy Linton <jlinton@redhat.com>
Cc: Prarit Bhargava <prarit@redhat.com>
Cc: Al Stone <ahs3@redhat.com>
Cc: Mark Salter <msalter@redhat.com>
Cc: Mark Rutland <mark.rutland@arm.com>
Cc: Dave Young <dyoung@redhat.com>
Cc: Baoquan He <bhe@redhat.com>
Cc: Pingfan Liu <piliu@redhat.com>
Signed-off-by: Bhupesh Sharma <bhsharma@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>