[tools] libbpf: fix ptr to u64 conversion warning on 32-bit platforms
Message-id: <20191112151107.11979-193-yauheni.kaliuta@redhat.com>
Patchwork-id: 285822
O-Subject: [RHEL8.2 193/248] libbpf: fix ptr to u64 conversion warning on 32-bit platforms
Bugzilla: 1747617
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747617

commit 36db2a94f19ae1fcf1e6d8253df0c32f90f92860
Author: Andrii Nakryiko <andriin@fb.com>
Date:   Mon Jul 8 21:00:07 2019 -0700

    libbpf: fix ptr to u64 conversion warning on 32-bit platforms

    On 32-bit platforms compiler complains about conversion:

    libbpf.c: In function perf_event_open_probe:
    libbpf.c:4112:17: error: cast from pointer to integer of different
    size [-Werror=pointer-to-int-cast]
      attr.config1 = (uint64_t)(void *)name; /* kprobe_func or uprobe_path */
                     ^

    Reported-by: Matt Hart <matthew.hart@linaro.org>
    Fixes: b26500274767 ("libbpf: add kprobe/uprobe attach API")
    Tested-by: Matt Hart <matthew.hart@linaro.org>
    Signed-off-by: Andrii Nakryiko <andriin@fb.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>