[net] netfilter: conntrack: fix IPV6=n builds
Message-id: <4ef2383643f566b978bbd16571ed27afa72f5fcf.1589567677.git.mleitner@redhat.com>
Patchwork-id: 310001
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 008/146] netfilter: conntrack: fix IPV6=n builds
Bugzilla: 1811193
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Phil Sutter <psutter@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1811193
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28605855
Conflicts: partial backport, as some hunks are not applicable due to
        missing commits. Backported here only to minimize conflicts later on.

commit 81e01647fd2c6dcd592c4a005f47ba9ed5a52847
Author: Florian Westphal <fw@strlen.de>
Date:   Mon Jan 21 14:46:47 2019 +0100

    netfilter: conntrack: fix IPV6=n builds

    Stephen Rothwell reports:
     After merging the netfilter-next tree, today's linux-next build
     (powerpc ppc64_defconfig) failed like this:

     ERROR: "nf_conntrack_invert_icmpv6_tuple" [nf_conntrack.ko] undefined!
     ERROR: "nf_conntrack_icmpv6_packet" [nf_conntrack.ko] undefined!
     ERROR: "nf_conntrack_icmpv6_init_net" [nf_conntrack.ko] undefined!
     ERROR: "icmpv6_pkt_to_tuple" [nf_conntrack.ko] undefined!
     ERROR: "nf_ct_gre_keymap_destroy" [nf_conntrack.ko] undefined!

    icmpv6 related errors are due to lack of IS_ENABLED(CONFIG_IPV6) (no
    icmpv6 support is builtin if kernel has CONFIG_IPV6=n), the
    nf_ct_gre_keymap_destroy error is due to lack of PROTO_GRE check.

    Fixes: a47c54048162 ("netfilter: conntrack: handle builtin l4proto packet functions via direct calls")
    Fixes: e2e48b471634 ("netfilter: conntrack: handle icmp pkt_to_tuple helper via direct calls")
    Fixes: 197c4300aec0 ("netfilter: conntrack: remove invert_tuple callback")
    Fixes: 2a389de86e4a ("netfilter: conntrack: remove l4proto init and get_net callbacks")
    Fixes: e56894356f60 ("netfilter: conntrack: remove l4proto destroy hook")
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>