[acpi] ACPI: blacklist: fix clang warning for unused DMI table
Message-id: <20191110173746.26019-283-ahs3@redhat.com>
Patchwork-id: 284899
O-Subject: [RHEL8.2 PATCH v5 282/299] ACPI: blacklist: fix clang warning for unused DMI table
Bugzilla: 1754787 1739728 1730098 1721297 1664185
RH-Acked-by: Jeremy Linton <jlinton@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664185
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1721297
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1730098
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1739728
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1754787
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24584640
Upstream Status: b80d6a42bdc97bdb6139107d6034222e9843c6e2
Tested: multiple BZs are covered by this patch set:

 bz1664185: this requires an ACPI HMAT table plus the hardware that it
 describes.  For full testing, PartnerQA is recommended.  Barring
 that, does an HMAT table exist, and are there sysfs entries for
 it showing up?

 bz1721297: this requires the latest ACPI PPTT tables in firmware, and
 the hardware that reflects it, so PartnerQA is required.  NB:
 there are additional patches for SPE that will need to be added
 -- see bz1504978 -- but these are the ACPI patches required for
 the SPE patches.

 bz1730098: same as bz1664185, but different partner.

 bz1739728: basic kernel testing and running of the kernel CI tests; in
 general, if a system boots and runs with all known hardware active
 and usable, the ACPI subsystem is behaving.  Re-ran CKI tests for
 v2.

 bz1754787: Windows 2018 string for _OSI, needs confirmation from the
 partner, also.

commit b80d6a42bdc97bdb6139107d6034222e9843c6e2
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jul 10 15:05:43 2019 +0200

    ACPI: blacklist: fix clang warning for unused DMI table

    When CONFIG_DMI is disabled, we only have a tentative declaration,
    which causes a warning from clang:

    drivers/acpi/blacklist.c:20:35: error: tentative array definition assumed to have one element [-Werror]
    static const struct dmi_system_id acpi_rev_dmi_table[] __initconst;

    As the variable is not actually used here, hide it entirely
    in an #ifdef to shut up the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
    (cherry picked from commit b80d6a42bdc97bdb6139107d6034222e9843c6e2)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>