[redhat] rpmspec: Add installation conflicts on older kexec-tools package
Message-id: <20191225024743.GB31354@MiWiFi-R3L-srv>
Patchwork-id: 292159
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 v2] rpmspec: Add installation conflicts on older kexec-tools package
Bugzilla: 1778123
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Bruno Meneguele <bmeneg@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1778123
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=25096731
Upstream: RHEL-only

The sub-section hotplug support patches introduce a new SECTION_IS_EARLY
flag to mem_section->section_mem_map. This will cause failure of
makedumpfile which is contianed in kexec-tools package, and accordingly
fail CKI sysrq-c test case since makedumpfile is used to parse and collect
dumping content after sysrq-c triggered.

The failure of makedumpfile is tracked in bz 1756206, and fixed in
kexec-tools-2.0.20-8.el8. Let's add requirement of package
kexec-tools >= 2.0.20-8 so that any later kernel patches won't get sysrq-c
CKI failure.

Tested:
On amd-pike-07.ml3.eng.bos.redhat.com, it will notice the kernel
rpm installation conflicts on kexec-tools < 2.0.20-8 as below:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[root@amd-pike-07 ~]# ll kernel-*
-rw-r--r--. 1 root root  2645644 Dec  3 00:10 kernel-4.18.0-159.el8.bz1778123.x86_64.rpm
-rw-r--r--. 1 root root 28180312 Dec  3 00:10 kernel-core-4.18.0-159.el8.bz1778123.x86_64.rpm
-rw-r--r--. 1 root root 24330004 Dec  3 00:10 kernel-modules-4.18.0-159.el8.bz1778123.x86_64.rpm

[root@ amd-pike-07 ~]# rpm -ivh kernel-*
error: Failed dependencies:
        kexec-tools < 2.0.20-8 conflicts with kernel-core-4.18.0-159.el8.bz1778123.x86_64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Baoquan He <bhe@redhat.com>
 redhat/kernel.spec.template | 1 +
 1 file changed, 1 insertion(+)
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>