[vdpa] vdpa-sim: depend on HAS_DMA
Message-id: <20200527032039.36912-23-jasowang@redhat.com>
Patchwork-id: 314453
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH V2 22/33] vdpa-sim: depend on HAS_DMA
Bugzilla: 1771441
RH-Acked-by: Michael S. Tsirkin <mst@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

From: "Michael S. Tsirkin" <mst@redhat.com>

set_dma_ops isn't available on all architectures:

        make ARCH=um
...

   drivers/vdpa/vdpa_sim/vdpa_sim.c: In function 'vdpasim_create':
>> drivers/vdpa/vdpa_sim/vdpa_sim.c:324:2: error: implicit declaration of function 'set_dma_ops'; did you mean 'set_groups'?
+[-Werror=implicit-function-declaration]
     set_dma_ops(dev, &vdpasim_dma_ops);
     ^~~~~~~~~~~
     set_groups

Disable vdpa-sim on architectures where it isn't.

Acked-by: Jason Wang <jasowang@redhat.com>
Signed-off-by: Michael S. Tsirkin <mst@redhat.com>
(cherry picked from commit 355b36e6bfd35bd4f4f28f182bb2f8bc07295c88)
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>