[netdrv] net/mlx5e: Fix missing switch_id for representors
Message-id: <01b116d10e485e30fddf9e90904e797eddb5929a.1601376847.git.poros@redhat.com>
Patchwork-id: 328884
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net PATCH 11/11] net/mlx5e: Fix missing switch_id for representors
Bugzilla: 1874073
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1874073

Upstream commit(s):
commit 1315971fea66d2c1b09cab115a487898ba628cac
Author: Parav Pandit <parav@mellanox.com>
Date:   Fri Jul 10 21:12:44 2020 +0300

    net/mlx5e: Fix missing switch_id for representors

    Cited commit in fixes tag missed to set the switch id of the PF and VF
    ports. Due to this flow cannot be offloaded, a simple command like below
    fails to offload with below error.

    tc filter add dev ens2f0np0 parent ffff: prio 1 flower \
     dst_mac 00:00:00:00:00:00/00:00:00:00:00:00 skip_sw \
     action mirred egress redirect dev ens2f0np0pf0vf0

    Error: mlx5_core: devices are not on same switch HW, can't offload forwarding.

    Hence, fix it by setting switch id for each PF and VF representors port
    as before the cited commit.

    Fixes: 71ad8d55f8e5 ("devlink: Replace devlink_port_attrs_set parameters with a struct")
    Signed-off-by: Parav Pandit <parav@mellanox.com>
    Reviewed-by: Roi Dayan <roid@mellanox.com>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>