[block] blk-iocost: Fix error on iocost_ioc_vrate_adj
Message-id: <20200428134524.26112-1-longman@redhat.com>
Patchwork-id: 305601
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH] blk-iocost: Fix error on iocost_ioc_vrate_adj
Bugzilla: 1828563
RH-Acked-by: Ming Lei <ming.lei@redhat.com>
RH-Acked-by: Frantisek Hrbata <fhrbata@redhat.com>
RH-Acked-by: Christoph von Recklinghausen <crecklin@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1828563
BuildInfo: https://brewweb.devel.redhat.com/taskinfo?taskID=28218495
Tested: CKI KT1 test was run with a result of "PASSED".
CKI Test: https://beaker.engineering.redhat.com/jobs/?jobsearch-0.table=Whiteboard&jobsearch-0.operation=contains&jobsearch-0.value=cki%40gitlab%3A549425

This patch fixes the known "Tracepoints: operational test" failure in
the CKI test suite.

commit d6c8e949a35d6906d6c03a50e9a9cdf4e494528a
Author: Waiman Long <longman@redhat.com>
Date:   Tue, 21 Apr 2020 09:07:55 -0400

    blk-iocost: Fix error on iocost_ioc_vrate_adj

    Systemtap 4.2 is unable to correctly interpret the "u32 (*missed_ppm)[2]"
    argument of the iocost_ioc_vrate_adj trace entry defined in
    include/trace/events/iocost.h leading to the following error:

      /tmp/stapAcz0G0/stap_c89c58b83cea1724e26395efa9ed4939_6321_aux_6.c:78:8:
      error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
       , u32[]* __tracepoint_arg_missed_ppm

    That argument type is indeed rather complex and hard to read. Looking
    at block/blk-iocost.c. It is just a 2-entry u32 array. By simplifying
    the argument to a simple "u32 *missed_ppm" and adjusting the trace
    entry accordingly, the compilation error was gone.

    Fixes: 7caa47151ab2 ("blkcg: implement blk-iocost")
    Acked-by: Steven Rostedt (VMware) <rostedt@goodmis.org>
    Acked-by: Tejun Heo <tj@kernel.org>
    Signed-off-by: Waiman Long <longman@redhat.com>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>