[net] netfilter: nft_bitwise: Adjust parentheses to fix memcmp size argument
Message-id: <255c6e397f480ffdacb61466ece39e6f6c983d48.1589567677.git.mleitner@redhat.com>
Patchwork-id: 310011
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 062/146] netfilter: nft_bitwise: Adjust parentheses to fix memcmp size argument
Bugzilla: 1811193
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Phil Sutter <psutter@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1811193
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28605855

commit 83c156d3ecc0121d27dc2b7f34e829b265c70c4f
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Wed Aug 14 09:58:09 2019 -0700

    netfilter: nft_bitwise: Adjust parentheses to fix memcmp size argument

    clang warns:

    net/netfilter/nft_bitwise.c:138:50: error: size argument in 'memcmp'
    call is a comparison [-Werror,-Wmemsize-comparison]
            if (memcmp(&priv->xor, &zero, sizeof(priv->xor) ||
                                          ~~~~~~~~~~~~~~~~~~^~
    net/netfilter/nft_bitwise.c:138:6: note: did you mean to compare the
    result of 'memcmp' instead?
            if (memcmp(&priv->xor, &zero, sizeof(priv->xor) ||
                ^
                                                           )
    net/netfilter/nft_bitwise.c:138:32: note: explicitly cast the argument
    to size_t to silence this warning
            if (memcmp(&priv->xor, &zero, sizeof(priv->xor) ||
                                          ^
                                          (size_t)(
    1 error generated.

    Adjust the parentheses so that the result of the sizeof is used for the
    size argument in memcmp, rather than the result of the comparison (which
    would always be true because sizeof is a non-zero number).

    Fixes: bd8699e9e292 ("netfilter: nft_bitwise: add offload support")
    Link: https://github.com/ClangBuiltLinux/linux/issues/638
    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>