[tools] perf tools: Fix cross compile for ARM64
Message-id: <20200514101858.720-175-mpetlan@redhat.com>
Patchwork-id: 307733
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 174/300] perf tools: Fix cross compile for ARM64
Bugzilla: 1818838
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1818838
https://bugzilla.redhat.com/show_bug.cgi?id=1818838

upstream
========
commit 71f699078b154fcb1c9162fd0208ada9ce532ffc
Author: John Garry <john.garry@huawei.com>
Date: Wed Nov 6 21:00:54 2019 +0800

description
===========
Currently when cross compiling perf tool for ARM64 on my x86 machine I
get this error:

  arch/arm64/util/sym-handling.c:9:10: fatal error: gelf.h: No such file or directory
   #include <gelf.h>

For the build, libelf is reported off:

  Auto-detecting system features:
  ...
  ...                        libelf: [ OFF ]

Indeed, test-libelf is not built successfully:

  more ./build/feature/test-libelf.make.output
  test-libelf.c:2:10: fatal error: libelf.h: No such file or directory
   #include <libelf.h>
          ^~~~~~~~~~
  compilation terminated.

I have no such problems natively compiling on ARM64, and I did not
previously have this issue for cross compiling. Fix by relocating the
gelf.h include.

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>