[net] bpf: fix building without CONFIG_INET
Message-id: <20190604085256.3304-301-yauheni.kaliuta@redhat.com>
Patchwork-id: 262298
O-Subject: [RHEL8.1 PATCH v2 301/627] bpf: fix building without CONFIG_INET
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit df3f94a0bbeb6cb6a02eb16b8e76f16b33cb2f8f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Oct 8 11:30:01 2018 -0700

    bpf: fix building without CONFIG_INET

    The newly added TCP and UDP handling fails to link when CONFIG_INET
    is disabled:

    net/core/filter.o: In function `sk_lookup':
    filter.c:(.text+0x7ff8): undefined reference to `tcp_hashinfo'
    filter.c:(.text+0x7ffc): undefined reference to `tcp_hashinfo'
    filter.c:(.text+0x8020): undefined reference to `__inet_lookup_established'
    filter.c:(.text+0x8058): undefined reference to `__inet_lookup_listener'
    filter.c:(.text+0x8068): undefined reference to `udp_table'
    filter.c:(.text+0x8070): undefined reference to `udp_table'
    filter.c:(.text+0x808c): undefined reference to `__udp4_lib_lookup'
    net/core/filter.o: In function `bpf_sk_release':
    filter.c:(.text+0x82e8): undefined reference to `sock_gen_put'

    Wrap the related sections of code in #ifdefs for the config option.

    Furthermore, sk_lookup() should always have been marked 'static', this
    also avoids a warning about a missing prototype when building with
    'make W=1'.

    Fixes: 6acc9b432e67 ("bpf: Add helper to retrieve socket in BPF")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Joe Stringer <joe@wand.net.nz>
    Acked-by: Song Liu <songliubraving@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>