[include] vdso: Fix clocksource.h macro detection
Message-id: <20201027003220.16553-214-longman@redhat.com>
Patchwork-id: 335581
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 213/213] vdso: Fix clocksource.h macro detection
Bugzilla: 1548297
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1548297

commit ca214e2c1793058e3a1387f9e343cc5b1731db15
Author: Vincenzo Frascino <vincenzo.frascino@arm.com>
Date:   Mon, 23 Mar 2020 13:39:20 +0000

    vdso: Fix clocksource.h macro detection

    CONFIG_GENERIC_GETTIMEOFDAY is a sufficient condition to verify if an
    architecture implements asm/vdso/clocksource.h or not. The current
    implementation wrongly assumes that the same is true for the config
    option CONFIG_ARCH_CLOCKSOURCE_DATA.

    This results in a series of build errors on ia64/sparc/sparc64 like this:

      In file included from ./include/linux/clocksource.h:31,
                       from ./include/linux/clockchips.h:14,
                       from ./include/linux/tick.h:8,
                       from fs/proc/stat.c:15:
      ./include/vdso/clocksource.h:9:10: fatal error: asm/vdso/clocksource.h:
      No such file or directory
          9 | #include <asm/vdso/clocksource.h>
            |          ^~~~~~~~~~~~~~~~~~~~~~~~

    Fix the issue removing the unneeded config condition.

    Fixes: 14ee2ac618e4 ("linux/clocksource.h: Extract common header for vDSO")
    Reported-by: Thomas Gleixner <tglx@linutronix.de>
    Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Link: https://lkml.kernel.org/r/20200323133920.46546-1-vincenzo.frascino@arm.com

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>