[tools] perf probe: Return a better scope DIE if there is no best scope
Message-id: <20191218212502.14325-11-mpetlan@redhat.com>
Patchwork-id: 292116
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 BZ1760227 v2 10/22] perf probe: Return a better scope DIE if there is no best scope
Bugzilla: 1760227
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1760227
https://bugzilla.redhat.com/show_bug.cgi?id=1760227

upstream
========
commit c701636aeec4c173208697d68da6e4271125564b
Author: Masami Hiramatsu <mhiramat@kernel.org>
Date: Tue Nov 5 09:16:49 2019 +0900

description
===========
Make find_best_scope() returns innermost DIE at given address if there
is no best matched scope DIE. Since Gcc sometimes generates intuitively
strange line info which is out of inlined function address range, we
need this fixup.

Without this, sometimes perf probe failed to probe on a line inside an
inlined function:

  # perf probe -D ksys_open:3
  Failed to find scope of probe point.
    Error: Failed to add events.

With this fix, 'perf probe' can probe it:

  # perf probe -D ksys_open:3
  p:probe/ksys_open _text+25707308
  p:probe/ksys_open_1 _text+25710596
  p:probe/ksys_open_2 _text+25711114
  p:probe/ksys_open_3 _text+25711343
  p:probe/ksys_open_4 _text+25714058
  p:probe/ksys_open_5 _text+2819653
  p:probe/ksys_open_6 _text+2819701

Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>