[include] gpiolib: of: Reshuffle contents of consumer.h for new library layout
Message-id: <20200512194917.141423-145-darcari@redhat.com>
Patchwork-id: 307177
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1829900 144/233] gpiolib: of: Reshuffle contents of consumer.h for new library layout
Bugzilla: 1829900
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Brian Masney <bmasney@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1829900

commit fce04b1ce8e326bf2cafaea4a0c91dbc3e99e403
Author: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Date:   Tue Jul 30 13:43:35 2019 +0300

    gpiolib: of: Reshuffle contents of consumer.h for new library layout

    Kernel build bot reported a compilation error after the commit

      f626d6dfb709 ("gpio: of: Break out OF-only code"):

    drivers/gpio/gpiolib-devres.o: In function `devm_gpiod_get_from_of_node':
    gpiolib-devres.c:(.text+0x19a): undefined reference to `gpiod_get_from_of_node'

    This happens due to move the latter under umbrella of CONFIG_OF_GPIO while
    customer.h contains staled data.

    Fix it by reshuffling contents of consumer.h to satisfy build dependencies.

    Reported-by: kbuild test robot <lkp@intel.com>
    Fixes: f626d6dfb709 ("gpio: of: Break out OF-only code"):
    Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Link: https://lore.kernel.org/r/20190730104337.21235-1-andriy.shevchenko@linux.intel.com
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>