[sound] ALSA: ASoC: core: move definition of enum snd_soc_bias_level
Message-id: <1602843533499326-606-patchset-jkysela@redhat.com>
Patchwork-id: 332219
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 PATCH 0605/1534] ALSA: ASoC: core: move definition of enum snd_soc_bias_level
Bugzilla: 1869536
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

To fix compilation error:

- error: field 'XXX' has incomplete type

Moves definition of enum snd_soc_bias_level from soc.h to soc-dapm.h.

Signed-off-by: Tzung-Bi Shih <tzungbi@google.com>
Link: https://lore.kernel.org/r/20200625153543.85039-2-tzungbi@google.com
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 10e834099d38dd2c02bf2bd5feaa3997cfcf139f)
Bugzilla: 1869536
Signed-off-by: Jan Stancek <jstancek@redhat.com>