[clocksource] clocksource/drivers/arm_arch_timer: Fix vDSO clockmode when vDSO disabled
Message-id: <20201027003220.16553-179-longman@redhat.com>
Patchwork-id: 335542
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 178/213] clocksource/drivers/arm_arch_timer: Fix vDSO clockmode when vDSO disabled
Bugzilla: 1548297
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1548297

commit a67de48b3075cbb6ec030205d7b78981def6596d
Author: Vincenzo Frascino <vincenzo.frascino@arm.com>
Date:   Mon, 24 Feb 2020 15:15:52 +0000

    clocksource/drivers/arm_arch_timer: Fix vDSO clockmode when vDSO disabled

    The arm_arch_timer requires VDSO_CLOCKMODE_ARCHTIMER to be defined to
    compile correctly. On ARM the vDSO can be disabled and when this is the
    case the compilation ends prematurely with an error:

     $ make ARCH=arm multi_v7_defconfig
     $ ./scripts/config -d VDSO
     $ make

    drivers/clocksource/arm_arch_timer.c:73:44: error:
    ‘VDSO_CLOCKMODE_ARCHTIMER’ undeclared here (not in a function)
      static enum vdso_clock_mode vdso_default = VDSO_CLOCKMODE_ARCHTIMER;

    Make the usage of VDSO_CLOCKMODE_ARCHTIMER depend on the VDSO enablement
    and initialize the vdso clockmode variable with VDSO_CLOCKMODE_NONE
    otherwise.

    [ tglx: Match changelog and patch content. ]

    Fixes: 5e3c6a312a09 ("ARM/arm64: vdso: Use common vdso clock mode storage")
    Reported-by: Marek Szyprowski <m.szyprowski@samsung.com>
    Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Link: https://lkml.kernel.org/r/20200224151552.57274-1-vincenzo.frascino@arm.com

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>