perf symbols: Use (long) for iterator for bfd symbols
Bugzilla: https://bugzilla.redhat.com/1944685

upstream
========
commit 96de68fff5ded8833bf5832658cb43c54f86ff6c
Author: Dmitry Safonov <dima@arista.com>
Date: Tue Feb 9 14:51:48 2021 +0000

description
===========
GCC (GCC) 8.4.0 20200304 fails to build perf with:
: util/symbol.c: In function 'dso__load_bfd_symbols':
: util/symbol.c:1626:16: error: comparison of integer expressions of different signednes
:   for (i = 0; i < symbols_count; ++i) {
:                 ^
: util/symbol.c:1632:16: error: comparison of integer expressions of different signednes
:    while (i + 1 < symbols_count &&
:                 ^
: util/symbol.c:1637:13: error: comparison of integer expressions of different signednes
:    if (i + 1 < symbols_count &&
:              ^
: cc1: all warnings being treated as errors

It's unlikely that the symtable will be that big, but the fix is an
oneliner and as perf has CORE_CFLAGS += -Wextra, which makes build to
fail together with CORE_CFLAGS += -Werror

Fixes: eac9a4342e54 ("perf symbols: Try reading the symbol table with libbfd")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>