[netdrv] net/mlx5e: Fix build error without IPV6
Message-id: <20200510150452.10307-74-ahleihel@redhat.com>
Patchwork-id: 306696
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1789380 v2 73/87] net/mlx5e: Fix build error without IPV6
Bugzilla: 1789380
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1789380
Upstream: v5.5-rc1
Conflicts:
 - drivers/net/ethernet/mellanox/mlx5/core/en/tc_tun.c
   Context diff due to already backported commit:
   6c8991f41546 ("net: ipv6_stub: use ip6_dst_lookup_flow instead of ip6_dst_lookup")

commit 5f9fc3325ef95398c363b9b7813a7e99d4d85d7d
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Wed Nov 27 21:27:00 2019 +0800

    net/mlx5e: Fix build error without IPV6

    If IPV6 is not set and CONFIG_MLX5_ESWITCH is y,
    building fails:

    drivers/net/ethernet/mellanox/mlx5/core/en/tc_tun.c:322:5: error: redefinition of mlx5e_tc_tun_create_header_ipv6
     int mlx5e_tc_tun_create_header_ipv6(struct mlx5e_priv *priv,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from drivers/net/ethernet/mellanox/mlx5/core/en/tc_tun.c:7:0:
    drivers/net/ethernet/mellanox/mlx5/core/en/tc_tun.h:67:1: note: previous definition of mlx5e_tc_tun_create_header_ipv6 was here
     mlx5e_tc_tun_create_header_ipv6(struct mlx5e_priv *priv,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Use #ifdef to guard this, also move mlx5e_route_lookup_ipv6
    to cleanup unused warning.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: e689e998e102 ("net/mlx5e: TC, Stub out ipv6 tun create header function")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Acked-by: Saeed Mahameed <saeedm@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>