[tools] kunit: testing kunit: Bug fix in test_run_timeout function
Message-id: <9f61392b763f0a58737f1da0732f2883abb7a625.1610738986.git@redhat.com>
Patchwork-id: 349893
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 V2 bz1900119 PATCH 26/90] kunit: testing kunit: Bug fix in test_run_timeout function
Bugzilla: 1900119
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1900119
commit 70efb58bbbc28f0cbd4060c9aa581d79201c8b1a
Author: Heidi Fahim <heidifahim@google.com>
Date:   Mon Dec 2 15:53:29 2019 -0800

    kunit: testing kunit: Bug fix in test_run_timeout function

    Assert in test_run_timeout was not updated with the build_dir argument
    and caused the following error:
    AssertionError: Expected call: run_kernel(timeout=3453)
    Actual call: run_kernel(build_dir=None, timeout=3453)

    Needed to update kunit_tool_test to reflect this fix
    https://lkml.org/lkml/2019/9/6/351

    Signed-off-by: Heidi Fahim <heidifahim@google.com>
    Reviewed-by: SeongJae Park <sjpark@amazon.de>
    Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
    Tested-by: Brendan Higgins <brendanhiggins@google.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: Nico Pache <npache@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>