[net] net_sched: fix unused variable warning in stmmac
Message-id: <20181011191457.685-152-ivecera@redhat.com>
Patchwork-id: 230814
O-Subject: [RHEL8.0 net PATCH 151/190] net_sched: fix unused variable warning in stmmac
Bugzilla: 1638022
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1638022

Upstream commit(s):
commit 191672ca07a7c10c3b84d01019a33d59b4317997
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Aug 22 17:25:44 2018 +0200

    net_sched: fix unused variable warning in stmmac

    The new tcf_exts_for_each_action() macro doesn't reference its
    arguments when CONFIG_NET_CLS_ACT is disabled, which leads to
    a harmless warning in at least one driver:

    drivers/net/ethernet/stmicro/stmmac/stmmac_tc.c: In function 'tc_fill_actions':
    drivers/net/ethernet/stmicro/stmmac/stmmac_tc.c:64:6: error: unused variable 'i' [-Werror=unused-variable]

    Adding a cast to void lets us avoid this kind of warning.
    To be on the safe side, do it for all three arguments, not
    just the one that caused the warning.

    Fixes: 244cd96adb5f ("net_sched: remove list_head from tc_action")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>