[samples] samples/bpf: Set -fno-stack-protector when building BPF programs
Message-id: <20200608222925.282045-72-yauheni.kaliuta@redhat.com>
Patchwork-id: 318033
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 072/257] samples/bpf: Set -fno-stack-protector when building BPF programs
Bugzilla: 1813372
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813372

commit 450278977acbf494a20367c22fbb38729772d1fc
Author: Toke Høiland-Jørgensen <toke@redhat.com>
Date:   Mon Dec 16 11:38:19 2019 +0100

    samples/bpf: Set -fno-stack-protector when building BPF programs

    It seems Clang can in some cases turn on stack protection by default, which
    doesn't work with BPF. This was reported once before[0], but it seems the
    flag to explicitly turn off the stack protector wasn't added to the
    Makefile, so do that now.

    The symptom of this is compile errors like the following:

    error: <unknown>:0:0: in function bpf_prog1 i32 (%struct.__sk_buff*): A call to built-in function '__stack_chk_fail' is not supported.

    [0] https://www.spinics.net/lists/netdev/msg556400.html

    Signed-off-by: Toke Høiland-Jørgensen <toke@redhat.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20191216103819.359535-1-toke@redhat.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>