[lib] iov_iter: Fix build error without CONFIG_CRYPTO
Message-id: <20190528133855.3742-7-ivecera@redhat.com>
Patchwork-id: 260895
O-Subject: [RHEL-8.1 net PATCH 6/6] iov_iter: Fix build error without CONFIG_CRYPTO
Bugzilla: 1714213
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Chris Leech <cleech@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1714213

Upstream commit(s):
commit 27fad74a5a77fe2e1f876db7bf27efcf2ec304b2
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Thu Apr 4 10:31:14 2019 +0800

    iov_iter: Fix build error without CONFIG_CRYPTO

    If CONFIG_CRYPTO is not set or set to m,
    gcc building warn this:

    lib/iov_iter.o: In function `hash_and_copy_to_iter':
    iov_iter.c:(.text+0x9129): undefined reference to `crypto_stats_get'
    iov_iter.c:(.text+0x9152): undefined reference to `crypto_stats_ahash_update'

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: d05f443554b3 ("iov_iter: introduce hash_and_copy_to_iter helper")
    Suggested-by: Al Viro <viro@zeniv.linux.org.uk>
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>