[char] ipmi: ipmb: Fix build error while CONFIG_I2C is set to m
Message-id: <20190918151314.27704-17-tcamuso@redhat.com>
Patchwork-id: 272426
O-Subject: [RHEL8.2 BZ 1752071 16/27] ipmi: ipmb: Fix build error while CONFIG_I2C is set to m
Bugzilla: 1752071
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzillas: https://bugzilla.redhat.com/show_bug.cgi?id=1752071
           https://bugzilla.redhat.com/show_bug.cgi?id=1725433
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=23542405
Testing:
    IPMI regression tests and full cki.test suite.
    https://beaker.engineering.redhat.com/jobs/?jobsearch-0.table=Whiteboard&jobsearch-0.operation=contains&jobsearch-0.value=cki%40gitlab%3A171332
        Overall result: PASSED
             Tests: OK

Cherry-picked from the following upstream commit.

commit 102308f557bca8e539a800614b0e274945a81cdf
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Wed Jun 12 11:18:25 2019 +0800

    ipmi: ipmb: Fix build error while CONFIG_I2C is set to m

    If CONFIG_I2C is m and CONFIG_I2C_SLAVE is y,
    building with CONFIG_IPMB_DEVICE_INTERFACE setting to
    y will fail:

    drivers/char/ipmi/ipmb_dev_int.o: In function `ipmb_remove':
    ipmb_dev_int.c: undefined reference to `i2c_slave_unregister'
    drivers/char/ipmi/ipmb_dev_int.o: In function `ipmb_write':
    ipmb_dev_int.c: undefined reference to `i2c_smbus_write_block_data'
    drivers/char/ipmi/ipmb_dev_int.o: In function `ipmb_probe':
    ipmb_dev_int.c: undefined reference to `i2c_slave_register'
    drivers/char/ipmi/ipmb_dev_int.o: In function `ipmb_driver_init':
    ipmb_dev_int.c: undefined reference to `i2c_register_driver'
    drivers/char/ipmi/ipmb_dev_int.o: In function `ipmb_driver_exit':
    ipmb_dev_int.c: undefined reference to `i2c_del_driver'

    Add I2C Kconfig dependency to fix this.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: 51bd6f291583 ("Add support for IPMB driver")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Message-Id: <20190612031825.24732-1-yuehaibing@huawei.com>
    Signed-off-by: Corey Minyard <cminyard@mvista.com>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>