[md] dm integrity: fix ppc64le warning
Message-id: <20200403161223.18728-17-snitzer@redhat.com>
Patchwork-id: 299158
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 16/17] dm integrity: fix ppc64le warning
Bugzilla: 1820280
RH-Acked-by: Heinz Mauelshagen <heinzm@redhat.com>
RH-Acked-by: Joe Thornber <thornber@redhat.com>
RH-Acked-by: Mikulas Patocka <mpatocka@redhat.com>

BZ: 1820280

commit e7fc1e57d9abd008b020bb92f1750f8e6c68a956
Author: Mike Snitzer <snitzer@redhat.com>
Date:   Thu Apr 2 21:11:24 2020 -0400

    dm integrity: fix ppc64le warning

    Otherwise:

    In file included from drivers/md/dm-integrity.c:13:
    drivers/md/dm-integrity.c: In function 'dm_integrity_status':
    drivers/md/dm-integrity.c:3061:10: error: format '%llu' expects
    argument of type 'long long unsigned int', but argument 4 has type
    'long int' [-Werror=format=]
       DMEMIT("%llu %llu",
              ^~~~~~~~~~~
        atomic64_read(&ic->number_of_mismatches),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ./include/linux/device-mapper.h:550:46: note: in definition of macro 'DMEMIT'
          0 : scnprintf(result + sz, maxlen - sz, x))
                                                  ^
    cc1: all warnings being treated as errors

    Fixes: 7649194a1636ab5 ("dm integrity: remove sector type casts")
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>