[tools] tools/io_uring: fix Makefile for pthread library link
Message-id: <20190829191348.5097-76-jmoyer@redhat.com>
Patchwork-id: 270022
O-Subject: [RHEL8.2 PATCH 75/98] tools/io_uring: fix Makefile for pthread library link
Bugzilla: 1706143
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Ming Lei <ming.lei@redhat.com>

From: Jens Axboe <axboe@kernel.dk>

BZ: 1706143
Brew: 23177771

commit 486f069253c3c738dec62daeb16f7232b2cca065
Author: Jens Axboe <axboe@kernel.dk>
Date:   Wed May 22 08:47:54 2019 -0600

    tools/io_uring: fix Makefile for pthread library link

    Currently fails with:

    io_uring-bench.o: In function `main':
    /home/axboe/git/linux-block/tools/io_uring/io_uring-bench.c:560: undefined reference to `pthread_create'
    /home/axboe/git/linux-block/tools/io_uring/io_uring-bench.c:588: undefined reference to `pthread_join'
    collect2: error: ld returned 1 exit status
    Makefile:11: recipe for target 'io_uring-bench' failed
    make: *** [io_uring-bench] Error 1

    Move -lpthread to the end.

    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>