[usb] usb: dwc3: add EXTCON dependency for qcom
Message-id: <20200407161320.17414-235-torez@redhat.com>
Patchwork-id: 299970
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 234/983] usb: dwc3: add EXTCON dependency for qcom
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit 3def4031b3e3fbb524cbd01555b057a6cef0d5e6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Sep 13 11:37:31 2018 +0200

    usb: dwc3: add EXTCON dependency for qcom

    Like the omap back-end, we get a link error with CONFIG_EXTCON=m
    when building the qcom back-end into the kernel:

    drivers/usb/dwc3/dwc3-qcom.o: In function `dwc3_qcom_probe':
    dwc3-qcom.c:(.text+0x13dc): undefined reference to `extcon_get_edev_by_phandle'
    dwc3-qcom.c:(.text+0x1b18): undefined reference to `devm_extcon_register_notifier'
    dwc3-qcom.c:(.text+0x1b9c): undefined reference to `extcon_get_state'

    Do the same thing as OMAP and add an explicit dependency on
    EXTCON.

    Fixes: a4333c3a6ba9 ("usb: dwc3: Add Qualcomm DWC3 glue driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>