[usb] usb: gadget: fsl: fix link error against usb-gadget module
Message-id: <20200407161320.17414-734-torez@redhat.com>
Patchwork-id: 300469
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 733/983] usb: gadget: fsl: fix link error against usb-gadget module
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit 2100e3ca3676e894fa48b8f6f01d01733387fe81
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Apr 16 14:25:32 2019 +0200

    usb: gadget: fsl: fix link error against usb-gadget module

    The dependency to ensure this driver links correctly fails since
    it can not be a loadable module:

    drivers/usb/phy/phy-fsl-usb.o: In function `fsl_otg_set_peripheral':
    phy-fsl-usb.c:(.text+0x2224): undefined reference to `usb_gadget_vbus_disconnect'

    Make the option 'tristate' so it can work correctly.

    Fixes: 5a8d651a2bde ("usb: gadget: move gadget API functions to udc-core")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>