[tools] libbpf: Fix build with gcc-8
Message-id: <20191018135423.24316-80-yauheni.kaliuta@redhat.com>
Patchwork-id: 280205
O-Subject: [RHEL8.2 080/268] libbpf: Fix build with gcc-8
Bugzilla: 1747615
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747615

commit d5adbdd77ecc1d841af244a10958792141830d30
Author: Andrey Ignatov <rdna@fb.com>
Date:   Wed Apr 10 18:36:43 2019 -0700

    libbpf: Fix build with gcc-8

    Reported in [1].

    With gcc 8.3.0 the following error is issued:

      cc -Ibpf@sta -I. -I.. -I.././include -I.././include/uapi
      -fdiagnostics-color=always -fsanitize=address,undefined -fno-omit-frame-pointer
      -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -g -fPIC -g -O2
      -Werror -Wall -Wno-pointer-arith -Wno-sign-compare  -MD -MQ
      'bpf@sta/src_libbpf.c.o' -MF 'bpf@sta/src_libbpf.c.o.d' -o
      'bpf@sta/src_libbpf.c.o' -c ../src/libbpf.c
      ../src/libbpf.c: In function 'bpf_object__elf_collect':
      ../src/libbpf.c:947:18: error: 'map_def_sz' may be used uninitialized in this
      function [-Werror=maybe-uninitialized]
         if (map_def_sz <= sizeof(struct bpf_map_def)) {
             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      ../src/libbpf.c:827:18: note: 'map_def_sz' was declared here
        int i, map_idx, map_def_sz, nr_syms, nr_maps = 0, nr_maps_glob = 0;
                        ^~~~~~~~~~

    According to [2] -Wmaybe-uninitialized is enabled by -Wall.
    Same error is generated by clang's -Wconditional-uninitialized.

    [1] https://github.com/libbpf/libbpf/pull/29#issuecomment-481902601
    [2] https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

    Fixes: d859900c4c56 ("bpf, libbpf: support global data/bss/rodata sections")
    Reported-by: Evgeny Vereshchagin <evvers@ya.ru>
    Signed-off-by: Andrey Ignatov <rdna@fb.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>