[include] bpf: pass translate() as a callback and remove its ndo_bpf subcommand
Message-id: <20190604085256.3304-285-yauheni.kaliuta@redhat.com>
Patchwork-id: 262279
O-Subject: [RHEL8.1 PATCH v2 285/627] bpf: pass translate() as a callback and remove its ndo_bpf subcommand
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

Conflicts: previous KABI extention.

  Skip nfp hunks, coming with a separate patchset.

  Leave BPF_OFFLOAD_TRANSLATE in enum bpf_netdev_command to keep nfp
  driver buildable.

  include/linux/netdevice.h due to leaving hunk on backporting of
     00db12c3d141 bpf: call verifier_prep from its callback in struct bpf_offload_dev

KABI: struct bpf_prog_offload_ops is not protected by KABI, safe to
  extend.

RHEL: squashed commit to keep the tree bisectable

commit b07ade27e93360197e453e5ca80eebdc9099dcb5
Author: Quentin Monnet <quentin.monnet@netronome.com>
Date:   Fri Nov 9 13:03:29 2018 +0000

    bpf: pass translate() as a callback and remove its ndo_bpf subcommand

    As part of the transition from ndo_bpf() to callbacks attached to struct
    bpf_offload_dev for some of the eBPF offload operations, move the
    functions related to code translation to the struct and remove the
    subcommand that was used to call them through the NDO.

    Signed-off-by: Quentin Monnet <quentin.monnet@netronome.com>
    Reviewed-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

commit ac8acec9912a93be9953446766e0bb73aeeecc64
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Mon Nov 12 15:10:42 2018 -0700

    bpf: Remove unused variable in nsim_bpf

    Clang warns:

    drivers/net/netdevsim/bpf.c:557:30: error: unused variable 'state'
    [-Werror,-Wunused-variable]
            struct nsim_bpf_bound_prog *state;
                                        ^
    1 error generated.

    The declaration should have been removed in commit b07ade27e933 ("bpf:
    pass translate() as a callback and remove its ndo_bpf subcommand").

    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Acked-by: Quentin Monnet <quentin.monnet@netronome.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>