[cpufreq] cpufreq: intel_pstate: Fix static checker warning for epp variable
Message-id: <20201001223620.960275-12-pusethi@redhat.com>
Patchwork-id: 329551
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1881199 v2 11/26] cpufreq: intel_pstate: Fix static checker warning for epp variable
Bugzilla: 1881199
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1881199

commit 3ff79754d7a2b27f6d2d56b3951fc9aa8080b063
Author: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
Date:   Thu Jul 9 13:05:22 2020 -0700

    cpufreq: intel_pstate: Fix static checker warning for epp variable

    Fix warning for:
    drivers/cpufreq/intel_pstate.c:731 store_energy_performance_preference()
    error: uninitialized symbol 'epp'.

    This warning is for a case, when energy_performance_preference attribute
    matches pre defined strings. In this case the value of raw epp will not
    be used to set EPP bits in MSR_HWP_REQUEST. So initializing with any
    value is fine.

    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Srinivas Pandruvada <srinivas.pandruvada@linux.intel.com>
    Acked-by: Viresh Kumar <viresh.kumar@linaro.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Puneet Sethi <pusethi@redhat.com>

Cc: Al Stone <ahs3@redhat.com>
Cc: Lenny Szubowicz <lszubowi@redhat.com>
Cc: Prarit Bhargava <prarit@redhat.com>
Cc: David Arcari <darcari@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>