[fs] ext4: fix build error when DX_DEBUG is defined
Message-id: <20181101124318.15263-2-lczerner@redhat.com>
Patchwork-id: 232444
O-Subject: [RHEL8.0 fs PATCH v2 1/3] ext4: fix build error when DX_DEBUG is defined
Bugzilla: 1644694
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

From: Gabriel Krisman Bertazi <krisman@collabora.co.uk>

BZ 1644694
https://bugzilla.redhat.com/show_bug.cgi?id=1644694

BREW 18978124
https://brewweb.devel.redhat.com/taskinfo?taskID=18978124

commit 799578ab16e86b074c184ec5abbda0bc698c7b0b

	Enabling DX_DEBUG triggers the build error below.  info is an attribute
	of  the dxroot structure.

	linux/fs/ext4/namei.c:2264:12: error: 'info'
	undeclared (first use in this function); did you mean 'insl'?
		   	  info->indirect_levels));

	Fixes: e08ac99fa2a2 ("ext4: add largedir feature")
	Signed-off-by: Gabriel Krisman Bertazi <krisman@collabora.co.uk>
	Signed-off-by: Theodore Ts'o <tytso@mit.edu>
	Reviewed-by: Lukas Czerner <lczerner@redhat.com>

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>