[netdrv] mlx4: fix "initializer element not constant" compiler error
Message-id: <a119d92c54dd624ea972fac330ae137d8693bb00.1589212234.git.poros@redhat.com>
Patchwork-id: 306807
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net PATCH 35/37] mlx4: fix "initializer element not constant" compiler error
Bugzilla: 1830928
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1830928

Upstream commit(s):
commit 41b145024ca717254bb6882f1312299db958bf0c
Author: Jacob Keller <jacob.e.keller@intel.com>
Date:   Fri Mar 27 14:08:35 2020 -0700

    mlx4: fix "initializer element not constant" compiler error

    A recent commit e8937681797c ("devlink: prepare to support region
    operations") used the region_cr_space_str and region_fw_health_str
    variables as initializers for the devlink_region_ops structures.

    This can result in compiler errors:
    drivers/net/ethernet/mellanox//mlx4/crdump.c:45:10: error: initializer
    element is not constant
       .name = region_cr_space_str,
               ^
    drivers/net/ethernet/mellanox//mlx4/crdump.c:45:10: note: (near
    initialization for ‘region_cr_space_ops.name’)
    drivers/net/ethernet/mellanox//mlx4/crdump.c:50:10: error: initializer
    element is not constant
       .name = region_fw_health_str,

    The variables were made to be "const char * const", indicating that both
    the pointer and data were constant. This was enough to resolve this on
    recent GCC (gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1) for this author).

    Unfortunately this is not enough for older compilers to realize that the
    variable can be treated as a constant expression.

    Fix this by introducing macros for the string and use those instead of
    the variable name in the region ops structures.

    Reported-by: tanhuazhong <tanhuazhong@huawei.com>
    Fixes: e8937681797c ("devlink: prepare to support region operations")
    Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>
    Reviewed-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>