[usb] usb: gadget: configfs: avoid spaces for indentation
Message-id: <20200407161320.17414-48-torez@redhat.com>
Patchwork-id: 299783
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 047/983] usb: gadget: configfs: avoid spaces for indentation
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit ad22a6663c6312825876fed25fd6d010d4b46db1
Author: Parth Y Shah <sparth1292@gmail.com>
Date:   Thu Jun 14 12:02:46 2018 +0530

    usb: gadget: configfs: avoid spaces for indentation

    This fixes the following checkpatch error:

    ERROR: code indent should use tabs where possible

    Here, spaces are replaced by a tab in 2 lines.

    Signed-off-by: Parth Y Shah <sparth1292@gmail.com>
    Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>