[sound] ALSA: soundwire: intel: fix another unused-function warning
Message-id: <16118254255780022-56-patchset-jkysela@redhat.com>
Patchwork-id: 351407
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 PATCH 55/93] ALSA: soundwire: intel: fix another unused-function warning
Bugzilla: 1783462
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Without CONFIG_PM, there is another warning about an unused function:

drivers/soundwire/intel.c:530:12: error: 'intel_link_power_down' defined but not used [-Werror=unused-function]

After a previous fix, the driver already uses both an #ifdef and
a __maybe_unused annotation but still gets it wrong. Remove the
ifdef and instead use __maybe_unused consistently to avoid the
problem for good.

Fixes: f046b2334083 ("soundwire: intel: fix intel_suspend/resume defined but not used warning")
Fixes: ebf878eddbb4 ("soundwire: intel: add pm_runtime support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20201203230502.1480063-1-arnd@kernel.org
Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 17e0da0b8979a53977f684813f5c9db817d170e2)
Bugzilla: 1783462
Signed-off-by: Jan Stancek <jstancek@redhat.com>