[md] md/raid5: use do_div() for 64 bit divisions in raid5_sync_request
Message-id: <20200928190706.8935-3-ncroxon@redhat.com>
Patchwork-id: 328297
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH V2 32/40] md/raid5: use do_div() for 64 bit divisions in raid5_sync_request
Bugzilla: 1856838
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Xiao Ni <xni@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Yufen Yu <yuyufen@huawei.com>

We get compilation error on 32-bit architectures (e.g. m68k), as:

  ERROR: modpost: "__udivdi3" [drivers/md/raid456.ko] undefined!

Since 'sync_blocks' is defined as u64, use do_div() to fix this error.

Fixes: c911c46c017c ("md/raid456: convert macro STRIPE_* to RAID5_STRIPE_*")
Signed-off-by: Yufen Yu <yuyufen@huawei.com>
Signed-off-by: Song Liu <songliubraving@fb.com>
(cherry picked from commit 83c3e5e17b5e3057ac304383a46e3c485d00ffed)
Signed-off-by: Nigel Croxon <ncroxon@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>