[infiniband] RMDA/siw: Require a 64 bit arch
Message-id: <20191029153151.25029-165-kheib@redhat.com>
Patchwork-id: 281604
O-Subject: [RHEL-8.2 PATCH 164/173] RMDA/siw: Require a 64 bit arch
Bugzilla: 1725830 1720892
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1720892
Bugzilla: http://bugzilla.redhat.com/1725830

commit 0b043644c0ca601cb19943a81aa1f1455dbe9461
Author: Jason Gunthorpe <jgg@mellanox.com>
Date:   Fri Jul 12 12:12:06 2019 -0300

    RMDA/siw: Require a 64 bit arch

    The new siw driver fails to build on i386 with

    drivers/infiniband/sw/siw/siw_qp.c:1025:3: error: invalid output size for constraint '+q'
                    smp_store_mb(*cq->notify, SIW_NOTIFY_NOT);

    As it is using 64 bit values with the smp_store_mb.

    Since the entire scheme here seems questionable, and we are in the merge
    window, fix the compile failures by disabling 32 bit support on this
    driver.

    A proper fix will be reviewed post merge window.

    Fixes: c0cf5bdde46c ("rdma/siw: addition to kernel build environment")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>