[infiniband] RDMA/core: Make the entire API tree static
Message-id: <20200512105530.4207-47-ahleihel@redhat.com>
Patchwork-id: 306918
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1789382 046/124] RDMA/core: Make the entire API tree static
Bugzilla: 1789382
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1789382
Upstream: v5.6-rc1
Conflicts:
 - drivers/infiniband/hw/mlx5/mlx5_ib.h
   Context diff due to missing declarations, that existed upstream
   as leftover..

commit 8889f6fa35884d09f24734e10fea0c9ddcbc6429
Author: Jason Gunthorpe <jgg@mellanox.com>
Date:   Thu Jan 30 11:21:21 2020 -0400

    RDMA/core: Make the entire API tree static

    Compilation of mlx5 driver without CONFIG_INFINIBAND_USER_ACCESS generates
    the following error.

    on x86_64:

     ld: drivers/infiniband/hw/mlx5/main.o: in function `mlx5_ib_handler_MLX5_IB_METHOD_VAR_OBJ_ALLOC':
     main.c:(.text+0x186d): undefined reference to `ib_uverbs_get_ucontext_file'
     ld: drivers/infiniband/hw/mlx5/main.o:(.rodata+0x2480): undefined reference to `uverbs_idr_class'
     ld: drivers/infiniband/hw/mlx5/main.o:(.rodata+0x24d8): undefined reference to `uverbs_destroy_def_handler'

    This is happening because some parts of the UAPI description are not
    static. This is a hold over from earlier code that relied on struct
    pointers to refer to object types, now object types are referenced by
    number. Remove the unused globals and add statics to the remaining UAPI
    description elements.

    Remove the redundent #ifdefs around mlx5_ib_*defs and obsolete
    mlx5_ib_get_devx_tree().

    The compiler now trims alot more unused code, including the above
    problematic definitions when !CONFIG_INFINIBAND_USER_ACCESS.

    Fixes: 7be76bef320b ("IB/mlx5: Introduce VAR object and its alloc/destroy methods")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>