perf tools: Fix arm64 build error with gcc-11
Bugzilla: https://bugzilla.redhat.com/1944685

upstream
========
commit 067012974c8ae31a8886046df082aeba93592972
Author: Jianlin Lv <Jianlin.Lv@arm.com>
Date: Thu Feb 18 11:12:45 2021 +0800

description
===========
gcc version: 11.0.0 20210208 (experimental) (GCC)

Following build error on arm64:

.......
In function ‘printf’,
    inlined from ‘regs_dump__printf’ at util/session.c:1141:3,
    inlined from ‘regs__printf’ at util/session.c:1169:2:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:107:10: \
  error: ‘%-5s’ directive argument is null [-Werror=format-overflow=]

107 |   return __printf_chk (__USE_FORTIFY_LEVEL - 1, __fmt, \
                __va_arg_pack ());

......
In function ‘fprintf’,
  inlined from ‘perf_sample__fprintf_regs.isra’ at \
    builtin-script.c:622:14:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:100:10: \
    error: ‘%5s’ directive argument is null [-Werror=format-overflow=]
  100 |   return __fprintf_chk (__stream, __USE_FORTIFY_LEVEL - 1, __fmt,
  101 |                         __va_arg_pack ());

cc1: all warnings being treated as errors
.......

This patch fixes Wformat-overflow warnings. Add helper function to
convert NULL to "unknown".

Conflicts:
==========
Omitting tools/perf/arch/riscv/include/perf_regs.h since we don't
support RISCV.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>