selftests/bpf: Fix open call in trigger_fstat_events
Bugzilla: http://bugzilla.redhat.com/1874006

commit d83971761fa278dcffa855110f024bf043ce6e6e
Author: Jiri Olsa <jolsa@kernel.org>
Date:   Wed Aug 26 12:18:45 2020 +0200

    selftests/bpf: Fix open call in trigger_fstat_events

    Alexei reported compile breakage on newer systems with
    following error:

      In file included from /usr/include/fcntl.h:290:0,
      4814                 from ./test_progs.h:29,
      4815                 from
      .../bpf-next/tools/testing/selftests/bpf/prog_tests/d_path.c:3:
      4816In function ‘open’,
      4817    inlined from ‘trigger_fstat_events’ at
      .../bpf-next/tools/testing/selftests/bpf/prog_tests/d_path.c:50:10,
      4818    inlined from ‘test_d_path’ at
      .../bpf-next/tools/testing/selftests/bpf/prog_tests/d_path.c:119:6:
      4819/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to
      ‘__open_missing_mode’ declared with attribute error: open with O_CREAT
      or O_TMPFILE in second argument needs 3 arguments
      4820    __open_missing_mode ();
      4821    ^~~~~~~~~~~~~~~~~~~~~~

    We're missing permission bits as 3rd argument
    for open call with O_CREAT flag specified.

    Fixes: e4d1af4b16f8 ("selftests/bpf: Add test for d_path helper")
    Reported-by: Alexei Starovoitov <ast@kernel.org>
    Signed-off-by: Jiri Olsa <jolsa@kernel.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20200826101845.747617-1-jolsa@kernel.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>