[netdrv] mt76: mt76x02: fix some checkpatch warnings
Message-id: <20191126234256.26042-587-jarod@redhat.com>
Patchwork-id: 290135
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 586/796] mt76: mt76x02: fix some checkpatch warnings
Bugzilla: 1776606
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit ff97c52a3a0a552e5c77653a147c377d4b676426
Author: Ryder Lee <ryder.lee@mediatek.com>
Date:   Wed Jul 24 16:58:18 2019 +0800

    mt76: mt76x02: fix some checkpatch warnings

    This fixes the following checkpatch warnings:

    ERROR: code indent should use tabs where possible
    CHECK: Alignment should match open parenthesis
    CHECK: No space is necessary after a cast
    CHECK: Please don't use multiple blank lines
    CHECK: Avoid precedence issues in macro
    WARNING: Statements should start on a tabstop
    WARNING: Unnecessary space before function pointer arguments

    Signed-off-by: Ryder Lee <ryder.lee@mediatek.com>
    Signed-off-by: Felix Fietkau <nbd@nbd.name>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>