[tools] selftests: net: use LDLIBS instead of LDFLAGS
Message-id: <20200330025343.24000-6-haliu@redhat.com>
Patchwork-id: 298330
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net PATCH 05/58] selftests: net: use LDLIBS instead of LDFLAGS
Bugzilla: 1816587
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1816587
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=27515480
Upstream Status: net.git commit 870f193d48c2

commit 870f193d48c25a97d61a8e6c04e3c29a2c606850
Author: Fathi Boudra <fathi.boudra@linaro.org>
Date:   Wed Jan 16 11:43:18 2019 -0600

    selftests: net: use LDLIBS instead of LDFLAGS

    reuseport_bpf_numa fails to build due to undefined reference errors:

     aarch64-linaro-linux-gcc
     --sysroot=/build/tmp-rpb-glibc/sysroots/hikey -Wall
     -Wl,--no-as-needed -O2 -g -I../../../../usr/include/  -Wl,-O1
     -Wl,--hash-style=gnu -Wl,--as-needed -lnuma  reuseport_bpf_numa.c
     -o
     /build/tmp-rpb-glibc/work/hikey-linaro-linux/kselftests/4.12-r0/linux-4.12-rc7/tools/testing/selftests/net/reuseport_bpf_numa
     /tmp/ccfUuExT.o: In function `send_from_node':
     /build/tmp-rpb-glibc/work/hikey-linaro-linux/kselftests/4.12-r0/linux-4.12-rc7/tools/testing/selftests/net/reuseport_bpf_numa.c:138:
     undefined reference to `numa_run_on_node'
     /tmp/ccfUuExT.o: In function `main':
     /build/tmp-rpb-glibc/work/hikey-linaro-linux/kselftests/4.12-r0/linux-4.12-rc7/tools/testing/selftests/net/reuseport_bpf_numa.c:230:
     undefined reference to `numa_available'
     /build/tmp-rpb-glibc/work/hikey-linaro-linux/kselftests/4.12-r0/linux-4.12-rc7/tools/testing/selftests/net/reuseport_bpf_numa.c:233:
     undefined reference to `numa_max_node'

    It's GNU Make and linker specific.

    The default Makefile rule looks like:

    $(CC) $(CFLAGS) $(LDFLAGS) $@ $^ $(LDLIBS)

    When linking is done by gcc itself, no issue, but when it needs to be passed
    to proper ld, only LDLIBS follows and then ld cannot know what libs to link
    with.

    More detail:
    https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

    LDFLAGS
    Extra flags to give to compilers when they are supposed to invoke the linker,
    ‘ld’, such as -L. Libraries (-lfoo) should be added to the LDLIBS variable
    instead.

    LDLIBS
    Library flags or names given to compilers when they are supposed to invoke the
    linker, ‘ld’. LOADLIBES is a deprecated (but still supported) alternative to
    LDLIBS. Non-library linker flags, such as -L, should go in the LDFLAGS
    variable.

    https://lkml.org/lkml/2010/2/10/362

    tools/perf: libraries must come after objects

    Link order matters, use LDLIBS instead of LDFLAGS to properly link against
    libnuma.

    Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>
    Signed-off-by: Shuah Khan <shuah@kernel.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>