[netdrv] drivers/net: netdevsim depends on INET
Message-id: <20200430155029.2684684-11-ivecera@redhat.com>
Patchwork-id: 306013
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 net PATCH 10/12] drivers/net: netdevsim depends on INET
Bugzilla: 1829778
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1829778

Upstream commit(s):
commit 1f399fc797b5f78df8a993effdc0ef04304fdcea
Author: Hongbo Yao <yaohongbo@huawei.com>
Date:   Thu Jan 16 21:14:04 2020 +0800

    drivers/net: netdevsim depends on INET

    If CONFIG_INET is not set and CONFIG_NETDEVSIM=y.
    Building drivers/net/netdevsim/fib.o will get the following error:

    drivers/net/netdevsim/fib.o: In function `nsim_fib4_rt_hw_flags_set':
    fib.c:(.text+0x12b): undefined reference to `fib_alias_hw_flags_set'
    drivers/net/netdevsim/fib.o: In function `nsim_fib4_rt_destroy':
    fib.c:(.text+0xb11): undefined reference to `free_fib_info'

    Correct the Kconfig for netdevsim.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: 48bb9eb47b270 ("netdevsim: fib: Add dummy implementation for FIB offload")
    Signed-off-by: Hongbo Yao <yaohongbo@huawei.com>
    Acked-by: Jakub Kicinski <kuba@kernel.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>