[hid] u2fzero: fix compiling error in u2fzero_probe()
Message-id: <20191114172113.1731017-259-benjamin.tissoires@redhat.com>
Patchwork-id: 287118
O-Subject: [PATCH RHEL 8.2 258/387] HID: u2fzero: fix compiling error in u2fzero_probe()
Bugzilla: 1740778
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1740778
Upstream Status: since v5.2
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24566877
Test: by me at https://gitlab.cee.redhat.com/btissoir/test-input-template/issues/1

commit e252e0e0028167ea3d1eafa99c2ff9f62c444b0a
Author: Mao Wenan <maowenan@huawei.com>
Date:   Sat Apr 13 21:44:59 2019 +0800

    HID: u2fzero: fix compiling error in u2fzero_probe()

    There is one compiling error in u2fzero_probe()->u2fzero_init_hwrng(),
    this is because HW_RANDOM is not set.

    drivers/hid/hid-u2fzero.o: In function `u2fzero_probe':
    hid-u2fzero.c:(.text+0xc70): undefined reference to `devm_hwrng_register'

    Fixes: 42337b9d4d958("HID: add driver for U2F Zero built-in LED and RNG")
    Reported-by: Hulk Robot <hulkci@huawei.com>
    Signed-off-by: Mao Wenan <maowenan@huawei.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>