[tools] perf unwind: Fix libunwind build failure on i386 systems
Message-id: <20200415143309.16001-435-mpetlan@redhat.com>
Patchwork-id: 302677
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 435/469] perf unwind: Fix libunwind build failure on i386 systems
Bugzilla: 1818835
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>

Bugzilla: 1818835
https://bugzilla.redhat.com/show_bug.cgi?id=1818835

upstream
========
commit 26acf400d2dcc72c7e713e1f55db47ad92010cc2
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Sep 26 14:36:48 2019 -0300

description
===========
Naresh Kamboju reported, that on the i386 build pr_err()
doesn't get defined properly due to header ordering:

  perf-in.o: In function `libunwind__x86_reg_id':
  tools/perf/util/libunwind/../../arch/x86/util/unwind-libunwind.c:109:
  undefined reference to `pr_err'

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>