[acpi] ACPI: Fix build failure when CONFIG_NLS is set to 'n'
Message-id: <20191110173746.26019-122-ahs3@redhat.com>
Patchwork-id: 284830
O-Subject: [RHEL8.2 PATCH v5 121/299] ACPI: Fix build failure when CONFIG_NLS is set to 'n'
Bugzilla: 1754787 1739728 1730098 1721297 1664185
RH-Acked-by: Jeremy Linton <jlinton@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664185
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1721297
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1730098
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1739728
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1754787
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24584640
Upstream Status: 2e61069b056f7ac3cde5f84a4be8aa703b57089d
Tested: multiple BZs are covered by this patch set:

 bz1664185: this requires an ACPI HMAT table plus the hardware that it
 describes.  For full testing, PartnerQA is recommended.  Barring
 that, does an HMAT table exist, and are there sysfs entries for
 it showing up?

 bz1721297: this requires the latest ACPI PPTT tables in firmware, and
 the hardware that reflects it, so PartnerQA is required.  NB:
 there are additional patches for SPE that will need to be added
 -- see bz1504978 -- but these are the ACPI patches required for
 the SPE patches.

 bz1730098: same as bz1664185, but different partner.

 bz1739728: basic kernel testing and running of the kernel CI tests; in
 general, if a system boots and runs with all known hardware active
 and usable, the ACPI subsystem is behaving.  Re-ran CKI tests for
 v2.

 bz1754787: Windows 2018 string for _OSI, needs confirmation from the
 partner, also.

commit 2e61069b056f7ac3cde5f84a4be8aa703b57089d
Author: Sinan Kaya <okaya@kernel.org>
Date:   Sun Dec 30 20:40:05 2018 +0000

    ACPI: Fix build failure when CONFIG_NLS is set to 'n'

    Observing link failure as follows when CONFIG_ACPI is set but
    both CONFIG_NLS and CONFIG_PCI are no set:

    drivers/acpi/device_sysfs.o: In function `description_show':
    device_sysfs.c:(.text+0x48a): undefined reference to `utf16s_to_utf8s'

    This issue was previously addressed implicitly by commit 8a226e00eeed
    (PCI: pci-label: Fix build failure when CONFIG_NLS is set to 'm' by
    allmodconfig) causing PCI_LABEL to be selected when ACPI was set
    which caused NLS to be selected too in that case.

    However, after commit 5d32a66541c46 (PCI/ACPI: Allow ACPI to be built
    without CONFIG_PCI set) it is possible to build ACPI support without
    PCI, so make ACPI select NLS directly to cover that case.

    Fixes: 5d32a66541c46 (PCI/ACPI: Allow ACPI to be built without CONFIG_PCI set)
    Signed-off-by: Sinan Kaya <okaya@kernel.org>
    [ rjw: Changelog ]
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
    (cherry picked from commit 2e61069b056f7ac3cde5f84a4be8aa703b57089d)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>