[mm] mm, memcg: fix build error around the usage of kmem_caches
Message-id: <20201216001840.9820-198-longman@redhat.com>
Patchwork-id: 345074
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 197/272] mm, memcg: fix build error around the usage of kmem_caches
Bugzilla: 1877019
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1877019

commit a87425a36fb2a98f560543703b3ce92270cdedd8
Author: Yafang Shao <laoar.shao@gmail.com>
Date:   Wed, 1 Apr 2020 21:06:30 -0700

    mm, memcg: fix build error around the usage of kmem_caches

    When I manually set default n to MEMCG_KMEM in init/Kconfig, bellow error
    occurs,

      mm/slab_common.c: In function 'memcg_slab_start':
      mm/slab_common.c:1530:30: error: 'struct mem_cgroup' has no member named
      'kmem_caches'
        return seq_list_start(&memcg->kmem_caches, *pos);
                                    ^
      mm/slab_common.c: In function 'memcg_slab_next':
      mm/slab_common.c:1537:32: error: 'struct mem_cgroup' has no member named
      'kmem_caches'
        return seq_list_next(p, &memcg->kmem_caches, pos);
                                      ^
      mm/slab_common.c: In function 'memcg_slab_show':
      mm/slab_common.c:1551:16: error: 'struct mem_cgroup' has no member named
      'kmem_caches'
        if (p == memcg->kmem_caches.next)
                      ^
        CC      arch/x86/xen/smp.o
      mm/slab_common.c: In function 'memcg_slab_start':
      mm/slab_common.c:1531:1: warning: control reaches end of non-void function
      [-Wreturn-type]
       }
       ^
      mm/slab_common.c: In function 'memcg_slab_next':
      mm/slab_common.c:1538:1: warning: control reaches end of non-void function
      [-Wreturn-type]
       }
       ^

    That's because kmem_caches is defined only when CONFIG_MEMCG_KMEM is set,
    while memcg_slab_start() will use it no matter CONFIG_MEMCG_KMEM is defined
    or not.

    By the way, the reason I mannuly undefined CONFIG_MEMCG_KMEM is to verify
    whether my some other code change is still stable when CONFIG_MEMCG_KMEM is
    not set. Unfortunately, the existing code has been already unstable since
    v4.11.

    Fixes: bc2791f857e1 ("slab: link memcg kmem_caches on their associated memory cgroup")
    Signed-off-by: Yafang Shao <laoar.shao@gmail.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Acked-by: Andrew Morton <akpm@linux-foundation.org>
    Cc: Tejun Heo <tj@kernel.org>
    Cc: Vladimir Davydov <vdavydov.dev@gmail.com>
    Cc: Johannes Weiner <hannes@cmpxchg.org>
    Cc: Michal Hocko <mhocko@kernel.org>
    Link: http://lkml.kernel.org/r/1580970260-2045-1-git-send-email-laoar.shao@gmail.com
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>