[pci] PCI: Remove unused attr variable in pci_dma_configure
Message-id: <20191110173746.26019-96-ahs3@redhat.com>
Patchwork-id: 284775
O-Subject: [RHEL8.2 PATCH v5 095/299] PCI: Remove unused attr variable in pci_dma_configure
Bugzilla: 1754787 1739728 1730098 1721297 1664185
RH-Acked-by: Jeremy Linton <jlinton@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664185
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1721297
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1730098
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1739728
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1754787
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24584640
Upstream Status: 664204410afb3b0f538d176ad0c2713b04abd4b9
Tested: multiple BZs are covered by this patch set:

 bz1664185: this requires an ACPI HMAT table plus the hardware that it
 describes.  For full testing, PartnerQA is recommended.  Barring
 that, does an HMAT table exist, and are there sysfs entries for
 it showing up?

 bz1721297: this requires the latest ACPI PPTT tables in firmware, and
 the hardware that reflects it, so PartnerQA is required.  NB:
 there are additional patches for SPE that will need to be added
 -- see bz1504978 -- but these are the ACPI patches required for
 the SPE patches.

 bz1730098: same as bz1664185, but different partner.

 bz1739728: basic kernel testing and running of the kernel CI tests; in
 general, if a system boots and runs with all known hardware active
 and usable, the ACPI subsystem is behaving.  Re-ran CKI tests for
 v2.

 bz1754787: Windows 2018 string for _OSI, needs confirmation from the
 partner, also.

commit 664204410afb3b0f538d176ad0c2713b04abd4b9
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Fri Dec 14 18:49:01 2018 -0700

    PCI: Remove unused attr variable in pci_dma_configure

    Clang warns:

    drivers/pci/pci-driver.c:1603:21: error: unused variable 'attr'
    [-Werror,-Wunused-variable]

    Commit e5361ca29f2f ("ACPI / scan: Refactor _CCA enforcement") removed
    attr's use and replaced it with its assigned value so it is no longer
    needed.

    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: Christoph Hellwig <hch@lst.de>
    (cherry picked from commit 664204410afb3b0f538d176ad0c2713b04abd4b9)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>