[tools] libbpf: Ignore -Wformat-nonliteral warning
Message-id: <20191018135423.24316-61-yauheni.kaliuta@redhat.com>
Patchwork-id: 280167
O-Subject: [RHEL8.2 061/268] libbpf: Ignore -Wformat-nonliteral warning
Bugzilla: 1747615
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747615

commit ff466b58055f2d28d8ddc1388af312e87a693efe
Author: Andrey Ignatov <rdna@fb.com>
Date:   Sat Apr 6 22:37:34 2019 -0700

    libbpf: Ignore -Wformat-nonliteral warning

    vsprintf() in __base_pr() uses nonliteral format string and it breaks
    compilation for those who provide corresponding extra CFLAGS, e.g.:
    https://github.com/libbpf/libbpf/issues/27

    If libbpf is built with the flags from PR:

      libbpf.c:68:26: error: format string is not a string literal
      [-Werror,-Wformat-nonliteral]
              return vfprintf(stderr, format, args);
                                      ^~~~~~
      1 error generated.

    Ignore this warning since the use case in libbpf.c is legit.

    Signed-off-by: Andrey Ignatov <rdna@fb.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>