[tools] perf hist: Support block formats with compare/sort/display
Message-id: <20200514101858.720-191-mpetlan@redhat.com>
Patchwork-id: 307749
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 190/300] perf hist: Support block formats with compare/sort/display
Bugzilla: 1818838
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1818838
https://bugzilla.redhat.com/show_bug.cgi?id=1818838

upstream
========
commit b65a7d372b1a55db6fb48a5b3c48941eb68716cb
Author: Jin Yao <yao.jin@linux.intel.com>
Date: Thu Nov 7 15:47:16 2019 +0800

description
===========
This patch provides helper routines to support new columns for block
info output.

The new columns are:

  Sampled Cycles%
  Sampled Cycles
  Avg Cycles%
  Avg Cycles
  [Program Block Range]
  Shared Object

 v5:
 ---
 1. Move more block related functions from builtin-report.c to
    block-info.c

 2. Set ms (map+sym) in block hist_entry. Because this info
    is needed for reporting the block range (i.e. source line)

Committer notes:

Remove unused set_fmt() function, some build were not completing with:

  util/block-info.c:396:20: error: unused function 'set_fmt' [-Werror,-Wunused-function]
  static inline void set_fmt(struct block_fmt *block_fmt,
                     ^
  1 error generated.

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>