[net] openvswitch: use div_u64() for 64-by-32 divisions
Message-id: <160406005763.139758.2220723860595971020.stgit@nst.lab.eng.brq.redhat.com>
Patchwork-id: 336384
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net PATCH 10/18] net: openvswitch: use div_u64() for 64-by-32 divisions
Bugzilla: 1888576
RH-Acked-by: Flavio Leitner <fbl@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1888576
Upstream Status: Backport net-next.git commit 659d4587fe72
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=32463682
Tested: Manually tested using the fave-ovn-multinode setup.
        LNST Test: https://platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/LNST-BREW-job/283/
        ENRT Test: https://beaker.engineering.redhat.com/jobs/4676329
        CKI  Test: https://beaker.engineering.redhat.com/jobs/?jobsearch-0.table=Whiteboard&jobsearch-0.operation=contains&jobsearch-0.value=cki%40gitlab%3A616086
        LNST OVS : https://beaker.engineering.redhat.com/jobs/4689904
                   https://beaker.engineering.redhat.com/jobs/4690934

Backport of upstream commit:

commit 659d4587fe7233bfdff303744b20d6f41ad04362
Author: Tonghao Zhang <xiangxia.m.yue@gmail.com>
Date:   Sat Apr 25 11:39:48 2020 +0800

    net: openvswitch: use div_u64() for 64-by-32 divisions

    Compile the kernel for arm 32 platform, the build warning found.
    To fix that, should use div_u64() for divisions.
    | net/openvswitch/meter.c:396: undefined reference to `__udivdi3'

    [add more commit msg, change reported tag, and use div_u64 instead
    of do_div by Tonghao]

    Fixes: e57358873bb5d6ca ("net: openvswitch: use u64 for meter bucket")
    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Tonghao Zhang <xiangxia.m.yue@gmail.com>
    Tested-by: Tonghao Zhang <xiangxia.m.yue@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Eelco Chaudron <echaudro@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>