[kernel] locking/lockdep: Move mark_lock() inside CONFIG_TRACE_IRQFLAGS && CONFIG_PROVE_LOCKING
Message-id: <20191111194853.28672-85-longman@redhat.com>
Patchwork-id: 285391
O-Subject: [RHEL8.2 PATCH 84/92] locking/lockdep: Move mark_lock() inside CONFIG_TRACE_IRQFLAGS && CONFIG_PROVE_LOCKING
Bugzilla: 1736654
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1736654

commit 886532aee3cd42d95196601ed16d7c3d4679e9e5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jun 17 14:47:05 2019 +0200

    locking/lockdep: Move mark_lock() inside CONFIG_TRACE_IRQFLAGS && CONFIG_PROVE_LOCKING

    The last cleanup patch triggered another issue, as now another function
    should be moved into the same section:

     kernel/locking/lockdep.c:3580:12: error: 'mark_lock' defined but not used [-Werror=unused-function]
      static int mark_lock(struct task_struct *curr, struct held_lock *this,

    Move mark_lock() into the same #ifdef section as its only caller, and
    remove the now-unused mark_lock_irq() stub helper.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Bart Van Assche <bvanassche@acm.org>
    Cc: Frederic Weisbecker <frederic@kernel.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Waiman Long <longman@redhat.com>
    Cc: Will Deacon <will.deacon@arm.com>
    Cc: Yuyang Du <duyuyang@gmail.com>
    Fixes: 0d2cc3b34532 ("locking/lockdep: Move valid_state() inside CONFIG_TRACE_IRQFLAGS && CONFIG_PROVE_LOCKING")
    Link: https://lkml.kernel.org/r/20190617124718.1232976-1-arnd@arndb.de
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>