perf bpf: Enclose libbpf.h include within HAVE_LIBBPF_SUPPORT
Bugzilla: https://bugzilla.redhat.com/1944684

upstream
========
commit c18cf78d7969db89934587fa476220eefe7bd4bd
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Oct 20 14:12:37 2020 -0300

description
===========
As it uses the 'deprecated' attribute in a way that breaks the build
with old gcc compilers, so to continue being able to build in such
systems where NO_LIBBPF=1 is being used, enclose it under
HAVE_LIBBPF_SUPPORT.

   1 centos:6          : FAIL gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
   2 oraclelinux:6     : FAIL gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23.0.1)

    CC       /tmp/build/perf/builtin-record.o
  In file included from util/bpf-loader.h:11,
                   from builtin-record.c:39:
  /git/linux/tools/lib/bpf/libbpf.h:203: error: wrong number of arguments specified for 'deprecated' attribute

Signed-off-by: Michael Petlan <mpetlan@redhat.com>