[x86] efi/libstub/x86: Fix unused-variable warning
Message-id: <20201001185358.23889-205-crecklin@redhat.com>
Patchwork-id: 329518
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 bz 1754739 v7 patch 204/226] efi/libstub/x86: Fix unused-variable warning
Bugzilla: 1754739
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Waiman Long <longman@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

commit bd1d7093a8086df37d260bd1f1d896c0922d34ef
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jan 13 18:22:35 2020 +0100

    efi/libstub/x86: Fix unused-variable warning

    The only users of these got removed, so they also need to be
    removed to avoid warnings:

      arch/x86/boot/compressed/eboot.c: In function 'setup_efi_pci':
      arch/x86/boot/compressed/eboot.c:117:16: error: unused variable 'nr_pci' [-Werror=unused-variable]
        unsigned long nr_pci;
                      ^~~~~~
      arch/x86/boot/compressed/eboot.c: In function 'setup_uga':
      arch/x86/boot/compressed/eboot.c:244:16: error: unused variable 'nr_ugas' [-Werror=unused-variable]
        unsigned long nr_ugas;
                      ^~~~~~~

    Fixes: 2732ea0d5c0a ("efi/libstub: Use a helper to iterate over a EFI handle array")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/20200113172245.27925-4-ardb@kernel.org
Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>

Signed-off-by: Jan Stancek <jstancek@redhat.com>