[tools] libbpf: Fix build on ppc64le architecture
Message-id: <20210113140908.457588-248-yauheni.kaliuta@redhat.com>
Patchwork-id: 348593
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 v2 248/291] libbpf: Fix build on ppc64le architecture
Bugzilla: 1874005
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874005

commit 3fb1a96a91120877488071a167d26d76be4be977
Author: Andrii Nakryiko <andriin@fb.com>
Date:   Tue Aug 18 09:44:56 2020 -0700

    libbpf: Fix build on ppc64le architecture

    On ppc64le we get the following warning:

      In file included from btf_dump.c:16:0:
      btf_dump.c: In function ‘btf_dump_emit_struct_def’:
      ../include/linux/kernel.h:20:17: error: comparison of distinct pointer types lacks a cast [-Werror]
        (void) (&_max1 == &_max2);  \
                       ^
      btf_dump.c:882:11: note: in expansion of macro ‘max’
          m_sz = max(0LL, btf__resolve_size(d->btf, m->type));
                 ^~~

    Fix by explicitly casting to __s64, which is a return type from
    btf__resolve_size().

    Fixes: 702eddc77a90 ("libbpf: Handle GCC built-in types for Arm NEON")
    Signed-off-by: Andrii Nakryiko <andriin@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20200818164456.1181661-1-andriin@fb.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>