[crypto] crypto/chcr: Add missing include file <linux/highmem.h>
Message-id: <20200701104937.29652-9-crecklin@redhat.com>
Patchwork-id: 321738
Patchwork-instance: patchwork
O-Subject: [RHEL 8.3 BZ1797945 v3 PATCH 08/18] crypto/chcr: Add missing include file <linux/highmem.h>
Bugzilla: 1797945
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: YueHaibing <yuehaibing@huawei.com>

drivers/crypto/chelsio/chcr_ktls.c: In function ‘chcr_short_record_handler’:
drivers/crypto/chelsio/chcr_ktls.c:1770:12: error: implicit declaration of function ‘kmap_atomic’;
 did you mean ‘in_atomic’? [-Werror=implicit-function-declaration]
    vaddr = kmap_atomic(skb_frag_page(f));
            ^~~~~~~~~~~

Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: dc05f3df8fac ("chcr: Handle first or middle part of record")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 21f6f946938693628721d68f13b8ea2afa789b4a)
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>