[tools] libperf: Fix arch include paths
Message-id: <20200415143309.16001-208-mpetlan@redhat.com>
Patchwork-id: 302473
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 208/469] libperf: Fix arch include paths
Bugzilla: 1818835
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>

Bugzilla: 1818835
https://bugzilla.redhat.com/show_bug.cgi?id=1818835

upstream
========
commit b81d39c7a1efb83caa3f4419939a46e96191abb6
Author: Jiri Olsa <jolsa@redhat.com>
Date: Tue Aug 20 14:46:24 2019 +0200

description
===========
Guenter Roeck reported problem with compilation when the ARCH is
specified:

  $ make ARCH=x86_64
  In file included from tools/include/asm/atomic.h:6:0,
                   from include/linux/atomic.h:5,
                   from tools/include/linux/refcount.h:41,
                   from cpumap.c:4: tools/include/asm/../../arch/x86/include/asm/atomic.h:11:10:
  fatal error: asm/cmpxchg.h: No such file or directory

The problem is that we don't use SRCARCH (the sanitized ARCH version)
and we don't get the proper include path.

Fixes: 314350491810 ("libperf: Make libperf.a part of the perf build")
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>