[x86] x86/resctrl: Remove unnecessary check for cbm_validate()
Message-id: <20190503123408.10382-79-prarit@redhat.com>
Patchwork-id: 252625
O-Subject: [RHEL8.1 BZ 1504489 78/79] x86/resctrl: Remove unnecessary check for cbm_validate()
Bugzilla: 1504489
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1504489

commit cb74635faa17cfa2991ddbe027596270af525c6d
Author: Babu Moger <Babu.Moger@amd.com>
Date:   Wed Nov 28 22:42:47 2018 +0000

    x86/resctrl: Remove unnecessary check for cbm_validate()

    The Smatch static checker reports the following error after commit:

      a36c5ff560fb ("x86/resctrl: Bring cbm_validate() into the resource structure"):

      arch/x86/kernel/cpu/resctrl/ctrlmondata.c:227 parse_cbm()
      error: uninitialized symbol 'cbm_val'.
      arch/x86/kernel/cpu/resctrl/ctrlmondata.c:236 parse_cbm()
      error: uninitialized symbol 'cbm_val'.

    This could happen if ->cbm_validate() is NULL which could leave cbm_val
    uninitialized.

    However, there is no case where ->cbm_validate() can be NULL as it is
    initialized based on a vendor check. So it is either an Intel or an AMD
    version it points to. And in both the cases it is initialized properly.
    Thus, remove the first check.

    Verified the fix running Smatch.

     [ bp: massage commit message. ]

    Fixes: a36c5ff560fb ("x86/resctrl: Bring cbm_validate() into the resource structure")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Babu Moger <babu.moger@amd.com>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Cc: Fenghua Yu <fenghua.yu@intel.com>
    Cc: "H. Peter Anvin" <hpa@zytor.com>
    Cc: Ingo Molnar <mingo@redhat.com>
    Cc: Reinette Chatre <reinette.chatre@intel.com>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: x86-ml <x86@kernel.org>
    Link: https://lkml.kernel.org/r/20181128224234.22998-1-babu.moger@amd.com

Cc: Prarit Bhargava <prarit@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>