[netdrv] cxgb4: reduce kernel stack usage in cudbg_collect_mem_region()
Message-id: <b1bb6eee690f189a6754fd3546a3adb3c2e61e48.1570819415.git.jtoppins@redhat.com>
Patchwork-id: 278754
O-Subject: [PATCH RHEL-8.2 21/24] cxgb4: reduce kernel stack usage in cudbg_collect_mem_region()
Bugzilla: 1725776
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

The cudbg_collect_mem_region() and cudbg_read_fw_mem() both use several
hundred kilobytes of kernel stack space. One gets inlined into the other,
which causes the stack usage to be combined beyond the warning limit
when building with clang:

drivers/net/ethernet/chelsio/cxgb4/cudbg_lib.c:1057:12: error: stack frame size of 1244 bytes in function 'cudbg_collect_mem_region' [-Werror,-Wframe-larger-than=]

Restructuring cudbg_collect_mem_region() lets clang do the same
optimization that gcc does and reuse the stack slots as it can
see that the large variables are never used together.

A better fix might be to avoid using cudbg_meminfo on the stack
altogether, but that requires a larger rewrite.

Fixes: a1c69520f785 ("cxgb4: collect MC memory dump")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 752c2ea2d8e7c23b0f64e2e7d4337f3604d44c9f)
Bugzilla: 1725776
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=23896583
Tested: build and boot
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>