[net] tipc: not enable tipc when ipv6 works as a module
Message-id: <68cea59318fa95b4a106c07f0a17de6de70a3f3b.1597916200.git.lxin@redhat.com>
Patchwork-id: 324370
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net PATCH 3/4] tipc: not enable tipc when ipv6 works as a module
Bugzilla: 1862458
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Andrea Claudi <aclaudi@redhat.com>

Brew Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=30820765
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1862458
Upstream Status: net.git commit c530189905efe
Tested: bug reproducer, CKI and tipcutils.git

Conflicts: \
  - Different context due to missing commit a7f7f6248d97.

commit c530189905efe91b6a464db4ec1b56b4c069609f
Author: Xin Long <lucien.xin@gmail.com>
Date:   Sun Aug 16 17:32:03 2020 +0800

    tipc: not enable tipc when ipv6 works as a module

    When using ipv6_dev_find() in one module, it requires ipv6 not to
    work as a module. Otherwise, this error occurs in build:

      undefined reference to `ipv6_dev_find'.

    So fix it by adding "depends on IPV6 || IPV6=n" to tipc/Kconfig,
    as it does in sctp/Kconfig.

    Fixes: 5a6f6f579178 ("tipc: set ub->ifindex for local ipv6 address")
    Reported-by: kernel test robot <lkp@intel.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Xin Long <lucien.xin@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Xin Long <lxin@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>