[drm] drm/i915: Add missing include file <linux/math64.h>
Message-id: <20200204211916.125317-87-lyude@redhat.com>
Patchwork-id: 294458
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 drm PATCH v2 86/91] drm/i915: Add missing include file <linux/math64.h>
Bugzilla: 1792565
RH-Acked-by: Dave Airlie <airlied@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Michel Dänzer <mdaenzer@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1792565
Upstream: since v5.4.14

commit 4ee1d755edf3e4820b81926d3c86b7da78195f09
Author:     YueHaibing <yuehaibing@huawei.com>
AuthorDate: Tue Jan 7 21:50:14 2020 +0800
Commit:     Greg Kroah-Hartman <gregkh@linuxfoundation.org>
CommitDate: Thu Jan 23 08:22:38 2020 +0100

    drm/i915: Add missing include file <linux/math64.h>

    commit ea38aa2ea5b0969776f0a47f174ce928a22be803 upstream.

    Fix build error:
    ./drivers/gpu/drm/i915/selftests/i915_random.h: In function i915_prandom_u32_max_state:
    ./drivers/gpu/drm/i915/selftests/i915_random.h:48:23: error:
     implicit declaration of function mul_u32_u32; did you mean mul_u64_u32_div? [-Werror=implicit-function-declaration]
      return upper_32_bits(mul_u32_u32(prandom_u32_state(state), ep_ro));

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: 7ce5b6850b47 ("drm/i915/selftests: Use mul_u32_u32() for 32b x 32b -> 64b result")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Reviewed-by: Chris Wilson <chris@chris-wilson.co.uk>
    Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>
    Link: https://patchwork.freedesktop.org/patch/msgid/20200107135014.36472-1-yuehaibing@huawei.com
    (cherry picked from commit 62bf5465b26d1f502430b9c654be7d16bf2e242d)
    Signed-off-by: Joonas Lahtinen <joonas.lahtinen@linux.intel.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Lyude Paul <lyude@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>