[usb] usb: renesas_usbhs: mark PM functions as __maybe_unused
Message-id: <20200407161320.17414-419-torez@redhat.com>
Patchwork-id: 300156
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 418/983] usb: renesas_usbhs: mark PM functions as __maybe_unused
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit eaf3074e0a8c2a39c4c14aa8ef1c2ec09ace9c79
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Dec 11 11:06:25 2018 +0100

    usb: renesas_usbhs: mark PM functions as __maybe_unused

    Without CONFIG_PM, we get a new build warning here:

    drivers/usb/renesas_usbhs/common.c:860:12: error: 'usbhsc_resume' defined but not used [-Werror=unused-function]
     static int usbhsc_resume(struct device *dev)
                ^~~~~~~~~~~~~
    drivers/usb/renesas_usbhs/common.c:844:12: error: 'usbhsc_suspend' defined but not used [-Werror=unused-function]
     static int usbhsc_suspend(struct device *dev)
                ^~~~~~~~~~~~~~

    Fixes: d54d334e75b9 ("usb: renesas_usbhs: Use SIMPLE_DEV_PM_OPS macro")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>