KVM: PPC: Book3S HV: Include prototypes
Bugzilla: http://bugzilla.redhat.com/1945745

commit d834915e8ee28884f1180dc566ba77c8768ec00a
Author: Cédric Le Goater <clg@kaod.org>
Date:   Mon Jan 4 15:32:02 2021 +0100

    KVM: PPC: Book3S HV: Include prototypes

    It fixes these W=1 compile errors :

     CC [M]  arch/powerpc/kvm/book3s_64_mmu_hv.o
    ../arch/powerpc/kvm/book3s_64_mmu_hv.c:879:5: error: no previous prototype for ‘kvm_unmap_hva_range_hv’ [-Werror=missing-prototypes]
      879 | int kvm_unmap_hva_range_hv(struct kvm *kvm, unsigned long start, unsigned long end)
          |     ^~~~~~~~~~~~~~~~~~~~~~
    ../arch/powerpc/kvm/book3s_64_mmu_hv.c:888:6: error: no previous prototype for ‘kvmppc_core_flush_memslot_hv’ [-Werror=missing-prototypes]
      888 | void kvmppc_core_flush_memslot_hv(struct kvm *kvm,
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../arch/powerpc/kvm/book3s_64_mmu_hv.c:970:5: error: no previous prototype for ‘kvm_age_hva_hv’ [-Werror=missing-prototypes]
      970 | int kvm_age_hva_hv(struct kvm *kvm, unsigned long start, unsigned long end)
          |     ^~~~~~~~~~~~~~
    ../arch/powerpc/kvm/book3s_64_mmu_hv.c:1011:5: error: no previous prototype for ‘kvm_test_age_hva_hv’ [-Werror=missing-prototypes]
     1011 | int kvm_test_age_hva_hv(struct kvm *kvm, unsigned long hva)
          |     ^~~~~~~~~~~~~~~~~~~
    ../arch/powerpc/kvm/book3s_64_mmu_hv.c:1019:6: error: no previous prototype for ‘kvm_set_spte_hva_hv’ [-Werror=missing-prototypes]
     1019 | void kvm_set_spte_hva_hv(struct kvm *kvm, unsigned long hva, pte_t pte)
          |      ^~~~~~~~~~~~~~~~~~~

    Signed-off-by: Cédric Le Goater <clg@kaod.org>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20210104143206.695198-20-clg@kaod.org

Signed-off-by: Greg Kurz <gkurz@redhat.com>