[redhat] disable more kabi switches for gcov build
Message-id: <2e9b8ebc97c9eb430116a118dc8003f44870abf9.1575989369.git.jstancek@redhat.com>
Patchwork-id: 291825
O-Subject: [RHEL8.2 PATCH] redhat: disable more kabi switches for gcov build
Bugzilla: 1781513
RH-Acked-by: Bruno Eduardo de Oliveira Meneguele <bmeneg@redhat.com>
RH-Acked-by: Čestmír Kalina <ckalina@redhat.com>
RH-Acked-by: Herton R. Krzesinski <herton@redhat.com>

Bugzilla: 1781513
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=25255969
Upstream: RHEL only
Tested: make rh-srpm-gcov + compile only in brew

gcov build disables with_kabichk, which makes Source300 undefined.
But there are still couple kabi switches which use SOURCE300,
which can cause brew build to fail:

  + tar xjvf '%{SOURCE300}' -C /builddir/build/BUILDROOT/kernel-4.18.0-161.el8.gcov.noarch/lib/modules/
  tar (child): %{SOURCE300}: Cannot open: No such file or directory
  tar (child): Error is not recoverable: exiting now
  tar: Child returned status 2
  tar: Error is not recoverable: exiting now
  RPM build errors:
  error: Bad exit status from /var/tmp/rpm-tmp.lcnD1l (%install)
      Bad exit status from /var/tmp/rpm-tmp.lcnD1l (%install)
  Child return code was: 1

Signed-off-by: Jan Stancek <jstancek@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>