[tools] perf probe: Fix to probe an inline function which has no entry pc
Message-id: <20191218212502.14325-7-mpetlan@redhat.com>
Patchwork-id: 292110
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 BZ1760227 v2 06/22] perf probe: Fix to probe an inline function which has no entry pc
Bugzilla: 1760227
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1760227
https://bugzilla.redhat.com/show_bug.cgi?id=1760227

upstream
========
commit eb6933b29d20bf2c3053883d409a53f462c1a3ac
Author: Masami Hiramatsu <mhiramat@kernel.org>
Date: Fri Oct 25 17:46:43 2019 +0900

description
===========
Fix perf probe to probe an inlne function which has no entry pc
or low pc but only has ranges attribute.

This seems very rare case, but I could find a few examples, as
same as probe_point_search_cb(), use die_entrypc() to get the
entry address in probe_point_inline_cb() too.

Without this patch:

  # perf probe -D __amd_put_nb_event_constraints
  Failed to get entry address of __amd_put_nb_event_constraints.
  Probe point '__amd_put_nb_event_constraints' not found.
    Error: Failed to add events.

With this patch:

  # perf probe -D __amd_put_nb_event_constraints
  p:probe/__amd_put_nb_event_constraints amd_put_event_constraints+43

Committer testing:

Before:

  [root@quaco ~]# perf probe -D __amd_put_nb_event_constraints
  Failed to get entry address of __amd_put_nb_event_constraints.
  Probe point '__amd_put_nb_event_constraints' not found.
    Error: Failed to add events.
  [root@quaco ~]#

After:

  [root@quaco ~]# perf probe -D __amd_put_nb_event_constraints
  p:probe/__amd_put_nb_event_constraints _text+33789
  [root@quaco ~]#

Fixes: 4ea42b181434 ("perf: Add perf probe subcommand, a kprobe-event setup helper")
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>