[usb] USB: OHCI: remove space before open square bracket '['
Message-id: <20200407161320.17414-772-torez@redhat.com>
Patchwork-id: 300507
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 771/983] USB: OHCI: remove space before open square bracket '['
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit 4e4feeec4e6cf6d0e14a45470c7f232cb685336b
Author: Naveen Kumar Parna <parna.naveenkumar@gmail.com>
Date:   Thu May 16 20:49:23 2019 +0530

    USB: OHCI: remove space before open square bracket '['

    This patch removes following checkpatch.pl error in usb/host/ohci-pci.c file.
    ERROR: space prohibited before open square bracket '['

    Signed-off-by: Naveen Kumar Parna <parna.naveenkumar@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>