[tools] tools: bpftool: fix infinite loop in map create
Message-id: <20190604085256.3304-605-yauheni.kaliuta@redhat.com>
Patchwork-id: 262604
O-Subject: [RHEL8.1 PATCH v2 605/627] tools: bpftool: fix infinite loop in map create
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit 8694d8c1f82cccec9380e0d3720b84eee315dfb7
Author: Alban Crequy <alban@kinvolk.io>
Date:   Fri Apr 12 14:40:50 2019 +0200

    tools: bpftool: fix infinite loop in map create

    "bpftool map create" has an infinite loop on "while (argc)". The error
    case is missing.

    Symptoms: when forgetting to type the keyword 'type' in front of 'hash':
    $ sudo bpftool map create /sys/fs/bpf/dir/foobar hash key 8 value 8 entries 128
    (infinite loop, taking all the CPU)
    ^C

    After the patch:
    $ sudo bpftool map create /sys/fs/bpf/dir/foobar hash key 8 value 8 entries 128
    Error: unknown arg hash

    Fixes: 0b592b5a01be ("tools: bpftool: add map create command")
    Signed-off-by: Alban Crequy <alban@kinvolk.io>
    Reviewed-by: Quentin Monnet <quentin.monnet@netronome.com>
    Acked-by: Song Liu <songliubraving@fb.com>
    Reviewed-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>