dm writecache: remove BUG() and fail gracefully instead
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1949682

Signed-off-by: Mike Snitzer <snitzer@redhat.com>

commit 857c4c0a8b2888d806f4308c58f59a6a81a1dee9
Author: Mike Snitzer <snitzer@redhat.com>
Date:   Fri Nov 13 14:52:28 2020 -0800

    dm writecache: remove BUG() and fail gracefully instead

    Building on arch/s390/ results in this build error:

    cc1: some warnings being treated as errors
    ../drivers/md/dm-writecache.c: In function 'persistent_memory_claim':
    ../drivers/md/dm-writecache.c:323:1: error: no return statement in function returning non-void [-Werror=return-type]

    Fix this by replacing the BUG() with an -EOPNOTSUPP return.

    Fixes: 48debafe4f2f ("dm: add writecache target")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>