[kernel] perf/core: Fix reversed NULL check in perf_event_groups_less()
Message-id: <20200605130702.31420-16-mpetlan@redhat.com>
Patchwork-id: 317396
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 015/112] perf/core: Fix reversed NULL check in perf_event_groups_less()
Bugzilla: 1841130
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1841130
https://bugzilla.redhat.com/show_bug.cgi?id=1841130

upstream
========
commit a6763625ae6f8aa5ee82fcd8fa4e5e38db20dbc6
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date: Thu Mar 12 13:56:37 2020 +0300

description
===========
This NULL check is reversed so it leads to a Smatch warning and
presumably a NULL dereference.

    kernel/events/core.c:1598 perf_event_groups_less()
    error: we previously assumed 'right->cgrp->css.cgroup' could be null
	(see line 1590)

Fixes: 95ed6c707f26 ("perf/cgroup: Order events in RB tree by cgroup id")
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>