ibmvnic: remove excessive irqsave
Bugzilla: http://bugzilla.redhat.com/1922193
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37531607

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/
commit 69cdb7947adb816fc9325b4ec02a6dddd5070b82
Author: Junlin Yang <yangjunlin@yulong.com>
Date: Fri, 5 Mar 2021 16:48:39 +0800

    ibmvnic_remove locks multiple spinlocks while disabling interrupts:
    spin_lock_irqsave(&adapter->state_lock, flags);
    spin_lock_irqsave(&adapter->rwi_lock, flags);

    As reported by coccinelle, the second _irqsave() overwrites the value
    saved in 'flags' by the first _irqsave(),   therefore when the second
    _irqrestore() comes,the value in 'flags' is not valid,the value saved
    by the first _irqsave() has been lost.
    This likely leads to IRQs remaining disabled. So remove the second
    _irqsave():
    spin_lock_irqsave(&adapter->state_lock, flags);
    spin_lock(&adapter->rwi_lock);

    Generated by: ./scripts/coccinelle/locks/flags.cocci
    ./drivers/net/ethernet/ibm/ibmvnic.c:5413:1-18:
    ERROR: nested lock+irqsave that reuses flags from line 5404.

Fixes: 4a41c421f367 ("ibmvnic: serialize access to work queue on remove")
Signed-off-by: Junlin Yang <yangjunlin@yulong.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Diego Domingos <didoming@redhat.com>