[kernel] fixed_phy: Add forward declaration for struct gpio_desc;
Message-id: <7c629f86173b0a394ac0e64aec1270d755b1d4cf.1573676614.git.poros@redhat.com>
Patchwork-id: 286611
O-Subject: [RHEL8.2 PATCH 314/320] net: fixed_phy: Add forward declaration for struct gpio_desc;
Bugzilla: 1772010
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1772010

Upstream commit(s):
commit ebe26aca98fcf9fbe5017b5cbe216413cee69df5
Author: Moritz Fischer <mdf@kernel.org>
Date:   Tue Sep 3 11:46:52 2019 -0700

    net: fixed_phy: Add forward declaration for struct gpio_desc;

    Add forward declaration for struct gpio_desc in order to address
    the following:

    ./include/linux/phy_fixed.h:48:17: error: 'struct gpio_desc' declared inside parameter list [-Werror]
    ./include/linux/phy_fixed.h:48:17: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]

    Fixes: 71bd106d2567 ("net: fixed-phy: Add fixed_phy_register_with_gpiod() API")
    Signed-off-by: Moritz Fischer <mdf@kernel.org>
    Reviewed-by: Florian Fainelli <f.fainelli@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>