[tools] perf evsel: Switch to libperf's cpumap.h
Message-id: <20200415143309.16001-229-mpetlan@redhat.com>
Patchwork-id: 302468
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 229/469] perf evsel: Switch to libperf's cpumap.h
Bugzilla: 1818835
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>

Bugzilla: 1818835
https://bugzilla.redhat.com/show_bug.cgi?id=1818835

upstream
========
commit f7004f5990e230710112b89f2f11777e5e64e258
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Wed Aug 21 16:39:29 2019 -0300

description
===========
We don't need what is in perf's util/cpumap.h, just the struct cpu_map
that is in libperf's internal/cpumap.h file to cover this one case:

  tools/perf/util/evsel.h:215:27: error: dereferencing pointer to incomplete type ‘struct perf_cpu_map’
  215 |  return evsel__cpus(evsel)->nr;

So switch to libperf's cpumap.h and add some missing struct foward
declarations and include sys/types.h to get pid_t.

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>