[fs] io_uring: fix missing kmap() declaration on powerpc
Message-id: <20200604174034.2713-155-jmoyer@redhat.com>
Patchwork-id: 317140
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 154/441] io_uring: fix missing kmap() declaration on powerpc
Bugzilla: 1784478
RH-Acked-by: Ming Lei <ming.lei@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Jens Axboe <axboe@kernel.dk>

BZ: 1784478
Brew: 28979848

commit aa4c3967756c6c576a38a23ac511be211462a6b7
Author: Jens Axboe <axboe@kernel.dk>
Date:   Fri Nov 29 10:14:00 2019 -0700

    io_uring: fix missing kmap() declaration on powerpc

    Christophe reports that current master fails building on powerpc with
    this error:

       CC      fs/io_uring.o
    fs/io_uring.c: In function ‘loop_rw_iter’:
    fs/io_uring.c:1628:21: error: implicit declaration of function ‘kmap’
    [-Werror=implicit-function-declaration]
         iovec.iov_base = kmap(iter->bvec->bv_page)
                          ^
    fs/io_uring.c:1628:19: warning: assignment makes pointer from integer
    without a cast [-Wint-conversion]
         iovec.iov_base = kmap(iter->bvec->bv_page)
                        ^
    fs/io_uring.c:1643:4: error: implicit declaration of function ‘kunmap’
    [-Werror=implicit-function-declaration]
         kunmap(iter->bvec->bv_page);
         ^

    which is caused by a missing highmem.h include. Fix it by including
    it.

    Fixes: 311ae9e159d8 ("io_uring: fix dead-hung for non-iter fixed rw")
    Reported-by: Christophe Leroy <christophe.leroy@c-s.fr>
    Tested-by: Christophe Leroy <christophe.leroy@c-s.fr>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>