[sound] ALSA: ASoC: SOF: core: fix undefined nocodec reference
Message-id: <15580872947136052-2085-patchset-jkysela@redhat.com>
Patchwork-id: 258283
O-Subject: [RHEL 8.1 PATCH 2084/2119] ALSA: ASoC: SOF: core: fix undefined nocodec reference
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

The existing code mistakenly uses IS_ENABLED in C code instead of as
in conditional compilation, leading to the following error:

ld: sound/soc/sof/core.o: in function `sof_machine_check':
sound/soc/sof/core.c:279: undefined reference to `sof_nocodec_setup'

Fix by using #if !IS_ENABLED()

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit ce38a75089f70f6380fc63a5478a7659b4eb3f47)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>