[tools] libbpf: Show supported ELF section names when failing to guess prog/attach type
Message-id: <20190925141552.30691-17-yauheni.kaliuta@redhat.com>
Patchwork-id: 274552
O-Subject: [RHEL8.2 PATCH v2 017/214] libbpf: Show supported ELF section names when failing to guess prog/attach type
Bugzilla: 1747341
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747341

commit c76e4c228b053eb108e6c3221bef338aa2c98fac
Author: Taeung Song <treeze.taeung@gmail.com>
Date:   Mon Jan 21 22:06:38 2019 +0900

    libbpf: Show supported ELF section names when failing to guess prog/attach type

    We need to let users check their wrong ELF section name with proper
    ELF section names when they fail to get a prog/attach type from it.
    Because users can't realize libbpf guess prog/attach types from given
    ELF section names. For example, when a 'cgroup' section name of a
    BPF program is used, show available ELF section names(types).

    Before:

        $ bpftool prog load bpf-prog.o /sys/fs/bpf/prog1
        Error: failed to guess program type based on ELF section name cgroup

    After:

        libbpf: failed to guess program type based on ELF section name 'cgroup'
        libbpf: supported section(type) names are: socket kprobe/ kretprobe/ classifier action tracepoint/ raw_tracepoint/ xdp perf_event lwt_in lwt_out lwt_xmit lwt_seg6local cgroup_skb/ingress cgroup_skb/egress cgroup/skb cgroup/sock cgroup/post_bind4 cgroup/post_bind6 cgroup/dev sockops sk_skb/stream_parser sk_skb/stream_verdict sk_skb sk_msg lirc_mode2 flow_dissector cgroup/bind4 cgroup/bind6 cgroup/connect4 cgroup/connect6 cgroup/sendmsg4 cgroup/sendmsg6

    Signed-off-by: Taeung Song <treeze.taeung@gmail.com>
    Cc: Quentin Monnet <quentin.monnet@netronome.com>
    Cc: Jakub Kicinski <jakub.kicinski@netronome.com>
    Cc: Andrey Ignatov <rdna@fb.com>
    Reviewed-by: Quentin Monnet <quentin.monnet@netronome.com>
    Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>