[net] netfilter: nf_tables_offload: avoid excessive stack usage
Message-id: <aed47e3f03f54f9511941e2631d49b94e3557509.1589567677.git.mleitner@redhat.com>
Patchwork-id: 310002
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 036/146] netfilter: nf_tables_offload: avoid excessive stack usage
Bugzilla: 1811193
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Phil Sutter <psutter@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1811193
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28605855

commit b44492afd2b123f605c3aa2cbeee3398d9ebbcc5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Sep 6 17:12:30 2019 +0200

    netfilter: nf_tables_offload: avoid excessive stack usage

    The nft_offload_ctx structure is much too large to put on the
    stack:

    net/netfilter/nf_tables_offload.c:31:23: error: stack frame size of 1200 bytes in function 'nft_flow_rule_create' [-Werror,-Wframe-larger-than=]

    Use dynamic allocation here, as we do elsewhere in the same
    function.

    Fixes: c9626a2cbdb2 ("netfilter: nf_tables: add hardware offload support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>