[netdrv] iwlwifi: dbg_ini: fix compile time assert build errors
Message-id: <20191126234256.26042-389-jarod@redhat.com>
Patchwork-id: 289641
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 388/796] iwlwifi: dbg_ini: fix compile time assert build errors
Bugzilla: 1776606
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit 1f66072503316134873060b24b7895dbbcccf00e
Author: Mauro Rossi <issor.oruam@gmail.com>
Date:   Thu Aug 1 09:04:34 2019 +0200

    iwlwifi: dbg_ini: fix compile time assert build errors

    This patch fixes and preserves existing code style, and readability,
    for IWL_ERR() and IWL_WARN() macros invocations recently added in dbg.c

    Fixes the following build errors with Android build system:

    /home/utente/pie-x86_kernel/kernel/drivers/net/wireless/intel/iwlwifi/fw/dbg.c: In function '_iwl_fw_dbg_apply_point':
    /home/utente/pie-x86_kernel/kernel/drivers/net/wireless/intel/iwlwifi/fw/dbg.c:2445:3:
    error: call to '__compiletime_assert_2446' declared with attribute error: BUILD_BUG_ON failed: err_str[sizeof(err_str) - 2] != '\n'
    /home/utente/pie-x86_kernel/kernel/drivers/net/wireless/intel/iwlwifi/fw/dbg.c:2451:3:
    error: call to '__compiletime_assert_2452' declared with attribute error: BUILD_BUG_ON failed: err_str[sizeof(err_str) - 2] != '\n'
    ...
    /home/utente/pie-x86_kernel/kernel/drivers/net/wireless/intel/iwlwifi/fw/dbg.c:2789:5:
    error: call to '__compiletime_assert_2790' declared with attribute error: BUILD_BUG_ON failed: invalid_ap_str[sizeof(invalid_ap_str) - 2] != '\n'
    /home/utente/pie-x86_kernel/kernel/drivers/net/wireless/intel/iwlwifi/fw/dbg.c:2800:5:
    error: call to '__compiletime_assert_2801' declared with attribute error: BUILD_BUG_ON failed: invalid_ap_str[sizeof(invalid_ap_str) - 2] != '\n'

    Fixes: 427ab6385cf3 ("iwlwifi: dbg_ini: enforce apply point early on buffer allocation tlv")
    Fixes: 57d88b116175 ("iwlwifi: dbg_ini: support debug info TLV")
    Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>
    Signed-off-by: Johannes Berg <johannes.berg@intel.com>
    Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
    Tested-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>