[net] mptcp: Fix undefined mptcp_handle_ipv6_mapped for modular IPV6
Message-id: <20200515101824.19445-31-fwestpha@redhat.com>
Patchwork-id: 309898
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 30/38] mptcp: Fix undefined mptcp_handle_ipv6_mapped for modular IPV6
Bugzilla: 1835796
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1835796
Upstream Status: commit 31484d56ca95

commit 31484d56ca9511e62c08626db338d2aaafb3aa3f
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Thu Jan 30 10:45:26 2020 +0100

    mptcp: Fix undefined mptcp_handle_ipv6_mapped for modular IPV6

    If CONFIG_MPTCP=y, CONFIG_MPTCP_IPV6=n, and CONFIG_IPV6=m:

        ERROR: "mptcp_handle_ipv6_mapped" [net/ipv6/ipv6.ko] undefined!

    This does not happen if CONFIG_MPTCP_IPV6=y, as CONFIG_MPTCP_IPV6
    selects CONFIG_IPV6, and thus forces CONFIG_IPV6 builtin.

    As exporting a symbol for an empty function would be a bit wasteful, fix
    this by providing a dummy version of mptcp_handle_ipv6_mapped() for the
    CONFIG_MPTCP_IPV6=n case.

    Rename mptcp_handle_ipv6_mapped() to mptcpv6_handle_mapped(), to make it
    clear this is a pure-IPV6 function, just like mptcpv6_init().

    Fixes: cec37a6e41aae7bf ("mptcp: Handle MP_CAPABLE options for outgoing connections")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>