[lib] lib/ubsan.c: don't mark __ubsan_handle_builtin_unreachable as noreturn
Message-id: <20190701141101.27482-3-jmarchan@redhat.com>
Patchwork-id: 266000
O-Subject: [RHEL8.1 BZ 1571628 2/5] lib/ubsan.c: don't mark __ubsan_handle_builtin_unreachable as noreturn
Bugzilla: 1571628
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1571628

commit 1c23b4108d716cc848b38532063a8aca4f86add8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Nov 16 15:08:35 2018 -0800

    lib/ubsan.c: don't mark __ubsan_handle_builtin_unreachable as noreturn

    gcc-8 complains about the prototype for this function:

      lib/ubsan.c:432:1: error: ignoring attribute 'noreturn' in declaration of a built-in function '__ubsan_handle_builtin_unreachable' because it conflicts with attribute 'const' [-Werror=attributes]

    This is actually a GCC's bug. In GCC internals
    __ubsan_handle_builtin_unreachable() declared with both 'noreturn' and
    'const' attributes instead of only 'noreturn':

       https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84210

    Workaround this by removing the noreturn attribute.

    [aryabinin: add information about GCC bug in changelog]
    Link: http://lkml.kernel.org/r/20181107144516.4587-1-aryabinin@virtuozzo.com
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Andrey Ryabinin <aryabinin@virtuozzo.com>
    Acked-by: Olof Johansson <olof@lixom.net>
    Cc: <stable@vger.kernel.org>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Cc: Jerome Marchand <jmarchan@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>