[redhat] kernel.spec: fix 'make scripts' for kernel-devel package
Message-id: <20200515164047.1186710-1-bmasney@redhat.com>
Patchwork-id: 309938
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1718979 PATCH v2] [redhat] kernel.spec: fix 'make scripts' for kernel-devel package
Bugzilla: 1718979
RH-Acked-by: Herton R. Krzesinski <herton@redhat.com>
RH-Acked-by: Jan Stancek <jstancek@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Bruno Meneguele <bmeneg@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1718979
Upstream status: RHEL only
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28604209
Tested: On an aarch64 board at home

Running 'make scripts' in /usr/src/kernels/$VERSION triggers the
following error:

    scripts/selinux/genheaders/genheaders.c:19:10: fatal error:
    classmap.h: No such file or directory

Let's fix that by including the necessary two files from the
directory security/selinux/include/ in the kernel-devel package.
Once those files are added, another error is triggered:

    scripts/sortextable.c:31:10: fatal error: tools/be_byteshift.h:
    No such file or directory

Let's correct that error by adding two more files from tools/include/
to the kernel-devel package as well. This will get 'make scripts'
working.

This change adds 20K (before compression) to the kernel-devel package.

Signed-off-by: Brian Masney <bmasney@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>