[tools] perf jvmti: Address gcc string overflow warning for strncpy()
Message-id: <20191126133941.32492-59-mpetlan@redhat.com>
Patchwork-id: 289069
O-Subject: [RHEL8.2 BZ1743210 v2 058/327] perf jvmti: Address gcc string overflow warning for strncpy()
Bugzilla: 1743210
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1743210
https://bugzilla.redhat.com/show_bug.cgi?id=1743210

upstream
========
commit dab0f4ebb22ee6d16051011d624cff79a99baa8a
Author: Jiri Olsa <jolsa@redhat.com>
Date: Fri May 31 15:13:21 2019 +0200

description
===========
We are getting false positive gcc warning when we compile with gcc9 (9.1.1):

     CC       jvmti/libjvmti.o
   In file included from /usr/include/string.h:494,
                    from jvmti/libjvmti.c:5:
   In function strncpy,
       inlined from copy_class_filename.constprop at jvmti/libjvmti.c:166:3:
   /usr/include/bits/string_fortified.h:106:10: error: __builtin_strncpy specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
     106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
         |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   jvmti/libjvmti.c: In function copy_class_filename.constprop:
   jvmti/libjvmti.c:165:26: note: length computed here
     165 |   size_t file_name_len = strlen(file_name);
         |                          ^~~~~~~~~~~~~~~~~
   cc1: all warnings being treated as errors

As per Arnaldo's suggestion use strlcpy(), which does the same thing and keeps
gcc silent.

Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>