[netdrv] net/mlx5e: Make mlx5e_dcbnl_ops static
Message-id: <20201202091426.24995-168-ahleihel@redhat.com>
Patchwork-id: 342769
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1858560 v2 167/199] net/mlx5e: Make mlx5e_dcbnl_ops static
Bugzilla: 1858560
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1858560
Upstream: v5.8-rc1

commit eb24387183d37f2f4f456654ef92679b1556f8df
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Fri May 29 00:36:10 2020 -0700

    net/mlx5e: Make mlx5e_dcbnl_ops static

    Fix sparse warning:
    drivers/net/ethernet/mellanox/mlx5/core/en_dcbnl.c:988:29:
    error: symbol 'mlx5e_dcbnl_ops' was not declared. Should it be static?

    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>