[tools] tool: make key and value optional in update command
Message-id: <20190925141552.30691-7-yauheni.kaliuta@redhat.com>
Patchwork-id: 274545
O-Subject: [RHEL8.2 PATCH v2 007/214] bpftool: make key and value optional in update command
Bugzilla: 1747341
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747341

commit 7d7209cb9afdfc3dfcdc1b45013e62afb1ad71b6
Author: Stanislav Fomichev <sdf@google.com>
Date:   Wed Jan 16 11:09:59 2019 -0800

    bpftool: make key and value optional in update command

    Bpftool expects both key and value for 'update' operations. For some
    map types, key should not be specified. Support updating those map types.

    Before:
    bpftool map create /sys/fs/bpf/q type queue value 4 entries 10 name q
    bpftool map update pinned /sys/fs/bpf/q value 0 1 2 3
    Error: did not find key

    After:
    bpftool map create /sys/fs/bpf/q type queue value 4 entries 10 name q
    bpftool map update pinned /sys/fs/bpf/q value 0 1 2 3

    Signed-off-by: Stanislav Fomichev <sdf@google.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>