[acpi] gpio: merrifield: Fix build err without CONFIG_ACPI
Message-id: <20191114232800.14205-28-lyude@redhat.com>
Patchwork-id: 287348
O-Subject: [RHEL8.2 drm v3 27/39] gpio: merrifield: Fix build err without CONFIG_ACPI
Bugzilla: 1731110
RH-Acked-by: Karol Herbst <kherbst@redhat.com>
RH-Acked-by: Ben Skeggs <bskeggs@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1731110
Upstream: since v5.2

commit fe066621c7966fe47fa17c6be6fd81adb3c0509f
Author:     YueHaibing <yuehaibing@huawei.com>
AuthorDate: Fri Apr 12 23:19:11 2019 +0800
Commit:     Rafael J. Wysocki <rafael.j.wysocki@intel.com>
CommitDate: Tue Apr 23 11:30:59 2019 +0200

    gpio: merrifield: Fix build err without CONFIG_ACPI

    When building CONFIG_ACPI is not set
    gcc warn this:

    drivers/gpio/gpio-merrifield.c: In function mrfld_gpio_get_pinctrl_dev_name:
    drivers/gpio/gpio-merrifield.c:388:19: error: dereferencing pointer to incomplete type struct acpi_device
       put_device(&adev->dev);
                       ^~

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: d00d2109c367 ("gpio: merrifield: Convert to use acpi_dev_get_first_match_dev()")
    Suggested-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Acked-by: Linus Walleij <linus.walleij@linaro.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>

Signed-off-by: Lyude Paul <lyude@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>