[kernel] bpf: Fix bpf_prog_test_run_tracing for !CONFIG_NET
Message-id: <20200610045258.353158-71-yauheni.kaliuta@redhat.com>
Patchwork-id: 319389
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 071/235] bpf: Fix bpf_prog_test_run_tracing for !CONFIG_NET
Bugzilla: 1845114
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1845114

commit 3e7c67d90e3ed2f34fce42699f11b150dd1d3999
Author: KP Singh <kpsingh@google.com>
Date:   Thu Mar 5 23:01:27 2020 +0100

    bpf: Fix bpf_prog_test_run_tracing for !CONFIG_NET

    test_run.o is not built when CONFIG_NET is not set and
    bpf_prog_test_run_tracing being referenced in bpf_trace.o causes the
    linker error:

    ld: kernel/trace/bpf_trace.o:(.rodata+0x38): undefined reference to
     `bpf_prog_test_run_tracing'

    Add a __weak function in bpf_trace.c to handle this.

    Fixes: da00d2f117a0 ("bpf: Add test ops for BPF_PROG_TYPE_TRACING")
    Signed-off-by: KP Singh <kpsingh@google.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20200305220127.29109-1-kpsingh@chromium.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>