[netdrv] cxgb4: fix 64-bit division on i386
Message-id: <20200609160508.1739-17-viskulka@redhat.com>
Patchwork-id: 318802
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1828665 v2 16/54] cxgb4: fix 64-bit division on i386
Bugzilla: 1828665
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1828665

commit 97c20ea8a115b405288404d8c84a90f43425630d
Author: Rahul Lakkireddy <rahul.lakkireddy@chelsio.com>
Date:   Fri Nov 8 20:05:22 2019 +0530

    cxgb4: fix 64-bit division on i386

    Fix following compile error on i386 architecture.

    ERROR: "__udivdi3" [drivers/net/ethernet/chelsio/cxgb4/cxgb4.ko] undefined!

    Fixes: 0e395b3cb1fb ("cxgb4: add FLOWC based QoS offload")
    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Rahul Lakkireddy <rahul.lakkireddy@chelsio.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Cc: Jarod Wilson <jarod@redhat.com>
Cc: Jonathan Toppins <jtoppins@redhat.com>
Cc: David Arcari <darcari@redhat.com>
Cc: Steve Best <sbest@redhat.com>
Cc: Vishal Kulkarni <viskulka@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>