[net] sched: Make NET_ACT_CT depends on NF_NAT
Message-id: <20191017202558.21496-12-ivecera@redhat.com>
Patchwork-id: 279910
O-Subject: [RHEL-8.2 net PATCH 11/14] net/sched: Make NET_ACT_CT depends on NF_NAT
Bugzilla: 1737820
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1737820

Upstream commit(s):
commit f11fe1dae1c46762a9a7b0dd142b6bfebe7783ff
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Tue Jul 16 15:16:02 2019 +0800

    net/sched: Make NET_ACT_CT depends on NF_NAT

    If NF_NAT is m and NET_ACT_CT is y, build fails:

    net/sched/act_ct.o: In function `tcf_ct_act':
    act_ct.c:(.text+0x21ac): undefined reference to `nf_ct_nat_ext_add'
    act_ct.c:(.text+0x229a): undefined reference to `nf_nat_icmp_reply_translation'
    act_ct.c:(.text+0x233a): undefined reference to `nf_nat_setup_info'
    act_ct.c:(.text+0x234a): undefined reference to `nf_nat_alloc_null_binding'
    act_ct.c:(.text+0x237c): undefined reference to `nf_nat_packet'

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: b57dc7c13ea9 ("net/sched: Introduce action ct")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>