bpf: BPF_PRELOAD depends on BPF_SYSCALL
Bugzilla: http://bugzilla.redhat.com/1874006

commit 7c0afcad7507636529e6a5a2a5eef5482619a449
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Thu Nov 5 11:51:09 2020 -0800

    bpf: BPF_PRELOAD depends on BPF_SYSCALL

    Fix build error when BPF_SYSCALL is not set/enabled but BPF_PRELOAD is
    by making BPF_PRELOAD depend on BPF_SYSCALL.

    ERROR: modpost: "bpf_preload_ops" [kernel/bpf/preload/bpf_preload.ko] undefined!

    Reported-by: kernel test robot <lkp@intel.com>
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20201105195109.26232-1-rdunlap@infradead.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>