[netdrv] phy: mscc: fix printf format
Message-id: <b8368bad20b1a5e7ca47bbb2b76acb114680ec21.1573676613.git.poros@redhat.com>
Patchwork-id: 286351
O-Subject: [RHEL8.2 PATCH 055/320] phy: mscc: fix printf format
Bugzilla: 1772010
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1772010

Upstream commit(s):
commit 31bae7dad359e7fee7e2857206107b744dfb2a4e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 26 15:20:11 2018 +0200

    phy: mscc: fix printf format

    gcc points out that the length of the temporary buffer may not be sufficient for
    large numbers of leds:

    drivers/net/phy/mscc.c: In function 'vsc85xx_probe':
    drivers/net/phy/mscc.c:460:45: error: '-mode' directive writing 5 bytes into a region of size between 0 and 9 [-Werror=format-overflow=]
       ret = sprintf(led_dt_prop, "vsc8531,led-%d-mode", i);
                                                 ^~~~~
    drivers/net/phy/mscc.c:460:9: note: 'sprintf' output between 19 and 28 bytes into a destination of size 22
       ret = sprintf(led_dt_prop, "vsc8531,led-%d-mode", i);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    While we can make a reasonable assumption that the number of LEDs is small,
    the cost of making the buffer a little bigger is insignificant as well.

    Fixes: 11bfdabb7ff5 ("net: phy: mscc: factorize code for LEDs mode")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>