[netdrv] mlx5: Fix addr's type in mlx5dr_icm_dm
Message-id: <20191105095158.18958-284-ahleihel@redhat.com>
Patchwork-id: 283299
O-Subject: [RHEL8.2 BZ 1724336 283/335] net/mlx5: Fix addr's type in mlx5dr_icm_dm
Bugzilla: 1760284 1724336
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1724336
Bugzilla: http://bugzilla.redhat.com/1760284
Upstream: v5.4-rc1

commit 334a306f7be8423932da8a0382616fe403d334cf
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Wed Sep 4 19:14:15 2019 -0700

    net/mlx5: Fix addr's type in mlx5dr_icm_dm

    clang errors when CONFIG_PHYS_ADDR_T_64BIT is not set:

    drivers/net/ethernet/mellanox/mlx5/core/steering/dr_icm_pool.c:121:8:
    error: incompatible pointer types passing 'u64 *' (aka 'unsigned long
    long *') to parameter of type 'phys_addr_t *' (aka 'unsigned int *')
    [-Werror,-Wincompatible-pointer-types]
                                       &icm_mr->dm.addr, &icm_mr->dm.obj_id);
                                       ^~~~~~~~~~~~~~~~
    include/linux/mlx5/driver.h:1092:39: note: passing argument to parameter
    'addr' here
                             u64 length, u16 uid, phys_addr_t *addr, u32 *obj_id);
                                                               ^
    1 error generated.

    Use phys_addr_t for addr's type in mlx5dr_icm_dm, which won't change
    anything with 64-bit builds because phys_addr_t is u64 when
    CONFIG_PHYS_ADDR_T_64BIT is set, which is always when CONFIG_64BIT is
    set.

    Fixes: 29cf8febd185 ("net/mlx5: DR, ICM pool memory allocator")
    Link: https://github.com/ClangBuiltLinux/linux/issues/653
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>