[net] ethtool: reduce stack usage with clang
Message-id: <20200915170040.2948050-7-ivecera@redhat.com>
Patchwork-id: 326513
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 net PATCH 06/97] ethtool: reduce stack usage with clang
Bugzilla: 1878274
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1878274

Upstream commit(s):
commit 3499e87ea0413ee5b2cc028f4c8ed4d424bc7f98
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Mar 7 16:58:35 2019 +0100

    ethtool: reduce stack usage with clang

    clang inlines the dev_ethtool() more aggressively than gcc does, leading
    to a larger amount of used stack space:

    net/core/ethtool.c:2536:24: error: stack frame size of 1216 bytes in function 'dev_ethtool' [-Werror,-Wframe-larger-than=]

    Marking the sub-functions that require the most stack space as
    noinline_for_stack gives us reasonable behavior on all compilers.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Michal Kubecek <mkubecek@suse.cz>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>