[sound] ALSA: ASoC: ti: remove compat dma probing
Message-id: <15580872947136052-1650-patchset-jkysela@redhat.com>
Patchwork-id: 258152
O-Subject: [RHEL 8.1 PATCH 1649/2119] ALSA: ASoC: ti: remove compat dma probing
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

After running into a link error:

sound/soc/ti/edma-pcm.o:(.rodata+0x18): undefined reference to `edma_filter_fn'

I checked all users of this, and they have new-style 'dma_slave_map' tables,
so none of them should still need it. Removing the associated lines
simplifies the code and avoids the build-time dependency on the
respective dmaengine drivers.

Acked-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 642aafea8889b712fe8e57aaa706d6c05d295059)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>