[usb] usb: Change usb_of_get_companion_dev() place to usb/common
Message-id: <20200407161320.17414-114-torez@redhat.com>
Patchwork-id: 299852
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 113/983] usb: Change usb_of_get_companion_dev() place to usb/common
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit fa827966090e2a6fc07b437d0d2ffae748ec6e28
Author: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
Date:   Mon Aug 20 12:10:26 2018 +0900

    usb: Change usb_of_get_companion_dev() place to usb/common

    Since renesas_usb3 udc driver calls usb_of_get_companion_dev()
    which is on usb/core/of.c, build error like below happens if we
    disable CONFIG_USB because the usb/core/ needs CONFIG_USB:

    ERROR: "usb_of_get_companion_dev" [drivers/usb/gadget/udc/renesas_usb3.ko] undefined!

    According to the usb/gadget/Kconfig, "NOTE:  Gadget support
    ** DOES NOT ** depend on host-side CONFIG_USB !!".
    So, to fix the issue, this patch changes the usb_of_get_companion_dev()
    place from usb/core/of.c to usb/common/common.c to be called by both
    host and gadget.

    Reported-by: John Garry <john.garry@huawei.com>
    Fixes: 39facfa01c9f ("usb: gadget: udc: renesas_usb3: Add register of usb role switch")
    Signed-off-by: Yoshihiro Shimoda <yoshihiro.shimoda.uh@renesas.com>
    Acked-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>