[infiniband] rdma/mlx5: Cleanup WQE page fault handler
Message-id: <20191103121056.7106-27-ahleihel@redhat.com>
Patchwork-id: 282304
O-Subject: [RHEL8.2 BZ 1724335 026/136] RDMA/mlx5: Cleanup WQE page fault handler
Bugzilla: 1724335
RH-Acked-by: Honggang Li <honli@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1724335
Upstream: v5.2

commit 0f51427bd0976fc4824ca16e73b7985f224cbbf8
Author: Leon Romanovsky <leonro@mellanox.com>
Date:   Mon Feb 25 08:56:14 2019 +0200

    RDMA/mlx5: Cleanup WQE page fault handler

    Refactor the page fault handler to be more readable and extensible, this
    cleanup was triggered by the error reported below. The code structure made
    it unclear to the automatic tools to identify that such a flow is not
    possible in real life because "requestor != NULL" means that "qp != NULL"
    too.

        drivers/infiniband/hw/mlx5/odp.c:1254 mlx5_ib_mr_wqe_pfault_handler()
        error: we previously assumed 'qp' could be null (see line 1230)

    Fixes: 08100fad5cac ("IB/mlx5: Add ODP SRQ support")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Reviewed-by: Moni Shoua <monis@mellanox.com>
    Signed-off-by: Leon Romanovsky <leonro@mellanox.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>