[tools] runqslower: Fix Makefile
Message-id: <20200608222925.282045-204-yauheni.kaliuta@redhat.com>
Patchwork-id: 318165
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 204/257] runqslower: Fix Makefile
Bugzilla: 1813372
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813372

commit 2577e373bbc07f18680287b3958d3b2fdebe4b20
Author: Yulia Kartseva <hex@fb.com>
Date:   Thu Jan 30 15:13:10 2020 -0800

    runqslower: Fix Makefile

    Fix undefined reference linker errors when building runqslower with
    gcc 7.4.0 on Ubuntu 18.04.
    The issue is with misplaced -lelf, -lz options in Makefile:
    $(Q)$(CC) $(CFLAGS) -lelf -lz $^ -o $@

    -lelf, -lz options should follow the list of target dependencies:
    $(Q)$(CC) $(CFLAGS) $^ -lelf -lz -o $@
    or after substitution
    cc -g -Wall runqslower.o libbpf.a -lelf -lz -o runqslower

    The current order of gcc params causes failure in libelf symbols resolution,
    e.g. undefined reference to `elf_memory'

    Fixes: 9c01546d26d2 ("tools/bpf: Add runqslower tool to tools/bpf")
    Signed-off-by: Julia Kartseva <hex@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Link: https://lore.kernel.org/bpf/908498f794661c44dca54da9e09dc0c382df6fcb.1580425879.git.hex@fb.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>