[samples] samples: bpf: Fix build error
Message-id: <20200610045258.353158-220-yauheni.kaliuta@redhat.com>
Patchwork-id: 319537
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 220/235] samples: bpf: Fix build error
Bugzilla: 1845114
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1845114

commit 23ad04669f81f958e9a4121b0266228d2eb3c357
Author: Matteo Croce <mcroce@redhat.com>
Date:   Mon May 11 13:32:34 2020 +0200

    samples: bpf: Fix build error

    GCC 10 is very strict about symbol clash, and lwt_len_hist_user contains
    a symbol which clashes with libbpf:

    /usr/bin/ld: samples/bpf/lwt_len_hist_user.o:(.bss+0x0): multiple definition of `bpf_log_buf'; samples/bpf/bpf_load.o:(.bss+0x8c0): first defined here
    collect2: error: ld returned 1 exit status

    bpf_log_buf here seems to be a leftover, so removing it.

    Signed-off-by: Matteo Croce <mcroce@redhat.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/bpf/20200511113234.80722-1-mcroce@redhat.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>