[netdrv] mlxsw: spectrum_router: Prevent ipv6 gateway with v4 route via replace and append
Message-id: <20191113174919.6852-41-ivecera@redhat.com>
Patchwork-id: 286165
O-Subject: [RHEL-8.2 PATCH 040/127] mlxsw: spectrum_router: Prevent ipv6 gateway with v4 route via replace and append
Bugzilla: 1737368
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1737368

Upstream commit(s):
commit 7973d9e76727aa42f0824f5569e96248a572d50b
Author: David Ahern <dsahern@gmail.com>
Date:   Tue Apr 23 16:03:29 2019 -0700

    mlxsw: spectrum_router: Prevent ipv6 gateway with v4 route via replace and append

    mlxsw currently does not support v6 gateways with v4 routes. Commit
    19a9d136f198 ("ipv4: Flag fib_info with a fib_nh using IPv6 gateway")
    prevents a route from being added, but nothing stops the replace or
    append. Add a catch for them too.
        $ ip  ro add 172.16.2.0/24 via 10.99.1.2
        $ ip  ro replace 172.16.2.0/24 via inet6 fe80::202:ff:fe00:b dev swp1s0
        Error: mlxsw_spectrum: IPv6 gateway with IPv4 route is not supported.
        $ ip  ro append 172.16.2.0/24 via inet6 fe80::202:ff:fe00:b dev swp1s0
        Error: mlxsw_spectrum: IPv6 gateway with IPv4 route is not supported.

    Signed-off-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>