[pci] PCI: mobiveil: Add missing ../pci.h include
Message-id: <20190313173355.111040.76585.stgit@tak.stowe>
Patchwork-id: 246100
O-Subject: [RHEL8.1 PATCH 35/51] PCI: mobiveil: Add missing ../pci.h include
Bugzilla: 1687935
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1687935
Build Info: https://brewweb.devel.redhat.com/taskinfi?taskID=20566133
Upstream Status: d3743012230f8dab30d47caba1f2ee9e382385e7

commit d3743012230f8dab30d47caba1f2ee9e382385e7
Author: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
Date:   Mon Jul 30 13:24:33 2018 +0100

    PCI: mobiveil: Add missing ../pci.h include

    PCI mobiveil host controller driver currently fails to compile
    with the following error:

    drivers/pci/controller/pcie-mobiveil.c: In function
    'mobiveil_pcie_probe':
    drivers/pci/controller/pcie-mobiveil.c:788:8: error: implicit
    declaration of function 'devm_of_pci_get_host_bridge_resources'; did you
    mean 'pci_get_host_bridge_device'?
    [-Werror=implicit-function-declaration]
      ret = devm_of_pci_get_host_bridge_resources(dev, 0, 0xff,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            pci_get_host_bridge_device

    Add the missing include file to pull in the required function declaration.

    Fixes: 9af6bcb11e12 ("PCI: mobiveil: Add Mobiveil PCIe Host Bridge IP
    driver")
    Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
    Cc: Bjorn Helgaas <bhelgaas@google.com>
    Cc: Subrahmanya Lingappa <l.subrahmanya@mobiveil.co.in>

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>