[scripts] redhat: fix modpost.c prerequisites
Message-id: <20200329134609.GA855@localhost.localdomain>
Patchwork-id: 298098
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 v2] redhat: fix modpost.c prerequisites
Bugzilla: 1818499
RH-Acked-by: Luis Goncalves <lgoncalv@redhat.com>
RH-Acked-by: Herton R. Krzesinski <herton@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jan Stancek <jstancek@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1818499
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27549982
Upstream Status: RHEL only
Tested: make mrproper && make rh-configs && \
        cp configs/kernel-4.18.0-$(uname -p).config .config && make scripts V=1

v2:
- Always run $(version_h) recipe for mod.o using FORCE prereq, otherwise
  changes in Makefile or Makefile.rhelver will not regenerate version.h.
- Make version.h depend on Makefile.rhelver. This is just to make it
  explicitly visible in the rule. The dependency is handled in filechk
  anyways.

Following commit included version.h in modpost.c

    commit e44d8f209d8e39dec4c5ccc5c4788b0c056a810d
    Author: Prarit Bhargava <prarit@redhat.com>
    Date:   Thu Mar 15 12:06:36 2018 -0300

    [kernel] modules: add rhelversion MODULE_INFO tag

    Patchwork-id: 7379
    O-Subject: [kernel team] [RHEL8.0 BZ 1544999 1/2] modules: add rhelversion MODULE_INFO tag
    Bugzilla: 1544999

but this change was not reflected in dependencies. Since there is no relation
between prepare and scripts prereqs for $(vmlinux-dirs) targets, they can be
processed in parallel and build may fail.

http://download.eng.bos.redhat.com/brewroot/work/tasks/1515/27531515/build.log

make 'HOSTCFLAGS=-O2 -g -pipe ... vmlinux
scripts/mod/modpost.c:23:10: fatal error: ../../include/generated/uapi/linux/version.h: No such file or directory
 #include "../../include/generated/uapi/linux/version.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.host:107: scripts/mod/modpost.o] Error 1

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>