[netdrv] mlx5: avoid 64-bit division in dr_icm_pool_mr_create()
Message-id: <20191105095158.18958-293-ahleihel@redhat.com>
Patchwork-id: 283308
O-Subject: [RHEL8.2 BZ 1724336 292/335] mlx5: avoid 64-bit division in dr_icm_pool_mr_create()
Bugzilla: 1760284 1724336
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1724336
Bugzilla: http://bugzilla.redhat.com/1760284
Upstream: v5.4-rc2

commit 8b6b82ad163b54a23f0e89710fb25461d45109c4
Author: Michal Kubecek <mkubecek@suse.cz>
Date:   Wed Oct 2 14:12:41 2019 +0200

    mlx5: avoid 64-bit division in dr_icm_pool_mr_create()

    Recently added code introduces 64-bit division in dr_icm_pool_mr_create()
    so that build on 32-bit architectures fails with

      ERROR: "__umoddi3" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!

    As the divisor is always a power of 2, we can use bitwise operation
    instead.

    Fixes: 29cf8febd185 ("net/mlx5: DR, ICM pool memory allocator")
    Reported-by: Borislav Petkov <bp@alien8.de>
    Signed-off-by: Michal Kubecek <mkubecek@suse.cz>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>