[netdrv] ath10k: work around uninitialized vht_pfr variable
Message-id: <20191126234256.26042-312-jarod@redhat.com>
Patchwork-id: 289711
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 311/796] ath10k: work around uninitialized vht_pfr variable
Bugzilla: 1776606
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>

commit ff414f31ce3750d259549c3b9eac8e855b5348f0
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 8 14:50:06 2019 +0200

    ath10k: work around uninitialized vht_pfr variable

    As clang points out, the vht_pfr is assigned to a struct member
    without being initialized in one case:

    drivers/net/wireless/ath/ath10k/mac.c:7528:7: error: variable 'vht_pfr' is used uninitialized whenever 'if' condition
          is false [-Werror,-Wsometimes-uninitialized]
                    if (!ath10k_mac_can_set_bitrate_mask(ar, band, mask,
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/wireless/ath/ath10k/mac.c:7551:20: note: uninitialized use occurs here
                    arvif->vht_pfr = vht_pfr;
                                     ^~~~~~~
    drivers/net/wireless/ath/ath10k/mac.c:7528:3: note: remove the 'if' if its condition is always true
                    if (!ath10k_mac_can_set_bitrate_mask(ar, band, mask,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/net/wireless/ath/ath10k/mac.c:7483:12: note: initialize the variable 'vht_pfr' to silence this warning
            u8 vht_pfr;

    Add an explicit but probably incorrect initialization here.
    I suspect we want a better fix here, but chose this approach to
    illustrate the issue.

    Fixes: 8b97b055dc9d ("ath10k: fix failure to set multiple fixed rate")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>