[tools] perf tools: Add size to 'struct perf_record_header_build_id'
Message-id: <20210108001544.23913-147-mpetlan@redhat.com>
Patchwork-id: 347455
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 148/197] perf tools: Add size to 'struct perf_record_header_build_id'
Bugzilla: 1884818 1908305
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1908305
https://bugzilla.redhat.com/show_bug.cgi?id=1908305

upstream
========
commit b0a323c7f0ece5dd76a5dc296ecd9175851a4283
Author: Jiri Olsa <jolsa@kernel.org>
Date: Tue Oct 13 21:24:39 2020 +0200

description
===========
We do not store size with build ids in perf data, but there's enough
space to do it. Adding misc bit PERF_RECORD_MISC_BUILD_ID_SIZE to mark
build id event with size.

With this fix the dso with md5 build id will have correct build id data
and will be usable for debuginfod processing if needed (coming in
following patches).

Committer notes:

Use %zu with size_t to fix this error on 32-bit arches:

  util/header.c: In function '__event_process_build_id':
  util/header.c:2105:3: error: format '%lu' expects argument of type 'long unsigned int', but argument 6 has type 'size_t' [-Werror=format=]
     pr_debug("build id event received for %s: %s [%lu]\n",
     ^

Signed-off-by: Michael Petlan <mpetlan@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>