[acpi] ACPI / NUMA: Add stub function for pxm_to_node()
Message-id: <20201223180920.3240723-199-ahs3@redhat.com>
Patchwork-id: 346853
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 198/235] ACPI / NUMA: Add stub function for pxm_to_node()
Bugzilla: 1865698 1851555
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1865698
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1851555
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33918986
Upstream Status: 4849bc777049b568a35d5d63ae326e93f0fff9de
Tested: Ran through the kernel CKI KT1 test suite multiple times to ensure the
 results were consistent, that we hit multiple platforms, and that they
 were successful.

commit 4849bc777049b568a35d5d63ae326e93f0fff9de
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Mon Sep 28 12:45:55 2020 -0700

    ACPI / NUMA: Add stub function for pxm_to_node()

    After commit 01feba590cd6 ("ACPI: Do not create new NUMA domains from
    ACPI static tables that are not SRAT"):

    $ scripts/config --file arch/x86/configs/x86_64_defconfig -d NUMA -e ACPI_NFIT

    $ make -skj"$(nproc)" distclean defconfig drivers/acpi/nfit/
    drivers/acpi/nfit/core.c: In function ‘acpi_nfit_register_region’:
    drivers/acpi/nfit/core.c:3010:27: error: implicit declaration of
    function ‘pxm_to_node’; did you mean ‘xa_to_node’?
    [-Werror=implicit-function-declaration]
     3010 |   ndr_desc->target_node = pxm_to_node(spa->proximity_domain);
          |                           ^~~~~~~~~~~
          |                           xa_to_node
    cc1: some warnings being treated as errors
    ...

    Add a stub function like acpi_map_pxm_to_node() had so that the build
    continues to work.

    Fixes: 01feba590cd6 ("ACPI: Do not create new NUMA domains from ACPI static tables that are not SRAT")
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Acked-by: Jonathan Cameron <Jonathan.Cameron@huawei.com>
    Reviewed-by: Hanjun Guo <guohanjun@huawei.com>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
    (cherry picked from commit 4849bc777049b568a35d5d63ae326e93f0fff9de)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>