[tools] bpf, tls: add tls header to tools infrastructure
Message-id: <20190604085256.3304-216-yauheni.kaliuta@redhat.com>
Patchwork-id: 262214
O-Subject: [RHEL8.1 PATCH v2 216/627] bpf, tls: add tls header to tools infrastructure
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit 421f4292f46e871cdcf8bdc3e6fdfcefe2e81a9d
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Tue Oct 16 15:59:36 2018 +0200

    bpf, tls: add tls header to tools infrastructure

    Andrey reported a build error for the BPF kselftest suite when compiled on
    a machine which does not have tls related header bits installed natively:

      test_sockmap.c:120:23: fatal error: linux/tls.h: No such file or directory
       #include <linux/tls.h>
                             ^
      compilation terminated.

    Fix it by adding the header to the tools include infrastructure and add
    definitions such as SOL_TLS that could potentially be missing.

    Fixes: e9dd904708c4 ("bpf: add tls support for testing in test_sockmap")
    Reported-by: Andrey Ignatov <rdna@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>