[netdrv] ixgbevf: fix a compilation error of skb_frag_t
Message-id: <20191112122226.14549-6-jkc@redhat.com>
Patchwork-id: 285644
O-Subject: [RHEL8.2 BZ 1721701 5/9] net/ixgbevf: fix a compilation error of skb_frag_t
Bugzilla: 1721701
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1721701

commit d601be97126e9736db4f3528c66792178fcf1796
Author: Qian Cai <cai@lca.pw>
Date:   Wed Jul 24 12:17:59 2019 -0400

    net/ixgbevf: fix a compilation error of skb_frag_t

    The linux-next commit "net: Rename skb_frag_t size to bv_len" [1]
    introduced a compilation error on powerpc as it forgot to deal with the
    renaming from "size" to "bv_len" for ixgbevf.

    [1] https://lore.kernel.org/netdev/20190723030831.11879-1-willy@infradead.org/T/#md052f1c7de965ccd1bdcb6f92e1990a52298eac5

    In file included from ./include/linux/cache.h:5,
                     from ./include/linux/printk.h:9,
                     from ./include/linux/kernel.h:15,
                     from ./include/linux/list.h:9,
                     from ./include/linux/module.h:9,
                     from
    drivers/net/ethernet/intel/ixgbevf/ixgbevf_main.c:12:
    drivers/net/ethernet/intel/ixgbevf/ixgbevf_main.c: In function
    'ixgbevf_xmit_frame_ring':
    drivers/net/ethernet/intel/ixgbevf/ixgbevf_main.c:4138:51: error:
    'skb_frag_t' {aka 'struct bio_vec'} has no member named 'size'
       count += TXD_USE_COUNT(skb_shinfo(skb)->frags[f].size);
                                                       ^
    ./include/uapi/linux/kernel.h:13:40: note: in definition of macro
    '__KERNEL_DIV_ROUND_UP'
     #define __KERNEL_DIV_ROUND_UP(n, d) (((n) + (d) - 1) / (d))
                                            ^
    drivers/net/ethernet/intel/ixgbevf/ixgbevf_main.c:4138:12: note: in
    expansion of macro 'TXD_USE_COUNT'
       count += TXD_USE_COUNT(skb_shinfo(skb)->frags[f].size);

    Signed-off-by: Qian Cai <cai@lca.pw>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ken Cox <jkc@redhat.com>

Cc: Ken Cox <jkc@redhat.com>
Signed-off-by: Ken Cox <jkc@redhat.com>

Cc: Ken Cox <jkc@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>