[net] sched: act_vlan: validate the control action inside init()
Message-id: <20190610212005.12299-148-ivecera@redhat.com>
Patchwork-id: 264136
O-Subject: [RHEL-8.1 net PATCH 147/194] net/sched: act_vlan: validate the control action inside init()
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 7e0c8892df7d0316ec853adbf84db536cd53258c
Author: Davide Caratti <dcaratti@redhat.com>
Date:   Wed Mar 20 15:00:14 2019 +0100

    net/sched: act_vlan: validate the control action inside init()

    the following script:

     # tc qdisc add dev crash0 clsact
     # tc filter add dev crash0 egress matchall \
     > action vlan pop pass index 90
     # tc actions replace action vlan \
     > pop goto chain 42 index 90 cookie c1a0c1a0
     # tc actions show action vlan

    had the following output:

     Error: Failed to init TC action chain.
     We have an error talking to the kernel
     total acts 1

             action order 0: vlan  pop goto chain 42
              index 90 ref 2 bind 1
             cookie c1a0c1a0

    Then, the first packet transmitted by crash0 made the kernel crash:

     BUG: unable to handle kernel NULL pointer dereference at 0000000000000000
     #PF error: [normal kernel read fault]
     PGD 800000007974f067 P4D 800000007974f067 PUD 79638067 PMD 0
     Oops: 0000 [#1] SMP PTI
     CPU: 3 PID: 0 Comm: swapper/3 Not tainted 5.0.0-rc4.gotochain_crash+ #536
     Hardware name: Red Hat KVM, BIOS 0.5.1 01/01/2011
     RIP: 0010:tcf_action_exec+0xb8/0x100
     Code: 00 00 00 20 74 1d 83 f8 03 75 09 49 83 c4 08 4d 39 ec 75 bc 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 49 8b 97 a8 00 00 00 <48> 8b 12 48 89 55 00 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3
     RSP: 0018:ffff982dfdb83be0 EFLAGS: 00010246
     RAX: 000000002000002a RBX: ffff982dfc55db00 RCX: 0000000000000000
     RDX: 0000000000000000 RSI: ffff982df97099c0 RDI: ffff982dfc55db00
     RBP: ffff982dfdb83c80 R08: ffff982df983fec8 R09: 0000000000000000
     R10: 0000000000000000 R11: 0000000000000000 R12: ffff982df5aacd00
     R13: ffff982df5aacd08 R14: 0000000000000001 R15: ffff982df97099c0
     FS:  0000000000000000(0000) GS:ffff982dfdb80000(0000) knlGS:0000000000000000
     CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
     CR2: 0000000000000000 CR3: 00000000796d0005 CR4: 00000000001606e0
     Call Trace:
      <IRQ>
      tcf_classify+0x58/0x120
      __dev_queue_xmit+0x40a/0x890
      ? ip6_finish_output2+0x369/0x590
      ip6_finish_output2+0x369/0x590
      ? ip6_output+0x68/0x110
      ip6_output+0x68/0x110
      ? nf_hook.constprop.35+0x79/0xc0
      mld_sendpack+0x16f/0x220
      mld_ifc_timer_expire+0x195/0x2c0
      ? igmp6_timer_handler+0x70/0x70
      call_timer_fn+0x2b/0x130
      run_timer_softirq+0x3e8/0x440
      ? enqueue_hrtimer+0x39/0x90
      __do_softirq+0xe3/0x2f5
      irq_exit+0xf0/0x100
      smp_apic_timer_interrupt+0x6c/0x130
      apic_timer_interrupt+0xf/0x20
      </IRQ>
     RIP: 0010:native_safe_halt+0x2/0x10
     Code: 7b ff ff ff 7f f3 c3 65 48 8b 04 25 00 5c 01 00 f0 80 48 02 20 48 8b 00 a8 08 74 8b eb c1 90 90 90 90 90 90 90 90 90 90 fb f4 <c3> 0f 1f 00 66 2e 0f 1f 84 00 00 00 00 00 f4 c3 90 90 90 90 90 90
     RSP: 0018:ffffa4714038feb8 EFLAGS: 00000246 ORIG_RAX: ffffffffffffff13
     RAX: ffffffff840184f0 RBX: 0000000000000003 RCX: 0000000000000000
     RDX: 0000000000000001 RSI: 0000000000000000 RDI: 0000001e57d3f387
     RBP: 0000000000000003 R08: 001125d9ca39e1eb R09: 0000000000000000
     R10: 000000000000027d R11: 000000000009f400 R12: 0000000000000000
     R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
      ? __sched_text_end+0x1/0x1
      default_idle+0x1c/0x140
      do_idle+0x1c4/0x280
      cpu_startup_entry+0x19/0x20
      start_secondary+0x1a7/0x200
      secondary_startup_64+0xa4/0xb0
     Modules linked in: act_vlan veth ip6table_filter ip6_tables iptable_filter binfmt_misc ext4 snd_hda_codec_generic mbcache crct10dif_pclmul jbd2 snd_hda_intel crc32_pclmul snd_hda_codec ghash_clmulni_intel snd_hwdep snd_hda_core snd_seq snd_seq_device snd_pcm aesni_intel crypto_simd cryptd glue_helper joydev snd_timer virtio_balloon snd pcspkr soundcore i2c_piix4 nfsd auth_rpcgss nfs_acl lockd grace sunrpc ip_tables xfs ata_generic pata_acpi qxl drm_kms_helper syscopyarea sysfillrect sysimgblt virtio_net fb_sys_fops virtio_blk ttm net_failover virtio_console failover ata_piix drm libata crc32c_intel virtio_pci serio_raw virtio_ring virtio floppy dm_mirror dm_region_hash dm_log dm_mod
     CR2: 0000000000000000

    Validating the control action within tcf_vlan_init() proved to fix the
    above issue. A TDC selftest is added to verify the correct behavior.

    Fixes: db50514f9a9c ("net: sched: add termination action to allow goto chain")
    Fixes: 97763dc0f401 ("net_sched: reject unknown tcfa_action values")
    Signed-off-by: Davide Caratti <dcaratti@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>