[netdrv] net/mlxfw: Improve FSM err message reporting and return codes
Message-id: <20200601180237.4179948-184-ivecera@redhat.com>
Patchwork-id: 315957
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 PATCH 183/290] net/mlxfw: Improve FSM err message reporting and return codes
Bugzilla: 1821646
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1821646

Upstream commit(s):
commit 86a1270fd79f99e7aa85c2c81cd59d0eab92112f
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Fri Feb 21 21:45:59 2020 +0000

    net/mlxfw: Improve FSM err message reporting and return codes

    Report unique and standard error codes corresponding to the specific
    FW flash error. In addition, add a more detailed error messages to
    netlink.

    Before:
    $ devlink dev flash pci/0000:05:00.0 file ...
    Error: mlxfw: Firmware flash failed.
    devlink answers: Invalid argument

    After:
    $ devlink dev flash pci/0000:05:00.0 file ...
    Error: mlxfw: Firmware flash failed: pending reset.
    devlink answers: Device busy

    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
    Reviewed-by: Ido Schimmel <idosch@mellanox.com>
    Acked-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>