[net] bpf: Fix build in minimal configurations
Message-id: <20200529062245.152030-198-yauheni.kaliuta@redhat.com>
Patchwork-id: 315445
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 198/235] bpf: Fix build in minimal configurations
Bugzilla: 1813370
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813370

commit ce27709b8162e5c501bc54292b8bf6bdecc4bbd4
Author: Alexei Starovoitov <ast@kernel.org>
Date:   Wed Nov 27 20:35:08 2019 -0800

    bpf: Fix build in minimal configurations

    Some kconfigs can have BPF enabled without a single valid program type.
    In such configurations the build will fail with:
    ./kernel/bpf/btf.c:3466:1: error: empty enum is invalid

    Fix it by adding unused value to the enum.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Link: https://lore.kernel.org/bpf/20191128043508.2346723-1-ast@kernel.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>