[netdrv] netdevsim: Fix build error without CONFIG_INET
Message-id: <f38e88f50e8411aa9c164ac4711eec797c957b73.1584973596.git.poros@redhat.com>
Patchwork-id: 297246
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net PATCH 18/21] netdevsim: Fix build error without CONFIG_INET
Bugzilla: 1805882
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1805882

Upstream commit(s):
commit d9bd6d279236a1c90c1e73220c2ae52996c8ff52
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Tue Aug 20 22:14:46 2019 +0800

    netdevsim: Fix build error without CONFIG_INET

    If CONFIG_INET is not set, building fails:

    drivers/net/netdevsim/dev.o: In function `nsim_dev_trap_report_work':
    dev.c:(.text+0x67b): undefined reference to `ip_send_check'

    Use ip_fast_csum instead of ip_send_check to avoid
    dependencies on CONFIG_INET.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: da58f90f11f5 ("netdevsim: Add devlink-trap support")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Reviewed-by: Ido Schimmel <idosch@mellanox.com>
    Tested-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>