[tools] bpf: Fix bpftool without skeleton code enabled
Message-id: <20210113140908.457588-64-yauheni.kaliuta@redhat.com>
Patchwork-id: 348405
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 v2 064/291] bpf: Fix bpftool without skeleton code enabled
Bugzilla: 1874005
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874005

commit 8ae4121bd89e3dce27b519ed469efbc15423af18
Author: John Fastabend <john.fastabend@gmail.com>
Date:   Thu Jul 2 21:31:59 2020 -0700

    bpf: Fix bpftool without skeleton code enabled

    Fix segfault from bpftool by adding emit_obj_refs_plain when skeleton
    code is disabled.

    Tested by deleting BUILD_BPF_SKELS in Makefile. We found this doing
    backports for Cilium when a testing image pulled in latest bpf-next
    bpftool, but kept using an older clang-7.

      # ./bpftool prog show
      Error: bpftool built without PID iterator support
      3: cgroup_skb  tag 7be49e3934a125ba  gpl
              loaded_at 2020-07-01T08:01:29-0700  uid 0
      Segmentation fault

    Fixes: d53dee3fe013 ("tools/bpftool: Show info for processes holding BPF map/prog/link/btf FDs")
    Reported-by: Joe Stringer <joe@wand.net.nz>
    Signed-off-by: John Fastabend <john.fastabend@gmail.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/bpf/159375071997.14984.17404504293832961401.stgit@john-XPS-13-9370

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>