[crypto] crypto: ccp - Reduce maximum stack usage
Message-id: <20200515085240.201138-19-vdronov@redhat.com>
Patchwork-id: 309844
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 BZ1765717 PATCH 18/39] crypto: ccp - Reduce maximum stack usage
Bugzilla: 1765717
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Herbert Xu <herbert.xu@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1765717
Upstream Status: merged into the linux.git
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28575492
Tested: KPET testset, see bz1765717 #c5

commit 72c8117adfced37df101c8c0b3f363e0906f83f0
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 12 10:59:24 2019 +0200

    crypto: ccp - Reduce maximum stack usage

    Each of the operations in ccp_run_cmd() needs several hundred
    bytes of kernel stack. Depending on the inlining, these may
    need separate stack slots that add up to more than the warning
    limit, as shown in this clang based build:

    drivers/crypto/ccp/ccp-ops.c:871:12: error: stack frame size of 1164 bytes in function 'ccp_run_aes_cmd' [-Werror,-Wframe-larger-than=]
    static int ccp_run_aes_cmd(struct ccp_cmd_queue *cmd_q, struct ccp_cmd *cmd)

    The problem may also happen when there is no warning, e.g. in the
    ccp_run_cmd()->ccp_run_aes_cmd()->ccp_run_aes_gcm_cmd() call chain with
    over 2000 bytes.

    Mark each individual function as 'noinline_for_stack' to prevent
    this from happening, and move the calls to the two special cases for aes
    into the top-level function. This will keep the actual combined stack
    usage to the mimimum: 828 bytes for ccp_run_aes_gcm_cmd() and
    at most 524 bytes for each of the other cases.

    Fixes: 63b945091a07 ("crypto: ccp - CCP device driver and interface support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

Signed-off-by: Vladis Dronov <vdronov@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>