[netdrv] qed: fix the allocation of the chains with an external PBL
Message-id: <1604491968-22298-95-git-send-email-mchopra@redhat.com>
Patchwork-id: 337464
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL-8.4 094/111] qed: fix the allocation of the chains with an external PBL
Bugzilla: 1857857
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

From: Alexander Lobakin <alobakin@marvell.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1857857
Upstream: linux.git

commit 1775da47c34a520108bea02dd4cbc21ee2e1b6c2
Author: Alexander Lobakin <alobakin@marvell.com>
Date:   Mon Jul 27 14:51:33 2020 +0300

    qed: fix the allocation of the chains with an external PBL

    Dan reports static checker warning:

    "The patch 9b6ee3cf95d3: "qed: sanitize PBL chains allocation" from Jul
    23, 2020, leads to the following static checker warning:

            drivers/net/ethernet/qlogic/qed/qed_chain.c:299 qed_chain_alloc_pbl()
            error: uninitialized symbol 'pbl_virt'.

    drivers/net/ethernet/qlogic/qed/qed_chain.c
       249  static int qed_chain_alloc_pbl(struct qed_dev *cdev, struct qed_chain *chain)
       250  {
       251          struct device *dev = &cdev->pdev->dev;
       252          struct addr_tbl_entry *addr_tbl;
       253          dma_addr_t phys, pbl_phys;
       254          __le64 *pbl_virt;
                    ^^^^^^^^^^^^^^^^
    [...]
       271          if (chain->b_external_pbl)
       272                  goto alloc_pages;
                            ^^^^^^^^^^^^^^^^ uninitialized
    [...]
       298                  /* Fill the PBL table with the physical address of the page */
       299                  pbl_virt[i] = cpu_to_le64(phys);
                            ^^^^^^^^^^^
    [...]
    "

    This issue was introduced with commit c3a321b06a80 ("qed: simplify
    initialization of the chains with an external PBL"), when
    chain->pbl_sp.table_virt initialization was moved up to
    qed_chain_init_params().
    Fix it by initializing pbl_virt with an already filled chain struct field.

    Fixes: c3a321b06a80 ("qed: simplify initialization of the chains with an external PBL")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Alexander Lobakin <alobakin@marvell.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Manish Chopra <mchopra@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>