[powerpc] pwerpc/vas: Include linux/types.h in uapi/asm/vas-api.h
Message-id: <20200427225815.197598-29-gduarte@redhat.com>
Patchwork-id: 305409
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH BZ 1725806 28/28] pwerpc/vas: Include linux/types.h in uapi/asm/vas-api.h
Bugzilla: 1725806
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

BZ 1725806
Upstream Status: 45591da765885f7320a111d290b3a28a23eed359

commit 45591da765885f7320a111d290b3a28a23eed359
Author: Stephen Rothwell <sfr@canb.auug.org.au>
Date:   Wed Apr 22 15:41:29 2020 +1000

    powerpc/vas: Include linux/types.h in uapi/asm/vas-api.h

    allyesconfig fails with:
      ./usr/include/asm/vas-api.h:15:2: error: unknown type name '__u32'
         15 |  __u32 version;
            |  ^~~~~
      ./usr/include/asm/vas-api.h:16:2: error: unknown type name '__s16'
         16 |  __s16 vas_id; /* specific instance of vas or -1 for default */
            |  ^~~~~
      ./usr/include/asm/vas-api.h:17:2: error: unknown type name '__u16'
         17 |  __u16 reserved1;
            |  ^~~~~
      ./usr/include/asm/vas-api.h:18:2: error: unknown type name '__u64'
         18 |  __u64 flags; /* Future use */
            |  ^~~~~
      ./usr/include/asm/vas-api.h:19:2: error: unknown type name '__u64'
         19 |  __u64 reserved2[6];
            |  ^~~~~

    uapi headers should be self contained, so add an include of
    linux/types.h.

    Fixes: 45f25a79fe50 ("powerpc/vas: Define VAS_TX_WIN_OPEN ioctl API")
    Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Acked-by: Haren Myneni <haren@linux.ibm.com>
    [mpe: Flesh out change log from linux-next error report]
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20200422154129.11f988fd@canb.auug.org.au

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>