[fs] xfs: substitute spaces with tabs
Message-id: <20181002164645.57545-157-bfoster@redhat.com>
Patchwork-id: 229643
O-Subject: [RHEL8 PATCH 156/183] xfs: substitute spaces with tabs
Bugzilla: 1633171
RH-Acked-by: Carlos Maiolino <cmaiolino@redhat.com>
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>

commit c2b6e1591b6b15e1dcd9c1596b0371b6abc48fed
Author: Thomas Bianchi <thomas.bianchi8@gmail.com>
Date:   Wed Aug 1 12:58:34 2018 -0700

    xfs: substitute spaces with tabs

    Inside xfs_attr_shortform_list removes spaces at the beginnig of the line
    and replaces with tabs.
    Issue found by checkpatch.

    ERROR: code indent should use tabs where possible

    Signed-off-by: Thomas Bianchi <thomas.bianchi8@gmail.com>
    Reviewed-by: Bill O'Donnell <billodo@redhat.com>
    Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

Signed-off-by: Brian Foster <bfoster@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>