[net] mptcp: Fix code formatting
Message-id: <20200515101824.19445-23-fwestpha@redhat.com>
Patchwork-id: 309888
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 22/38] mptcp: Fix code formatting
Bugzilla: 1835796
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1835796
Upstream Status: commit edc7e4898d5f

commit edc7e4898d5fdb164de1ab9d3a0c30ef9888e4f1
Author: Mat Martineau <mathew.j.martineau@linux.intel.com>
Date:   Fri Jan 24 16:04:03 2020 -0800

    mptcp: Fix code formatting

    checkpatch.pl had a few complaints in the last set of MPTCP patches:

    ERROR: code indent should use tabs where possible
    +^I         subflow, sk->sk_family, icsk->icsk_af_ops, target, mapped);$

    CHECK: Comparison to NULL could be written "!new_ctx"
    +       if (new_ctx == NULL) {

    ERROR: "foo * bar" should be "foo *bar"
    +static const struct proto_ops * tcp_proto_ops(struct sock *sk)

    Signed-off-by: Mat Martineau <mathew.j.martineau@linux.intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>