[netdrv] sfc: Fix build with CONFIG_RFS_ACCEL disabled
Message-id: <20201021000816.2891-90-jarod@redhat.com>
Patchwork-id: 333719
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 089/101] sfc: Fix build with CONFIG_RFS_ACCEL disabled.
Bugzilla: 1856681
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1856681

commit da7955405fb25c11a541234b32d06d9c09f81be6
Author: David S. Miller <davem@davemloft.net>
Date:   Mon Aug 3 18:29:39 2020 -0700

    sfc: Fix build with CONFIG_RFS_ACCEL disabled.

       drivers/net/ethernet/sfc/ef100_nic.c:835:3: error: 'const struct efx_nic_type' has no member named 'filter_rfs_expire_one'
         835 |  .filter_rfs_expire_one = efx_mcdi_filter_rfs_expire_one,
             |   ^~~~~~~~~~~~~~~~~~~~~
    >> drivers/net/ethernet/sfc/ef100_nic.c:835:27: error: initialization of 'void (*)(struct efx_nic *, u32)' {aka 'void (*)(struct efx_nic *, unsigned int)'} from incompatible pointer type 'bool (*)(struct efx_nic *, u32,  unsigned int)' {aka '_Bool (*)(struct efx_nic *, unsigned int,  unsigned int)'} [-Werror=incompatible-pointer-types]
         835 |  .filter_rfs_expire_one = efx_mcdi_filter_rfs_expire_one,
             |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>