[include] netfilter: nf_tables: constify nft_reg_load{8, 16, 64}()
Message-id: <20201214205039.8084-9-fwestpha@redhat.com>
Patchwork-id: 344580
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net 08/17] netfilter: nf_tables: constify nft_reg_load{8, 16, 64}()
Bugzilla: 1906915
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1906915
Upstream Status: commit 7cd9a58d6860a

Without it, followup patch causes build failure:
error: passing argument 1 of 'nft_reg_load16' discards 'const' qualifier ...

commit 7cd9a58d6860ae09acd7f0c219b5fa333703f72f
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Tue Nov 19 23:05:52 2019 +0100

    netfilter: nf_tables: constify nft_reg_load{8, 16, 64}()

    This patch constifies the pointer to source register data that is passed
    as an input parameter.

    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>