[documentation] dt-bindings: net: mvusb: Fix example errors
Message-id: <650aa8f429c4a4932ed0f508d849f38a38d7edf5.1610380954.git.poros@redhat.com>
Patchwork-id: 347952
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 202/206] dt-bindings: net: mvusb: Fix example errors
Bugzilla: 1878147
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1878147

Upstream commit(s):
commit d61f4d61ff7f73bed1f4c613de59b4534c08a088
Author: Rob Herring <robh@kernel.org>
Date:   Wed Apr 1 11:58:04 2020 -0600

    dt-bindings: net: mvusb: Fix example errors

    The example for Marvell USB to MDIO Controller doesn't build:

    Error: Documentation/devicetree/bindings/net/marvell,mvusb.example.dts:18.9-14 syntax error
    FATAL ERROR: Unable to parse input tree

    This is due to label refs being used which can't be resolved.

    Fixes: 61e0150cb44b ("dt-bindings: net: add marvell usb to mdio bindings")
    Cc: Tobias Waldekranz <tobias@waldekranz.com>
    Cc: "David S. Miller" <davem@davemloft.net>
    Cc: netdev@vger.kernel.org
    Signed-off-by: Rob Herring <robh@kernel.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>