[tools] libbpf: Avoid designated initializers for unnamed union members
Message-id: <20191112151107.11979-224-yauheni.kaliuta@redhat.com>
Patchwork-id: 285885
O-Subject: [RHEL8.2 224/248] libbpf: Avoid designated initializers for unnamed union members
Bugzilla: 1747617
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747617

commit 4be6e05c4d4c2ff87750d3242f69999245d119f8
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date:   Fri Jul 19 11:34:07 2019 -0300

    libbpf: Avoid designated initializers for unnamed union members

    As it fails to build in some systems with:

      libbpf.c: In function 'perf_buffer__new':
      libbpf.c:4515: error: unknown field 'sample_period' specified in initializer
      libbpf.c:4516: error: unknown field 'wakeup_events' specified in initializer

    Doing as:

        attr.sample_period = 1;

    I.e. not as a designated initializer makes it build everywhere.

    Cc: Andrii Nakryiko <andriin@fb.com>
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Daniel Borkmann <daniel@iogearbox.net>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Namhyung Kim <namhyung@kernel.org>
    Fixes: fb84b8224655 ("libbpf: add perf buffer API")
    Link: https://lkml.kernel.org/n/tip-hnlmch8qit1ieksfppmr32si@git.kernel.org
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>