[netdrv] i40e: reduce stack usage in i40e_set_fc
Message-id: <20191126112013.1684118-36-sassmann@redhat.com>
Patchwork-id: 288962
O-Subject: [RHEL8.2 PATCH 35/74] i40e: reduce stack usage in i40e_set_fc
Bugzilla: 1721695
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1721695
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24945929

The functions i40e_aq_get_phy_abilities_resp() and i40e_set_fc() both
have giant structure on the stack, which makes each one use stack frames
larger than 500 bytes.

As clang decides one function into the other, we get a warning for
exceeding the frame size limit on 32-bit architectures:

drivers/net/ethernet/intel/i40e/i40e_common.c:1654:23: error: stack frame size of 1116 bytes in function 'i40e_set_fc' [-Werror,-Wframe-larger-than=]

When building with gcc, the inlining does not happen, but i40e_set_fc()
calls i40e_aq_get_phy_abilities_resp() anyway, so they add up on the
kernel stack just as much.

The parts that actually use large stacks don't overlap, so make sure
each one is a separate function, and mark them as noinline_for_stack to
prevent the compilers from combining them again.

Fixes: 0a862b43acc6 ("i40e/i40evf: Add module_types and update_link_info")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Tested-by: Andrew Bowers <andrewx.bowers@intel.com>
Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>

Signed-off-by: Stefan Assmann <sassmann@redhat.com>
(cherry picked from commit 33b165684ab70867d4545643f550a5d48d3ddc57)
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>