[x86] kvm: x86: Fix warning due to implicit truncation on 32-bit KVM
Message-id: <20200420163605.943242-1-vkuznets@redhat.com>
Patchwork-id: 304130
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 virt PATCH v2 461/614] KVM: x86: Fix warning due to implicit truncation on 32-bit KVM
Bugzilla: 1813987
RH-Acked-by: Andrew Jones <drjones@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Sean Christopherson <sean.j.christopherson@intel.com>

Explicitly cast the integer literal to an unsigned long when stuffing a
non-canonical value into the host virtual address during private memslot
deletion.  The explicit cast fixes a warning that gets promoted to an
error when running with KVM's newfangled -Werror setting.

  arch/x86/kvm/x86.c:9739:9: error: large integer implicitly truncated
  to unsigned type [-Werror=overflow]

Fixes: a3e967c0b87d3 ("KVM: Terminate memslot walks via used_slots"
Signed-off-by: Sean Christopherson <sean.j.christopherson@intel.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit abbed4fa94f69d2046c6f7c12f6ecabf195c553e)
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>