tracing: Annotate ftrace_graph_hash pointer with __rcu
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1941211

commit 24a9729f831462b1d9d61dc85ecc91c59037243f
Author: Amol Grover <frextrite@gmail.com>
Date:   Sat, 1 Feb 2020 12:57:04 +0530

    tracing: Annotate ftrace_graph_hash pointer with __rcu

    Fix following instances of sparse error
    kernel/trace/ftrace.c:5664:29: error: incompatible types in comparison
    kernel/trace/ftrace.c:5785:21: error: incompatible types in comparison
    kernel/trace/ftrace.c:5864:36: error: incompatible types in comparison
    kernel/trace/ftrace.c:5866:25: error: incompatible types in comparison

    Use rcu_dereference_protected to access the __rcu annotated pointer.

    Link: http://lkml.kernel.org/r/20200201072703.17330-1-frextrite@gmail.com

    Reviewed-by: Joel Fernandes (Google) <joel@joelfernandes.org>
    Signed-off-by: Amol Grover <frextrite@gmail.com>
    Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>

Signed-off-by: Waiman Long <longman@redhat.com>