[kernel] bpf: Remove inline from bpf_do_trace_printk
Message-id: <20210113140908.457588-220-yauheni.kaliuta@redhat.com>
Patchwork-id: 348565
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 v2 220/291] bpf: Remove inline from bpf_do_trace_printk
Bugzilla: 1874005
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874005

commit 0d360d64b01231cdb36e1936de889f308fd9317f
Author: Stanislav Fomichev <sdf@google.com>
Date:   Thu Aug 6 11:26:12 2020 -0700

    bpf: Remove inline from bpf_do_trace_printk

    I get the following error during compilation on my side:
    kernel/trace/bpf_trace.c: In function 'bpf_do_trace_printk':
    kernel/trace/bpf_trace.c:386:34: error: function 'bpf_do_trace_printk' can never be inlined because it uses variable argument lists
     static inline __printf(1, 0) int bpf_do_trace_printk(const char *fmt, ...)
                                      ^

    Fixes: ac5a72ea5c89 ("bpf: Use dedicated bpf_trace_printk event instead of trace_printk()")
    Signed-off-by: Stanislav Fomichev <sdf@google.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20200806182612.1390883-1-sdf@google.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>