[scsi] scsi: lpfc: avoid uninitialized variable warning
Message-id: <20190705124643.32224-3-dkennedy@redhat.com>
Patchwork-id: 266388
O-Subject: [RHEL8.1 patch-v2 estor 02/16] scsi: lpfc: avoid uninitialized variable warning
Bugzilla: 1714795
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

clang -Wuninitialized incorrectly sees a variable being used without
initialization:

drivers/scsi/lpfc/lpfc_nvme.c:2102:37: error: variable 'localport' is uninitialized when used here
      [-Werror,-Wuninitialized]
                lport = (struct lpfc_nvme_lport *)localport->private;
                                                  ^~~~~~~~~
drivers/scsi/lpfc/lpfc_nvme.c:2059:38: note: initialize the variable 'localport' to silence this warning
        struct nvme_fc_local_port *localport;
                                            ^
                                             = NULL
1 error generated.

This is clearly in dead code, as the condition leading up to it is always
false when CONFIG_NVME_FC is disabled, and the variable is always
initialized when nvme_fc_register_localport() got called successfully.

Change the preprocessor conditional to the equivalent C construct, which
makes the code more readable and gets rid of the warning.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: James Smart <james.smart@broadcom.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit faf5a744f4f8d76e7c03912b5cd381ac8045f6ec)
Signed-off-by: Dick Kennedy <dkennedy@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>