[iommu] vt-d: Don't dereference iommu_device if IOMMU_API is not built
Message-id: <20201203134230.2445359-4-vkuznets@redhat.com>
Patchwork-id: 342992
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 virt PATCH 3/3] iommu/vt-d: Don't dereference iommu_device if IOMMU_API is not built
Bugzilla: 1887216
RH-Acked-by: Alex Williamson <alex.williamson@redhat.com>
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>

commit 9def3b1a07c41e21c68a0eb353e3e569fdd1d2b1 (tag: iommu-fix-v5.10)
Author: Bartosz Golaszewski <bgolaszewski@baylibre.com>
Date:   Tue Oct 13 09:30:55 2020 +0200

    iommu/vt-d: Don't dereference iommu_device if IOMMU_API is not built

    Since commit c40aaaac1018 ("iommu/vt-d: Gracefully handle DMAR units
    with no supported address widths") dmar.c needs struct iommu_device to
    be selected. We can drop this dependency by not dereferencing struct
    iommu_device if IOMMU_API is not selected and by reusing the information
    stored in iommu->drhd->ignored instead.

    This fixes the following build error when IOMMU_API is not selected:

    drivers/iommu/intel/dmar.c: In function free_iommu:
    drivers/iommu/intel/dmar.c:1139:41: error: struct iommu_device has no member named ops
     1139 |  if (intel_iommu_enabled && iommu->iommu.ops) {
                                                    ^

    Fixes: c40aaaac1018 ("iommu/vt-d: Gracefully handle DMAR units with no supported address widths")
    Signed-off-by: Bartosz Golaszewski <bgolaszewski@baylibre.com>
    Acked-by: Lu Baolu <baolu.lu@linux.intel.com>
    Acked-by: David Woodhouse <dwmw@amazon.co.uk>
    Link: https://lore.kernel.org/r/20201013073055.11262-1-brgl@bgdev.pl
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

Conflicts:
	drivers/iommu/intel/dmar.c (drivers/iommu/dmar.c in RHEL)

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>