[tools] selftests: bpf: add config fragment LWTUNNEL
Message-id: <20190604085256.3304-191-yauheni.kaliuta@redhat.com>
Patchwork-id: 262192
O-Subject: [RHEL8.1 PATCH v2 191/627] selftests: bpf: add config fragment LWTUNNEL
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit d3c72d7a20d8ebb0618d06fc49e83a4d74d96205
Author: Anders Roxell <anders.roxell@linaro.org>
Date:   Wed Oct 10 11:21:23 2018 +0200

    selftests: bpf: add config fragment LWTUNNEL

    When test_lwt_seg6local.sh was added commit c99a84eac026
    ("selftests/bpf: test for seg6local End.BPF action") config fragment
    wasn't added, and without CONFIG_LWTUNNEL enabled we see this:
    Error: CONFIG_LWTUNNEL is not enabled in this kernel.
    selftests: test_lwt_seg6local [FAILED]

    Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
    Acked-by: Song Liu <songliubraving@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>