[include] bpf: Add bpf_jit_blinding_enabled for !CONFIG_BPF_JIT
Message-id: <20200529062245.152030-230-yauheni.kaliuta@redhat.com>
Patchwork-id: 315474
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 230/235] bpf: Add bpf_jit_blinding_enabled for !CONFIG_BPF_JIT
Bugzilla: 1813370
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813370

commit b8cd76ca4ae34731d47cd6a876d912a08efcc240
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Sat Nov 23 21:37:31 2019 +0100

    bpf: Add bpf_jit_blinding_enabled for !CONFIG_BPF_JIT

    Add a definition of bpf_jit_blinding_enabled() when CONFIG_BPF_JIT is not set
    in order to fix a recent build regression:

      [...]
      CC      kernel/bpf/verifier.o
      CC      kernel/bpf/inode.o
    kernel/bpf/verifier.c: In function ‘fixup_bpf_calls’:
    kernel/bpf/verifier.c:9132:25: error: implicit declaration of function ‘bpf_jit_blinding_enabled’; did you mean ‘bpf_jit_kallsyms_enabled’? [-Werror=implicit-function-declaration]
     9132 |  bool expect_blinding = bpf_jit_blinding_enabled(prog);
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~
          |                         bpf_jit_kallsyms_enabled
      CC      kernel/bpf/helpers.o
      CC      kernel/bpf/hashtab.o
      [...]

    Fixes: d2e4c1e6c294 ("bpf: Constant map key tracking for prog array pokes")
    Reported-by: Jakub Sitnicki <jakub@cloudflare.com>
    Reported-by: Andrii Nakryiko <andriin@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/40baf8f3507cac4851a310578edfb98ce73b5605.1574541375.git.daniel@iogearbox.net

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>