[nvme] nvmet: include <linux/scatterlist.h>
Message-id: <20190916085522.19912-45-gtiwari@redhat.com>
Patchwork-id: 271954
O-Subject: [RHEL8.2 V3 044/138] nvmet: include <linux/scatterlist.h>
Bugzilla: 1718463 1711181 1724950 1725066
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Milburn <dmilburn@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1725066
Bugzilla: http://bugzilla.redhat.com/1724950
Bugzilla: http://bugzilla.redhat.com/1711181
Bugzilla: http://bugzilla.redhat.com/1718463

commit a5dffbb66d250a7ef07e27a2e75b8d9d7af2ab41
Author: Enrico Weigelt, metux IT consult <info@metux.net>
Date:   Wed Apr 24 12:34:39 2019 +0200

    nvmet: include <linux/scatterlist.h>

    Build breaks:

        drivers/nvme/target/core.c: In function 'nvmet_req_alloc_sgl':
        drivers/nvme/target/core.c:939:12: error: implicit declaration of \
    function 'sgl_alloc'; did you mean 'bio_alloc'? \
    [-Werror=implicit-function-declaration]
          req->sg = sgl_alloc(req->transfer_len, GFP_KERNEL, &req->sg_cnt);
                    ^~~~~~~~~
                    bio_alloc
        drivers/nvme/target/core.c:939:10: warning: assignment makes pointer \
    from integer without a cast [-Wint-conversion]
          req->sg = sgl_alloc(req->transfer_len, GFP_KERNEL, &req->sg_cnt);
                  ^
        drivers/nvme/target/core.c: In function 'nvmet_req_free_sgl':
        drivers/nvme/target/core.c:952:3: error: implicit declaration of \
    function 'sgl_free'; did you mean 'ida_free'? [-Werror=implicit-function-declaration]
           sgl_free(req->sg);
           ^~~~~~~~
           ida_free

    Cause:

        1. missing include to <linux/scatterlist.h>
        2. SGL_ALLOC needs to be enabled

    Therefore adding the missing include, as well as Kconfig dependency.

    Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
    Reviewed-by: Sagi Grimberg <sagi@grimberg.me>
    Reviewed-by: Minwoo Im <minwoo.im@samsung.com>
    Reviewed-by: Chaitanya Kulkarni <chaitanya.kulkarni@wdc.com>
    Signed-off-by: Christoph Hellwig <hch@lst.de>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>