[net] bpf: skmsg, fix potential psock NULL pointer dereference
Message-id: <89c51df27f86250b9a6cb23091322db94b110fc2.1581076285.git.sdubroca@redhat.com>
Patchwork-id: 294551
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.2 net 02/13] bpf: skmsg, fix potential psock NULL pointer dereference
Bugzilla: 1798179
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1798179
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=26291480
Tested: ktls selftest

commit 8163999db445021f2651a8a47b5632483e8722ea
Author: John Fastabend <john.fastabend@gmail.com>
Date:   Thu Nov 21 08:25:09 2019 -0800

    bpf: skmsg, fix potential psock NULL pointer dereference

    Report from Dan Carpenter,

     net/core/skmsg.c:792 sk_psock_write_space()
     error: we previously assumed 'psock' could be null (see line 790)

     net/core/skmsg.c
       789 psock = sk_psock(sk);
       790 if (likely(psock && sk_psock_test_state(psock, SK_PSOCK_TX_ENABLED)))
     Check for NULL
       791 schedule_work(&psock->work);
       792 write_space = psock->saved_write_space;
                         ^^^^^^^^^^^^^^^^^^^^^^^^
       793          rcu_read_unlock();
       794          write_space(sk);

    Ensure psock dereference on line 792 only occurs if psock is not null.

    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Fixes: 604326b41a6f ("bpf, sockmap: convert to generic sk_msg interface")
    Signed-off-by: John Fastabend <john.fastabend@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Sabrina Dubroca <sdubroca@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>