[tools] perf annotate tui browser: Do not use member from variable within its own initialization
Message-id: <20191126133941.32492-57-mpetlan@redhat.com>
Patchwork-id: 289065
O-Subject: [RHEL8.2 BZ1743210 v2 056/327] perf annotate TUI browser: Do not use member from variable within its own initialization
Bugzilla: 1743210
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1743210
https://bugzilla.redhat.com/show_bug.cgi?id=1743210

upstream
========
commit d5b2179d6a675ee8cdbd3250d42f1e32d5a45fb1
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue May 28 16:02:56 2019 -0300

description
===========
Some compilers will complain when using a member of a struct to
initialize another member, in the same struct initialization.

For instance:

  debian:8      Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
  oraclelinux:7 clang version 3.4.2 (tags/RELEASE_34/dot2-final)

Produce:

  ui/browsers/annotate.c:104:12: error: variable 'ops' is uninitialized when used within its own initialization [-Werror,-Wuninitialized]
                                              (!ops.current_entry ||
                                                ^~~
  1 error generated.

So use an extra variable, initialized just before that struct, to have
the value used in the expressions used to init two of the struct
members.

Fixes: c298304bd747 ("perf annotate: Use a ops table for annotation_line__write()")
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>