[tools] tools/bpf: add missing strings.h include
Message-id: <20190925141552.30691-81-yauheni.kaliuta@redhat.com>
Patchwork-id: 274688
O-Subject: [RHEL8.2 PATCH v2 081/214] tools/bpf: add missing strings.h include
Bugzilla: 1747341
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747341

commit 62b8cea62e8bad0511260faab8e8de04c76a69af
Author: Andrii Nakryiko <andriin@fb.com>
Date:   Thu Feb 7 11:29:24 2019 -0800

    tools/bpf: add missing strings.h include

    Few files in libbpf are using bzero() function (defined in strings.h header), but
    don't include corresponding header. When libbpf is added as a dependency to pahole,
    this undeterministically causes warnings on some machines:

    bpf.c:225:2: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
      bzero(&attr, sizeof(attr));
        ^~~~~

    Signed-off-by: Andrii Nakryiko <andriin@fb.com>
    Reported-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>