[netdrv] net: mlx5e: fix fs_tcp.c build when IPV6 is not enabled
Message-id: <20201209085358.12844-176-ahleihel@redhat.com>
Patchwork-id: 343880
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1858561 v2 175/180] net: mlx5e: fix fs_tcp.c build when IPV6 is not enabled
Bugzilla: 1858561
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1858561
Upstream: v5.10-rc7

commit 8a78a440108e55ddd845b0ef46df575248667520
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Wed Dec 2 20:39:44 2020 -0800

    net: mlx5e: fix fs_tcp.c build when IPV6 is not enabled

    Fix build when CONFIG_IPV6 is not enabled by making a function
    be built conditionally.

    Fixes these build errors and warnings:

    ../drivers/net/ethernet/mellanox/mlx5/core/en_accel/fs_tcp.c: In function 'accel_fs_tcp_set_ipv6_flow':
    ../include/net/sock.h:380:34: error: 'struct sock_common' has no member named 'skc_v6_daddr'; did you mean 'skc_daddr'?
      380 | #define sk_v6_daddr  __sk_common.skc_v6_daddr
          |                                  ^~~~~~~~~~~~
    ../drivers/net/ethernet/mellanox/mlx5/core/en_accel/fs_tcp.c:55:14: note: in expansion of macro 'sk_v6_daddr'
       55 |         &sk->sk_v6_daddr, 16);
          |              ^~~~~~~~~~~
    At top level:
    ../drivers/net/ethernet/mellanox/mlx5/core/en_accel/fs_tcp.c:47:13: warning: 'accel_fs_tcp_set_ipv6_flow' defined but not used [-Wunused-function]
       47 | static void accel_fs_tcp_set_ipv6_flow(struct mlx5_flow_spec *spec, struct sock *sk)

    Fixes: 5229a96e59ec ("net/mlx5e: Accel, Expose flow steering API for rules add/del")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: kernel test robot <lkp@intel.com>
    Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>