[net] mptcp: Fix build with PROC_FS disabled.
Message-id: <20200515101824.19445-25-fwestpha@redhat.com>
Patchwork-id: 309889
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 24/38] mptcp: Fix build with PROC_FS disabled.
Bugzilla: 1835796
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1835796
Upstream Status: commit f6f7d8cf5534

commit f6f7d8cf55348751cc8a5f40c8f9835ee1752df4
Author: David S. Miller <davem@davemloft.net>
Date:   Wed Jan 29 10:39:23 2020 +0100

    mptcp: Fix build with PROC_FS disabled.

    net/mptcp/subflow.c: In function ‘mptcp_subflow_create_socket’:
    net/mptcp/subflow.c:624:25: error: ‘struct netns_core’ has no member named ‘sock_inuse’

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>