kernel/bpf/verifier: Fix build when NET is not enabled
Bugzilla: http://bugzilla.redhat.com/1874006

commit 49a2a4d4163f95e36e2bec50e06813b73401bc76
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Tue Oct 6 19:16:13 2020 -0700

    kernel/bpf/verifier: Fix build when NET is not enabled

    Fix build errors in kernel/bpf/verifier.c when CONFIG_NET is
    not enabled.

    ../kernel/bpf/verifier.c:3995:13: error: ‘btf_sock_ids’ undeclared here (not in a function); did you mean ‘bpf_sock_ops’?
      .btf_id = &btf_sock_ids[BTF_SOCK_TYPE_SOCK_COMMON],

    ../kernel/bpf/verifier.c:3995:26: error: ‘BTF_SOCK_TYPE_SOCK_COMMON’ undeclared here (not in a function); did you mean ‘PTR_TO_SOCK_COMMON’?
      .btf_id = &btf_sock_ids[BTF_SOCK_TYPE_SOCK_COMMON],

    Fixes: 1df8f55a37bd ("bpf: Enable bpf_skc_to_* sock casting helper to networking prog type")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/bpf/20201007021613.13646-1-rdunlap@infradead.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>