[vfio] vfio iommu: Use shift operation for 64-bit integer division
Message-id: <160591307183.28916.8187803230262676670.stgit@gimli.home>
Patchwork-id: 340480
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 kernel PATCH 12/32] vfio iommu: Use shift operation for 64-bit integer division
Bugzilla: 1497898
RH-Acked-by: Auger Eric <eric.auger@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Cornelia Huck <cohuck@redhat.com>

From: Kirti Wankhede <kwankhede@nvidia.com>

Bugzilla: 1497898
Upstream Status: v5.8-rc1

Fixes compilation error with ARCH=i386.

Error fixed by this commit:
ld: drivers/vfio/vfio_iommu_type1.o: in function `vfio_dma_populate_bitmap':
>> vfio_iommu_type1.c:(.text+0x666): undefined reference to `__udivdi3'

Fixes: d6a4c185660c ("vfio iommu: Implementation of ioctl for dirty pages tracking")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Kirti Wankhede <kwankhede@nvidia.com>
Signed-off-by: Alex Williamson <alex.williamson@redhat.com>
(cherry picked from commit cd0bb41ea86027d3a5c3555772692323cbc05bc1)
Signed-off-by: Jan Stancek <jstancek@redhat.com>