[tools] perf scripts python: export-to-postgresql.py: Fix DROP VIEW power_events_view
Message-id: <20191126133941.32492-266-mpetlan@redhat.com>
Patchwork-id: 289269
O-Subject: [RHEL8.2 BZ1743210 v2 265/327] perf scripts python: export-to-postgresql.py: Fix DROP VIEW power_events_view
Bugzilla: 1743210
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1743210
https://bugzilla.redhat.com/show_bug.cgi?id=1743210

upstream
========
commit d8d051df9f906232715282cc0570c94273b197bc
Author: Adrian Hunter <adrian.hunter@intel.com>
Date: Mon Jul 8 08:52:31 2019 +0300

description
===========
PostgreSQL can error if power_events_view is not dropped before its
dependent tables e.g.

  Exception: Query failed: ERROR:  cannot drop table mwait because other
  objects depend on it
  DETAIL:  view power_events_view depends on table mwait

Fixes: aba44287a224 ("perf scripts python: export-to-postgresql.py: Export Intel PT power and ptwrite events")
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>