[sound] ALSA: ASoC: component: suppress uninitialized-variable warning
Message-id: <1602843533499326-143-patchset-jkysela@redhat.com>
Patchwork-id: 331791
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 PATCH 0142/1534] ALSA: ASoC: component: suppress uninitialized-variable warning
Bugzilla: 1869536
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Old versions of gcc (tested on gcc-4.8) produce a warning for
correct code:

sound/soc/soc-compress.c: In function 'soc_compr_open':
sound/soc/soc-compress.c:75:28: error: 'component' is used uninitialized in this function [-Werror=uninitialized]
  struct snd_soc_component *component, *save = NULL;

Change the for_each_rtd_components() macro to ensure 'component'
gets initialized to a value the compiler does not complain about.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20200428214754.3925368-1-arnd@arndb.de
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit be16a0f0dc8fab8e25d9cdbeb4f8f28afc9186d2)
Bugzilla: 1869536
Signed-off-by: Jan Stancek <jstancek@redhat.com>