[include] posix-timers: Unbreak CONFIG_POSIX_TIMERS=n build
Message-id: <20200318140709.5005-74-prarit@redhat.com>
Patchwork-id: 297046
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1810244 v3 73/79] posix-timers: Unbreak CONFIG_POSIX_TIMERS=n build
Bugzilla: 1810244
RH-Acked-by: Phil Auld <pauld@redhat.com>
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Waiman Long <longman@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1810244

commit 8f2edb4a78f7f5fa35c025849152b1d2dfaee4eb
Author: Thomas Gleixner <tglx@linutronix.de>
Date:   Thu Aug 29 08:19:40 2019 +0200

    posix-timers: Unbreak CONFIG_POSIX_TIMERS=n build

    The rework of the posix-cpu-timers patch series dropped the empty
    declaration of struct cpu_timer for the CONFIG_POSIX_TIMERS=n case which
    causes the build to fail:

    ./include/linux/posix-timers.h:218:20: error: field 'cpu' has incomplete type

    Add it back.

    Fixes: 60bda037f1dd ("posix-cpu-timers: Utilize timerqueue for storage")
    Reported-by: Ingo Molnar <mingo@kernel.org>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>