powerpc/64s: Include <asm/nmi.h> header file to fix a warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1941211
Conflicts: Merge conflict due to missing upstream commit a99b9c5ed43e
	   ("powerpc/traps: Show instructions on exceptions").

commit de3c83c2fd2b87cf68214eda76dfa66989d78cb6
Author: Mathieu Malaterre <malat@debian.org>
Date:   Tue, 12 Mar 2019 21:18:23 +0100

    powerpc/64s: Include <asm/nmi.h> header file to fix a warning

    Make sure to include <asm/nmi.h> to provide the following prototype:
    hv_nmi_check_nonrecoverable.

    Remove the following warning treated as error (W=1):

      arch/powerpc/kernel/traps.c:393:6: error: no previous prototype for 'hv_nmi_check_nonrecoverable'

    Fixes: ccd477028a20 ("powerpc/64s: Fix HV NMI vs HV interrupt recoverability test")
    Signed-off-by: Mathieu Malaterre <malat@debian.org>
    Reviewed-by: Christophe Leroy <christophe.leroy@c-s.fr>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Waiman Long <longman@redhat.com>