[include] gpio: Move gpiochip_lock/unlock_as_irq to gpio/driver.h
Message-id: <20200514181537.37426-1-darcari@redhat.com>
Patchwork-id: 308005
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 v2 BZ 1829900 157/233] gpio: Move gpiochip_lock/unlock_as_irq to gpio/driver.h
Bugzilla: 1829900
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1829900
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=28576699
Conflicts: there was a merge conflict between upstream 9091373ab7ea and this
	   patch which was resolved by ae0755b56da9.  This patch includes
	   an extra blankline in gpio/driver.h which was inserted by the
	   latter patch.

commit c7663fa2a6631e5dddc1b7b2ba2e905ddffaff90
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Thu Aug 22 11:18:17 2019 +0800

    gpio: Move gpiochip_lock/unlock_as_irq to gpio/driver.h

    If CONFIG_GPIOLIB is not, gpiochip_lock/unlock_as_irq will
    conflict as this:

    In file included from sound/soc/codecs/wm5100.c:18:0:
    ./include/linux/gpio.h:224:19: error: static declaration of gpiochip_lock_as_irq follows non-static declaration
     static inline int gpiochip_lock_as_irq(struct gpio_chip *chip,
                       ^~~~~~~~~~~~~~~~~~~~
    In file included from sound/soc/codecs/wm5100.c:17:0:
    ./include/linux/gpio/driver.h:494:5: note: previous declaration of gpiochip_lock_as_irq was here
     int gpiochip_lock_as_irq(struct gpio_chip *chip, unsigned int offset);
         ^~~~~~~~~~~~~~~~~~~~
    In file included from sound/soc/codecs/wm5100.c:18:0:
    ./include/linux/gpio.h:231:20: error: static declaration of gpiochip_unlock_as_irq follows non-static declaration
     static inline void gpiochip_unlock_as_irq(struct gpio_chip *chip,
                        ^~~~~~~~~~~~~~~~~~~~~~
    In file included from sound/soc/codecs/wm5100.c:17:0:
    ./include/linux/gpio/driver.h:495:6: note: previous declaration of gpiochip_unlock_as_irq was here
     void gpiochip_unlock_as_irq(struct gpio_chip *chip, unsigned int offset);
         ^~~~~~~~~~~~~~~~~~~~~~

    Move them to gpio/driver.h and use CONFIG_GPIOLIB guard this.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: d74be6dfea1b ("gpio: remove gpiod_lock/unlock_as_irq()")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Link: https://lore.kernel.org/r/20190822031817.32888-1-yuehaibing@huawei.com
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>