net: mana: fix PCI_HYPERV dependency
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1957820

commit 45b102dd81491e30ac7596b5515856141f99319f
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Apr 22 15:34:34 2021 +0200

    net: mana: fix PCI_HYPERV dependency

    The MANA driver causes a build failure in some configurations when
    it selects an unavailable symbol:

    WARNING: unmet direct dependencies detected for PCI_HYPERV
      Depends on [n]: PCI [=y] && X86_64 [=y] && HYPERV [=n] && PCI_MSI [=y] && PCI_MSI_IRQ_DOMAIN [=y] && SYSFS [=y]
      Selected by [y]:
      - MICROSOFT_MANA [=y] && NETDEVICES [=y] && ETHERNET [=y] && NET_VENDOR_MICROSOFT [=y] && PCI_MSI [=y] && X86_64 [=y]
    drivers/pci/controller/pci-hyperv.c: In function 'hv_irq_unmask':
    drivers/pci/controller/pci-hyperv.c:1217:9: error: implicit declaration of function 'hv_set_msi_entry_from_desc' [-Werror=implicit-function-declaration]
     1217 |         hv_set_msi_entry_from_desc(&params->int_entry.msi_entry, msi_desc);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~

    A PCI driver should never depend on a particular host bridge
    implementation in the first place, but if we have this dependency
    it's better to express it as a 'depends on' rather than 'select'.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Dexuan Cui <decui@microsoft.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>