[scripts] selinux: use kernel linux/socket.h for genheaders and mdp
Message-id: <20201026102737.928688-3-omosnace@redhat.com>
Patchwork-id: 335278
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 02/39] selinux: use kernel linux/socket.h for genheaders and mdp
Bugzilla: 1878149
RH-Acked-by: Richard Guy Briggs <rgb@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>

BZ: 1878149
Conflicts:
  - scripts/selinux/mdp/mdp.c - upstream had one extra #include

commit ff1bf4c0714e7936330bb316090a75eaa35061e7
Author: Paulo Alcantara <paulo@paulo.ac>
Date:   Sun Feb 24 21:55:28 2019 -0300

    selinux: use kernel linux/socket.h for genheaders and mdp

    When compiling genheaders and mdp from a newer host kernel, the
    following error happens:

        In file included from scripts/selinux/genheaders/genheaders.c:18:
        ./security/selinux/include/classmap.h:238:2: error: #error New
        address family defined, please update secclass_map.  #error New
        address family defined, please update secclass_map.  ^~~~~
        make[3]: *** [scripts/Makefile.host:107:
        scripts/selinux/genheaders/genheaders] Error 1 make[2]: ***
        [scripts/Makefile.build:599: scripts/selinux/genheaders] Error 2
        make[1]: *** [scripts/Makefile.build:599: scripts/selinux] Error 2
        make[1]: *** Waiting for unfinished jobs....

    Instead of relying on the host definition, include linux/socket.h in
    classmap.h to have PF_MAX.

    Signed-off-by: Paulo Alcantara <paulo@paulo.ac>
    Acked-by: Stephen Smalley <sds@tycho.nsa.gov>
    [PM: manually merge in mdp.c, subject line tweaks]
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>