[kernel] bpf: cgroup: Fix build error without CONFIG_NET
Message-id: <20191112151107.11979-185-yauheni.kaliuta@redhat.com>
Patchwork-id: 285967
O-Subject: [RHEL8.2 185/248] bpf: cgroup: Fix build error without CONFIG_NET
Bugzilla: 1747617
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747617

commit 6705fea0c799a4efb9a9ce2968a2f7a570e33dc2
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Wed Jul 3 16:26:30 2019 +0800

    bpf: cgroup: Fix build error without CONFIG_NET

    If CONFIG_NET is not set and CONFIG_CGROUP_BPF=y,
    gcc building fails:

    kernel/bpf/cgroup.o: In function `cg_sockopt_func_proto':
    cgroup.c:(.text+0x237e): undefined reference to `bpf_sk_storage_get_proto'
    cgroup.c:(.text+0x2394): undefined reference to `bpf_sk_storage_delete_proto'
    kernel/bpf/cgroup.o: In function `__cgroup_bpf_run_filter_getsockopt':
    (.text+0x2a1f): undefined reference to `lock_sock_nested'
    (.text+0x2ca2): undefined reference to `release_sock'
    kernel/bpf/cgroup.o: In function `__cgroup_bpf_run_filter_setsockopt':
    (.text+0x3006): undefined reference to `lock_sock_nested'
    (.text+0x32bb): undefined reference to `release_sock'

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Suggested-by: Stanislav Fomichev <sdf@fomichev.me>
    Fixes: 0d01da6afc54 ("bpf: implement getsockopt and setsockopt hooks")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>