[tools] bpftool: Use linux/types.h from source tree for profiler build
Message-id: <20200610045258.353158-92-yauheni.kaliuta@redhat.com>
Patchwork-id: 319407
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 092/235] bpftool: Use linux/types.h from source tree for profiler build
Bugzilla: 1845114
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1845114

commit fe4eb069edb7ab845160350d9e67d572c026a4a7
Author: Tobias Klauser <tklauser@distanz.ch>
Date:   Thu Mar 12 14:03:30 2020 +0100

    bpftool: Use linux/types.h from source tree for profiler build

    When compiling bpftool on a system where the /usr/include/asm symlink
    doesn't exist (e.g. on an Ubuntu system without gcc-multilib installed),
    the build fails with:

        CLANG    skeleton/profiler.bpf.o
      In file included from skeleton/profiler.bpf.c:4:
      In file included from /usr/include/linux/bpf.h:11:
      /usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
      #include <asm/types.h>
               ^~~~~~~~~~~~~
      1 error generated.
      make: *** [Makefile:123: skeleton/profiler.bpf.o] Error 1

    This indicates that the build is using linux/types.h from system headers
    instead of source tree headers.

    To fix this, adjust the clang search path to include the necessary
    headers from tools/testing/selftests/bpf/include/uapi and
    tools/include/uapi. Also use __bitwise__ instead of __bitwise in
    skeleton/profiler.h to avoid clashing with the definition in
    tools/testing/selftests/bpf/include/uapi/linux/types.h.

    Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Reviewed-by: Quentin Monnet <quentin@isovalent.com>
    Link: https://lore.kernel.org/bpf/20200312130330.32239-1-tklauser@distanz.ch

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>