[usb] usb: typec: fusb302: Fix an undefined reference to 'extcon_get_state'
Message-id: <20201216155447.212357-415-torez@redhat.com>
Patchwork-id: 345609
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 1900751 0414/1059] usb: typec: fusb302: Fix an undefined reference to 'extcon_get_state'
Bugzilla: 1900751 1856683 1838295 1837563 1783493
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1900751
Bugzilla: https://bugzilla.redhat.com/1837563
Bugzilla: https://bugzilla.redhat.com/1856683
Bugzilla: https://bugzilla.redhat.com/1853229
Bugzilla: https://bugzilla.redhat.com/1838295
Bugzilla: https://bugzilla.redhat.com/1836895
Bugzilla: https://bugzilla.redhat.com/1798825
Bugzilla: https://bugzilla.redhat.com/1789257
Bugzilla: https://bugzilla.redhat.com/1783493

Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33777895
Upstream Status: 547fc228755d79af648898187e7831a825d4f42c

Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit 547fc228755d79af648898187e7831a825d4f42c
Author: zhong jiang <zhongjiang@huawei.com>
Date:   Fri Dec 13 20:16:18 2019 +0800

usb: typec: fusb302: Fix an undefined reference to 'extcon_get_state'

Fixes the following compile error:

drivers/usb/typec/tcpm/fusb302.o: In function `tcpm_get_current_limit':
fusb302.c:(.text+0x3ee): undefined reference to `extcon_get_state'
fusb302.c:(.text+0x422): undefined reference to `extcon_get_state'
fusb302.c:(.text+0x450): undefined reference to `extcon_get_state'
fusb302.c:(.text+0x48c): undefined reference to `extcon_get_state'
drivers/usb/typec/tcpm/fusb302.o: In function `fusb302_probe':
fusb302.c:(.text+0x980): undefined reference to `extcon_get_extcon_dev'
make: *** [vmlinux] Error 1

It is because EXTCON is build as a module, but FUSB302 is not.

Suggested-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: zhong jiang <zhongjiang@huawei.com>
Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Reviewed-by: Guenter Roeck <linux@roeck-us.net>
Link: https://lore.kernel.org/r/1576239378-50795-1-git-send-email-zhongjiang@huawei.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>