[net] cfg80211: select CONFIG_CRC32
Message-id: <20210117173911.1916180-120-jarod@redhat.com>
Patchwork-id: 350078
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 PATCH v2 119/176] cfg80211: select CONFIG_CRC32
Bugzilla: 1857772
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1857772

commit 152a8a6c017bfdeda7f6d052fbc6e151891bd9b6
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sun Jan 3 22:36:21 2021 +0100

    cfg80211: select CONFIG_CRC32

    Without crc32 support, this fails to link:

    arm-linux-gnueabi-ld: net/wireless/scan.o: in function `cfg80211_scan_6ghz':
    scan.c:(.text+0x928): undefined reference to `crc32_le'

    Fixes: c8cb5b854b40 ("nl80211/cfg80211: support 6 GHz scanning")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>