[iommu] arm-smmu-v3: Fix build error without CONFIG_PCI_ATS
Message-id: <20191126052402.14821-29-jsnitsel@redhat.com>
Patchwork-id: 288824
O-Subject: [RHEL8.2 PATCH BZ1729845 28/28] iommu/arm-smmu-v3: Fix build error without CONFIG_PCI_ATS
Bugzilla: 1729845
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Auger Eric <eric.auger@redhat.com>
RH-Acked-by: Mark Salter <msalter@redhat.com>

Bugzilla: 1729845
Upstream Status: 097a7df2e3af1b716cd39ce90001a2c372488e58
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24947401

commit 097a7df2e3af1b716cd39ce90001a2c372488e58
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Tue Sep 3 14:50:56 2019 +0800

    iommu/arm-smmu-v3: Fix build error without CONFIG_PCI_ATS

    If CONFIG_PCI_ATS is not set, building fails:

    drivers/iommu/arm-smmu-v3.c: In function arm_smmu_ats_supported:
    drivers/iommu/arm-smmu-v3.c:2325:35: error: struct pci_dev has no member named ats_cap; did you mean msi_cap?
      return !pdev->untrusted && pdev->ats_cap;
				       ^~~~~~~

    ats_cap should only used when CONFIG_PCI_ATS is defined,
    so use #ifdef block to guard this.

    Fixes: bfff88ec1afe ("iommu/arm-smmu-v3: Rework enabling/disabling of ATS for PCI masters")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(imported from commit 097a7df2e3af1b716cd39ce90001a2c372488e58)
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>