[kernel] audit: Add __rcu annotation to RCU pointer
Message-id: <d42b85d2ec0910845223841e6a8e87f2c233d644.1586464474.git.rgb@redhat.com>
Patchwork-id: 302719
Patchwork-instance: patchwork
O-Subject: [PATCH V1 RHEL8.3 BZ1822776] audit: Add __rcu annotation to RCU pointer
Bugzilla: 1822776
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Ondrej Mosnacek <omosnace@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>

BZ: 1822776
Upstream Status: audit/next 5.5-rc1
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27875244

commit cb5172d96d16df72db8b55146b0ec00bfd97f079
Author: Amol Grover <frextrite@gmail.com>
Date:   Mon Dec 2 00:03:48 2019 +0530

    audit: Add __rcu annotation to RCU pointer

    Add __rcu annotation to RCU-protected global pointer auditd_conn.

    auditd_conn is an RCU-protected global pointer,i.e., accessed
    via RCU methods rcu_dereference() and rcu_assign_pointer(),
    hence it must be annotated with __rcu for sparse to report
    warnings/errors correctly.

    Fix multiple instances of the sparse error:
    error: incompatible types in comparison expression
    (different address spaces)

    Reviewed-by: Joel Fernandes (Google) <joel@joelfernandes.org>
    Signed-off-by: Amol Grover <frextrite@gmail.com>
    [PM: tweak subject line]
    Signed-off-by: Paul Moore <paul@paul-moore.com>

Signed-off-by: Richard Guy Briggs <rgb@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>