[kernel] bpf: Fix build error without CONFIG_INET
Message-id: <20191112151107.11979-101-yauheni.kaliuta@redhat.com>
Patchwork-id: 285745
O-Subject: [RHEL8.2 101/248] bpf: Fix build error without CONFIG_INET
Bugzilla: 1747617
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747617

commit 7f94208c8f9a0a6d2ff0e0c0858c00ad8e5c8617
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Wed Jun 12 17:18:47 2019 +0800

    bpf: Fix build error without CONFIG_INET

    If CONFIG_INET is not set, building fails:

    kernel/bpf/verifier.o: In function `check_mem_access':
    verifier.c: undefined reference to `bpf_xdp_sock_is_valid_access'
    kernel/bpf/verifier.o: In function `convert_ctx_accesses':
    verifier.c: undefined reference to `bpf_xdp_sock_convert_ctx_access'

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: fada7fdc83c0 ("bpf: Allow bpf_map_lookup_elem() on an xskmap")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Acked-by: Jonathan Lemon <jonathan.lemon@gmail.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>