iwlwifi: pcie: fix iwl_so_trans_cfg link error when CONFIG_IWLMVM is disabled
Bugzilla: http://bugzilla.redhat.com/1937053

commit 62541e266703549550e77fd46138422dbdc881f1
Author: Kalle Valo <kvalo@codeaurora.org>
Date:   Thu Feb 25 09:04:21 2021 +0200

    iwlwifi: pcie: fix iwl_so_trans_cfg link error when CONFIG_IWLMVM is disabled

    Randy reported an error on his randconfig builds:

    ERROR: modpost: "iwl_so_trans_cfg" [drivers/net/wireless/intel/iwlwifi/iwlwifi.ko] undefined!

    The problem was that when CONFIG_IWLMVM was disabled we were still accessing
    iwl_so_trans_cfg. Fix it by moving IS_ENABLED() check before the access.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Fixes: 930be4e76f26 ("iwlwifi: add support for SnJ with Jf devices")
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Acked-by: Luca Coelho <luciano.coelho@intel.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/1614236661-20274-1-git-send-email-kvalo@codeaurora.org

Signed-off-by: Jarod Wilson <jarod@redhat.com>