[net] nfp: flower: remove unused index from nfp_fl_pedit()
Message-id: <20190610212005.12299-193-ivecera@redhat.com>
Patchwork-id: 264228
O-Subject: [RHEL-8.1 net PATCH 192/194] nfp: flower: remove unused index from nfp_fl_pedit()
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit c0bc5d8e2badeebe14b4005da794a8705b69320e
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Fri Feb 8 17:41:13 2019 +0100

    nfp: flower: remove unused index from nfp_fl_pedit()

    Static checker warning complains on uninitialized variable:

            drivers/net/ethernet/netronome/nfp/flower/action.c:618 nfp_fl_pedit()
            error: uninitialized symbol 'idx'.

    Which is actually never used from the functions that take it as
    parameter. Remove it.

    Fixes: 738678817573 ("drivers: net: use flow action infrastructure")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
    Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>