[md] dm table: don't copy from a NULL pointer in realloc_argv()
Message-id: <20190701141101.27482-5-jmarchan@redhat.com>
Patchwork-id: 266003
O-Subject: [RHEL8.1 BZ 1571628 4/5] dm table: don't copy from a NULL pointer in realloc_argv()
Bugzilla: 1571628
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Mike Snitzer <snitzer@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1571628

commit a0651926553cfe7992166432e418987760882652
Author: Jerome Marchand <jmarchan@redhat.com>
Date:   Wed Jun 12 18:22:26 2019 +0200

    dm table: don't copy from a NULL pointer in realloc_argv()

    For the first call to realloc_argv() in dm_split_args(), old_argv is
    NULL and size is zero. Then memcpy is called, with the NULL old_argv
    as the source argument and a zero size argument. AFAIK, this is
    undefined behavior and generates the following warning when compiled
    with UBSAN on ppc64le:

    In file included from ./arch/powerpc/include/asm/paca.h:19,
                     from ./arch/powerpc/include/asm/current.h:16,
                     from ./include/linux/sched.h:12,
                     from ./include/linux/kthread.h:6,
                     from drivers/md/dm-core.h:12,
                     from drivers/md/dm-table.c:8:
    In function 'memcpy',
        inlined from 'realloc_argv' at drivers/md/dm-table.c:565:3,
        inlined from 'dm_split_args' at drivers/md/dm-table.c:588:9:
    ./include/linux/string.h:345:9: error: argument 2 null where non-null expected [-Werror=nonnull]
      return __builtin_memcpy(p, q, size);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    drivers/md/dm-table.c: In function 'dm_split_args':
    ./include/linux/string.h:345:9: note: in a call to built-in function '__builtin_memcpy'

    Signed-off-by: Jerome Marchand <jmarchan@redhat.com>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>

Cc: Mike Snitzer <snitzer@redhat.com>
Cc: Ming Lei <ming.lei@redhat.com>
Cc: Jerome Marchand <jmarchan@redhat.com>
Cc: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>