samples/bpf: Fix a compilation error with fallthrough marking
Bugzilla: http://bugzilla.redhat.com/1874006

Conflicts: samples/bpf/hbm.c missing hunk from
  df561f6688fe ("treewide: Use fallthrough pseudo-keyword")

commit 544d6adf3c3dddbf80e5757a3098c63612f5f8f8
Author: Yonghong Song <yhs@fb.com>
Date:   Mon Oct 5 21:34:27 2020 -0700

    samples/bpf: Fix a compilation error with fallthrough marking

    Compiling samples/bpf hits an error related to fallthrough marking.
        ...
        CC  samples/bpf/hbm.o
      samples/bpf/hbm.c: In function ‘main’:
      samples/bpf/hbm.c:486:4: error: ‘fallthrough’ undeclared (first use in this function)
          fallthrough;
          ^~~~~~~~~~~

    The "fallthrough" is not defined under tools/include directory.
    Rather, it is "__fallthrough" is defined in linux/compiler.h.
    Including "linux/compiler.h" and using "__fallthrough" fixed the issue.

    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20201006043427.1891805-1-yhs@fb.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>