[scripts] bpf: Emit an #error directive known types list needs updating
Message-id: <20191127192852.21674-30-yauheni.kaliuta@redhat.com>
Patchwork-id: 290424
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 30/69] scripts/bpf: Emit an #error directive known types list needs updating
Bugzilla: 1772081
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1772081

commit 456a513bb5d494f169271b16334049d50c7e630b
Author: Jakub Sitnicki <jakub@cloudflare.com>
Date:   Wed Oct 16 10:58:11 2019 +0200

    scripts/bpf: Emit an #error directive known types list needs updating

    Make the compiler report a clear error when bpf_helpers_doc.py needs
    updating rather than rely on the fact that Clang fails to compile
    English:

    ../../../lib/bpf/bpf_helper_defs.h:2707:1: error: unknown type name 'Unrecognized'
    Unrecognized type 'struct bpf_inet_lookup', please add it to known types!

    Signed-off-by: Jakub Sitnicki <jakub@cloudflare.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/20191016085811.11700-1-jakub@cloudflare.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>