[tools] selftests: bpf: fix compiler warning in flow_dissector test
Message-id: <20191018135423.24316-221-yauheni.kaliuta@redhat.com>
Patchwork-id: 280373
O-Subject: [RHEL8.2 221/268] selftests: bpf: fix compiler warning in flow_dissector test
Bugzilla: 1747615
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747615

commit 5fac1718e706d94a7078addee9075cfaea00ca8c
Author: Alakesh Haloi <alakesh.haloi@gmail.com>
Date:   Tue May 28 19:02:18 2019 +0000

    selftests: bpf: fix compiler warning in flow_dissector test

    Add missing header file following compiler warning:

      prog_tests/flow_dissector.c: In function tx_tap:
      prog_tests/flow_dissector.c:175:9: warning: implicit declaration of function writev; did you mean write? [-Wimplicit-function-declaration]
        return writev(fd, iov, ARRAY_SIZE(iov));
               ^~~~~~
               write

    Fixes: 0905beec9f52 ("selftests/bpf: run flow dissector tests in skb-less mode")
    Signed-off-by: Alakesh Haloi <alakesh.haloi@gmail.com>
    Acked-by: Song Liu <songliubraving@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>