[sound] ALSA: ASoC: cx2072x: mark PM function as __maybe_unused
Message-id: <15693081207948942-955-patchset-jkysela@redhat.com>
Patchwork-id: 274008
O-Subject: [RHEL 8.2 PATCH 0954/1298] ALSA: ASoC: cx2072x: mark PM function as __maybe_unused
Bugzilla: 1738610
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

While the suspend function is already marked __maybe_unused,
the resume function is not, which leads to a warning when
CONFIG_PM is disabled:

sound/soc/codecs/cx2072x.c:1625:12: error: unused function 'cx2072x_runtime_resume' [-Werror,-Wunused-function]

Mark this one like the other one.

Fixes: a497a4363706 ("ASoC: Add support for Conexant CX2072X CODEC")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 83ee240aad9147ed5dac5a7c7b4c559d134072e7)
Bugzilla: 1738610
Signed-off-by: Phillip Lougher <plougher@redhat.com>