[net] mptcp: support IPV6_V6ONLY setsockopt
Message-id: <71043ed61acbd032e42ede10be457a8837588125.1605646322.git.dcaratti@redhat.com>
Patchwork-id: 339825
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net 025/134] mptcp: support IPV6_V6ONLY setsockopt
Bugzilla: 1874368
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1874368
Upstream Status: net.git commit c9b95a135987

commit c9b95a13598750e2840d99322f844ec0ff9e6246
Author: Florian Westphal <fw@strlen.de>
Date:   Sun Jul 5 01:30:17 2020 +0200

    mptcp: support IPV6_V6ONLY setsockopt

    Without this, Opensshd fails to open an ipv6 socket listening
    socket:
      error: setsockopt IPV6_V6ONLY: Operation not supported
      error: Bind to port 22 on :: failed: Address already in use.

    Opensshd opens an ipv4 and and ipv6 listening socket, but because
    IPV6_V6ONLY setsockopt fails, the port number is already in use.

    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>