[net] sched: cls_u32: disallow linking to root hnode
Message-id: <20190610212005.12299-9-ivecera@redhat.com>
Patchwork-id: 263992
O-Subject: [RHEL-8.1 net PATCH 008/194] net: sched: cls_u32: disallow linking to root hnode
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 27594ec4b6a7035450ba43624d1648cbd2c0aaea
Author: Al Viro <viro@zeniv.linux.org.uk>
Date:   Mon Oct 8 06:22:34 2018 -0400

    net: sched: cls_u32: disallow linking to root hnode

    Operation makes no sense.  Nothing will actually break if we do so
    (depth limit in u32_classify() will prevent infinite loops), but
    according to maintainers it's best prohibited outright.

    NOTE: doing so guarantees that u32_destroy() will trigger the call
    of u32_destroy_hnode(); we might want to make that unconditional.

    Test:
    tc qdisc add dev eth0 ingress
    tc filter add dev eth0 parent ffff: protocol ip prio 100 u32 \
    link 800: offset at 0 mask 0f00 shift 6 plus 0 eat match ip protocol 6 ff
    should fail with
    Error: cls_u32: Not linking to root node

    Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>
    Signed-off-by: Jamal Hadi Salim <jhs@mojatatu.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>