[kernel] sched: Fix unreliable rseq cpu_id for new tasks
Message-id: <20201009211330.32269-36-pauld@redhat.com>
Patchwork-id: 330516
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 35/48] sched: Fix unreliable rseq cpu_id for new tasks
Bugzilla: 1877360
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Waiman Long <longman@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1877360

commit ce3614daabea8a2d01c1dd17ae41d1ec5e5ae7db
Author: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Date:   Mon Jul 6 16:49:10 2020 -0400

    sched: Fix unreliable rseq cpu_id for new tasks

    While integrating rseq into glibc and replacing glibc's sched_getcpu
    implementation with rseq, glibc's tests discovered an issue with
    incorrect __rseq_abi.cpu_id field value right after the first time
    a newly created process issues sched_setaffinity.

    For the records, it triggers after building glibc and running tests, and
    then issuing:

      for x in {1..2000} ; do posix/tst-affinity-static  & done

    and shows up as:

    error: Unexpected CPU 2, expected 0
    error: Unexpected CPU 2, expected 0
    error: Unexpected CPU 2, expected 0
    error: Unexpected CPU 2, expected 0
    error: Unexpected CPU 138, expected 0
    error: Unexpected CPU 138, expected 0
    error: Unexpected CPU 138, expected 0
    error: Unexpected CPU 138, expected 0

    This is caused by the scheduler invoking __set_task_cpu() directly from
    sched_fork() and wake_up_new_task(), thus bypassing rseq_migrate() which
    is done by set_task_cpu().

    Add the missing rseq_migrate() to both functions. The only other direct
    use of __set_task_cpu() is done by init_idle(), which does not involve a
    user-space task.

    Based on my testing with the glibc test-case, just adding rseq_migrate()
    to wake_up_new_task() is sufficient to fix the observed issue. Also add
    it to sched_fork() to keep things consistent.

    The reason why this never triggered so far with the rseq/basic_test
    selftest is unclear.

    The current use of sched_getcpu(3) does not typically require it to be
    always accurate. However, use of the __rseq_abi.cpu_id field within rseq
    critical sections requires it to be accurate. If it is not accurate, it
    can cause corruption in the per-cpu data targeted by rseq critical
    sections in user-space.

    Reported-By: Florian Weimer <fweimer@redhat.com>
    Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Tested-By: Florian Weimer <fweimer@redhat.com>
    Cc: stable@vger.kernel.org # v4.18+
    Link: https://lkml.kernel.org/r/20200707201505.2632-1-mathieu.desnoyers@efficios.com

Signed-off-by: Phil Auld <pauld@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>