[tools] libbpf: Use __u32 instead of u32 in bpf_program__load
Message-id: <20190604085256.3304-175-yauheni.kaliuta@redhat.com>
Patchwork-id: 262166
O-Subject: [RHEL8.1 PATCH v2 175/627] libbpf: Use __u32 instead of u32 in bpf_program__load
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit e5b0863c2064f2d40de9de4862317f9db4ccffff
Author: Andrey Ignatov <rdna@fb.com>
Date:   Wed Oct 3 15:26:43 2018 -0700

    libbpf: Use __u32 instead of u32 in bpf_program__load

    Make bpf_program__load consistent with other interfaces: use __u32
    instead of u32. That in turn fixes build of samples:

    In file included from ./samples/bpf/trace_output_user.c:21:0:
    ./tools/lib/bpf/libbpf.h:132:9: error: unknown type name ‘u32’
             u32 kern_version);
             ^

    Fixes: commit 29cd77f41620d ("libbpf: Support loading individual progs")
    Signed-off-by: Andrey Ignatov <rdna@fb.com>
    Acked-by: Alexei Starovoitov <ast@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>