[wireless] ath11k: fix debugfs build failure
Message-id: <20200413203652.3431-520-jarod@redhat.com>
Patchwork-id: 301982
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 519/615] ath11k: fix debugfs build failure
Bugzilla: 1807052
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1807052

commit a45ceea5015d5be4bab4f6ce59cffcbeceba7e6c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jan 7 22:50:04 2020 +0100

    ath11k: fix debugfs build failure

    When CONFIG_ATH11K_DEBUGFS is disabled, but CONFIG_MAC80211_DEBUGFS
    is turned on, the driver fails to build:

    drivers/net/wireless/ath/ath11k/debugfs_sta.c: In function 'ath11k_dbg_sta_open_htt_peer_stats':
    drivers/net/wireless/ath/ath11k/debugfs_sta.c:416:4: error: 'struct ath11k' has no member named 'debug'
      ar->debug.htt_stats.stats_req = stats_req;
        ^~

    It appears that just using the former symbol is sufficient here,
    adding a Kconfig dependency takes care of the corner cases.

    Fixes: d5c65159f289 ("ath11k: driver for Qualcomm IEEE 802.11ax devices")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>