[net] netfilter: nf_flow_table: fix big-endian integer overflow
Message-id: <d15ab616756338a9357a4c3bb6eddd75bcc0d919.1589567677.git.mleitner@redhat.com>
Patchwork-id: 310052
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 092/146] netfilter: nf_flow_table: fix big-endian integer overflow
Bugzilla: 1811193
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Phil Sutter <psutter@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1811193
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28605855

commit c9b3b8207bc487de02cbca968927ba2c2cb46aaf
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Dec 10 21:24:28 2019 +0100

    netfilter: nf_flow_table: fix big-endian integer overflow

    In some configurations, gcc reports an integer overflow:

    net/netfilter/nf_flow_table_offload.c: In function 'nf_flow_rule_match':
    net/netfilter/nf_flow_table_offload.c:80:21: error: unsigned conversion from 'int' to '__be16' {aka 'short unsigned int'} changes value from '327680' to '0' [-Werror=overflow]
       mask->tcp.flags = TCP_FLAG_RST | TCP_FLAG_FIN;
                         ^~~~~~~~~~~~

    From what I can tell, we want the upper 16 bits of these constants,
    so they need to be shifted in cpu-endian mode.

    Fixes: c29f74e0df7a ("netfilter: nf_flow_table: hardware offload support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>