[x86] x86/apic/uv: Avoid unused variable warning
Message-id: <20201117181708.29519-20-framsay@redhat.com>
Patchwork-id: 339758
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 PATCH v3 19/38] x86/apic/uv: Avoid unused variable warning
Bugzilla: 1861439
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1861439
Upstream Status: upstream linux commit d0b7788804482b2689946cd8d910ac3e03126c8d
Brew Info: https://brewweb.devel.redhat.com/taskinfo?taskID=33073987
Tested: PASS, Details in BZ

commit d0b7788804482b2689946cd8d910ac3e03126c8d
Author: Arnd Bergmann <arnd@arndb.de>
Date: Thu Dec 12 15:03:57 2019 +0100

	When CONFIG_PROC_FS is disabled, the compiler warns about an unused
	variable:

	arch/x86/kernel/apic/x2apic_uv_x.c: In function 'uv_setup_proc_files':
	arch/x86/kernel/apic/x2apic_uv_x.c:1546:8: error: unused variable 'name' [-Werror=unused-variable]
	  char *name = hubless ? "hubless" : "hubbed";

	Simplify the code so this variable is no longer needed.

	Fixes: 8785968bce1c ("x86/platform/uv: Add UV Hubbed/Hubless Proc FS Files")
	Signed-off-by: Arnd Bergmann <arnd@arndb.de>
	Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
	Link: https://lore.kernel.org/r/20191212140419.315264-1-arnd@arndb.de

v2: trim spaces from commit ids
v3: cleanup of patch meta-data ordering, no code changes

Signed-off-by: Frank Ramsay <framsay@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>