[net] netfilter: nft_tproxy: Add missing config check
Message-id: <20191118111116.743-4-psutter@redhat.com>
Patchwork-id: 287613
O-Subject: [RHEL8.2 net 3/9] netfilter: nft_tproxy: Add missing config check
Bugzilla: 1762977
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1762977
Upstream Status: commit 033eab53fff7a

commit 033eab53fff7acc0f5718dee6fda641734b94416
Author: Mate Eckl <ecklm94@gmail.com>
Date:   Thu Aug 2 21:18:31 2018 +0200

    netfilter: nft_tproxy: Add missing config check

    A config check was missing form the code when using
    nf_defrag_ipv6_enable with NFT_TPROXY != n and NF_DEFRAG_IPV6 = n and
    this caused the following error:

    ../net/netfilter/nft_tproxy.c: In function 'nft_tproxy_init':
    ../net/netfilter/nft_tproxy.c:237:3: error: implicit declaration of function
    +'nf_defrag_ipv6_enable' [-Werror=implicit-function-declaration]
       err = nf_defrag_ipv6_enable(ctx->net);

    This patch adds a check for NF_TABLES_IPV6 when NF_DEFRAG_IPV6 is
    selected by Kconfig.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Fixes: 4ed8eb6570a4 ("netfilter: nf_tables: Add native tproxy support")
    Signed-off-by: Mate Eckl <ecklm94@gmail.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Phil Sutter <psutter@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>