[tools] selftests/bpf: Fix build of sockmap_ktls.c
Message-id: <d74becdd4b6dec1c590660fb0cc102e8c27c664f.1589962818.git.sdubroca@redhat.com>
Patchwork-id: 312959
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 net 51/52] selftests/bpf: Fix build of sockmap_ktls.c
Bugzilla: 1819627
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1819627
Brew: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=28687932
Tested: sockmap + tls selftests

commit 500897804a369358f4d27356787dcf9b33527fd7
Author: Alexei Starovoitov <ast@kernel.org>
Date:   Wed Feb 19 12:55:14 2020 -0800

    selftests/bpf: Fix build of sockmap_ktls.c

    The selftests fails to build with:
    tools/testing/selftests/bpf/prog_tests/sockmap_ktls.c: In function ‘test_sockmap_ktls_disconnect_after_delete’:
    tools/testing/selftests/bpf/prog_tests/sockmap_ktls.c:72:37: error: ‘TCP_ULP’ undeclared (first use in this function)
       72 |  err = setsockopt(cli, IPPROTO_TCP, TCP_ULP, "tls", strlen("tls"));
          |                                     ^~~~~~~

    Similar to commit that fixes build of sockmap_basic.c on systems with old
    /usr/include fix the build of sockmap_ktls.c

    Fixes: d1ba1204f2ee ("selftests/bpf: Test unhashing kTLS socket after removing from map")
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: John Fastabend <john.fastabend@gmail.com>
    Link: https://lore.kernel.org/bpf/20200219205514.3353788-1-ast@kernel.org

Signed-off-by: Sabrina Dubroca <sdubroca@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>