[netdrv] mlxsw: spectrum_router: Skip loopback RIFs during MAC validation
Message-id: <20200601180237.4179948-90-ivecera@redhat.com>
Patchwork-id: 315864
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 PATCH 089/290] mlxsw: spectrum_router: Skip loopback RIFs during MAC validation
Bugzilla: 1821646
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1821646

Upstream commit(s):
commit 314bd842d98e1035cc40b671a71e07f48420e58f
Author: Amit Cohen <amitc@mellanox.com>
Date:   Sun Dec 29 13:40:22 2019 +0200

    mlxsw: spectrum_router: Skip loopback RIFs during MAC validation

    When a router interface (RIF) is created the MAC address of the backing
    netdev is verified to have the same MSBs as existing RIFs. This is
    required in order to avoid changing existing RIF MAC addresses that all
    share the same MSBs.

    Loopback RIFs are special in this regard as they do not have a MAC
    address, given they are only used to loop packets from the overlay to
    the underlay.

    Without this change, an error is returned when trying to create a RIF
    after the creation of a GRE tunnel that is represented by a loopback
    RIF. 'rif->dev->dev_addr' points to the GRE device's local IP, which
    does not share the same MSBs as physical interfaces. Adding an IP
    address to any physical interface results in:

    Error: mlxsw_spectrum: All router interface MAC addresses must have the
    same prefix.

    Fix this by skipping loopback RIFs during MAC validation.

    Fixes: 74bc99397438 ("mlxsw: spectrum_router: Veto unsupported RIF MAC addresses")
    Signed-off-by: Amit Cohen <amitc@mellanox.com>
    Signed-off-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>