[net] ipv4: avoid compile error in fib_info_nh_uses_dev
Message-id: <8feee16743f279713f7d04af31028371ec9e1c51.1559054178.git.poros@redhat.com>
Patchwork-id: 261038
O-Subject: [RHEL8.1 net PATCH 14/18] net/ipv4: avoid compile error in fib_info_nh_uses_dev
Bugzilla: 1714656
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1714656

Upstream commit(s):
commit 075e264fa33e7838680802ba514a8d67433e48d1
Author: Eric Dumazet <edumazet@google.com>
Date:   Fri Sep 21 10:58:07 2018 -0700

    net/ipv4: avoid compile error in fib_info_nh_uses_dev

    net/ipv4/fib_frontend.c: In function 'fib_info_nh_uses_dev':
    net/ipv4/fib_frontend.c:322:6: error: unused variable 'ret' [-Werror=unused-variable]
    cc1: all warnings being treated as errors

    Fixes: 78f2756c5fc0 ("net/ipv4: Move device validation to helper")
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Cc: David Ahern <dsahern@gmail.com>
    Reviewed-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>