[scsi] scsi: lpfc: fix 32-bit format string warning
Message-id: <20190326145855.8147-10-dkennedy@redhat.com>
Patchwork-id: 247744
O-Subject: [rhel8.1 patch e-stor 09/44] scsi: lpfc: fix 32-bit format string warning
Bugzilla: 1692882
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Ewan Milne <emilne@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

On 32-bit architectures, we see a warning when %ld is used to print a
size_t:

In file included from drivers/scsi/lpfc/lpfc_init.c:62:
drivers/scsi/lpfc/lpfc_init.c: In function 'lpfc_new_io_buf':
drivers/scsi/lpfc/lpfc_logmsg.h:62:45: error: format '%ld' expects argument of type 'long int', but argument 5 has type 'unsigned int' [-Werror=format=]

This is harmless, but portable code should just use %zd to avoid the
warning.

Fixes: 0794d601d174 ("scsi: lpfc: Implement common IO buffers between NVME and SCSI")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit f996861be108f6152d60d7357301697c3309c77f)
Signed-off-by: Dick Kennedy <dkennedy@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>