[xen] swiotlb: fix phys_addr_t overflow warning
Message-id: <20190822214914.19135-68-ddutile@redhat.com>
Patchwork-id: 269598
O-Subject: [PATCH RHEL-8.1 v3 67/79] swiotlb: fix phys_addr_t overflow warning
Bugzilla: 1738631
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Mark Salter <msalter@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1738631

commit 9c106119f6538f65bdddb7948a157d90625effa7
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jun 17 15:28:43 2019 +0200

    swiotlb: fix phys_addr_t overflow warning

    On architectures that have a larger dma_addr_t than phys_addr_t,
    the swiotlb_tbl_map_single() function truncates its return code
    in the failure path, making it impossible to identify the error
    later, as we compare to the original value:

    kernel/dma/swiotlb.c:551:9: error: implicit conversion from 'dma_addr_t' (aka 'unsigned long long') to 'phys_addr_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]
            return DMA_MAPPING_ERROR;

    Use an explicit typecast here to convert it to the narrower type,
    and use the same expression in the error handling later.

    Fixes: b907e20508d0 ("swiotlb: remove SWIOTLB_MAP_ERROR")
    Acked-by: Stefano Stabellini <sstabellini@kernel.org>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>