[net] rtnetlink: Add more extack messages to rtnl_newlink
Message-id: <b5a5fbb414e86e2c076944fea38407faa8e1df2a.1570459136.git.poros@redhat.com>
Patchwork-id: 276926
O-Subject: [RHEL8.2 net PATCH 01/18] rtnetlink: Add more extack messages to rtnl_newlink
Bugzilla: 1757750
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1757750

Upstream commit(s):
commit 68d57f3b1d1a87b4022a0a7463126d7ea172bda1
Author: David Ahern <dsahern@gmail.com>
Date:   Tue Nov 6 12:51:16 2018 -0800

    rtnetlink: Add more extack messages to rtnl_newlink

    Add extack arg to the nla_parse_nested calls in rtnl_newlink, and
    add messages for unknown device type and link network namespace id.
    In particular, it improves the failure message when the wrong link
    type is used. From
        $ ip li add bond1 type bonding
        RTNETLINK answers: Operation not supported
    to
        $ ip li add bond1 type bonding
        Error: Unknown device type.

    (The module name is bonding but the link type is bond.)

    Signed-off-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>