[acpi] ACPI/IORT: Fix build error when IOMMU_SUPPORT is disabled
Message-id: <20191110173746.26019-243-ahs3@redhat.com>
Patchwork-id: 285003
O-Subject: [RHEL8.2 PATCH v5 242/299] ACPI/IORT: Fix build error when IOMMU_SUPPORT is disabled
Bugzilla: 1754787 1739728 1730098 1721297 1664185
RH-Acked-by: Jeremy Linton <jlinton@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664185
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1721297
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1730098
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1739728
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1754787
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24584640
Upstream Status: 8212688600edcb4a147ab7e4634c448938f9121a
Tested: multiple BZs are covered by this patch set:

 bz1664185: this requires an ACPI HMAT table plus the hardware that it
 describes.  For full testing, PartnerQA is recommended.  Barring
 that, does an HMAT table exist, and are there sysfs entries for
 it showing up?

 bz1721297: this requires the latest ACPI PPTT tables in firmware, and
 the hardware that reflects it, so PartnerQA is required.  NB:
 there are additional patches for SPE that will need to be added
 -- see bz1504978 -- but these are the ACPI patches required for
 the SPE patches.

 bz1730098: same as bz1664185, but different partner.

 bz1739728: basic kernel testing and running of the kernel CI tests; in
 general, if a system boots and runs with all known hardware active
 and usable, the ACPI subsystem is behaving.  Re-ran CKI tests for
 v2.

 bz1754787: Windows 2018 string for _OSI, needs confirmation from the
 partner, also.

commit 8212688600edcb4a147ab7e4634c448938f9121a
Author: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
Date:   Thu May 16 16:52:58 2019 +0100

    ACPI/IORT: Fix build error when IOMMU_SUPPORT is disabled

    If IOMMU_SUPPORT is not enabled (and therefore IOMMU_API is not
    selected), struct iommu_fwspec is an empty struct and
    IOMMU_FWSPEC_PCI_RC_ATS is not defined, resulting in the following
    compilation errors:

    drivers/acpi/arm64/iort.c: In function iort_iommu_configure:
    drivers/acpi/arm64/iort.c:1079:21: error: struct iommu_fwspec has no member named flag:
        dev->iommu_fwspec->flags |= IOMMU_FWSPEC_PCI_RC_ATS;
                         ^~
    drivers/acpi/arm64/iort.c:1079:32: error: IOMMU_FWSPEC_PCI_RC_ATS
    undeclared (first use in this function)
        dev->iommu_fwspec->flags |= IOMMU_FWSPEC_PCI_RC_ATS;
                                    ^~~~~~~~~~~~~~~~~~~~~~~
    drivers/acpi/arm64/iort.c:1079:32: note: each undeclared identifier is reported only once for each function it appears in

    Move iort_iommu_configure() (and the helpers functions it relies on)
    into CONFIG_IOMMU_API preprocessor guarded code so that when
    CONFIG_IOMMU_SUPPORT is not enabled we prevent compiling code that is
    basically equivalent to no-OP, fixing the build errors.

    Cc: Jean-Philippe Brucker <jean-philippe.brucker@arm.com>
    Cc: Will Deacon <will.deacon@arm.com>
    Cc: Robin Murphy <robin.murphy@arm.com>
    Link: https://lore.kernel.org/linux-arm-kernel/20190515034253.79348-1-wangkefeng.wang@huawei.com/
    Fixes: 5702ee24182f ("ACPI/IORT: Check ATS capability in root complex nodes")
    Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
    Signed-off-by: Will Deacon <will.deacon@arm.com>
    (cherry picked from commit 8212688600edcb4a147ab7e4634c448938f9121a)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>