perf tests x86: Move insn.h include to make sure it finds stddef.h
Bugzilla: https://bugzilla.redhat.com/1944685

upstream
========
commit c1f272df510c6b1db68ca6597724d17b557d1407
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Mar 4 09:51:52 2021 -0300

description
===========
In some versions of alpine Linux the perf build is broken since commit
1d509f2a6ebca1ae ("x86/insn: Support big endian cross-compiles"):

  In file included from /usr/include/linux/byteorder/little_endian.h:13,
                   from /usr/include/asm/byteorder.h:5,
                   from arch/x86/util/../../../../arch/x86/include/asm/insn.h:10,
                   from arch/x86/util/archinsn.c:2:
  /usr/include/linux/swab.h:161:8: error: unknown type name '__always_inline'
   static __always_inline __u16 __swab16p(const __u16 *p)

So move the inclusion of arch/x86/include/asm/insn.h to later in the
places where linux/stddef.h (that conditionally defines
__always_inline) to workaround this problem on Alpine Linux 3.9 to 3.11,
3.12 onwards works.

Signed-off-by: Michael Petlan <mpetlan@redhat.com>