[tools] perf tools: Free temporary 'sys' string in read_event_files()
Message-id: <6eafe5c22e6fc67c665ca3fa44e3a8ae3c68e02c.1559304074.git.mpetlan@redhat.com>
Patchwork-id: 261498
O-Subject: [RHEL8.1 BZ1709243 141/217] perf tools: Free temporary 'sys' string in read_event_files()
Bugzilla: 1709243
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1709243
https://bugzilla.redhat.com/show_bug.cgi?id=1709243

upstream
========
commit 1e44224fb0528b4c0cc176bde2bb31e9127eb14b
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:14 2018 -0400

description
===========
For each system in a given pevent, read_event_files() reads in a
temporary 'sys' string.  Be sure to free this string before moving onto
to the next system and/or leaving read_event_files().

Fixes the following coverity complaints:

  Error: RESOURCE_LEAK (CWE-772):

  tools/perf/util/trace-event-read.c:343: overwrite_var: Overwriting
  "sys" in "sys = read_string()" leaks the storage that "sys" points to.

  tools/perf/util/trace-event-read.c:353: leaked_storage: Variable "sys"
  going out of scope leaks the storage it points to.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>