[usb] usb: mtu3: fix up undefined reference to usb_debug_root
Message-id: <20200407161320.17414-776-torez@redhat.com>
Patchwork-id: 300511
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 775/983] usb: mtu3: fix up undefined reference to usb_debug_root
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit 9610450ea31eb061b9914de2bf6ced424956182d
Author: Chunfeng Yun <chunfeng.yun@mediatek.com>
Date:   Sun May 5 14:02:49 2019 +0800

    usb: mtu3: fix up undefined reference to usb_debug_root

    When CONFIG_USB is not set, and CONFIG_USB_GADGET is set,
    there is an issue:

    ld:
    drivers/usb/mtu3/mtu3_debugfs.o: in function 'ssusb_debugfs_create_root':
    mtu3_debugfs.c:(.text+0xba3): undefined reference to 'usb_debug_root'

    usb_debug_root is only built when CONFIG_USB is enabled, so here drop it
    and use NULL instead.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Chunfeng Yun <chunfeng.yun@mediatek.com>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>