[tools] perf/ui/gtk: Fix gtk2 build
Message-id: <20200522095131.24335-40-mpetlan@redhat.com>
Patchwork-id: 313685
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 39/98] perf/ui/gtk: Fix gtk2 build
Bugzilla: 1818841
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1818841
https://bugzilla.redhat.com/show_bug.cgi?id=1818841

upstream
========
commit 93e843f95f095aeb533ab67ac4718f848d38dfa0
Author: Jiri Olsa <jolsa@kernel.org>
Date: Mon Jan 13 11:43:58 2020 +0100

description
===========
Ravi Bangoria reported an issue when doing the gtk2 feature detection on
Fedora 31, where some types got deprecated:

  /usr/include/gtk-2.0/gtk/gtktypeutils.h:236:1: error: ‘GTypeDebugFlags’ is deprecated [-Werror=deprecated-declarations]
    236 | void            gtk_type_init   (GTypeDebugFlags    debug_flags);

Fix this for perf by allowing the compile to pass with deprecated
symbols via the -Wno-deprecated-declarations compiler directive.

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>