[bluetooth] Bluetooth: btusb: avoid unused function warning
Message-id: <20200707102204.31859-20-gtiwari@redhat.com>
Patchwork-id: 321861
Patchwork-instance: patchwork
O-Subject: [RHEL8 BZ 1838924 019/165] Bluetooth: btusb: avoid unused function warning
Bugzilla: 1838924
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1838924

commit 42d22098127d6384f789107f59caae87d7520fc4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 18 21:59:02 2019 +0200

    Bluetooth: btusb: avoid unused function warning

    The btusb_rtl_cmd_timeout() function is used inside of an
    ifdef, leading to a warning when this part is hidden
    from the compiler:

    drivers/bluetooth/btusb.c:530:13: error: unused function 'btusb_rtl_cmd_timeout' [-Werror,-Wunused-function]

    Use an IS_ENABLED() check instead so the compiler can see
    the code and then discard it silently.

    Fixes: d7ef0d1e3968 ("Bluetooth: btusb: Use cmd_timeout to reset Realtek device")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>