[sound] ALSA: ASoC: Intel: boards: Fix compile-testing RT1011/RT5682
Message-id: <15898774120838792-656-patchset-jkysela@redhat.com>
Patchwork-id: 311617
Patchwork-instance: patchwork
O-Subject: [RHEL 8.3 PATCH v2 0655/1765] ALSA: ASoC: Intel: boards: Fix compile-testing RT1011/RT5682
Bugzilla: 1797509
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

On non-x86, the new driver results in a build failure:

sound/soc/intel/boards/cml_rt1011_rt5682.c:14:10: fatal error: asm/cpu_device_id.h: No such file or directory

The asm/cpu_device_id.h header is not actually needed here,
so don't include it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20200102135322.1841053-1-arnd@arndb.de
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit ff3b57417012fcc963ec281f5705bed837e4b1ac)
Bugzilla: 1797509
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>