[powerpc] silence a -Wcast-function-type warning in dawr_write_file_bool
Message-id: <20201117152733.1509856-8-gkurz@redhat.com>
Patchwork-id: 339691
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 kernel virt PATCH 07/41] powerpc: silence a -Wcast-function-type warning in dawr_write_file_bool
Bugzilla: 1882796
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Mathieu Malaterre <malat@debian.org>

In commit c1fe190c0672 ("powerpc: Add force enable of DAWR on P9
option") the following piece of code was added:

   smp_call_function((smp_call_func_t)set_dawr, &null_brk, 0);

Since GCC 8 this triggers the following warning about incompatible
function types:

  arch/powerpc/kernel/hw_breakpoint.c:408:21: error: cast between incompatible function types from 'int (*)(struct arch_hw_breakpoint *)' to 'void (*)(void *)' [-Werror=cast-function-type]

Since the warning is there for a reason, and should not be hidden behind
a cast, provide an intermediate callback function to avoid the warning.

Fixes: c1fe190c0672 ("powerpc: Add force enable of DAWR on P9 option")
Suggested-by: Christoph Hellwig <hch@infradead.org>
Signed-off-by: Mathieu Malaterre <malat@debian.org>
Signed-off-by: Michael Neuling <mikey@neuling.org>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 548c54acba5bd1388d50727a9a126a42d0cd4ad0)
Signed-off-by: Greg Kurz <gkurz@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>