[netdrv] i40e: fix return of uninitialized aq_ret in i40e_set_vsi_promisc
Message-id: <20201028131535.49723-3-sassmann@redhat.com>
Patchwork-id: 335977
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 2/3] i40e: fix return of uninitialized aq_ret in i40e_set_vsi_promisc
Bugzilla: 1835705
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

From: Stefan Assmann <sassmann@kpanic.de>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1835705
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=32517963

drivers/net/ethernet/intel/i40e/i40e_virtchnl_pf.c: In function ‘i40e_set_vsi_promisc’:
drivers/net/ethernet/intel/i40e/i40e_virtchnl_pf.c:1176:14: error: ‘aq_ret’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  i40e_status aq_ret;

In case the code inside the if statement and the for loop does not get
executed aq_ret will be uninitialized when the variable gets returned at
the end of the function.

Avoid this by changing num_vlans from int to u16, so aq_ret always gets
set. Making this change in additional places as num_vlans should never
be negative.

Fixes: 37d318d7805f ("i40e: Remove scheduling while atomic possibility")
Signed-off-by: Stefan Assmann <sassmann@kpanic.de>
Acked-by: Jakub Kicinski <kuba@kernel.org>
Tested-by: Aaron Brown <aaron.f.brown@intel.com>
Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>

Signed-off-by: Stefan Assmann <sassmann@redhat.com>
(cherry picked from commit e1e1b5356eb48dce4307f5cae10e4d6d5bd3df74)
Signed-off-by: Jan Stancek <jstancek@redhat.com>