[net] Provide stub for __netif_set_xps_queue if there is no CONFIG_XPS
Message-id: <20181122193455.25856-10-ivecera@redhat.com>
Patchwork-id: 233602
O-Subject: [RHEL8.0 net PATCH 09/16] net: Provide stub for __netif_set_xps_queue if there is no CONFIG_XPS
Bugzilla: 1651781
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Ken Cox <jkc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1651781

Upstream commit(s):
commit c9fbb2d25295a566b97d62e6904741e8e1702d83
Author: Krzysztof Kozlowski <krzk@kernel.org>
Date:   Fri Aug 10 10:47:43 2018 +0200

    net: Provide stub for __netif_set_xps_queue if there is no CONFIG_XPS

    Building virtio_net driver without CONFIG_XPS fails with:

        drivers/net/virtio_net.c: In function 'virtnet_set_affinity':
        drivers/net/virtio_net.c:1910:3: error: implicit declaration of function '__netif_set_xps_queue' [-Werror=implicit-function-declaration]
           __netif_set_xps_queue(vi->dev, mask, i, false);
           ^
    Fixes: 4d99f6602cb5 ("net: allow to call netif_reset_xps_queues() under cpus_read_lock")
    Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>