platform/x86: intel_pmc_core: add ACPI dependency
Bugzilla: http://bugzilla.redhat.com/1783557

commit f75bf693c919438cbe44717d63aa11856a062b9a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 21 15:49:39 2021 +0200

    platform/x86: intel_pmc_core: add ACPI dependency

    The driver now fails to build without ACPI:

    drivers/platform/x86/intel_pmc_core.c: In function 'pmc_core_get_tgl_lpm_reqs':
    drivers/platform/x86/intel_pmc_core.c:617:41: error: invalid use of undefined type 'struct acpi_device'
      617 |         out_obj = acpi_evaluate_dsm(adev->handle, &s0ix_dsm_guid, 0,

    This could probably be made optional, but it won't be used without
    ACPI in practice, so just add a Kconfig dependency.

    Fixes: 428131364f00 ("platform/x86: intel_pmc_core: Get LPM requirements for Tiger Lake")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Link: https://lore.kernel.org/r/20210421134957.3329062-1-arnd@kernel.org
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>

v2: added missing PCI dependency

Signed-off-by: David Arcari <darcari@redhat.com>