[misc] misc: kgdbts: Fix restrict error
Message-id: <20181128174629.20727-14-labbott@redhat.com>
Patchwork-id: 233887
O-Subject: [RHEL8.0 BZ 1626466 13/17] misc: kgdbts: Fix restrict error
Bugzilla: 1582754
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1582754
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=19300249
Testing: Compile only

commit fa0218ef733e6f247a1a3986e3eb12460064ac77
Author: Laura Abbott <labbott@redhat.com>
Date:   Tue Sep 11 10:44:03 2018 -0700

    misc: kgdbts: Fix restrict error

    kgdbts current fails when compiled with restrict:

    drivers/misc/kgdbts.c: In function ‘configure_kgdbts’:
    drivers/misc/kgdbts.c:1070:2: error: ‘strcpy’ source argument is the same as destination [-Werror=restrict]
      strcpy(config, opt);
      ^~~~~~~~~~~~~~~~~~~

    As the error says, config is being used in both the source and destination.
    Refactor the code to avoid the extra copy and put the parsing closer to
    the actual location.

    Signed-off-by: Laura Abbott <labbott@redhat.com>
    Acked-by: Daniel Thompson <daniel.thompson@linaro.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Cc: Laura Abbott <labbott@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>