[tools] tools build: Add -lrt to FEATURE_CHECK_LDFLAGS-libaio
Message-id: <20191104222454.10863-288-mpetlan@redhat.com>
Patchwork-id: 282929
O-Subject: [RHEL8.2 BZ1715508 287/327] tools build: Add -lrt to FEATURE_CHECK_LDFLAGS-libaio
Bugzilla: 1715508
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715508
https://bugzilla.redhat.com/show_bug.cgi?id=1715508

upstream
========
commit aa8f9c517ebce7a0959da064ef2660ea03f133f8
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Feb 12 11:20:56 2019 -0300

description
===========
Since we need it to resolve the AIO symbols, otherwise we fail with:

  $ cat /tmp/build/perf/feature/test-all.make.output
  /usr/bin/ld: /tmp/ccEqrj36.o: undefined reference to symbol 'aio_return64@@GLIBC_2.2.5'
  /usr/bin/ld: //usr/lib64/librt.so.1: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status
  $

When we added the aio support in 'perf record' only the test-libaio.bin
target got the -lrt, i.e. the feature detection slow path. Fix it.

Fixes: 2a07d814747b ("tools build feature: Check if libaio is available")
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>