[tools] lib/lockdep: Rename "trywlock" into "trywrlock"
Message-id: <20191111194853.28672-7-longman@redhat.com>
Patchwork-id: 285318
O-Subject: [RHEL8.2 PATCH 06/92] tools/lib/lockdep: Rename "trywlock" into "trywrlock"
Bugzilla: 1736654
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1736654

commit 7f3c7952d111ac93573fb86f4d5aeff527a07fcc
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Thu Dec 6 17:11:29 2018 -0800

    tools/lib/lockdep: Rename "trywlock" into "trywrlock"

    This patch avoids that the following compiler warning is reported while
    compiling the lockdep unit tests:

    include/liblockdep/rwlock.h: In function 'liblockdep_pthread_rwlock_trywlock':
    include/liblockdep/rwlock.h:66:9: warning: implicit declaration of function 'pthread_rwlock_trywlock'; did you mean 'pthread_rwlock_trywrlock'? [-Wimplicit-function-declaration]
      return pthread_rwlock_trywlock(&lock->rwlock) == 0 ? 1 : 0;
             ^~~~~~~~~~~~~~~~~~~~~~~
             pthread_rwlock_trywrlock

    Signed-off-by: Bart Van Assche <bvanassche@acm.org>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Cc: Johannes Berg <johannes@sipsolutions.net>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Sasha Levin <sasha.levin@oracle.com>
    Cc: Sasha Levin <sashal@kernel.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Waiman Long <longman@redhat.com>
    Cc: johannes.berg@intel.com
    Cc: tj@kernel.org
    Fixes: 5a52c9b480e0 ("liblockdep: Add public headers for pthread_rwlock_t implementation")
    Link: https://lkml.kernel.org/r/20181207011148.251812-6-bvanassche@acm.org
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>