[net] bpf: Fix static checker warning
Message-id: <20200529062245.152030-195-yauheni.kaliuta@redhat.com>
Patchwork-id: 315402
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 195/235] bpf: Fix static checker warning
Bugzilla: 1813370
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813370

commit d0f010434124598988ba1c97fbb0e4e820ff5d8c
Author: Alexei Starovoitov <ast@kernel.org>
Date:   Tue Nov 26 15:01:06 2019 -0800

    bpf: Fix static checker warning

    kernel/bpf/btf.c:4023 btf_distill_func_proto()
            error: potentially dereferencing uninitialized 't'.

    kernel/bpf/btf.c
      4012          nargs = btf_type_vlen(func);
      4013          if (nargs >= MAX_BPF_FUNC_ARGS) {
      4014                  bpf_log(log,
      4015                          "The function %s has %d arguments. Too many.\n",
      4016                          tname, nargs);
      4017                  return -EINVAL;
      4018          }
      4019          ret = __get_type_size(btf, func->type, &t);
                                                           ^^
    t isn't initialized for the first -EINVAL return

    This is unlikely path, since BTF should have been validated at this point.
    Fix it by returning 'void' BTF.

    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/20191126230106.237179-1-ast@kernel.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>