[netdrv] net/mlx5e: Fix compilation warning in en_tc.c
Message-id: <20190611144900.12371-42-ahleihel@redhat.com>
Patchwork-id: 265169
O-Subject: [RHEL8.1 BZ 1691238 v2 41/45] net/mlx5e: Fix compilation warning in en_tc.c
Bugzilla: 1691238
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1691238
Upstream: net-next/master
Conflicts:
 - drivers/net/ethernet/mellanox/mlx5/core/eswitch.h
   Context diff due to missing patches from v5.1

commit ee576ec1c1c66ec1cd0c4735bb12bc08f675f530
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Thu Mar 21 15:51:33 2019 -0700

    net/mlx5e: Fix compilation warning in en_tc.c

    Amazingly a mlx5e_tc function is being called from the eswitch layer,
    which is by itself very terrible! The function was declared locally in
    eswitch_offloads.c so it could be used there, which caused the following
    compilation warning, fix that.

    drivers/.../mlx5/core/en_tc.c:3242:6: [-Werror=missing-prototypes]
    error: no previous prototype for ‘mlx5e_tc_clean_fdb_peer_flows’

    Fixes: 04de7dda7394 ("net/mlx5e: Infrastructure for duplicated offloading of TC flows")
    Reviewed-by: Roi Dayan <roid@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>