[netdrv] mlx4: avoid large stack usage in mlx4_init_hca()
Message-id: <20200402134258.14983-4-ahleihel@redhat.com>
Patchwork-id: 298970
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1789363 03/14] mlx4: avoid large stack usage in mlx4_init_hca()
Bugzilla: 1789363 1789361
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1789361
Bugzilla: http://bugzilla.redhat.com/1789363
Upstream: v5.4-rc1

commit 9eed21c01c7827f029000f77d59b61d1b16cb024
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 22 17:01:55 2019 +0200

    mlx4: avoid large stack usage in mlx4_init_hca()

    The mlx4_dev_cap and mlx4_init_hca_param are really too large
    to be put on the kernel stack, as shown by this clang warning:

    drivers/net/ethernet/mellanox/mlx4/main.c:3304:12: error: stack frame size of 1088 bytes in function 'mlx4_load_one' [-Werror,-Wframe-larger-than=]

    With gcc, the problem is the same, but it does not warn because
    it does not inline this function, and therefore stays just below
    the warning limit, while clang is just above it.

    Use kzalloc for dynamic allocation instead of putting them
    on stack. This gets the combined stack frame down to 424 bytes.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Saeed Mahameed <saeedm@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>