[net] report invalid mtu value via netlink extack
Message-id: <20190912144125.11447-4-ivecera@redhat.com>
Patchwork-id: 271242
O-Subject: [RHEL-8.2 net PATCH 3/4] net: report invalid mtu value via netlink extack
Bugzilla: 1751279
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1751279

Upstream commit(s):
commit 7a4c53bee3324ac00bf964aa2f82d15d279e86e4
Author: Stephen Hemminger <stephen@networkplumber.org>
Date:   Fri Jul 27 13:43:23 2018 -0700

    net: report invalid mtu value via netlink extack

    If an invalid MTU value is set through rtnetlink return extra error
    information instead of putting message in kernel log. For other cases
    where there is no visible API, keep the error report in the log.

    Example:
            # ip li set dev enp12s0 mtu 10000
            Error: mtu greater than device maximum.

            # ifconfig enp12s0 mtu 10000
            SIOCSIFMTU: Invalid argument
            # dmesg | tail -1
            [ 2047.795467] enp12s0: mtu greater than device maximum

    Signed-off-by: Stephen Hemminger <stephen@networkplumber.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>