[net] xfrm: kconfig: make xfrm depend on inet
Message-id: <de0e9a506b83dedb6f57a963d0a9fbfda87b0633.1588230322.git.lxin@redhat.com>
Patchwork-id: 305935
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net PATCH 12/21] xfrm: kconfig: make xfrm depend on inet
Bugzilla: 1815980 1761579
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Sabrina Dubroca <sdubroca@redhat.com>

Brew Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28250034
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1761579
          https://bugzilla.redhat.com/show_bug.cgi?id=1815980
Upstream Status: ipsec.git commit e54d152
Tested: CKI and bug reproducer

commit e54d1527658f2226c1f63d6fb76fa9b97d1c3947
Author: Florian Westphal <fw@strlen.de>
Date:   Fri Apr 12 10:14:46 2019 +0200

    xfrm: kconfig: make xfrm depend on inet

    when CONFIG_INET is not enabled:
    net/xfrm/xfrm_output.c: In function ‘xfrm4_tunnel_encap_add’:
    net/xfrm/xfrm_output.c:234:2: error: implicit declaration of function ‘ip_select_ident’ [-Werror=implicit-function-declaration]
    ip_select_ident(dev_net(dst->dev), skb, NULL);

    XFRM only supports ipv4 and ipv6 so change dependency to INET and place
    user-visible options (pfkey sockets, migrate support and the like)
    under 'if INET' guard as well.

    Fixes: 1de70830066b7 ("xfrm: remove output2 indirection from xfrm_mode")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>