[sound] ALSA: ASoC: meson: axg-spdifout: select SND_PCM_IEC958
Message-id: <15580872947136052-288-patchset-jkysela@redhat.com>
Patchwork-id: 256867
O-Subject: [RHEL 8.1 PATCH 0287/2119] ALSA: ASoC: meson: axg-spdifout: select SND_PCM_IEC958
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

When CONFIG_SND_PCM_IEC958 is disabled, we get a link error for the
new driver:

sound/soc/meson/axg-spdifout.o: In function `axg_spdifout_hw_params':
axg-spdifout.c:(.text+0x650): undefined reference to `snd_pcm_create_iec958_consumer_hw_params'

The other users use 'select', so we should do the same here.

Fixes: 53eb4b7aaa04 ("ASoC: meson: add axg spdif output")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Jerome Brunet <jbrunet@baylibre.com>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit a241c3d95b8b985834d218eedde3923ed683e862)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>