[tools] perf cs-etm: Add proper header file for symbols
Message-id: <20191104222454.10863-132-mpetlan@redhat.com>
Patchwork-id: 282776
O-Subject: [RHEL8.2 BZ1715508 131/327] perf cs-etm: Add proper header file for symbols
Bugzilla: 1715508
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715508
https://bugzilla.redhat.com/show_bug.cgi?id=1715508

upstream
========
commit 859dcf64389c93a647f230a7cfd206d30bc9d286
Author: Mathieu Poirier <mathieu.poirier@linaro.org>
Date: Fri Feb 8 15:35:43 2019 -0700

description
===========
After 'commit e22c1c751140 ("perf thread: Don't include symbol.h,
symbol_conf.h is enough")'

Compilation of the perf tools is broken when using the functionality
provided by the openCSD library:

[...]

...                       timerfd: [ on  ]
...                  sched_getcpu: [ on  ]
...                           sdt: [ OFF ]
...                         setns: [ on  ]
...                    libopencsd: [ on  ]

[...]

  CC       util/arm-spe.o
  CC       util/arm-spe-pkt-decoder.o
  CC       util/s390-cpumsf.o
  CC       util/cs-etm.o
  CC       util/parse-branch-options.o
util/cs-etm.c: In function cs_etm__mem_access:
util/cs-etm.c:297:24: error: storage size of al isnt known
  struct  addr_location al;

And rightly so since file cs-etm.c doesn't include symbol.h, something
that is rectified in this patch.

Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>