[tools] selftests/powerpc: Fix compile error on tlbie_test due to newer gcc
Message-id: <20191004140740.23304-6-drosario@redhat.com>
Patchwork-id: 276747
O-Subject: [RHEL-8.2 BZ1755707 PATCH 5/5] selftests/powerpc: Fix compile error on tlbie_test due to newer gcc
Bugzilla: 1755707
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

RHBZ#:
------
https://bugzilla.redhat.com/show_bug.cgi?id=1755707

DESCRIPTION:
------------
Newer versions of GCC (>= 9) demand that the size of the string to be
copied must be explicitly smaller than the size of the destination.
Thus, the NULL char has to be taken into account on strncpy.

This will avoid the following compiling error:

  tlbie_test.c: In function 'main':
  tlbie_test.c:639:4: error: 'strncpy' specified bound 100 equals destination size
      strncpy(logdir, optarg, LOGDIR_NAME_SIZE);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Signed-off-by: Desnes A. Nunes do Rosario <desnesn@linux.ibm.com>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20191003211010.9711-1-desnesn@linux.ibm.com

UPSTREAM STATUS:
----------------
commit 3439595d5b85f0af565f5a58e495d885537fb227

https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=3439595d5b85f0af565f5a58e495d885537fb227

Signed-off-by: Phillip Lougher <plougher@redhat.com>