[fs] io_uring: fix 1-bit bitfields to be unsigned
Message-id: <20200604174034.2713-292-jmoyer@redhat.com>
Patchwork-id: 317068
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 291/441] io_uring: fix 1-bit bitfields to be unsigned
Bugzilla: 1784478
RH-Acked-by: Ming Lei <ming.lei@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Randy Dunlap <rdunlap@infradead.org>

BZ: 1784478
Brew: 28979848

commit e1d85334d62386e9503e4a0d5d022e2d8e0011a0
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Wed Feb 5 20:57:10 2020 -0800

    io_uring: fix 1-bit bitfields to be unsigned

    Make bitfields of size 1 bit be unsigned (since there is no room
    for the sign bit).
    This clears up the sparse warnings:

      CHECK   ../fs/io_uring.c
    ../fs/io_uring.c:207:50: error: dubious one-bit signed bitfield
    ../fs/io_uring.c:208:55: error: dubious one-bit signed bitfield
    ../fs/io_uring.c:209:63: error: dubious one-bit signed bitfield
    ../fs/io_uring.c:210:54: error: dubious one-bit signed bitfield
    ../fs/io_uring.c:211:57: error: dubious one-bit signed bitfield

    Found by sight and then verified with sparse.

    Fixes: 69b3e546139a ("io_uring: change io_ring_ctx bool fields into bit fields")
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Jens Axboe <axboe@kernel.dk>
    Cc: io-uring@vger.kernel.org
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Jeff Moyer <jmoyer@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>