[netdrv] qed: Fix build error without CONFIG_DEVLINK
Message-id: <1572549557-5438-1-git-send-email-mchopra@redhat.com>
Patchwork-id: 282157
O-Subject: [RHEL8.2 PATCH 40/39] qed: Fix build error without CONFIG_DEVLINK
Bugzilla: 1720392
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>

From: YueHaibing <yuehaibing@huawei.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1720392
Upstream: linux.git

commit bd8d7d9088289ba099721e7c696d988842b6cc24
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Sat Jun 1 16:06:05 2019 +0800

    qed: Fix build error without CONFIG_DEVLINK

    Fix gcc build error while CONFIG_DEVLINK is not set

    drivers/net/ethernet/qlogic/qed/qed_main.o: In function `qed_remove':
    qed_main.c:(.text+0x1eb4): undefined reference to `devlink_unregister'

    Select DEVLINK to fix this.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: 24e04879abdd ("qed: Add qed devlink parameters table")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Acked-by: Michal Kalderon <michal.kalderon@marvell.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Backport note:
==============

This patch was supposed to be part of previous series "[RHEL8.2 PATCH 00/39]
qed*: Drivers updates" sent but got missed. Sending it as patch [40/39]
instead of respinning the series.

Signed-off-by: Manish Chopra <mchopra@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>