[powerpc] powerpc/spinlocks: Include correct header for static key
Message-id: <20200106160551.GB4312@pauld.bos.csb>
Patchwork-id: 292224
Patchwork-instance: patchwork
O-Subject: Re: [RHEL8.2 3/2] powerpc/spinlocks: Include correct header for static key
Bugzilla: 1767529
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Christoph von Recklinghausen <crecklin@redhat.com>
RH-Acked-by: Waiman Long <longman@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1767529
Upstream Status: https://github.com/linuxppc/linux/commits/fixes
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=25360452
Tested: Sanity tests with Kt1 and ltp/stress. This fixes a build error for non RH
configs so there is no real code change.

commit 6da3eced8c5f3b03340b0c395bacd552c4d52411
Author: Jason A. Donenfeld <Jason@zx2c4.com>
Date:   Mon Dec 23 14:31:47 2019 +0100

    Recently, the spinlock implementation grew a static key optimization,
    but the jump_label.h header include was left out, leading to build
    errors:

      linux/arch/powerpc/include/asm/spinlock.h:44:7: error: implicit declaration of function 'static_branch_unlikely'
       44 |  if (!static_branch_unlikely(&shared_processor))

    This commit adds the missing header.

    mpe: The build break is only seen with CONFIG_JUMP_LABEL=n.

    Fixes: 656c21d6af5d ("powerpc/shared: Use static key to detect shared processor")
    Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>
    Reviewed-by: Srikar Dronamraju <srikar@linux.ibm.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20191223133147.129983-1-Jason@zx2c4.com

Signed-off-by: Phil Auld <pauld@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>