[tools] perf pmu: Suppress potential format-truncation warning
Message-id: <245067b6ea59a0404a633a11903ca1768fb6eada.1560250175.git.mpetlan@redhat.com>
Patchwork-id: 264937
O-Subject: [RHEL8.1 BZ1715507 032/234] perf pmu: Suppress potential format-truncation warning
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit 11a64a05dc649815670b1be9fe63d205cb076401
Author: Ben Hutchings <ben@decadent.org.uk>
Date: Sun Nov 11 18:45:24 2018 +0000

description
===========
Depending on which functions are inlined in util/pmu.c, the snprintf()
calls in perf_pmu__parse_{scale,unit,per_pkg,snapshot}() might trigger a
warning:

  util/pmu.c: In function 'pmu_aliases':
  util/pmu.c:178:31: error: '%s' directive output may be truncated writing up to 255 bytes into a region of size between 0 and 4095 [-Werror=format-truncation=]
    snprintf(path, PATH_MAX, "%s/%s.unit", dir, name);
                               ^~

I found this when trying to build perf from Linux 3.16 with gcc 8.
However I can reproduce the problem in mainline if I force
__perf_pmu__new_alias() to be inlined.

Suppress this by using scnprintf() as has been done elsewhere in perf.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>