[fs] ext4: use BUG() instead of BUG_ON(1)
Message-id: <20190517091449.6738-87-lczerner@redhat.com>
Patchwork-id: 256608
O-Subject: [RHEL8.1 fs PATCH 86/89] ext4: use BUG() instead of BUG_ON(1)
Bugzilla: 1698815
RH-Acked-by: Eric Sandeen <esandeen@redhat.com>
RH-Acked-by: Bill O'Donnell <billodo@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ 1698815
https://bugzilla.redhat.com/show_bug.cgi?id=1698815

BREW 21698455
https://brewweb.devel.redhat.com/taskinfo?taskID=21698455

commit 1e83bc8156028a938845a869a3317c3cab9630ac

BUG_ON(1) leads to bogus warnings from clang when
CONFIG_PROFILE_ANNOTATED_BRANCHES is set:

 fs/ext4/inode.c:544:4: error: variable 'retval' is used uninitialized whenever 'if' condition is false
      [-Werror,-Wsometimes-uninitialized]
                        BUG_ON(1);
                        ^~~~~~~~~
 include/asm-generic/bug.h:61:36: note: expanded from macro 'BUG_ON'
                                   ^~~~~~~~~~~~~~~~~~~
 include/linux/compiler.h:48:23: note: expanded from macro 'unlikely'
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 fs/ext4/inode.c:591:6: note: uninitialized use occurs here
        if (retval > 0 && map->m_flags & EXT4_MAP_MAPPED) {
            ^~~~~~
 fs/ext4/inode.c:544:4: note: remove the 'if' if its condition is always true
                        BUG_ON(1);
                        ^
 include/asm-generic/bug.h:61:32: note: expanded from macro 'BUG_ON'
                               ^
 fs/ext4/inode.c:502:12: note: initialize the variable 'retval' to silence this warning

Change it to BUG() so clang can see that this code path can never
continue.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Theodore Ts'o <tytso@mit.edu>
Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
Reviewed-by: Jan Kara <jack@suse.cz>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>