bpf: Avoid old-style declaration warnings
Bugzilla: http://bugzilla.redhat.com/1874007

commit e2c69f3a5b4edfbcade2c38862c1839fc371c5d5
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 22 22:51:51 2021 +0100

    bpf: Avoid old-style declaration warnings

    gcc -Wextra wants type modifiers in the normal order:

    kernel/bpf/bpf_lsm.c:70:1: error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]
       70 | const static struct bpf_func_proto bpf_bprm_opts_set_proto = {
          | ^~~~~
    kernel/bpf/bpf_lsm.c:91:1: error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]
       91 | const static struct bpf_func_proto bpf_ima_inode_hash_proto = {
          | ^~~~~

    Fixes: 3f6719c7b62f ("bpf: Add bpf_bprm_opts_set helper")
    Fixes: 27672f0d280a ("bpf: Add a BPF helper for getting the IMA hash of an inode")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: KP Singh <kpsingh@kernel.org>
    Link: https://lore.kernel.org/bpf/20210322215201.1097281-1-arnd@kernel.org

Signed-off-by: Jiri Olsa <jolsa@redhat.com>