[sound] ALSA: ASoC: rockchip: pdm: select CONFIG_RATIONAL
Message-id: <15693081207948942-1117-patchset-jkysela@redhat.com>
Patchwork-id: 274261
O-Subject: [RHEL 8.2 PATCH 1116/1298] ALSA: ASoC: rockchip: pdm: select CONFIG_RATIONAL
Bugzilla: 1738610
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Without this, we get a link error:

sound/soc/rockchip/rockchip_pdm.o: In function `rockchip_pdm_hw_params':
rockchip_pdm.c:(.text+0x754): undefined reference to `rational_best_approximation'

Fixes: 624e8e00acaf ("ASoC: rockchip: pdm: fixup pdm fractional div")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 41d92e0c835bff7dec343bf41e79d24b326d94c1)
Bugzilla: 1738610
Signed-off-by: Phillip Lougher <plougher@redhat.com>