[tools] perf tests bp_account: Make global variable static
Message-id: <20200522095131.24335-80-mpetlan@redhat.com>
Patchwork-id: 313694
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 79/98] perf tests bp_account: Make global variable static
Bugzilla: 1818841
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1818841
https://bugzilla.redhat.com/show_bug.cgi?id=1818841

upstream
========
commit cff20b3151ccab690715cb6cf0f5da5cccb32adf
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Mon Mar 2 11:13:19 2020 -0300

description
===========
To fix the build with newer gccs, that without this patch exit with:

    LD       /tmp/build/perf/tests/perf-in.o
  ld: /tmp/build/perf/tests/bp_account.o:/git/perf/tools/perf/tests/bp_account.c:22: multiple definition of `the_var'; /tmp/build/perf/tests/bp_signal.o:/git/perf/tools/perf/tests/bp_signal.c:38: first defined here
  make[4]: *** [/git/perf/tools/build/Makefile.build:145: /tmp/build/perf/tests/perf-in.o] Error 1

First noticed in fedora:rawhide/32 with:

  [perfbuilder@a5ff49d6e6e4 ~]$ gcc --version
  gcc (GCC) 10.0.1 20200216 (Red Hat 10.0.1-0.8)

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>