[tools] perf tools: Increase MAX_NR_CPUS and MAX_CACHES
Message-id: <20190925175839.23722-2-framsay@redhat.com>
Patchwork-id: 275113
O-Subject: [RHEL 8.2 PATCH 1/8] perf tools: Increase MAX_NR_CPUS and MAX_CACHES
Bugzilla: 1753332
RH-Acked-by: Arnaldo Carvalho de Melo <acme@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1753332
Upstream Status: 9f94c7f947e919c343b30f080285af53d0fa9902
Brew Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=23561112
Tested: Pass, details in BZ

commit 9f94c7f947e919c343b30f080285af53d0fa9902
Author: Kyle Meyer <kyle.meyer@hpe.com>
Date: Thu, 20 Jun 2019 14:36:30 -0500

Attempting to profile 1024 or more CPUs with perf causes two errors:

  perf record -a
  [ perf record: Woken up X times to write data ]
  way too many cpu caches..
  [ perf record: Captured and wrote X MB perf.data (X samples) ]

  perf report -C 1024
  Error: failed to set  cpu bitmap
  Requested CPU 1024 too large. Consider raising MAX_NR_CPUS

  Increasing MAX_NR_CPUS from 1024 to 2048 and redefining MAX_CACHES as
  MAX_NR_CPUS * 4 returns normal functionality to perf:

  perf record -a
  [ perf record: Woken up X times to write data ]
  [ perf record: Captured and wrote X MB perf.data (X samples) ]

  perf report -C 1024
  ...

	Signed-off-by: Kyle Meyer <kyle.meyer@hpe.com>
	Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
	Cc: Jiri Olsa <jolsa@redhat.com>
	Cc: Namhyung Kim <namhyung@kernel.org>
	Cc: Peter Zijlstra <peterz@infradead.org>
	Link: http://lkml.kernel.org/r/20190620193630.154025-1-meyerk@stormcage.eag.rdlabs.hpecorp.net
	Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Phillip Lougher <plougher@redhat.com>