kunit: Fix kunit.py parse subcommand (use null build_dir)
commit 3959d0a63b3202ea2aa12b3f6effd5400d773d31
Author: David Gow <davidgow@google.com>
Date:   Wed Oct 21 00:16:03 2020 -0700

    kunit: Fix kunit.py parse subcommand (use null build_dir)

    When JSON support was added in [1], the KunitParseRequest tuple was
    updated to contain a 'build_dir' field, but kunit.py parse doesn't
    accept --build_dir as an option. The code nevertheless tried to access
    it, resulting in this error:

    AttributeError: 'Namespace' object has no attribute 'build_dir'

    Given that the parser only uses the build_dir variable to set the
    'build_environment' json field, we set it to None (which gives the JSON
    'null') for now. Ultimately, we probably do want to be able to set this,
    but since it's new functionality which (for the parse subcommand) never
    worked, this is the quickest way of getting it back up and running.

    [1]: https://git.kernel.org/pub/scm/linux/kernel/git/shuah/linux-kselftest.git/commit/?h=kunit-fixes&id=21a6d1780d5bbfca0ce9b8104ca6233502fcbf86

    Fixes: 21a6d1780d5b ("kunit: tool: allow generating test results in JSON")
    Signed-off-by: David Gow <davidgow@google.com>
    Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
    Tested-by: Brendan Higgins <brendanhiggins@google.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1939309
Signed-off-by: Nico Pache <npache@redhat.com>