[sound] ALSA: ASoC: SOF: Fix randbuild error
Message-id: <15728751819462729-113-patchset-jkysela@redhat.com>
Patchwork-id: 282551
O-Subject: [RHEL 8.2 PATCH 112/167] ALSA: ASoC: SOF: Fix randbuild error
Bugzilla: 1710702
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

When LEDS_TRIGGER_AUDIO is m and SND_SOC_SOF is y,

sound/soc/sof/control.o: In function `snd_sof_switch_put':
control.c:(.text+0x587): undefined reference to `ledtrig_audio_set'
control.c:(.text+0x593): undefined reference to `ledtrig_audio_set'

Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: 5d43001ae436 ("ASoC: SOF: acpi led support for switch controls")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Acked-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Link: https://lore.kernel.org/r/20191014091308.23688-1-yuehaibing@huawei.com
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 9899a7a869935c4c93247b290ac7a70e0deab202)
Bugzilla: 1710702
Signed-off-by: Phillip Lougher <plougher@redhat.com>