[net] ethtool: potential NULL dereference in strset_prepare_data()
Message-id: <20200915170040.2948050-37-ivecera@redhat.com>
Patchwork-id: 326453
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 net PATCH 36/97] ethtool: potential NULL dereference in strset_prepare_data()
Bugzilla: 1878274
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1878274

Upstream commit(s):
commit ac9c41d5a053e71777e8c2191681358499eff04b
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Wed Jan 8 08:42:36 2020 +0300

    ethtool: potential NULL dereference in strset_prepare_data()

    Smatch complains that the NULL checking isn't done consistently:

        net/ethtool/strset.c:253 strset_prepare_data()
        error: we previously assumed 'dev' could be null (see line 233)

    It looks like there is a missing return on this path.

    Fixes: 71921690f974 ("ethtool: provide string sets with STRSET_GET request")
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Reviewed-by: Michal Kubecek <mkubecek@suse.cz>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>