[s390] s390/purgatory: Remove duplicate variable definitions
Message-id: <20181025082656.9417-5-prudo@redhat.com>
Patchwork-id: 231830
O-Subject: [RHEL8.0 PATCH 4/4] [s390] s390/purgatory: Remove duplicate variable definitions
Bugzilla: 1642447
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Baoquan He <bhe@redhat.com>
RH-Acked-by: Dave Young <dyoung@redhat.com>

Bugzilla: 1642447
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=18908425
Tested: by IBM

commit 287d6070acbb2529e24462faffca46663885dddc
Author: Philipp Rudo <prudo@linux.ibm.com>
Date:   Wed Jun 27 12:03:43 2018 +0200

    s390/purgatory: Remove duplicate variable definitions

    Currently there are some variables in the purgatory (e.g. kernel_entry)
    which are defined twice, once in assembler- and once in c-code. The reason
    for this is that these variables are set during purgatory load, where
    sanity checks on the corresponding Elf_Sym's are made, while they are used
    in assembler-code. Thus adding a second definition in c-code is a handy
    workaround to guarantee correct Elf_Sym's are created.

    When the purgatory is compiled with -fcommon (default for gcc on s390) this
    is no problem because both symbols are merged by the linker. However this
    is not required by ISO C and when the purgatory is built with -fno-common
    the linker fails with errors like

    arch/s390/purgatory/purgatory.o:(.bss+0x18): multiple definition of `kernel_entry'
    arch/s390/purgatory/head.o:/.../arch/s390/purgatory/head.S:230: first defined here

    Thus remove the duplicate definitions and add the required size and type
    information to the assembler definition. Also add -fno-common to the
    command line options to prevent similar hacks in the future.

    Signed-off-by: Philipp Rudo <prudo@linux.ibm.com>
    Acked-by: Heiko Carstens <heiko.carstens@de.ibm.com>
    Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>

Signed-off-by: Philipp Rudo <prudo@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>