[tools] perf metric: Add metric group test
Message-id: <20201214095352.11924-139-mpetlan@redhat.com>
Patchwork-id: 344353
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 138/248] perf metric: Add metric group test
Bugzilla: 1811839 1731571 1838555 1838896 1873271
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1873271
https://bugzilla.redhat.com/show_bug.cgi?id=1873271

upstream
========
commit dfce77c580e02c19efacfe9110261c935d1ddb60
Author: Jiri Olsa <jolsa@kernel.org>
Date: Sun Jul 19 20:13:18 2020 +0200

description
===========
Adding test for metric group plus compute_metric_group function to get
metrics values within the group.

Committer notes:

Fixed this;

  tests/parse-metric.c:327:7: error: missing field 'val' initializer [-Werror,-Wmissing-field-initializers]
                  { 0 },
                      ^

Signed-off-by: Michael Petlan <mpetlan@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>