[netdrv] mlxsw: spectrum_qdisc: Fix 64-bit division error in mlxsw_sp_qdisc_tbf_rate_kbps
Message-id: <20200601180237.4179948-140-ivecera@redhat.com>
Patchwork-id: 315911
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 PATCH 139/290] mlxsw: spectrum_qdisc: Fix 64-bit division error in mlxsw_sp_qdisc_tbf_rate_kbps
Bugzilla: 1821646
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1821646

Upstream commit(s):
commit 91a7d4bf3ee3794d4090cedd17b8e865645f5f79
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Thu Jan 30 18:51:23 2020 -0700

    mlxsw: spectrum_qdisc: Fix 64-bit division error in mlxsw_sp_qdisc_tbf_rate_kbps

    When building arm32 allmodconfig:

    ERROR: "__aeabi_uldivmod"
    [drivers/net/ethernet/mellanox/mlxsw/mlxsw_spectrum.ko] undefined!

    rate_bytes_ps has type u64, we need to use a 64-bit division helper to
    avoid a build error.

    Fixes: a44f58c41bfb ("mlxsw: spectrum_qdisc: Support offloading of TBF Qdisc")
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Reviewed-by: Ido Schimmel <idosch@mellanox.com>
    Tested-by: Ido Schimmel <idosch@mellanox.com>
    Acked-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>