[i2c] i2c: nvidia-gpu: mark resume function as __maybe_unused
Message-id: <20201216155447.212357-134-torez@redhat.com>
Patchwork-id: 345314
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 1900751 0133/1059] i2c: nvidia-gpu: mark resume function as __maybe_unused
Bugzilla: 1900751 1856683 1838295 1837563 1783493
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1900751
Bugzilla: https://bugzilla.redhat.com/1837563
Bugzilla: https://bugzilla.redhat.com/1856683
Bugzilla: https://bugzilla.redhat.com/1853229
Bugzilla: https://bugzilla.redhat.com/1838295
Bugzilla: https://bugzilla.redhat.com/1836895
Bugzilla: https://bugzilla.redhat.com/1798825
Bugzilla: https://bugzilla.redhat.com/1789257
Bugzilla: https://bugzilla.redhat.com/1783493

Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33777895
Upstream Status: 32774a8153b4c62e408297fba352248afb2e0143

Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit 32774a8153b4c62e408297fba352248afb2e0143
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Dec 10 21:53:45 2018 +0100

i2c: nvidia-gpu: mark resume function as __maybe_unused

When CONFIG_PM is disabled, this is needed to avoid a harmless
unused-function warning:

drivers/i2c/busses/i2c-nvidia-gpu.c:345:12: error: 'gpu_i2c_resume' defined but not used [-Werror=unused-function]

Fixes: c71bcdcb42a7 ("i2c: add i2c bus driver for NVIDIA GPU")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
Signed-off-by: Wolfram Sang <wsa@the-dreams.de>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>