[netdrv] sfc: avoid an unused-variable warning
Message-id: <20201021000816.2891-13-jarod@redhat.com>
Patchwork-id: 333631
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 012/101] sfc: avoid an unused-variable warning
Bugzilla: 1856681
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1856681

commit b113cabd4378ddd98dccdd7748a16f9f1f094ef0
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 27 15:41:06 2020 +0200

    sfc: avoid an unused-variable warning

    'nic_data' is no longer used outside of the #ifdef block
    in efx_ef10_set_mac_address:

    drivers/net/ethernet/sfc/ef10.c:3231:28: error: unused variable 'nic_data' [-Werror,-Wunused-variable]
            struct efx_ef10_nic_data *nic_data = efx->nic_data;

    Move the variable into a local scope.

    Fixes: dfcabb078847 ("sfc: move vport_id to struct efx_nic")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>