net: psample: fix build error when CONFIG_INET is not enabled
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1955163

commit 07a7f30819475a6f058df6bba5150c50e7942cfb
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Fri May 22 13:05:26 2020 -0700

    net: psample: fix build error when CONFIG_INET is not enabled

    Fix psample build error when CONFIG_INET is not set/enabled by
    bracketing the tunnel code in #ifdef CONFIG_NET / #endif.

    ../net/psample/psample.c: In function ‘__psample_ip_tun_to_nlattr’:
    ../net/psample/psample.c:216:25: error: implicit declaration of function ‘ip_tunnel_info_opts’; did you mean ‘ip_tunnel_info_opts_set’? [-Werror=implicit-function-declaration]

    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc: Yotam Gigi <yotam.gi@gmail.com>
    Cc: Cong Wang <xiyou.wangcong@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>