[usb] Revert "usb: mtu3: fix up undefined reference to usb_debug_root"
Message-id: <20200407161320.17414-840-torez@redhat.com>
Patchwork-id: 300577
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 839/983] Revert "usb: mtu3: fix up undefined reference to usb_debug_root"
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit e137d34f94ebcb6508d7c8614ac045583fffbe2a
Author: Chunfeng Yun <chunfeng.yun@mediatek.com>
Date:   Mon Jun 10 10:52:29 2019 +0800

    Revert "usb: mtu3: fix up undefined reference to usb_debug_root"

    It's not needed after [1] is applied, because usb_debug_root is created
    by usb common core but not usbcore now.

    [1] 812086d362a1 ("USB: move usb debugfs directory creation to the usb common core")

    Signed-off-by: Chunfeng Yun <chunfeng.yun@mediatek.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>