[netdrv] net/mlx5: reduce stack usage in qp_read_field
Message-id: <20201202091426.24995-167-ahleihel@redhat.com>
Patchwork-id: 342767
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1858560 v2 166/199] net/mlx5: reduce stack usage in qp_read_field
Bugzilla: 1858560
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1858560
Upstream: v5.8-rc1

commit e1167e16114f78f948078749aa1608a785f65807
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Apr 28 23:23:47 2020 +0200

    net/mlx5: reduce stack usage in qp_read_field

    Moving the mlx5_ifc_query_qp_out_bits structure on the stack was a bit
    excessive and now causes the compiler to complain on 32-bit architectures:

    drivers/net/ethernet/mellanox/mlx5/core/debugfs.c: In function 'qp_read_field':
    drivers/net/ethernet/mellanox/mlx5/core/debugfs.c:274:1: error: the frame size of 1104 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

    Revert the previous patch partially to use dynamically allocation as
    the code did before. Unfortunately there is no good error handling
    in case the allocation fails.

    Fixes: 57a6c5e992f5 ("net/mlx5: Replace hand written QP context struct with automatic getters")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Saeed Mahameed <saeedm@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>