[powerpc] powerpc/64s/radix: Fix build failure with RADIX_MMU=n
Message-id: <20201105170229.2023.21528.sendpatchset@sbest.bos.csb>
Patchwork-id: 337605
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 BZ1894922 1/3] powerpc/64s/radix: Fix build failure with RADIX_MMU=n
Bugzilla: 1894922
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1894922
Upstream:
commit 18217da36103c25d87870624dfa569e6b9906a90

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=18217da36103c25d87870624dfa569e6b9906a90

Depends: 1854543

Description:
After merging the powerpc tree, today's linux-next build (powerpc64
allnoconfig) failed like this:

 arch/powerpc/mm/book3s64/pgtable.c:216:3:
 error: implicit declaration of function 'radix__flush_all_lpid_guest'

radix__flush_all_lpid_guest() is only declared for
CONFIG_PPC_RADIX_MMU which is not set for this build.

Fix it by adding an empty version for the RADIX_MMU=n case, which
should never be called.

Fixes: 99161de3a283 ("powerpc/64s/radix: tidy up TLB flushing code")
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
[mpe: Munge change log]
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20190930101342.36c1afa0@canb.auug.org.au

Signed-off-by: Steve Best <sbest@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>