[tools] perf python: Include rwsem.c in the pythong biding
Message-id: <20200605130702.31420-90-mpetlan@redhat.com>
Patchwork-id: 317471
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 089/112] perf python: Include rwsem.c in the pythong biding
Bugzilla: 1841130
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1841130
https://bugzilla.redhat.com/show_bug.cgi?id=1841130

upstream
========
commit 460c3ed999d700fa84c953f83141f580ef456b3c
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Fri Apr 3 09:29:52 2020 -0300

description
===========
We'll need it for the cgroup patches, and its better to have it in a
separate patch in case we need to later revert the cgroup patches.

I.e. without this we have:

  [root@five ~]# perf test -v python
  19: 'import perf' in python                               :
  --- start ---
  test child forked, pid 148447
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ImportError: /tmp/build/perf/python/perf.cpython-37m-x86_64-linux-gnu.so: undefined symbol: down_write
  test child finished with -1
  ---- end ----
  'import perf' in python: FAILED!
  [root@five ~]#

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>