[wireless] ath11k: fix compiler warnings without CONFIG_THERMAL
Message-id: <20201023173140.4030081-359-jarod@redhat.com>
Patchwork-id: 334588
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 PATCH 0358/1137] ath11k: fix compiler warnings without CONFIG_THERMAL
Bugzilla: 1860496
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1860496

commit c9be1a642a7b9ec021e3f32e084dc781b3e5216d
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Fri Apr 3 16:34:14 2020 +0800

    ath11k: fix compiler warnings without CONFIG_THERMAL

    drivers/net/wireless/ath/ath11k/thermal.h:45:1:
     warning: no return statement in function returning non-void [-Wreturn-type]
    drivers/net/wireless/ath/ath11k/core.c:416:28: error:
     passing argument 1 of 'ath11k_thermal_unregister' from incompatible pointer type [-Werror=incompatible-pointer-types]

    Add missing return 0 in ath11k_thermal_set_throttling,
    and fix ath11k_thermal_unregister param type.

    Fixes: 2a63bbca06b2 ("ath11k: add thermal cooling device support")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/20200403083414.31392-1-yuehaibing@huawei.com

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>