selftests/bpf: Define string const as global for test_sysctl_prog.c
Bugzilla: http://bugzilla.redhat.com/1874006

commit 6e057fc15a2da4ee03eb1fa6889cf687e690106e
Author: Yonghong Song <yhs@fb.com>
Date:   Thu Sep 10 13:27:18 2020 -0700

    selftests/bpf: Define string const as global for test_sysctl_prog.c

    When tweaking llvm optimizations, I found that selftest build failed
    with the following error:
      libbpf: elf: skipping unrecognized data section(6) .rodata.str1.1
      libbpf: prog 'sysctl_tcp_mem': bad map relo against '.L__const.is_tcp_mem.tcp_mem_name'
              in section '.rodata.str1.1'
      Error: failed to open BPF object file: Relocation failed
      make: *** [/work/net-next/tools/testing/selftests/bpf/test_sysctl_prog.skel.h] Error 255
      make: *** Deleting file `/work/net-next/tools/testing/selftests/bpf/test_sysctl_prog.skel.h'

    The local string constant "tcp_mem_name" is put into '.rodata.str1.1' section
    which libbpf cannot handle. Using untweaked upstream llvm, "tcp_mem_name"
    is completely inlined after loop unrolling.

    Commit 7fb5eefd7639 ("selftests/bpf: Fix test_sysctl_loop{1, 2}
    failure due to clang change") solved a similar problem by defining
    the string const as a global. Let us do the same here
    for test_sysctl_prog.c so it can weather future potential llvm changes.

    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Link: https://lore.kernel.org/bpf/20200910202718.956042-1-yhs@fb.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>