[samples] samples/bpf: fix a compilation failure
Message-id: <20190604085256.3304-125-yauheni.kaliuta@redhat.com>
Patchwork-id: 262123
O-Subject: [RHEL8.1 PATCH v2 125/627] samples/bpf: fix a compilation failure
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit 534e0e52bc23de588e81b5a6f75e10c8c4b189fc
Author: Yonghong Song <yhs@fb.com>
Date:   Mon Sep 17 22:08:13 2018 -0700

    samples/bpf: fix a compilation failure

    samples/bpf build failed with the following errors:

      $ make samples/bpf/
      ...
      HOSTCC  samples/bpf/sockex3_user.o
      /data/users/yhs/work/net-next/samples/bpf/sockex3_user.c:16:8: error: redefinition of ‘struct bpf_flow_keys’
       struct bpf_flow_keys {
              ^
      In file included from /data/users/yhs/work/net-next/samples/bpf/sockex3_user.c:4:0:
      ./usr/include/linux/bpf.h:2338:9: note: originally defined here
        struct bpf_flow_keys *flow_keys;
               ^
      make[3]: *** [samples/bpf/sockex3_user.o] Error 1

    Commit d58e468b1112d ("flow_dissector: implements flow dissector BPF hook")
    introduced struct bpf_flow_keys in include/uapi/linux/bpf.h and hence
    caused the naming conflict with samples/bpf/sockex3_user.c.

    The fix is to rename struct bpf_flow_keys in samples/bpf/sockex3_user.c
    to flow_keys to avoid the conflict.

    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>