[tools] tools: PCI: Fix compiler warning in pcitest
Message-id: <20190925153813.30733.56772.stgit@tak.stowe>
Patchwork-id: 274838
O-Subject: [RHEL8.2 PATCH 51/51] tools: PCI: Fix compiler warning in pcitest
Bugzilla: 1753749
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1753749
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=23690407
Upstream Status: 81cb4203a5fec7d3f8cf4f145e8e7077b2dcbc78

commit 81cb4203a5fec7d3f8cf4f145e8e7077b2dcbc78
Author: Alan Mikhak <alan.mikhak@sifive.com>
Date:   Thu May 23 14:18:01 2019 -0700

    tools: PCI: Fix compiler warning in pcitest

    Fix the following compiler warning in pcitest:

    pcitest.c: In function main:
    pcitest.c:214:4: warning: too many arguments for
    format [-Wformat-extra-args]
        "usage: %s [options]\n"

    Fixes: fbca0b284bd0 ("tools: PCI: Add 'h' in optstring of getopt()")
    Signed-off-by: Alan Mikhak <alan.mikhak@sifive.com>
    Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
    Reviewed-by: Paul Walmsley <paul.walmsley@sifive.com>

Signed-off-by: Phillip Lougher <plougher@redhat.com>