[usb] usb: dwc3: of-simple: avoid unused function warnings
Message-id: <20200407161320.17414-80-torez@redhat.com>
Patchwork-id: 299813
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 079/983] usb: dwc3: of-simple: avoid unused function warnings
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit 66174b6998a645c39867c3a301b4ee4611d6ca5b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Aug 13 23:56:55 2018 +0200

    usb: dwc3: of-simple: avoid unused function warnings

    An incorrect #ifdef caused a pair of harmless warnings when CONFIG_PM_SLEEP
    is disabled:

    drivers/usb/dwc3/dwc3-of-simple.c:223:12: error: 'dwc3_of_simple_resume' defined but not used [-Werror=unused-function]
     static int dwc3_of_simple_resume(struct device *dev)
                ^~~~~~~~~~~~~~~~~~~~~
    drivers/usb/dwc3/dwc3-of-simple.c:213:12: error: 'dwc3_of_simple_suspend' defined but not used [-Werror=unused-function]
     static int dwc3_of_simple_suspend(struct device *dev)

    Since the #ifdef method is generally hard to get right, use
    a simpler __maybe_unused annotation here to let the compiler
    drop the unused functions silently. This also improves
    compile-time coverage.

    Fixes: 76251db86561 ("usb: dwc3: of-simple: reset host controller at suspend/resume")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Felipe Balbi <felipe.balbi@linux.intel.com>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>