[mm] x86/mm: Rename is_kernel_text to __is_kernel_text
Message-id: <20200610045258.353158-103-yauheni.kaliuta@redhat.com>
Patchwork-id: 319417
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 103/235] x86/mm: Rename is_kernel_text to __is_kernel_text
Bugzilla: 1845114
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1845114

commit b56cd05c55a10afd479a1877d7f6a50d92d8536e
Author: Jiri Olsa <jolsa@kernel.org>
Date:   Thu Mar 12 20:55:56 2020 +0100

    x86/mm: Rename is_kernel_text to __is_kernel_text

    The kbuild test robot reported compile issue on x86 in one of
    the following patches that adds <linux/kallsyms.h> include into
    <linux/bpf.h>, which is picked up by init_32.c object.

    The problem is that <linux/kallsyms.h> defines global function
    is_kernel_text which colides with the static function of the
    same name defined in init_32.c:

      $ make ARCH=i386
      ...
      >> arch/x86/mm/init_32.c:241:19: error: redefinition of 'is_kernel_text'
        static inline int is_kernel_text(unsigned long addr)
                          ^~~~~~~~~~~~~~
       In file included from include/linux/bpf.h:21:0,
                        from include/linux/bpf-cgroup.h:5,
                        from include/linux/cgroup-defs.h:22,
                        from include/linux/cgroup.h:28,
                        from include/linux/hugetlb.h:9,
                        from arch/x86/mm/init_32.c:18:
       include/linux/kallsyms.h:31:19: note: previous definition of 'is_kernel_text' was here
        static inline int is_kernel_text(unsigned long addr)

    Renaming the init_32.c is_kernel_text function to __is_kernel_text.

    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Jiri Olsa <jolsa@kernel.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Song Liu <songliubraving@fb.com>
    Link: https://lore.kernel.org/bpf/20200312195610.346362-2-jolsa@kernel.org
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>