[usb] usb: host: Fix excessive alignment restriction for local memory allocations
Message-id: <20200407161320.17414-906-torez@redhat.com>
Patchwork-id: 300640
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 905/983] usb: host: Fix excessive alignment restriction for local memory allocations
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit ff2437befd8fe52046e0db949347b5bcfab6b097
Author: Fredrik Noring <noring@nocrew.org>
Date:   Tue Jun 25 17:08:23 2019 +0200

    usb: host: Fix excessive alignment restriction for local memory allocations

    The PAGE_SHIFT alignment restriction to devm_gen_pool_create() quickly
    exhaust local memory because most allocations are much smaller than
    PAGE_SIZE. This causes USB device failures such as

            usb 1-2.1: reset full-speed USB device number 4 using sm501-usb
            sd 1:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x03 driverbyte=0x00
            sd 1:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 00 00 08 7c 00 00 f0 00
            print_req_error: I/O error, dev sda, sector 2172 flags 80700

    when trying to boot from the SM501 USB controller on SH4 with QEMU.

    Align allocations as required but not necessarily much more than that.
    The HCCA, TD and ED structures align with 256, 32 and 16 byte memory
    boundaries, as specified by the Open HCI[1]. The min_alloc_order argument
    to devm_gen_pool_create is now somewhat arbitrarily set to 4 (16 bytes).
    Perhaps it could be somewhat lower for general buffer allocations.

    Reference:

    [1] "Open Host Controller Interface Specification for USB",
        release 1.0a, Compaq, Microsoft, National Semiconductor, 1999,
        pp. 16, 19, 33.

    Reported-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Fredrik Noring <noring@nocrew.org>
    Tested-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Christoph Hellwig <hch@lst.de>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>