[wireless] mt76: mt7915: Fix build error
Message-id: <20201023173140.4030081-761-jarod@redhat.com>
Patchwork-id: 334703
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 PATCH 0760/1137] mt76: mt7915: Fix build error
Bugzilla: 1860496
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1860496

commit 472f0a240250df443ffc4f39835e829916193ca1
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Fri May 22 11:45:33 2020 +0800

    mt76: mt7915: Fix build error

    In file included from ./include/linux/firmware.h:6:0,
                     from drivers/net/wireless/mediatek/mt76/mt7915/mcu.c:4:
    In function ‘__mt7915_mcu_msg_send’,
        inlined from ‘mt7915_mcu_send_message’ at drivers/net/wireless/mediatek/mt76/mt7915/mcu.c:370:6:
    ./include/linux/compiler.h:396:38: error: call to ‘__compiletime_assert_545’ declared with attribute error: BUILD_BUG_ON failed: cmd == MCU_EXT_CMD_EFUSE_ACCESS && mcu_txd->set_query != MCU_Q_QUERY
      _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
                                          ^
    ./include/linux/compiler.h:377:4: note: in definition of macro ‘__compiletime_assert’
        prefix ## suffix();    \
        ^~~~~~
    ./include/linux/compiler.h:396:2: note: in expansion of macro ‘_compiletime_assert’
      _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      ^~~~~~~~~~~~~~~~~~~
    ./include/linux/build_bug.h:39:37: note: in expansion of macro ‘compiletime_assert’
     #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                         ^~~~~~~~~~~~~~~~~~
    ./include/linux/build_bug.h:50:2: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
      BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
      ^~~~~~~~~~~~~~~~
    drivers/net/wireless/mediatek/mt76/mt7915/mcu.c:280:2: note: in expansion of macro ‘BUILD_BUG_ON’
      BUILD_BUG_ON(cmd == MCU_EXT_CMD_EFUSE_ACCESS &&
      ^~~~~~~~~~~~

    BUILD_BUG_ON is meaningless here, chang it to WARN_ON.

    Fixes: e57b7901469f ("mt76: add mac80211 driver for MT7915 PCIe-based chipsets")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/20200522034533.61716-1-yuehaibing@huawei.com

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>