[net] xfrm: interface: use IS_REACHABLE to avoid some compile errors
Message-id: <935a7423772c8840d05bbf6eaf5a3b121d35de19.1595405604.git.lxin@redhat.com>
Patchwork-id: 322406
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net PATCH 15/16] xfrm: interface: use IS_REACHABLE to avoid some compile errors
Bugzilla: 1840976 1835075
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Brew Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=30221458
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1840976
          https://bugzilla.redhat.com/show_bug.cgi?id=1835075
Upstream Status: ipsec-next.git commit 0a0d93b
Tested: CKI and bug reproducer

commit 0a0d93b943a20e4210491911e82c3b4a34391ce4
Author: Xin Long <lucien.xin@gmail.com>
Date:   Fri Jul 17 15:02:30 2020 +0800

    xfrm: interface: use IS_REACHABLE to avoid some compile errors

    kernel test robot reported some compile errors:

      ia64-linux-ld: net/xfrm/xfrm_interface.o: in function `xfrmi4_fini':
      net/xfrm/xfrm_interface.c:900: undefined reference to `xfrm4_tunnel_deregister'
      ia64-linux-ld: net/xfrm/xfrm_interface.c:901: undefined reference to `xfrm4_tunnel_deregister'
      ia64-linux-ld: net/xfrm/xfrm_interface.o: in function `xfrmi4_init':
      net/xfrm/xfrm_interface.c:873: undefined reference to `xfrm4_tunnel_register'
      ia64-linux-ld: net/xfrm/xfrm_interface.c:876: undefined reference to `xfrm4_tunnel_register'
      ia64-linux-ld: net/xfrm/xfrm_interface.c:885: undefined reference to `xfrm4_tunnel_deregister'

    This happened when set CONFIG_XFRM_INTERFACE=y and CONFIG_INET_TUNNEL=m.
    We don't really want xfrm_interface to depend inet_tunnel completely,
    but only to disable the tunnel code when inet_tunnel is not seen.

    So instead of adding "select INET_TUNNEL" for XFRM_INTERFACE, this patch
    is only to change to IS_REACHABLE to avoid these compile error.

    Reported-by: kernel test robot <lkp@intel.com>
    Fixes: da9bbf0598c9 ("xfrm: interface: support IPIP and IPIP6 tunnels processing with .cb_handler")
    Signed-off-by: Xin Long <lucien.xin@gmail.com>
    Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>