[tools] selftests/bpf: fix compilation error for flow_dissector.c
Message-id: <93f9c8b6a7648300bd18046785dab559fc79ceb6.1573822046.git.jbenc@redhat.com>
Patchwork-id: 287421
O-Subject: [RHEL8.2 net 12/77] selftests/bpf: fix compilation error for flow_dissector.c
Bugzilla: 1749817
RH-Acked-by: Matteo Croce <mcroce@redhat.com>
RH-Acked-by: Eelco Chaudron <echaudro@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1749817

commit fe937ea12ec83da6c6bbbdb54a03062155318d0e
Author: Alan Maguire <alan.maguire@oracle.com>
Date:   Wed May 29 10:48:14 2019 +0100

    selftests/bpf: fix compilation error for flow_dissector.c

    When building the tools/testing/selftest/bpf subdirectory,
    (running both a local directory "make" and a
    "make -C tools/testing/selftests/bpf") I keep hitting the
    following compilation error:

    prog_tests/flow_dissector.c: In function 'create_tap':
    prog_tests/flow_dissector.c:150:38: error: 'IFF_NAPI' undeclared (first
    use in this function)
       .ifr_flags = IFF_TAP | IFF_NO_PI | IFF_NAPI | IFF_NAPI_FRAGS,
                                          ^
    prog_tests/flow_dissector.c:150:38: note: each undeclared identifier is
    reported only once for each function it appears in
    prog_tests/flow_dissector.c:150:49: error: 'IFF_NAPI_FRAGS' undeclared

    Adding include/uapi/linux/if_tun.h to tools/include/uapi/linux
    resolves the problem and ensures the compilation of the file
    does not depend on having up-to-date kernel headers locally.

    Signed-off-by: Alan Maguire <alan.maguire@oracle.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>