[tools] tool: make key optional in lookup command
Message-id: <20190925141552.30691-8-yauheni.kaliuta@redhat.com>
Patchwork-id: 274559
O-Subject: [RHEL8.2 PATCH v2 008/214] bpftool: make key optional in lookup command
Bugzilla: 1747341
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747341

commit 8a89fff60a7ef63a23b112bdfa76d7ba160a4a68
Author: Stanislav Fomichev <sdf@google.com>
Date:   Wed Jan 16 11:10:00 2019 -0800

    bpftool: make key optional in lookup command

    Bpftool expects key for 'lookup' operations. For some map types, key should
    not be specified. Support looking up those map types.

    Before:
    bpftool map create /sys/fs/bpf/q type queue value 4 entries 10 name q
    bpftool map update pinned /sys/fs/bpf/q value 0 1 2 3
    bpftool map lookup pinned /sys/fs/bpf/q
    Error: did not find key

    After:
    bpftool map create /sys/fs/bpf/q type queue value 4 entries 10 name q
    bpftool map update pinned /sys/fs/bpf/q value 0 1 2 3
    bpftool map lookup pinned /sys/fs/bpf/q
    key:   value: 00 01 02 03

    Signed-off-by: Stanislav Fomichev <sdf@google.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>