[powerpc] powerpc/pseries: Fix build break due to pnv_npu2_init()
Message-id: <d2ffd40c42b7e78dd3357c42e715d4c017221761.1557901788.git.sbobroff@redhat.com>
Patchwork-id: 256067
O-Subject: [RHEL8.1 BZ1704056 PATCH 4/4] powerpc/pseries: Fix build break due to pnv_npu2_init()
Bugzilla: 1704567
RH-Acked-by: Thomas Huth <thuth@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>

From: "Jason A. Donenfeld" <Jason@zx2c4.com>

Commit 3be2df00e299 ("powerpc/pseries/npu: Enable platform support")
added a call to pnv_npu2_init() in pseries code. This causes a build
break if we build with CONFIG_PPC_PSERIES && !CONFIG_PPC_POWERNV:

  powerpc64le-pc-linux-gnu-ld: arch/powerpc/platforms/pseries/pci.o: in function `pSeries_final_fixup':
  pci.c:(.init.text+0x1b0): undefined reference to `pnv_npu2_init'

This commit therefore wraps that line in an ifdef, so that pseries
builds without powernv.

Fixes: 3be2df00e299 ("powerpc/pseries/npu: Enable platform support")
Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>
Reviewed-by: Alexey Kardashevskiy <aik@ozlabs.ru>
[mpe: Frob change log a bit to blame a different commit]
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit da727097a482a93645ba5beea8d389ebab11fc64)

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1704567
Testing: Inspection only, it's a build time issue.
Signed-off-by: Sam Bobroff <sbobroff@redhat.com>
Upstream: Patch is upstream
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>