[netdrv] netronome: fix ipv6 link error
Message-id: <20201013172431.1403167-74-ivecera@redhat.com>
Patchwork-id: 330917
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 PATCH 73/74] netronome: fix ipv6 link error
Bugzilla: 1886717
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1886717

Upstream commit(s):
commit ea217e874aef6aa523331a9b5a8d49223460cf3e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jan 8 14:15:15 2020 +0100

    netronome: fix ipv6 link error

    When the driver is built-in but ipv6 is a module, the flower
    support produces a link error:

    drivers/net/ethernet/netronome/nfp/flower/tunnel_conf.o: In function `nfp_tunnel_keep_alive_v6':
    tunnel_conf.c:(.text+0x2aa8): undefined reference to `nd_tbl'

    Add a Kconfig dependency to avoid that configuration.

    Fixes: 9ea9bfa12240 ("nfp: flower: support ipv6 tunnel keep-alive messages from fw")
    Acked-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>