[tools] libbpf: silence GCC8 warning about string truncation
Message-id: <20191112151107.11979-227-yauheni.kaliuta@redhat.com>
Patchwork-id: 285869
O-Subject: [RHEL8.2 227/248] libbpf: silence GCC8 warning about string truncation
Bugzilla: 1747617
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747617

commit cb8ffde5694ae5fffb456eae932aac442aa3a207
Author: Andrii Nakryiko <andriin@fb.com>
Date:   Wed Jul 24 14:47:53 2019 -0700

    libbpf: silence GCC8 warning about string truncation

    Despite a proper NULL-termination after strncpy(..., ..., IFNAMSIZ - 1),
    GCC8 still complains about *expected* string truncation:

      xsk.c:330:2: error: 'strncpy' output may be truncated copying 15 bytes
      from a string of length 15 [-Werror=stringop-truncation]
        strncpy(ifr.ifr_name, xsk->ifname, IFNAMSIZ - 1);

    This patch gets rid of the issue altogether by using memcpy instead.
    There is no performance regression, as strncpy will still copy and fill
    all of the bytes anyway.

    v1->v2:
    - rebase against bpf tree.

    Cc: Magnus Karlsson <magnus.karlsson@intel.com>
    Signed-off-by: Andrii Nakryiko <andriin@fb.com>
    Acked-by: Magnus Karlsson <magnus.karlsson@intel.com>
    Acked-by: Song Liu <songliubraving@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>