rtw88: pci: Add prototypes for .probe, .remove and .shutdown
Bugzilla: http://bugzilla.redhat.com/1937053

commit 2e86ef413ab3f8da6ecf6c86b4eee5fb47bd77f6
Author: Lee Jones <lee.jones@linaro.org>
Date:   Thu Nov 26 13:31:52 2020 +0000

    rtw88: pci: Add prototypes for .probe, .remove and .shutdown

    Also strip out other duplicates from driver specific headers.

    Ensure 'main.h' is explicitly included in 'pci.h' since the latter
    uses some defines from the former.  It avoids issues like:

     from drivers/net/wireless/realtek/rtw88/rtw8822be.c:5:
     drivers/net/wireless/realtek/rtw88/pci.h:209:28: error: ‘RTK_MAX_TX_QUEUE_NUM’ undeclared here (not in a function); did you mean ‘RTK_MAX_RX_DESC_NUM’?
     209 | DECLARE_BITMAP(tx_queued, RTK_MAX_TX_QUEUE_NUM);
     | ^~~~~~~~~~~~~~~~~~~~

    Fixes the following W=1 kernel build warning(s):

     drivers/net/wireless/realtek/rtw88/pci.c:1488:5: warning: no previous prototype for ‘rtw_pci_probe’ [-Wmissing-prototypes]
     1488 | int rtw_pci_probe(struct pci_dev *pdev,
     | ^~~~~~~~~~~~~
     drivers/net/wireless/realtek/rtw88/pci.c:1568:6: warning: no previous prototype for ‘rtw_pci_remove’ [-Wmissing-prototypes]
     1568 | void rtw_pci_remove(struct pci_dev *pdev)
     | ^~~~~~~~~~~~~~
     drivers/net/wireless/realtek/rtw88/pci.c:1590:6: warning: no previous prototype for ‘rtw_pci_shutdown’ [-Wmissing-prototypes]
     1590 | void rtw_pci_shutdown(struct pci_dev *pdev)
     | ^~~~~~~~~~~~~~~~

    Cc: Yan-Hsuan Chuang <yhchuang@realtek.com>
    Cc: Kalle Valo <kvalo@codeaurora.org>
    Cc: "David S. Miller" <davem@davemloft.net>
    Cc: Jakub Kicinski <kuba@kernel.org>
    Cc: linux-wireless@vger.kernel.org
    Cc: netdev@vger.kernel.org
    Signed-off-by: Lee Jones <lee.jones@linaro.org>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/20201126133152.3211309-18-lee.jones@linaro.org

Signed-off-by: Jarod Wilson <jarod@redhat.com>