[iommu] arm-smmu-v3: Fix compilation when CONFIG_CMA=n
Message-id: <20191125175220.10229-195-jsnitsel@redhat.com>
Patchwork-id: 288716
O-Subject: [RHEL8.2 PATCH v3 194/266] iommu/arm-smmu-v3: Fix compilation when CONFIG_CMA=n
Bugzilla: 1722978
RH-Acked-by: David Milburn <dmilburn@redhat.com>
RH-Acked-by: Bhupesh Sharma <bhsharma@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1722978
Upstream Status: 900a85ca43f4ae88c325a468cb8827e4852b9141
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24919229

commit 900a85ca43f4ae88c325a468cb8827e4852b9141
Author: Will Deacon <will@kernel.org>
Date:   Tue Jul 2 12:53:18 2019 +0100

    iommu/arm-smmu-v3: Fix compilation when CONFIG_CMA=n

    When compiling a kernel without support for CMA, CONFIG_CMA_ALIGNMENT
    is not defined which results in the following build failure:

    In file included from ./include/linux/list.h:9:0
		     from ./include/linux/kobject.h:19,
		     from ./include/linux/of.h:17
		     from ./include/linux/irqdomain.h:35,
		     from ./include/linux/acpi.h:13,
		     from drivers/iommu/arm-smmu-v3.c:12:
    drivers/iommu/arm-smmu-v3.c: In function arm_smmu_device_hw_probe:
    drivers/iommu/arm-smmu-v3.c:194:40: error: CONFIG_CMA_ALIGNMENT undeclared (first use in this function)
     #define Q_MAX_SZ_SHIFT   (PAGE_SHIFT + CONFIG_CMA_ALIGNMENT)

    Fix the breakage by capping the maximum queue size based on MAX_ORDER
    when CMA is not enabled.

    Reported-by: Zhangshaokun <zhangshaokun@hisilicon.com>
    Signed-off-by: Will Deacon <will@kernel.org>
    Tested-by: Shaokun Zhang <zhangshaokun@hisilicon.com>
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(imported from commit 900a85ca43f4ae88c325a468cb8827e4852b9141)

Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>