[net] tcp: fix build fong CONFIG_MPTCP=n
Message-id: <b5b08016dbaedb1f9e59ae076c810fc8317c4934.1605646322.git.dcaratti@redhat.com>
Patchwork-id: 339847
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net 070/134] tcp: fix build fong CONFIG_MPTCP=n
Bugzilla: 1874368
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1874368
Upstream Status: net.git commit 0e8642cf369a

commit 0e8642cf369a37b718c15effa6ffd52c00fd7d15
Author: Eric Dumazet <edumazet@google.com>
Date:   Fri Jul 31 19:09:29 2020 -0700

    tcp: fix build fong CONFIG_MPTCP=n

    Fixes these errors:

    net/ipv4/syncookies.c: In function 'tcp_get_cookie_sock':
    net/ipv4/syncookies.c:216:19: error: 'struct tcp_request_sock' has no
    member named 'drop_req'
      216 |   if (tcp_rsk(req)->drop_req) {
          |                   ^~
    net/ipv4/syncookies.c: In function 'cookie_tcp_reqsk_alloc':
    net/ipv4/syncookies.c:289:27: warning: unused variable 'treq'
    [-Wunused-variable]
      289 |  struct tcp_request_sock *treq;
          |                           ^~~~
    make[3]: *** [scripts/Makefile.build:280: net/ipv4/syncookies.o] Error 1
    make[3]: *** Waiting for unfinished jobs....

    Fixes: 9466a1ccebbe ("mptcp: enable JOIN requests even if cookies are in use")
    Signed-off-by: Eric Dumazet <edumazet@google.com>
    Cc: Florian Westphal <fw@strlen.de>
    Acked-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>