[netdrv] peak_usb: fix clang build warning
Message-id: <20200521180844.15700-223-torez@redhat.com>
Patchwork-id: 313276
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 1825410, 1821835, 1825141, 1788005 222/359] peak_usb: fix clang build warning
Bugzilla: 1825410 1821835
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1825410
Bugzilla: https://bugzilla.redhat.com/1821835
Bugzilla: https://bugzilla.redhat.com/1825141
Bugzilla: https://bugzilla.redhat.com/1788005
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28738146
Testing: on Dell Whitehaven Precision 7730, HP ZBook 15 G3/80D5 and
	ThinkCentre M910z All-in-One

commit a2ae6da025ed73e4312d983b5e57300bc77090f3
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Mar 7 11:31:55 2019 +0100

    peak_usb: fix clang build warning

    Clang points out undefined behavior when building the pcan_usb_pro driver:

    drivers/net/can/usb/peak_usb/pcan_usb_pro.c:136:15: error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Werror,-Wvarargs]

    Changing the function prototype to avoid argument promotion in the
    varargs call avoids the warning, and should make this well-defined.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>