[netdrv] mlxsw: spectrum_acl: Track rules that forbid egress block bind
Message-id: <20200601180237.4179948-5-ivecera@redhat.com>
Patchwork-id: 315779
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 PATCH 004/290] mlxsw: spectrum_acl: Track rules that forbid egress block bind
Bugzilla: 1821646
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1821646

Upstream commit(s):
commit c9588e28123c563a355964c6ee8ca5dd28aebd6a
Author: Jiri Pirko <jiri@mellanox.com>
Date:   Sat Jul 27 20:32:56 2019 +0300

    mlxsw: spectrum_acl: Track rules that forbid egress block bind

    Some matches and actions are not supported on egress. Track such rules
    and forbid a bind of block which contains them to egress.

    With this patch, the kernel tells the user he cannot do that:
    $ tc qdisc add dev ens16np1 ingress_block 22 clsact
    $ tc filter add block 22 protocol 802.1q pref 2 handle 101 flower vlan_id 100 skip_sw action pass
    $ tc qdisc add dev ens16np2 egress_block 22 clsact
    Error: mlxsw_spectrum: Block cannot be bound to egress because it contains unsupported rules.

    Signed-off-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: Ido Schimmel <idosch@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>