[tools] libbpf, hashmap: Fix signedness warnings
Message-id: <20200924164430.191293-112-yauheni.kaliuta@redhat.com>
Patchwork-id: 327962
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 112/243] libbpf, hashmap: Fix signedness warnings
Bugzilla: 1874003
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874003

commit 8d35d74f52ae07689e575ea21f7dc2e07dd1392f
Author: Ian Rogers <irogers@google.com>
Date:   Fri May 15 09:50:03 2020 -0700

    libbpf, hashmap: Fix signedness warnings

    Fixes the following warnings:

      hashmap.c: In function ‘hashmap__clear’:
      hashmap.h:150:20: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
        150 |  for (bkt = 0; bkt < map->cap; bkt++)        \

      hashmap.c: In function ‘hashmap_grow’:
      hashmap.h:150:20: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
        150 |  for (bkt = 0; bkt < map->cap; bkt++)        \

    Signed-off-by: Ian Rogers <irogers@google.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Link: https://lore.kernel.org/bpf/20200515165007.217120-4-irogers@google.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>