[kernel] bpf: fix sysctl.c warning
Message-id: <20190925141552.30691-209-yauheni.kaliuta@redhat.com>
Patchwork-id: 274736
O-Subject: [RHEL8.2 PATCH v2 209/214] bpf: fix sysctl.c warning
Bugzilla: 1747341
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747341

commit 78c3aff834f7939d1a2570e366e33f2a880d4d9e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 4 21:34:12 2019 +0100

    bpf: fix sysctl.c warning

    When CONFIG_BPF_SYSCALL or CONFIG_SYSCTL is disabled, we get
    a warning about an unused function:

    kernel/sysctl.c:3331:12: error: 'proc_dointvec_minmax_bpf_stats' defined but not used [-Werror=unused-function]
     static int proc_dointvec_minmax_bpf_stats(struct ctl_table *table, int write,

    The CONFIG_BPF_SYSCALL check was already handled, but the SYSCTL check
    is needed on top.

    Fixes: 492ecee892c2 ("bpf: enable program stats")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Reviewed-by: Christian Brauner <christian@brauner.io>
    Acked-by: Song Liu <songliubraving@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>