[tools] selftest: include stdio.h in kselftest.h
Message-id: <a477e8ad3f1dc2681abc316a124316c4e6f42e4d.1596793349.git.jbenc@redhat.com>
Patchwork-id: 323516
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 05/63] selftest: include stdio.h in kselftest.h
Bugzilla: 1866908
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1866908

commit a18261d71bbc625bc32abbcded71acc408cca393
Author: Tycho Andersen <tycho@tycho.ws>
Date:   Fri Jan 18 17:12:14 2019 -0700

    selftest: include stdio.h in kselftest.h

    While playing around with a way to skip the seccomp get_metadata test, I
    noticed that this header uses printf() without defining it, leading to,

    ../kselftest.h: In function ‘ksft_print_header’:
    ../kselftest.h:61:3: warning: implicit declaration of function ‘printf’ [-Wimplicit-function-declaration]
       printf("TAP version 13\n");
       ^~~~~~
    ../kselftest.h:61:3: warning: incompatible implicit declaration of built-in function ‘printf’
    ../kselftest.h:61:3: note: include ‘<stdio.h>’ or provide a declaration of ‘printf’

    if user code doesn't also use printf.

    Signed-off-by: Tycho Andersen <tycho@tycho.ws>
    Acked-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Shuah Khan <shuah@kernel.org>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>