x86/PCI: Fix intel_mid_pci.c build error when ACPI is not enabled
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1955693
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=36482478
Upstream Status: 035fff1f7aab43e420e0098f0854470a5286fb83

commit 035fff1f7aab43e420e0098f0854470a5286fb83
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Fri Aug 21 17:10:27 2020 -0700

    x86/PCI: Fix intel_mid_pci.c build error when ACPI is not enabled

    Fix build error when CONFIG_ACPI is not set/enabled by adding the header
    file <asm/acpi.h> which contains a stub for the function in the build
    error.

        ../arch/x86/pci/intel_mid_pci.c: In function ‘intel_mid_pci_init’:
        ../arch/x86/pci/intel_mid_pci.c:303:2: error: implicit declaration of function ‘acpi_noirq_set’; did you mean ‘acpi_irq_get’? [-Werror=implicit-function-declaration]
          acpi_noirq_set();

    Fixes: a912a7584ec3 ("x86/platform/intel-mid: Move PCI initialization to arch_init()")
    Link: https://lore.kernel.org/r/ea903917-e51b-4cc9-2680-bc1e36efa026@infradead.org
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>
    Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
    Reviewed-by: Jesse Barnes <jsbarnes@google.com>
    Acked-by: Thomas Gleixner <tglx@linutronix.de>
    Cc: stable@vger.kernel.org      # v4.16+
    Cc: Jacob Pan <jacob.jun.pan@linux.intel.com>
    Cc: Len Brown <lenb@kernel.org>
    Cc: Jesse Barnes <jsbarnes@google.com>
    Cc: Arjan van de Ven <arjan@linux.intel.com>

Signed-off-by: Myron Stowe <mstowe@redhat.com>