[kernel] locking/lockdep: Avoid bogus Clang warning
Message-id: <20191111194853.28672-53-longman@redhat.com>
Patchwork-id: 285374
O-Subject: [RHEL8.2 PATCH 52/92] locking/lockdep: Avoid bogus Clang warning
Bugzilla: 1736654
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1736654

commit 3771b0fe9dfc3801eac0142d1af6ba94dee83c6c
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 25 13:57:57 2019 +0100

    locking/lockdep: Avoid bogus Clang warning

    When lockdep is enabled, and -Wuninitialized warnings are enabled,
    Clang produces a silly warning for every file we compile:

     In file included from  kernel/sched/fair.c:23:
      kernel/sched/sched.h:1094:15: error: variable 'cookie' is uninitialized when used here [-Werror,-Wuninitialized]
             rf->cookie = lockdep_pin_lock(&rq->lock);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      include/linux/lockdep.h:474:60: note: expanded from macro 'lockdep_pin_lock'
      #define lockdep_pin_lock(l)                     ({ struct pin_cookie cookie; cookie; })
                                                                                 ^~~~~~
      kernel/sched/sched.h:1094:15: note: variable 'cookie' is declared here
      include/linux/lockdep.h:474:34: note: expanded from macro 'lockdep_pin_lock'
      #define lockdep_pin_lock(l)                     ({ struct pin_cookie cookie; cookie; })
                                                        ^

    As the 'struct pin_cookie' structure is empty in this configuration,
    there is no need to initialize it for correctness, but it also
    does not hurt to set it to an empty structure, so do that to
    avoid the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Will Deacon <will.deacon@arm.com>
    Cc: Bart Van Assche <bvanassche@acm.org>
    Cc: Joel Fernandes (Google) <joel@joelfernandes.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Nathan Chancellor <natechancellor@gmail.com>
    Cc: Nick Desaulniers <ndesaulniers@google.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Steven Rostedt (VMware) <rostedt@goodmis.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Waiman Long <longman@redhat.com>
    Cc: clang-built-linux@googlegroups.com
    Link: http://lkml.kernel.org/r/20190325125807.1437049-1-arnd@arndb.de
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>