[powerpc] bpf, powerpc: Fix misuse of fallthrough in bpf_jit_comp()
Message-id: <20210113140908.457588-275-yauheni.kaliuta@redhat.com>
Patchwork-id: 348622
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 v2 275/291] bpf, powerpc: Fix misuse of fallthrough in bpf_jit_comp()
Bugzilla: 1874005
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874005

Conflicts: df561f6688fe ("treewide: Use fallthrough pseudo-keyword")
  was actually skipped for the file, so just remove the comment to
  align with upstream.

commit 9cf51446e68607136e42a4e531a30c888c472463
Author: He Zhe <zhe.he@windriver.com>
Date:   Mon Sep 28 17:00:23 2020 +0800

    bpf, powerpc: Fix misuse of fallthrough in bpf_jit_comp()

    The user defined label following "fallthrough" is not considered by GCC
    and causes build failure.

    kernel-source/include/linux/compiler_attributes.h:208:41: error: attribute
    'fallthrough' not preceding a case label or default label [-Werror]
     208   define fallthrough _attribute((fallthrough_))
                              ^~~~~~~~~~~~~

    Fixes: df561f6688fe ("treewide: Use fallthrough pseudo-keyword")
    Signed-off-by: He Zhe <zhe.he@windriver.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Cc: Gustavo A. R. Silva <gustavoars@kernel.org>
    Link: https://lore.kernel.org/bpf/20200928090023.38117-1-zhe.he@windriver.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>