[sound] ALSA: ASoC: rt1015: add missing header inclusion
Message-id: <1602843533499326-608-patchset-jkysela@redhat.com>
Patchwork-id: 332323
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 PATCH 0607/1534] ALSA: ASoC: rt1015: add missing header inclusion
Bugzilla: 1869536
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

To fix compilation error:

error: implicit declaration of function 'ACPI_PTR'
[-Werror,-Wimplicit-function-declaration]
                .acpi_match_table = ACPI_PTR(rt1015_acpi_match),
		                    ^

Adds the missing header "acpi.h" inclusion and sorts in alphabetical.

Signed-off-by: Tzung-Bi Shih <tzungbi@google.com>
Link: https://lore.kernel.org/r/20200625153543.85039-4-tzungbi@google.com
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 72ac4a4bef48e67bb26bc5a01d68c8163def013d)
Bugzilla: 1869536
Signed-off-by: Jan Stancek <jstancek@redhat.com>