[sound] ALSA: ASoC: rt5682: fix I2C/Soundwire dependencies
Message-id: <1602843533499326-149-patchset-jkysela@redhat.com>
Patchwork-id: 331783
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 PATCH 0148/1534] ALSA: ASoC: rt5682: fix I2C/Soundwire dependencies
Bugzilla: 1869536
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

If one of the two is a loadable module, the combined driver must
not be built-in:

aarch64-linux-ld: sound/soc/codecs/rt5682.o: in function `rt5682_sdw_hw_free':
rt5682.c:(.text+0xb34): undefined reference to `sdw_stream_remove_slave'
aarch64-linux-ld: sound/soc/codecs/rt5682.o: in function `rt5682_sdw_hw_params':
rt5682.c:(.text+0xe78): undefined reference to `sdw_stream_add_slave'

In particular, the soundwire driver must not be built-in if
CONFIG_I2C=m.

Fixes: 5549ea647997 ("ASoC: rt5682: fix unmet dependencies")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20200428214642.3925004-1-arnd@arndb.de
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit fd443a20c2f0950f3c31765a08f7dd49b3bc69cb)
Bugzilla: 1869536
Signed-off-by: Jan Stancek <jstancek@redhat.com>