[x86] x86: i8259: Add missing include file
Message-id: <20201012135442.3302-84-longman@redhat.com>
Patchwork-id: 330741
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 83/89] x86: i8259: Add missing include file
Bugzilla: 1885084
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1885084

commit 0a957467c5fd46142bc9c52758ffc552d4c5e2f7
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Wed, 15 Aug 2018 13:22:27 -0700

    x86: i8259: Add missing include file

    i8259.h uses inb/outb and thus needs to include asm/io.h to avoid the
    following build error, as seen with x86_64:defconfig and CONFIG_SMP=n.

      In file included from drivers/rtc/rtc-cmos.c:45:0:
      arch/x86/include/asm/i8259.h: In function 'inb_pic':
      arch/x86/include/asm/i8259.h:32:24: error:
            implicit declaration of function 'inb'

      arch/x86/include/asm/i8259.h: In function 'outb_pic':
      arch/x86/include/asm/i8259.h:45:2: error:
            implicit declaration of function 'outb'

    Reported-by: Sebastian Gottschall <s.gottschall@dd-wrt.com>
    Suggested-by: Sebastian Gottschall <s.gottschall@dd-wrt.com>
    Fixes: 447ae3166702 ("x86: Don't include linux/irq.h from asm/hardirq.h")
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>