[x86] kvm: fix a missing-prototypes "vmread_error"
Message-id: <20200420170611.951134-1-vkuznets@redhat.com>
Patchwork-id: 304290
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 virt PATCH v2 601/614] x86/kvm: fix a missing-prototypes "vmread_error"
Bugzilla: 1813987
RH-Acked-by: Andrew Jones <drjones@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Qian Cai <cai@lca.pw>

The commit 842f4be95899 ("KVM: VMX: Add a trampoline to fix VMREAD error
handling") removed the declaration of vmread_error() causes a W=1 build
failure with KVM_WERROR=y. Fix it by adding it back.

arch/x86/kvm/vmx/vmx.c:359:17: error: no previous prototype for 'vmread_error' [-Werror=missing-prototypes]
 asmlinkage void vmread_error(unsigned long field, bool fault)
                 ^~~~~~~~~~~~

Signed-off-by: Qian Cai <cai@lca.pw>
Message-Id: <20200402153955.1695-1-cai@lca.pw>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 514ccc194971d0649e4e7ec8a9b3a6e33561d7bf)
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>