[drm] drm/atomic_helper: Remove dangling variable
Message-id: <20181128174629.20727-17-labbott@redhat.com>
Patchwork-id: 233886
O-Subject: [RHEL8.0 BZ 1626466 16/17] [drm] drm/atomic_helper: Remove dangling variable
Bugzilla: 1582754
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>
RH-Acked-by: Lyude Paul <lyude@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1582754
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=19300249
Testing: Compile only
Upstream status: RHEL only

Commit 267e61f7d775 ("[drm] drm/atomic_helper: Stop modesets on
unregistered connectors harder") reverted a commit but left
a variable around leading to a warning:

drivers/gpu/drm/drm_atomic.c: In function 'drm_atomic_set_crtc_for_connector':
drivers/gpu/drm/drm_atomic.c:1549:24: error: unused variable 'connector' [-Werror=unused-variable]
  struct drm_connector *connector = conn_state->connector;
                        ^~~~~~~~~

Clean up this stray variable.

Signed-off-by: Laura Abbott <labbott@redhat.com>

Cc: David Airlie <airlied@redhat.com>
Cc: Adam Jackson <ajax@redhat.com>
Cc: Rob Clark <rclark@redhat.com>
Cc: Lyude Paul <lyude@redhat.com>
Cc: Laura Abbott <labbott@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>