[kernel] sched/debug: Remove sd->*_idx range on sysctl
Message-id: <20191021140050.21010-15-pauld@redhat.com>
Patchwork-id: 280487
O-Subject: [RHEL8.2 14/31] sched/debug: Remove sd->*_idx range on sysctl
Bugzilla: 1757535
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Daniel Bristot de Oliveira <bristot@redhat.com>
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Waiman Long <longman@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1757535
Upstream Status: Linux
Depends: 1725618
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24130523
Tested: By me with kt1 and stress/ltp on various architectures, and with
   local scheduler sanity tests. By kernel perf team with a battery of
   performance tests. Results of those are in the bug.

commit 3d8d53554405952993bb0279ef3ebebc51740074
Author: Dietmar Eggemann <dietmar.eggemann@arm.com>
Date:   Mon May 27 07:21:12 2019 +0100

    sched/debug: Remove sd->*_idx range on sysctl

    This reverts:

      commit 201c373e8e48 ("sched/debug: Limit sd->*_idx range on sysctl")

    Load indexes (sd->*_idx) are no longer needed without rq->cpu_load[].
    The range check for load indexes can be removed as well. Get rid of it
    before the rq->cpu_load[] since it uses CPU_LOAD_IDX_MAX.

    At the same time, fix the following coding style issues detected by
    scripts/checkpatch.pl:

      ERROR: space prohibited before that ','
      ERROR: space prohibited before that close parenthesis ')'

    Signed-off-by: Dietmar Eggemann <dietmar.eggemann@arm.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Acked-by: Rik van Riel <riel@surriel.com>
    Cc: Frederic Weisbecker <fweisbec@gmail.com>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Morten Rasmussen <morten.rasmussen@arm.com>
    Cc: Patrick Bellasi <patrick.bellasi@arm.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Quentin Perret <quentin.perret@arm.com>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Valentin Schneider <valentin.schneider@arm.com>
    Cc: Vincent Guittot <vincent.guittot@linaro.org>
    Link: https://lkml.kernel.org/r/20190527062116.11512-4-dietmar.eggemann@arm.com
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Phil Auld <pauld@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>