[include] cpumask: make cpumask_next_wrap available without smp
Message-id: <20200417154942.9655-4-eperezma@redhat.com>
Patchwork-id: 303564
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH v2 3/9] cpumask: make cpumask_next_wrap available without smp
Bugzilla: 1718086
RH-Acked-by: Jason Wang <jasowang@redhat.com>
RH-Acked-by: Michael S. Tsirkin <mst@redhat.com>

From: Willem de Bruijn <willemb@google.com>

The kbuild robot shows build failure on machines without CONFIG_SMP:

  drivers/net/virtio_net.c:1916:10: error:
    implicit declaration of function 'cpumask_next_wrap'

cpumask_next_wrap is exported from lib/cpumask.o, which has

    lib-$(CONFIG_SMP) += cpumask.o

same as other functions, also define it as static inline in the
NR_CPUS==1 branch in include/linux/cpumask.h.

If wrap is true and next == start, return nr_cpumask_bits, or 1.
Else wrap across the range of valid cpus, here [0].

Fixes: 2ca653d607ce ("virtio_net: Stripe queue affinities across cores.")
Signed-off-by: Willem de Bruijn <willemb@google.com>
Tested-by: Krzysztof Kozlowski <krzk@kernel.org>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 9af18e56d43ca4864ce65c3542c513827c2697de)

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1718086
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>