[wireless] rtw88: include interrupt.h for tasklet_struct
Message-id: <20200413203652.3431-123-jarod@redhat.com>
Patchwork-id: 301570
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 122/615] rtw88: include interrupt.h for tasklet_struct
Bugzilla: 1807052
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1807052

commit c3226d93f85c27170abac78dbe233c0a0ad12d35
Author: Brian Norris <briannorris@chromium.org>
Date:   Fri Oct 11 18:44:21 2019 -0700

    rtw88: include interrupt.h for tasklet_struct

    Depending on implicit header includes, we might see this compilation
    error:

    .../main.h:1391:24: error: field has incomplete type 'struct tasklet_struct'
            struct tasklet_struct tx_tasklet;
                                  ^

    Fixes: 3745d3e550d1 ("rtw88: add driver TX queue support")
    Signed-off-by: Brian Norris <briannorris@chromium.org>
    Acked-by: Yan-Hsuan Chuang <yhchuang@realtek.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>