[netdrv] net: bareudp: avoid uninitialized variable warning
Message-id: <80272edb181419cff06528a70728a9778df0e473.1605350564.git.gnault@redhat.com>
Patchwork-id: 339481
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net PATCH 08/20] net: bareudp: avoid uninitialized variable warning
Bugzilla: 1839788
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Xin Long <lxin@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1839788
Upstream Status: linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33070105
Tested: CKI net + upstream kselftest included in this series

commit ee2875566868687a95b8ec23913c0d6bce220efd
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 5 19:22:14 2020 +0200

    net: bareudp: avoid uninitialized variable warning

    clang points out that building without IPv6 would lead to returning
    an uninitialized variable if a packet with family!=AF_INET is
    passed into bareudp_udp_encap_recv():

    drivers/net/bareudp.c:139:6: error: variable 'err' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
            if (family == AF_INET)
                ^~~~~~~~~~~~~~~~~
    drivers/net/bareudp.c:146:15: note: uninitialized use occurs here
            if (unlikely(err)) {
                         ^~~
    include/linux/compiler.h:78:42: note: expanded from macro 'unlikely'
     # define unlikely(x)    __builtin_expect(!!(x), 0)
                                                ^
    drivers/net/bareudp.c:139:2: note: remove the 'if' if its condition is always true
            if (family == AF_INET)
            ^~~~~~~~~~~~~~~~~~~~~~

    This cannot happen in practice, so change the condition in a way that
    gcc sees the IPv4 case as unconditionally true here.
    For consistency, change all the similar constructs in this file the
    same way, using "if(IS_ENABLED())" instead of #if IS_ENABLED()".

    Fixes: 571912c69f0e ("net: UDP tunnel encapsulation module for tunnelling different protocols like MPLS, IP, NSH etc.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Guillaume Nault <gnault@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>