[tools] perf tools: Initialize perf_data_file fd field
Message-id: <0887316dbf67d954951cc06a676412d7d3abcb74.1559304074.git.mpetlan@redhat.com>
Patchwork-id: 261411
O-Subject: [RHEL8.1 BZ1709243 107/217] perf tools: Initialize perf_data_file fd field
Bugzilla: 1709243
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1709243
https://bugzilla.redhat.com/show_bug.cgi?id=1709243

upstream
========
commit c04c859f439fb4de9039246370d60a07b9b5bcb5
Author: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Date: Wed Aug 29 16:16:48 2018 -0400

description
===========
Building the perf CTF converter fails with gcc 4.8.4 on Ubuntu 14.04
with the following error:

  error: missing initializer for field ‘fd’ of ‘struct perf_data_file’
  [-Werror=missing-field-initializers]

Per 4b838b0db4e9 ("perf tools: Add compression id into 'struct
kmod_path'") and the ensuing discussion on the mailing list, it appears
that this affects other distributions and gcc versions.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>