[net] netfilter: nf_tables: use-after-free in dynamic operations
Message-id: <20200428181433.12226-1-psutter@redhat.com>
Patchwork-id: 305626
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net] netfilter: nf_tables: use-after-free in dynamic operations
Bugzilla: 1822577
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1822577
Upstream Status: commit 3f3a390dbd59d
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28234312
Tested: Just basic functional testing. Problem happened just twice in
        customer environment according to reporter, circumstances
	unknown.

Note that referenced commit in Fixes: tag does not exist downstream. But
as mentioned in BZ, the problem already existed before that commit.

commit 3f3a390dbd59d236f62cff8e8b20355ef7069e3d
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Mon Mar 11 13:04:16 2019 +0100

    netfilter: nf_tables: use-after-free in dynamic operations

    Smatch reports:

           net/netfilter/nf_tables_api.c:2167 nf_tables_expr_destroy()
            error: dereferencing freed memory 'expr->ops'

    net/netfilter/nf_tables_api.c
        2162 static void nf_tables_expr_destroy(const struct nft_ctx *ctx,
        2163                                   struct nft_expr *expr)
        2164 {
        2165        if (expr->ops->destroy)
        2166                expr->ops->destroy(ctx, expr);
                                                    ^^^^
    --> 2167        module_put(expr->ops->type->owner);
                               ^^^^^^^^^
        2168 }

    Smatch says there are three functions which free expr->ops.

    Fixes: b8e204006340 ("netfilter: nft_compat: use .release_ops and remove list of extension")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Phil Sutter <psutter@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>