[kernel] bpf, netns: Fix build without CONFIG_INET
Message-id: <17e0aeb7aa0b6bb1eb996bd10a384e0a53780b97.1608036136.git.jbenc@redhat.com>
Patchwork-id: 344768
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net 50/90] bpf, netns: Fix build without CONFIG_INET
Bugzilla: 1882709
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Eelco Chaudron <echaudro@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1882709

commit 343ead287dde0064c430ee1db477726f52e0269c
Author: Jakub Sitnicki <jakub@cloudflare.com>
Date:   Tue Jul 21 12:07:16 2020 +0200

    bpf, netns: Fix build without CONFIG_INET

    When CONFIG_NET is set but CONFIG_INET isn't, build fails with:

      ld: kernel/bpf/net_namespace.o: in function `netns_bpf_attach_type_unneed':
      kernel/bpf/net_namespace.c:32: undefined reference to `bpf_sk_lookup_enabled'
      ld: kernel/bpf/net_namespace.o: in function `netns_bpf_attach_type_need':
      kernel/bpf/net_namespace.c:43: undefined reference to `bpf_sk_lookup_enabled'

    This is because without CONFIG_INET bpf_sk_lookup_enabled symbol is not
    available. Wrap references to bpf_sk_lookup_enabled with preprocessor
    conditionals.

    Fixes: 1559b4aa1db4 ("inet: Run SK_LOOKUP BPF program on socket lookup")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Jakub Sitnicki <jakub@cloudflare.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Link: https://lore.kernel.org/bpf/20200721100716.720477-1-jakub@cloudflare.com

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>