[kernel] locking/lockdep: Avoid a Clang warning
Message-id: <20191111194853.28672-44-longman@redhat.com>
Patchwork-id: 285357
O-Subject: [RHEL8.2 PATCH 43/92] locking/lockdep: Avoid a Clang warning
Bugzilla: 1736654
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1736654

commit 3fe7522fb766f6ee76bf7bc2837f1e3cc52c4e27
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Mar 7 08:52:12 2019 +0100

    locking/lockdep: Avoid a Clang warning

    Clang warns about a tentative array definition without a length:

      kernel/locking/lockdep.c:845:12: error: tentative array definition assumed to have one element [-Werror]

    There is no real reason to do this here, so just set the same length as
    in the real definition later in the same file.  It has to be hidden in
    an #ifdef or annotated __maybe_unused though, to avoid the unused-variable
    warning if CONFIG_PROVE_LOCKING is disabled.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Andy Lutomirski <luto@kernel.org>
    Cc: Arnaldo Carvalho de Melo <acme@redhat.com>
    Cc: Bart Van Assche <bvanassche@acm.org>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Dave Hansen <dave.hansen@linux.intel.com>
    Cc: Frederic Weisbecker <frederic@kernel.org>
    Cc: H. Peter Anvin <hpa@zytor.com>
    Cc: Jiri Olsa <jolsa@redhat.com>
    Cc: Joel Fernandes (Google) <joel@joelfernandes.org>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Paul E. McKenney <paulmck@linux.vnet.ibm.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Rik van Riel <riel@surriel.com>
    Cc: Stephane Eranian <eranian@google.com>
    Cc: Steven Rostedt (VMware) <rostedt@goodmis.org>
    Cc: Tetsuo Handa <penguin-kernel@I-love.SAKURA.ne.jp>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: Vince Weaver <vincent.weaver@maine.edu>
    Cc: Waiman Long <longman@redhat.com>
    Cc: Will Deacon <will.deacon@arm.com>
    Link: https://lkml.kernel.org/r/20190307075222.3424524-1-arnd@arndb.de
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>