[tools] perf tools: Add missing sigqueue() prototype for systems lacking it
Message-id: <679b032fd8e7ff237d42f91b57c6d2923d64c343.1560250176.git.mpetlan@redhat.com>
Patchwork-id: 265026
O-Subject: [RHEL8.1 BZ1715507 125/234] perf tools: Add missing sigqueue() prototype for systems lacking it
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit 748fe0889c1ff12d378946bd5326e8ee8eacf5cf
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Dec 11 15:48:47 2018 -0300

description
===========
There are systems such as the Android NDK API level 24 has the
sigqueue() function but doesn't provide a prototype, adding noise to the
build:

  util/evlist.c: In function 'perf_evlist__prepare_workload':
  util/evlist.c:1494:4: warning: implicit declaration of function 'sigqueue' [-Wimplicit-function-declaration]
      if (sigqueue(getppid(), SIGUSR1, val))
      ^
  util/evlist.c:1494:4: warning: nested extern declaration of 'sigqueue' [-Wnested-externs]

Define a LACKS_SIGQUEUE_PROTOTYPE define so that code needing that can
get a prototype.

Checked in the bionic git repo to be available since level 23:

https://android.googlesource.com/platform/bionic/+/master/libc/include/signal.h#123

  int sigqueue(pid_t __pid, int __signal, const union sigval __value) __INTRODUCED_IN(23);

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>