[infiniband] IB/ucm: fix UCM link error
Message-id: <bbdf55cf90d7afb2667633726c11ddc014ecb595.1553550054.git.jtoppins@redhat.com>
Patchwork-id: 247627
O-Subject: [PATCH RDMAv4.19 RHEL-8.1 155/189] IB/ucm: fix UCM link error
Bugzilla: 1685304
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Building UCM with CONFIG_INFINIBAND_USER_ACCESS=m results in a
set of link errors including:

drivers/infiniband/core/ucm.o: In function `ib_ucm_event_handler':
ucm.c:(.text+0x6dc): undefined reference to `ib_copy_path_rec_to_user'
drivers/infiniband/core/ucma.o: In function `ucma_event_handler':
ucma.c:(.text+0xdc0): undefined reference to `ib_copy_ah_attr_to_user'

To get it to build-test again, this makes the option itself a
tristate, which lets Kconfig figure out the dependency correctly.

Fixes: 486edfb1039d ("IB/ucm: Fix compiling ucm.c")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>
(cherry picked from commit 845b397a7771f2d3504beff5521f452be0d22eec)
Bugzilla: 1685304
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=20667100
Tested: standard RDMA smoke and regression suite
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>