[drm] drm/amd/display: fix struct init in update_bounding_box
Message-id: <20191218151019.27933-1-ddutile@redhat.com>
Patchwork-id: 292083
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL-8.2] drm/amd/display: fix struct init in update_bounding_box
Bugzilla: 1784621
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Waiman Long <longman@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>

From: Raul E Rangel <rrangel@chromium.org>

dcn20_resource.c:2636:9: error: missing braces around initializer [-Werror=missing-braces]
  struct _vcs_dpi_voltage_scaling_st calculated_states[MAX_CLOCK_LIMIT_STATES] = {0};
         ^

Fixes: 7ed4e6352c16f ("drm/amd/display: Add DCN2 HW Sequencer and Resource")

Signed-off-by: Raul E Rangel <rrangel@chromium.org>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit 960b6f4f2d2e96d5f7ffe2854e0040b46cafbd36)

This upstream patch fixes RHEL-8 kernel builds on RHEL-7 systems.

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1784621
Brew: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=25423915

Testing:
Well brew built so a new build error wasn't introduced.
Local, RHEL-7 build to ensure that is fixed now.
No RHEL-8 testing, since no functional change, just RHEL-7 compiler
satisfaction.

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>