bpf: Fix build failure for kernel/trace/bpf_trace.c with CONFIG_NET=n
Bugzilla: http://bugzilla.redhat.com/1874006

commit ebfb4d40ed9dd45d2d6780f58d0cd9336d647890
Author: Yonghong Song <yhs@fb.com>
Date:   Tue Oct 6 23:29:33 2020 -0700

    bpf: Fix build failure for kernel/trace/bpf_trace.c with CONFIG_NET=n

    When CONFIG_NET is not defined, I hit the following build error:
        kernel/trace/bpf_trace.o:(.rodata+0x110): undefined reference to `bpf_prog_test_run_raw_tp'

    Commit 1b4d60ec162f ("bpf: Enable BPF_PROG_TEST_RUN for raw_tracepoint")
    added test_run support for raw_tracepoint in /kernel/trace/bpf_trace.c.
    But the test_run function bpf_prog_test_run_raw_tp is defined in
    net/bpf/test_run.c, only available with CONFIG_NET=y.

    Adding a CONFIG_NET guard for
        .test_run = bpf_prog_test_run_raw_tp;
    fixed the above build issue.

    Fixes: 1b4d60ec162f ("bpf: Enable BPF_PROG_TEST_RUN for raw_tracepoint")
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20201007062933.3425899-1-yhs@fb.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>