[block] block: iolatency: avoid 64-bit division
Message-id: <20180815045426.24566-52-ming.lei@redhat.com>
Patchwork-id: 226946
O-Subject: [RHEL8.0 051/126] block: iolatency: avoid 64-bit division
Bugzilla: 1614198
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ: 1614198

commit 88b7210c81096c018f5836aff4749743c0d34623
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Jul 10 17:21:34 2018 +0200

    block: iolatency: avoid 64-bit division

    On 32-bit architectures, dividing a 64-bit number needs to use the
    do_div() function or something like it to avoid a link failure:

    block/blk-iolatency.o: In function `iolatency_prfill_limit':
    blk-iolatency.c:(.text+0x8cc): undefined reference to `__aeabi_uldivmod'

    Using div_u64() gives us the best output and avoids the need for an
    explicit cast.

    Fixes: d70675121546 ("block: introduce blk-iolatency io controller")
    Reviewed-by: Josef Bacik <josef@toxicpanda.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>