[wireless] PCI: Move ASPM declarations to linux/pci.h
Message-id: <20200330211518.13699.49001.stgit@tak.stowe>
Patchwork-id: 298654
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 02/45] PCI: Move ASPM declarations to linux/pci.h
Bugzilla: 1807175
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Gopal Tiwari <gtiwari@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1807175
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=27532441
Upstream Status: 7ce2e76a0420801fb4b53b9e6850940e6b326433

Conflict(s):
  Not a conflict per say, but, due to RHEL 8 commit 7e74379c7b3f
  ("[netdrv] mt76: mt76x2e: disable pcie_aspm by default") implementing a
  RHEL specific work-around - compiling
  ./drivers/net/wireless/mediatek/mt76/pci.c now breaks with this patch
  incorporated:
    drivers/net/wireless/mediatek/mt76/pci.c:7:10:
    fatal error: linux/pci-aspm.h: No such file or directory
  In that commit, this specific patch is mentioned; specifically that this
  patch hadn't been taken yet so RHEL specific code was added to work
  around such.  Remove the RHEL specific code now that this patch is in
  place and the work-around is no longer necessary.

commit 7ce2e76a0420801fb4b53b9e6850940e6b326433 (pci/pci/aspm)
Author: Krzysztof Wilczynski <kw@linux.com>
Date:   Tue Aug 27 11:56:20 2019 +0200

    PCI: Move ASPM declarations to linux/pci.h

    Move ASPM definitions and function prototypes from include/linux/pci-aspm.h
    to include/linux/pci.h so users only need to include <linux/pci.h>:

      PCIE_LINK_STATE_L0S
      PCIE_LINK_STATE_L1
      PCIE_LINK_STATE_CLKPM
      pci_disable_link_state()
      pci_disable_link_state_locked()
      pcie_no_aspm()

    No functional changes intended.

    Link: https://lore.kernel.org/r/20190827095620.11213-1-kw@linux.com
    Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
    Signed-off-by: Bjorn Helgaas <bhelgaas@google.com>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>