[lib] livepatch/samples/selftest: Use klp_shadow_alloc() API correctly
Message-id: <20200319210505.28066-26-ycote@redhat.com>
Patchwork-id: 297159
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 livepatch v2 PATCH 25/32] livepatch/samples/selftest: Use klp_shadow_alloc() API correctly
Bugzilla: 1807115
RH-Acked-by: Artem Savkov <asavkov@redhat.com>
RH-Acked-by: Joe Lawrence <joe.lawrence@redhat.com>

From: Petr Mladek <pmladek@suse.com>

The commit e91c2518a5d22a ("livepatch: Initialize shadow variables
safely by a custom callback") leads to the following static checker
warning:

  samples/livepatch/livepatch-shadow-fix1.c:86 livepatch_fix1_dummy_alloc()
  error: 'klp_shadow_alloc()' 'leak' too small (4 vs 8)

It is because klp_shadow_alloc() is used a wrong way:

  int *leak;
  shadow_leak = klp_shadow_alloc(d, SV_LEAK, sizeof(leak), GFP_KERNEL,
				 shadow_leak_ctor, leak);

The code is supposed to store the "leak" pointer into the shadow variable.
3rd parameter correctly passes size of the data (size of pointer). But
the 5th parameter is wrong. It should pass pointer to the data (pointer
to the pointer) but it passes the pointer directly.

It works because shadow_leak_ctor() handle "ctor_data" as the data
instead of pointer to the data. But it is semantically wrong and
confusing.

The same problem is also in the module used by selftests. In this case,
"pvX" variables are introduced. They represent the data stored in
the shadow variables.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Petr Mladek <pmladek@suse.com>
Reviewed-by: Joe Lawrence <joe.lawrence@redhat.com>
Acked-by: Miroslav Benes <mbenes@suse.cz>
Reviewed-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>
Signed-off-by: Jiri Kosina <jkosina@suse.cz>
(cherry picked from commit be6da98425b69388ed31b18bd2497f826116f29b)
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>