[tty] kgdboc: Fix restrict error
Message-id: <20181128174629.20727-15-labbott@redhat.com>
Patchwork-id: 233873
O-Subject: [RHEL8.0 BZ 1626466 14/17] kgdboc: Fix restrict error
Bugzilla: 1582754
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1582754
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=19300249
Testing: Compile only

commit 2dd453168643d9475028cd867c57e65956a0f7f9
Author: Laura Abbott <labbott@redhat.com>
Date:   Mon Sep 10 16:20:14 2018 -0700

    kgdboc: Fix restrict error

    There's an error when compiled with restrict:

    drivers/tty/serial/kgdboc.c: In function ‘configure_kgdboc’:
    drivers/tty/serial/kgdboc.c:137:2: error: ‘strcpy’ source argument is the same
    as destination [-Werror=restrict]
      strcpy(config, opt);
      ^~~~~~~~~~~~~~~~~~~

    As the error implies, this is from trying to use config as both source and
    destination. Drop the call to the function where config is the argument
    since nothing else happens in the function.

    Signed-off-by: Laura Abbott <labbott@redhat.com>
    Reviewed-by: Daniel Thompson <daniel.thompson@linaro.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Cc: Laura Abbott <labbott@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>