[fpga] fpga: zynqmp: fix modular build
Message-id: <20210119160045.185160-13-lgoncalv@redhat.com>
Patchwork-id: 350271
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ1494702 PATCH 12/27] fpga: zynqmp: fix modular build
Bugzilla: 1494702
RH-Acked-by: Clark Williams <williams@redhat.com>
RH-Acked-by: Tom Rix <trix@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1494702
Upstream Status: Linus Tree (linux.git)
Build info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=34362661
                (with FPGA configs disabled as it is now in RHEL-8.4)
            https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=34363235
                (with FPGA configs enabled, to test the feature)
Tested: Build with the FPGA code enabled tested by Erico Nunes wrt the new code.
        RHEL-8.4 build (with FPGA support disabled) passed CKI tests.

commit 6a47d6efc6931b02d10163de2fb85ec9953c4f5e
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue, 5 May 2020 16:00:11 +0200

    fpga: zynqmp: fix modular build

    Two symbols need to be exported to allow the zynqmp-fpga module
    to get loaded dynamically:

    ERROR: modpost: "zynqmp_pm_fpga_load" [drivers/fpga/zynqmp-fpga.ko] undefined!
    ERROR: modpost: "zynqmp_pm_fpga_get_status" [drivers/fpga/zynqmp-fpga.ko] undefined!

    To ensure this is done correctly, also fix the Kconfig dependency
    to only allow building the fpga driver when the firmware driver is
    either disabled, or when it is reachable. With that, the dependency
    on the SoC itself can be removed, and there are no surprises when
    the fpga driver is built-in but the firmware a module.

    Fixes: 4db8180ffe7c ("firmware: xilinx: Remove eemi ops for fpga related APIs")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Moritz Fischer <mdf@kernel.org>

Signed-off-by: Luis Claudio R. Goncalves <lgoncalv@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>