[netdrv] igc: Fix static checker warning
Message-id: <20201120135541.358500-81-vinschen@redhat.com>
Patchwork-id: 340264
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 80/98] igc: Fix static checker warning
Bugzilla: 1838742
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

From: Sasha Neftin <sasha.neftin@intel.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1838742
Brew:     https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33182676

drivers/net/ethernet/intel/igc/igc_mac.c:424 igc_check_for_copper_link()
error: uninitialized symbol 'link'.
This patch come to fix this warning and initialize the 'link' symbol.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Fixes: 707abf069548 ("igc: Add initial LTR support")
Signed-off-by: Sasha Neftin <sasha.neftin@intel.com>
Tested-by: Aaron Brown <aaron.f.brown@intel.com>
Signed-off-by: Tony Nguyen <anthony.l.nguyen@intel.com>
(cherry picked from commit 360d749e0c8e689414d9a583102a59f795a6892d)
Signed-off-by: Corinna Vinschen <vinschen@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>