[samples] bpf: print a warning about headers_install
Message-id: <20191112151107.11979-79-yauheni.kaliuta@redhat.com>
Patchwork-id: 285747
O-Subject: [RHEL8.2 079/248] samples: bpf: print a warning about headers_install
Bugzilla: 1747617
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747617

commit 07c3bbdb1a9b2046631a2a2950a0c16e10cfcab3
Author: Jakub Kicinski <jakub.kicinski@netronome.com>
Date:   Wed Jun 5 16:47:22 2019 -0700

    samples: bpf: print a warning about headers_install

    It seems like periodically someone posts patches to "fix"
    header includes.  The issue is that samples expect the
    include path to have the uAPI headers (from usr/) first,
    and then tools/ headers, so that locally installed uAPI
    headers take precedence.  This means that if users didn't
    run headers_install they will see all sort of strange
    compilation errors, e.g.:

      HOSTCC  samples/bpf/test_lru_dist
      samples/bpf/test_lru_dist.c:39:8: error: redefinition of struct list_head
       struct list_head {
              ^~~~~~~~~
       In file included from samples/bpf/test_lru_dist.c:9:0:
       ../tools/include/linux/types.h:69:8: note: originally defined here
        struct list_head {
               ^~~~~~~~~

    Try to detect this situation, and print a helpful warning.

    v2: just use HOSTCC (Jiong).

    Signed-off-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Reviewed-by: Quentin Monnet <quentin.monnet@netronome.com>
    Acked-by: Martin KaFai Lau <kafai@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>