[lib] genalloc.c: include vmalloc.h
Message-id: <20191126132229.17000-3-ddutile@redhat.com>
Patchwork-id: 289014
O-Subject: [PATCH RHEL-8.2 02/12] lib/genalloc.c: include vmalloc.h
Bugzilla: 1754732
RH-Acked-by: Myron Stowe <mstowe@redhat.com>
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1754732

commit 35004f2e55807a1a1491db24ab512dd2f770a130
Author: Olof Johansson <olof@lixom.net>
Date:   Sat Jan 5 13:21:18 2019 -0800

    lib/genalloc.c: include vmalloc.h

    Fixes build break on most ARM/ARM64 defconfigs:

      lib/genalloc.c: In function 'gen_pool_add_virt':
      lib/genalloc.c:190:10: error: implicit declaration of function 'vzalloc_node'; did you mean 'kzalloc_node'?
      lib/genalloc.c:190:8: warning: assignment to 'struct gen_pool_chunk *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
      lib/genalloc.c: In function 'gen_pool_destroy':
      lib/genalloc.c:254:3: error: implicit declaration of function 'vfree'; did you mean 'kfree'?

    Fixes: 6862d2fc8185 ('lib/genalloc.c: use vzalloc_node() to allocate the bitmap')
    Cc: Huang Shijie <sjhuang@iluvatar.ai>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Alexey Skidanov <alexey.skidanov@intel.com>
    Signed-off-by: Olof Johansson <olof@lixom.net>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>