[misc] h8300: pci: Remove local declaration of pcibios_penalize_isa_irq
Message-id: <20191110173746.26019-297-ahs3@redhat.com>
Patchwork-id: 284935
O-Subject: [RHEL8.2 PATCH v5 296/299] h8300: pci: Remove local declaration of pcibios_penalize_isa_irq
Bugzilla: 1754787 1739728 1730098 1721297 1664185
RH-Acked-by: Jeremy Linton <jlinton@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664185
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1721297
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1730098
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1739728
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1754787
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24584640
Upstream Status: 21c7acc439b55d0569d7c2fc2eea5194b3910406
Tested: multiple BZs are covered by this patch set:

 bz1664185: this requires an ACPI HMAT table plus the hardware that it
 describes.  For full testing, PartnerQA is recommended.  Barring
 that, does an HMAT table exist, and are there sysfs entries for
 it showing up?

 bz1721297: this requires the latest ACPI PPTT tables in firmware, and
 the hardware that reflects it, so PartnerQA is required.  NB:
 there are additional patches for SPE that will need to be added
 -- see bz1504978 -- but these are the ACPI patches required for
 the SPE patches.

 bz1730098: same as bz1664185, but different partner.

 bz1739728: basic kernel testing and running of the kernel CI tests; in
 general, if a system boots and runs with all known hardware active
 and usable, the ACPI subsystem is behaving.  Re-ran CKI tests for
 v2.

 bz1754787: Windows 2018 string for _OSI, needs confirmation from the
 partner, also.

commit 21c7acc439b55d0569d7c2fc2eea5194b3910406
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Thu Dec 27 08:46:38 2018 -0800

    h8300: pci: Remove local declaration of pcibios_penalize_isa_irq

    h8300 builds fail with:

    In file included from drivers/of/address.c:11:
    include/linux/pci.h:1966:20: error: redefinition of 'pcibios_penalize_isa_irq'

    This is because CONFIG_PCI is not enabled, and pcibios_penalize_isa_irq()
    is now declared as inline static function in generic code if this is the
    case. Since h8300 does not support PCI to start with, fix the problem by
    removing the architecture specific pci.h.

    Fixes: 5d32a66541c46 ("PCI/ACPI: Allow ACPI to be built without CONFIG_PCI set")
    Cc: Sinan Kaya <okaya@kernel.org>
    Cc: Bjorn Helgaas <bhelgaas@google.com>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Yoshinori Sato <ysato@users.sourceforge.jp>
    (cherry picked from commit 21c7acc439b55d0569d7c2fc2eea5194b3910406)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>