[ntb] NTB: ntb_transport: Ensure qp->tx_mw_dma_addr is initaliazed
Message-id: <20200830190828.186945.46706.stgit@tak.stowe>
Patchwork-id: 325289
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 23/90] NTB: ntb_transport: Ensure qp->tx_mw_dma_addr is initaliazed
Bugzilla: 1908031
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1908031
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=30987425
Upstream Status: 51cb8dbf13246a0b144bff01d7d617efe550a055

commit 51cb8dbf13246a0b144bff01d7d617efe550a055
Author: Logan Gunthorpe <logang@deltatee.com>
Date:   Tue Feb 19 12:56:36 2019 -0700

    NTB: ntb_transport: Ensure qp->tx_mw_dma_addr is initaliazed

    Dan Carpenter's static checker reported:

        drivers/ntb/ntb_transport.c:1926 ntb_transport_create_queue()
        error: we previously assumed 'qp->tx_dma_chan' could be null (see line 1872)

    This is because the tx_mw_dma_addr is uninitialized in this function and
    may be incorrectly released using a NULL DMA channel.

    In practice this bug will not likely be seen. I'd guess you could hit
    this if you loaded ntb_netdev with use_dma=True, then unloaded it and
    loaded it again after setting the module parameter to use_dma=False.

    To fix this, we simply ensure that tx_mw_dma_addr is always
    initialized to zero. This is the safest in case any other part of the
    code operates on it if it is non-zero.

    Fixes: c59666bb32b9 ("NTB: ntb_transport: Ensure the destination buffer is mapped for TX DMA")
    Signed-off-by: Logan Gunthorpe <logang@deltatee.com>
    Cc: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

Signed-off-by: Myron Stowe <myron.stowe@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>