[block] rbd: work around -Wuninitialized warning
Message-id: <20200519180620.418410-53-jlayton@redhat.com>
Patchwork-id: 312662
Patchwork-instance: patchwork
O-Subject: [RHEL8.3.0 PATCH BZ#1827767 052/119] rbd: work around -Wuninitialized warning
Bugzilla: 1827767
RH-Acked-by: Xiubo Li <xiubli@redhat.com>
RH-Acked-by: Zheng Yan <zyan@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

gcc -O3 warns about a dummy variable that is passed
down into rbd_img_fill_nodata without being initialized:

drivers/block/rbd.c: In function 'rbd_img_fill_nodata':
drivers/block/rbd.c:2573:13: error: 'dummy' is used uninitialized in this function [-Werror=uninitialized]
  fctx->iter = *fctx->pos;

Since this is a dummy, I assume the warning is harmless, but
it's better to initialize it anyway and avoid the warning.

Fixes: mmtom ("init/Kconfig: enable -O3 for all arches")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Ilya Dryomov <idryomov@gmail.com>
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit a55e601b2f02df5db7070e9a37bd655c9c576a52)
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>