[powerpc] powerpc/powernv: Fix build with IOMMU_API=n
Message-id: <20200507001932.102069-46-mroth@redhat.com>
Patchwork-id: 306312
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 kernel PATCH 45/48] powerpc/powernv: Fix build with IOMMU_API=n
Bugzilla: 1805101
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>

From: Michael Ellerman <mpe@ellerman.id.au>

The builds breaks when IOMMU_API=n, eg. skiroot_defconfig:

  arch/powerpc/platforms/powernv/npu-dma.c:96:28: error: 'get_gpu_pci_dev_and_pe' defined but not used
  arch/powerpc/platforms/powernv/npu-dma.c:126:13: error: 'pnv_npu_set_window' defined but not used

Fixes: b4d37a7b6934 ("powerpc/powernv: Remove unused pnv_npu_try_dma_set_bypass() function")
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit 79cb6879135b7441f0955ca3f86be8c8d21c7199)

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1805101
Signed-off-by: Michael Roth <mroth@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>