[char] tpm: eventlog: Replace zero-length array with flexible-array member
Message-id: <20201118173033.49741-4-jsnitsel@redhat.com>
Patchwork-id: 339987
Patchwork-instance: patchwork
O-Subject: [RHEL8.4.0 PATCH 03/16] tpm: eventlog: Replace zero-length array with flexible-array member
Bugzilla: 1887536 1855183
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: 1887536
Bugzilla: 1855183
Upstream Status: ab91c2a89f86be2898cee208d492816ec238b2cf
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33134445

commit ab91c2a89f86be2898cee208d492816ec238b2cf
Author: Gustavo A. R. Silva <gustavo@embeddedor.com>
Date:   Fri May 8 11:38:26 2020 -0500

    tpm: eventlog: Replace zero-length array with flexible-array member

    The current codebase makes use of the zero-length array language
    extension to the C90 standard, but the preferred mechanism to declare
    variable-length types such as these ones is a flexible array member[1][2],
    introduced in C99:

    struct foo {
	    int stuff;
	    struct boo array[];
    };

    By making use of the mechanism above, we will get a compiler warning
    in case the flexible array does not occur last in the structure, which
    will help us prevent some kind of undefined behavior bugs from being
    inadvertently introduced[3] to the codebase from now on.

    Also, notice that, dynamic memory allocations won't be affected by
    this change:

    "Flexible array members have incomplete type, and so the sizeof operator
    may not be applied. As a quirk of the original implementation of
    zero-length arrays, sizeof evaluates to zero."[1]

    sizeof(flexible-array-member) triggers a warning because flexible array
    members have incomplete type[1]. There are some instances of code in
    which the sizeof operator is being incorrectly/erroneously applied to
    zero-length arrays and the result is zero. Such instances may be hiding
    some bugs. So, this work (flexible-array member conversions) will also
    help to get completely rid of those sorts of issues.

    Also, the following issue shows up due to the flexible-array member
    having incomplete type[4]:

    drivers/char/tpm/eventlog/tpm2.c: In function ‘tpm2_bios_measurements_start’:
    drivers/char/tpm/eventlog/tpm2.c:54:46: error: invalid application of ‘sizeof’ to incomplete type ‘u8[]’ {aka ‘unsigned char[]’}
       54 |  size = sizeof(struct tcg_pcr_event) - sizeof(event_header->event)
	  |                                              ^
    drivers/char/tpm/eventlog/tpm2.c: In function ‘tpm2_bios_measurements_next’:
    drivers/char/tpm/eventlog/tpm2.c:102:10: error: invalid application of ‘sizeof’ to incomplete type ‘u8[]’ {aka ‘unsigned char[]’}
      102 |    sizeof(event_header->event) + event_header->event_size;
	  |          ^
    drivers/char/tpm/eventlog/tpm2.c: In function ‘tpm2_binary_bios_measurements_show’:
    drivers/char/tpm/eventlog/tpm2.c:140:10: error: invalid application of ‘sizeof’ to incomplete type ‘u8[]’ {aka ‘unsigned char[]’}
      140 |    sizeof(event_header->event) + event_header->event_size;
	  |          ^
    scripts/Makefile.build:266: recipe for target 'drivers/char/tpm/eventlog/tpm2.o' failed
    make[3]: *** [drivers/char/tpm/eventlog/tpm2.o] Error 1

    As mentioned above: "Flexible array members have incomplete type, and
    so the sizeof operator may not be applied. As a quirk of the original
    implementation of zero-length arrays, sizeof evaluates to zero."[1] As
    in "sizeof(event_header->event) always evaluated to 0, so removing it
    has no effect".

    Lastly, make use of the struct_size() helper to deal with the
    flexible array member and its host structure.

    This issue was found with the help of Coccinelle.

    [1] https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html
    [2] https://github.com/KSPP/linux/issues/21
    [3] commit 76497732932f ("cxgb3/l2t: Fix undefined behaviour")
    [4] https://github.com/KSPP/linux/issues/43

    Signed-off-by: Gustavo A. R. Silva <gustavo@embeddedor.com>
    Reviewed-by: Kees Cook <keescook@chromium.org>
    Reviewed-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
    Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>

(cherry picked from commit ab91c2a89f86be2898cee208d492816ec238b2cf)
Cc: John Linville <linville@redhat.com>
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>