[tools] perf parse: Fix potential memory leak when handling tracepoint errors
Message-id: <20200514101858.720-249-mpetlan@redhat.com>
Patchwork-id: 307811
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 248/300] perf parse: Fix potential memory leak when handling tracepoint errors
Bugzilla: 1818838
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1818838
https://bugzilla.redhat.com/show_bug.cgi?id=1818838

upstream
========
commit 4584f084aa9d8033d5911935837dbee7b082d0e9
Author: Ian Rogers <irogers@google.com>
Date: Wed Nov 20 10:09:25 2019 -0800

description
===========
An error may be in place when tracepoint_error is called, use
parse_events__handle_error to avoid a memory leak and to capture the
first and last error. Error detected by LLVM's libFuzzer using the
following event:

$ perf stat -e 'msr/event/,f:e'
event syntax error: 'msr/event/,f:e'
                     \___ can't access trace events

Error:  No permissions to read /sys/kernel/debug/tracing/events/f/e
Hint:   Try 'sudo mount -o remount,mode=755 /sys/kernel/debug/tracing/'

Initial error:
event syntax error: 'msr/event/,f:e'
                                \___ no value assigned for term
Run 'perf list' for a list of valid events

 Usage: perf stat [<options>] [<command>]

    -e, --event <event>   event selector. use 'perf list' to list available events

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>