powerpc/pseries/eeh: Make pseries_pcibios_bus_add_device() static
Bugzilla: http://bugzilla.redhat.com/1924090
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37569338

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/

commit 44159329e0ad160af7cc7e84fa6d97531c8ed78f
Author: Cédric Le Goater <clg@kaod.org>
Date:   Mon Jan 4 15:31:46 2021 +0100

    powerpc/pseries/eeh: Make pseries_pcibios_bus_add_device() static

    pseries_pcibios_bus_add_device() is a local routine defining the
    pcibios_bus_add_device() handler of the pseries machine in
    eeh_pseries_init(). It doesn't need to be external.

    It fixes this W=1 compile error:

    ../arch/powerpc/platforms/pseries/eeh_pseries.c:46:6: error: no previous prototype for ‘pseries_pcibios_bus_add_device’ [-Werror=missing-prototypes]
       46 | void pseries_pcibios_bus_add_device(struct pci_dev *pdev)
          |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Fixes: dae7253f9f78 ("powerpc/pseries: Add pseries SR-IOV Machine dependent calls")
    Signed-off-by: Cédric Le Goater <clg@kaod.org>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20210104143206.695198-4-clg@kaod.org
    Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>

Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>