[nvdimm] libnvdimm/region: Fix build error
Message-id: <20200526194714.16297-1-didoming@redhat.com>
Patchwork-id: 314424
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH BZ1779218 6/5] libnvdimm/region: Fix build error
Bugzilla: 1779218
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1779218
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28739413

On CONFIG_PPC32=y build fails:

drivers/nvdimm/region_devs.c:1034:14: note: in expansion of macro ‘do_div’
  remainder = do_div(per_mapping, mappings);
              ^~~~~~
In file included from ./arch/powerpc/include/generated/asm/div64.h:1:0,
                 from ./include/linux/kernel.h:18,
                 from ./include/asm-generic/bug.h:19,
                 from ./arch/powerpc/include/asm/bug.h:109,
                 from ./include/linux/bug.h:5,
                 from ./include/linux/scatterlist.h:7,
                 from drivers/nvdimm/region_devs.c:5:
./include/asm-generic/div64.h:243:22: error: passing argument 1 of ‘__div64_32’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   __rem = __div64_32(&(n), __base); \

Use div_u64 instead of do_div to fix this.

commit 04ff4863e1261187ef6152d2cf1f9a20e9b4cc04

Fixes: 2522afb86a8c ("libnvdimm/region: Introduce an 'align' attribute")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Link: https://lore.kernel.org/r/20200331115024.31628-1-yuehaibing@huawei.com
Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>