[net] sched: Remove TCA_OPTIONS from policy
Message-id: <09972d1687c30bf5ea2d9da35e46354b64318393.1544623655.git.dcaratti@redhat.com>
Patchwork-id: 235214
O-Subject: [RHEL8.0 net 5/5] net: sched: Remove TCA_OPTIONS from policy
Bugzilla: 1658516
RH-Acked-by: David S. Miller <davem@redhat.com>
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1658516
Upstream Status: net.git commit e72bde6b6629

commit e72bde6b66299602087c8c2350d36a525e75d06e
Author: David Ahern <dsahern@gmail.com>
Date:   Wed Oct 24 08:32:49 2018 -0700

    net: sched: Remove TCA_OPTIONS from policy

    Marco reported an error with hfsc:
    root@Calimero:~# tc qdisc add dev eth0 root handle 1:0 hfsc default 1
    Error: Attribute failed policy validation.

    Apparently a few implementations pass TCA_OPTIONS as a binary instead
    of nested attribute, so drop TCA_OPTIONS from the policy.

    Fixes: 8b4c3cdd9dd8 ("net: sched: Add policy validation for tc attributes")
    Reported-by: Marco Berizzi <pupilla@libero.it>
    Signed-off-by: David Ahern <dsahern@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Davide Caratti <dcaratti@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>