[tools] bpf: pull in pkt_sched.h header for tooling to fix bpftool build
Message-id: <20190604085256.3304-568-yauheni.kaliuta@redhat.com>
Patchwork-id: 262568
O-Subject: [RHEL8.1 PATCH v2 568/627] bpf: pull in pkt_sched.h header for tooling to fix bpftool build
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit ad6dd7a9c47ba587c0aba57f73737764cd31136f
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Thu Jan 17 16:15:09 2019 +0100

    bpf: pull in pkt_sched.h header for tooling to fix bpftool build

    Dan reported that bpftool does not compile for him:

      $ make tools/bpf
        DESCEND  bpf

      Auto-detecting system features:
      ..                        libbfd: [ on  ]
      ..        disassembler-four-args: [ OFF ]

        DESCEND  bpftool

      Auto-detecting system features:
      ..                        libbfd: [ on  ]
      ..        disassembler-four-args: [ OFF ]

        CC       /opt/linux.git/tools/bpf/bpftool/net.o
      In file included from /opt/linux.git/tools/include/uapi/linux/pkt_cls.h:6:0,
                     from /opt/linux.git/tools/include/uapi/linux/tc_act/tc_bpf.h:14,
                     from net.c:13:
      net.c: In function 'show_dev_tc_bpf':
      net.c:164:21: error: 'TC_H_CLSACT' undeclared (first use in this function)
        handle = TC_H_MAKE(TC_H_CLSACT, TC_H_MIN_INGRESS);
      [...]

    Fix it by importing pkt_sched.h header copy into tooling
    infrastructure.

    Fixes: 49a249c38726 ("tools/bpftool: copy a few net uapi headers to tools directory")
    Fixes: f6f3bac08ff9 ("tools/bpf: bpftool: add net support")
    Reported-by: Dan Gilson <dan_gilson@yahoo.com>
    Reference: https://bugzilla.kernel.org/show_bug.cgi?id=202315
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Martin KaFai Lau <kafai@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>