[net] ovs: datapath: hide clang frame-overflow warnings
Message-id: <160405997971.139758.6099593249468581713.stgit@nst.lab.eng.brq.redhat.com>
Patchwork-id: 336376
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net PATCH 02/18] ovs: datapath: hide clang frame-overflow warnings
Bugzilla: 1888576
RH-Acked-by: Flavio Leitner <fbl@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1888576
Upstream Status: Backport net-next.git commit 260637903f47
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=32463682
Tested: Manually tested using the fave-ovn-multinode setup.
        LNST Test: https://platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/LNST-BREW-job/283/
        ENRT Test: https://beaker.engineering.redhat.com/jobs/4676329
        CKI  Test: https://beaker.engineering.redhat.com/jobs/?jobsearch-0.table=Whiteboard&jobsearch-0.operation=contains&jobsearch-0.value=cki%40gitlab%3A616086
        LNST OVS : https://beaker.engineering.redhat.com/jobs/4689904
                   https://beaker.engineering.redhat.com/jobs/4690934

Backport of upstream commit:

commit 260637903f47f20c5918bb5c1eea52b2a28ea863
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 22 17:00:01 2019 +0200

    ovs: datapath: hide clang frame-overflow warnings

    Some functions in the datapath code are factored out so that each
    one has a stack frame smaller than 1024 bytes with gcc. However,
    when compiling with clang, the functions are inlined more aggressively
    and combined again so we get

    net/openvswitch/datapath.c:1124:12: error: stack frame size of 1528 bytes in function 'ovs_flow_cmd_set' [-Werror,-Wframe-larger-than=]

    Marking both get_flow_actions() and ovs_nla_init_match_and_action()
    as 'noinline_for_stack' gives us the same behavior that we see with
    gcc, and no warning. Note that this does not mean we actually use
    less stack, as the functions call each other, and we still get
    three copies of the large 'struct sw_flow_key' type on the stack.

    The comment tells us that this was previously considered safe,
    presumably since the netlink parsing functions are called with
    a known backchain that does not also use a lot of stack space.

    Fixes: 9cc9a5cb176c ("datapath: Avoid using stack larger than 1024.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Eelco Chaudron <echaudro@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>