[fs] smb3: remove static checker warning
Message-id: <20201203054653.24822-49-lsahlber@redhat.com>
Patchwork-id: 342893
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 FS BZ 1903883 48/85] smb3: remove static checker warning
Bugzilla: 1903883
RH-Acked-by: Steve Dickson <SteveD@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>

From: Steve French <stfrench@microsoft.com>

Bugzilla: 1903883
Build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33455430

Remove static checker warning pointed out by Dan Carpenter:

The patch feeaec621c09: "cifs: multichannel: move channel selection
above transport layer" from Apr 24, 2020, leads to the following
static checker warning:

        fs/cifs/smb2pdu.c:149 smb2_hdr_assemble()
        error: we previously assumed 'tcon->ses' could be null (see line 133)

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
CC: Aurelien Aptel <aptel@suse.com>
Signed-off-by: Steve French <stfrench@microsoft.com>
(cherry picked from commit edb161353680e6d488d94cbcaf967745bee98d17)
Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>