[tools] tools build: Fix the zstd test in the test-all.c common case feature test
Message-id: <20191126133941.32492-187-mpetlan@redhat.com>
Patchwork-id: 289306
O-Subject: [RHEL8.2 BZ1743210 v2 186/327] tools build: Fix the zstd test in the test-all.c common case feature test
Bugzilla: 1743210
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1743210
https://bugzilla.redhat.com/show_bug.cgi?id=1743210

upstream
========
commit 3469fa84c1631face938efc42b3f488a2c2504e0
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Tue Jun 18 17:59:16 2019 -0300

description
===========
We were renanimg 'main' to 'main_zstd' but then using 'main_libzstd();'
in the main() for test-all.c, causing this:

  $ cat /tmp/build/perf/feature/test-all.make.output
  test-all.c: In function main:
  test-all.c:236:2: error: implicit declaration of function main_test_libzstd; did you mean main_test_zstd? [-Werror=implicit-function-declaration]
    main_test_libzstd();
    ^~~~~~~~~~~~~~~~~
    main_test_zstd
  cc1: all warnings being treated as errors
  $

I.e. what was supposed to be the fast path feature test was _always_
failing, duh, fix it.

Fixes: 3b1c5d965971 ("tools build: Implement libzstd feature check, LIBZSTD_DIR and NO_LIBZSTD defines")
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>