bpftool: Fix compilation failure for net.o with older glibc
Bugzilla: http://bugzilla.redhat.com/1874007

commit 6f02b540d7597f357bc6ee711346761045d4e108
Author: Alan Maguire <alan.maguire@oracle.com>
Date:   Wed Jan 6 15:59:06 2021 +0000

    bpftool: Fix compilation failure for net.o with older glibc

    For older glibc ~2.17, #include'ing both linux/if.h and net/if.h
    fails due to complaints about redefinition of interface flags:

      CC       net.o
    In file included from net.c:13:0:
    /usr/include/linux/if.h:71:2: error: redeclaration of enumerator ‘IFF_UP’
      IFF_UP    = 1<<0,  /* sysfs */
      ^
    /usr/include/net/if.h:44:5: note: previous definition of ‘IFF_UP’ was here
         IFF_UP = 0x1,  /* Interface is up.  */

    The issue was fixed in kernel headers in [1], but since compilation
    of net.c picks up system headers the problem can recur.

    Dropping #include <linux/if.h> resolves the issue and it is
    not needed for compilation anyhow.

    [1] https://lore.kernel.org/netdev/1461512707-23058-1-git-send-email-mikko.rapeli__34748.27880641$1462831734$gmane$org@iki.fi/

    Fixes: f6f3bac08ff9 ("tools/bpf: bpftool: add net support")
    Signed-off-by: Alan Maguire <alan.maguire@oracle.com>
    Signed-off-by: Andrii Nakryiko <andrii@kernel.org>
    Acked-by: Martin KaFai Lau <kafai@fb.com>
    Link: https://lore.kernel.org/bpf/1609948746-15369-1-git-send-email-alan.maguire@oracle.com

Signed-off-by: Jiri Olsa <jolsa@redhat.com>