[net] bpf: avoid unused variable warning in tcp_bpf_rtt()
Message-id: <187aca2fdb8252c82f7d606ee1cf9f743204d62b.1573822046.git.jbenc@redhat.com>
Patchwork-id: 287453
O-Subject: [RHEL8.2 net 58/77] bpf: avoid unused variable warning in tcp_bpf_rtt()
Bugzilla: 1749817
RH-Acked-by: Matteo Croce <mcroce@redhat.com>
RH-Acked-by: Eelco Chaudron <echaudro@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1749817

commit bef8e2639242e7f7214f1ab3b37ace1415a4f750
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 8 14:57:21 2019 +0200

    bpf: avoid unused variable warning in tcp_bpf_rtt()

    When CONFIG_BPF is disabled, we get a warning for an unused
    variable:

    In file included from drivers/target/target_core_device.c:26:
    include/net/tcp.h:2226:19: error: unused variable 'tp' [-Werror,-Wunused-variable]
            struct tcp_sock *tp = tcp_sk(sk);

    The variable is only used in one place, so it can be
    replaced with its value there to avoid the warning.

    Fixes: 23729ff23186 ("bpf: add BPF_CGROUP_SOCK_OPS callback that is executed on every RTT")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Soheil Hassas Yeganeh <soheil@google.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>