[usb] usb: typec: tps6598x: Fix build error without CONFIG_REGMAP_I2C
Message-id: <20201216155447.212357-196-torez@redhat.com>
Patchwork-id: 345340
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 1900751 0195/1059] usb: typec: tps6598x: Fix build error without CONFIG_REGMAP_I2C
Bugzilla: 1900751 1856683 1838295 1837563 1783493
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1900751
Bugzilla: https://bugzilla.redhat.com/1837563
Bugzilla: https://bugzilla.redhat.com/1856683
Bugzilla: https://bugzilla.redhat.com/1853229
Bugzilla: https://bugzilla.redhat.com/1838295
Bugzilla: https://bugzilla.redhat.com/1836895
Bugzilla: https://bugzilla.redhat.com/1798825
Bugzilla: https://bugzilla.redhat.com/1789257
Bugzilla: https://bugzilla.redhat.com/1783493

Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33777895
Upstream Status: 35af2445dc306403254a181507b390ec9eb725d5

Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit 35af2445dc306403254a181507b390ec9eb725d5
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Tue Sep 3 20:10:26 2019 +0800

usb: typec: tps6598x: Fix build error without CONFIG_REGMAP_I2C

If CONFIG_REGMAP_I2C is not set, building fails:

drivers/usb/typec/tps6598x.o: In function `tps6598x_probe':
tps6598x.c:(.text+0x5f0): undefined reference to `__devm_regmap_init_i2c'

Select REGMAP_I2C to fix this.

Reported-by: Hulk Robot <hulkci@huawei.com>
Fixes: 0a4c005bd171 ("usb: typec: driver for TI TPS6598x USB Power Delivery controllers")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Acked-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Link: https://lore.kernel.org/r/20190903121026.22148-1-yuehaibing@huawei.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>