[tools] bpf_helpers.h: Add note for building with vmlinux.h or linux/types.h
Message-id: <20200924164430.191293-6-yauheni.kaliuta@redhat.com>
Patchwork-id: 327853
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 006/243] bpf_helpers.h: Add note for building with vmlinux.h or linux/types.h
Bugzilla: 1874003
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874003

commit ae460c022453337850bdc36a36bf7596a6cfcf99
Author: Yoshiki Komachi <komachi.yoshiki@gmail.com>
Date:   Tue Apr 21 09:05:27 2020 +0900

    bpf_helpers.h: Add note for building with vmlinux.h or linux/types.h

    The following error was shown when a bpf program was compiled without
    vmlinux.h auto-generated from BTF:

     # clang -I./linux/tools/lib/ -I/lib/modules/$(uname -r)/build/include/ \
       -O2 -Wall -target bpf -emit-llvm -c bpf_prog.c -o bpf_prog.bc
     ...
     In file included from linux/tools/lib/bpf/bpf_helpers.h:5:
     linux/tools/lib/bpf/bpf_helper_defs.h:56:82: error: unknown type name '__u64'
     ...

    It seems that bpf programs are intended for being built together with
    the vmlinux.h (which will have all the __u64 and other typedefs). But
    users may mistakenly think "include <linux/types.h>" is missing
    because the vmlinux.h is not common for non-bpf developers. IMO, an
    explicit comment therefore should be added to bpf_helpers.h as this
    patch shows.

    Signed-off-by: Yoshiki Komachi <komachi.yoshiki@gmail.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Link: https://lore.kernel.org/bpf/1587427527-29399-1-git-send-email-komachi.yoshiki@gmail.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>