[netdrv] phy: marvell: Fix build
Message-id: <45bb19f91ab4899b7f0fd20ec8bedd6554e45d96.1573676613.git.poros@redhat.com>
Patchwork-id: 286349
O-Subject: [RHEL8.2 PATCH 053/320] net: phy: marvell: Fix build.
Bugzilla: 1772010
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1772010

Upstream commit(s):
commit 4b1bd69769454175268908f50b32f1cbfee5bb83
Author: David S. Miller <davem@davemloft.net>
Date:   Tue Sep 25 22:41:31 2018 -0700

    net: phy: marvell: Fix build.

    Local variable 'autoneg' doesn't even exist:

    drivers/net/phy/marvell.c: In function 'm88e1121_config_aneg':
    drivers/net/phy/marvell.c:468:25: error: 'autoneg' undeclared (first use in this function); did you mean 'put_net'?
      if (phydev->autoneg != autoneg || changed) {
                             ^~~~~~~

    Fixes: d6ab93364734 ("net: phy: marvell: Avoid unnecessary soft reset")
    Reported-by:Vakul Garg <vakul.garg@nxp.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>