[tools] bpf: fix core_reloc.c compilation error
Message-id: <20191127192852.21674-18-yauheni.kaliuta@redhat.com>
Patchwork-id: 290433
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 18/69] tools/bpf: fix core_reloc.c compilation error
Bugzilla: 1772081
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1772081

commit b707659213d3c70f2c704ec950df6263b4bffe84
Author: Yonghong Song <yhs@fb.com>
Date:   Wed Aug 7 17:38:56 2019 -0700

    tools/bpf: fix core_reloc.c compilation error

    On my local machine, I have the following compilation errors:
    =====
      In file included from prog_tests/core_reloc.c:3:0:
      ./progs/core_reloc_types.h:517:46: error: expected =, ,, ;, asm or __attribute__ before fancy_char_ptr_t
     typedef const char * const volatile restrict fancy_char_ptr_t;
                                                  ^
      ./progs/core_reloc_types.h:527:2: error: unknown type name fancy_char_ptr_t
        fancy_char_ptr_t d;
        ^
    =====

    I am using gcc 4.8.5. Later compilers may change their behavior not emitting the
    error. Nevertheless, let us fix the issue. "restrict" can be tested
    without typedef.

    Fixes: 9654e2ae908e ("selftests/bpf: add CO-RE relocs modifiers/typedef tests")
    Cc: Andrii Nakryiko <andriin@fb.com>
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>