[scsi] scsi: lpfc: Add dependency on CPU_FREQ
Message-id: <20201102183934.26793-49-dkennedy@redhat.com>
Patchwork-id: 336856
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 PATCH-v2 e-stor 48/58] scsi: lpfc: Add dependency on CPU_FREQ
Bugzilla: 1887549
RH-Acked-by: Ewan Milne <emilne@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Guenter Roeck <linux@roeck-us.net>

Since commit 317aeb83c92b ("scsi: lpfc: Add blk_io_poll support for latency
improvment"), the lpfc driver depends on CPUFREQ. Without it, builds fail
with

drivers/scsi/lpfc/lpfc_sli.c: In function 'lpfc_init_idle_stat_hb':
drivers/scsi/lpfc/lpfc_sli.c:7329:26: error:
	implicit declaration of function 'get_cpu_idle_time'

Add the missing dependency.

Link: https://lore.kernel.org/r/20200722023027.36866-1-linux@roeck-us.net
Fixes: 317aeb83c92b ("scsi: lpfc: Add blk_io_poll support for latency improvment")
Cc: Dick Kennedy <dick.kennedy@broadcom.com>
Cc: James Smart <jsmart2021@gmail.com>
Reviewed-by: James Smart <james.smart@broadcom.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit e3d2bf6505ddd4d11226dc2ad2071981564a35db)
Signed-off-by: Dick Kennedy <dkennedy@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>