[fpga] fpga: zynqmp-fpga: Correctly handle error pointer
Message-id: <20200602160015.1206517-59-lgoncalv@redhat.com>
Patchwork-id: 316129
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 BZ 1494701 V3 058/109] fpga: zynqmp-fpga: Correctly handle error pointer
Bugzilla: 1689274 1660310 1494701 1494699
RH-Acked-by: Clark Williams <williams@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Tom Rix <trix@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1494699
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1494701
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1689274
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1660310

Upstream Status: Linus tree, from v5.6.13.
Brew Build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28984697
Testing: Basic manual testing on the available HW.

commit 498ddaa3b4e72152ae42dab2d4ebe93092885422
Author: Moritz Fischer <mdf@kernel.org>
Date: Thu, 30 May 2019 09:52:59 -0500

    fpga: zynqmp-fpga: Correctly handle error pointer

    Fixes the following static checker errors:

    drivers/fpga/zynqmp-fpga.c:50 zynqmp_fpga_ops_write()
    error: 'eemi_ops' dereferencing possible ERR_PTR()

    drivers/fpga/zynqmp-fpga.c:84 zynqmp_fpga_ops_state()
    error: 'eemi_ops' dereferencing possible ERR_PTR()

    Note: This does not handle the EPROBE_DEFER value in a
          special manner.

    Fixes commit c09f7471127e ("fpga manager: Adding FPGA Manager support for
    Xilinx zynqmp")
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Moritz Fischer <mdf@kernel.org>
    Acked-by: Alan Tull <atull@kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Luis Claudio R. Goncalves <lgoncalv@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>