[fs] nfsd: avoid uninitialized variable warning
Message-id: <4589a40c4d6a7ff09873399bc63e3a5a0805d54a.1591958517.git.bcodding@redhat.com>
Patchwork-id: 320088
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 fs PATCH 01/52] nfsd: avoid uninitialized variable warning
Bugzilla: 1831672
RH-Acked-by: Scott Mayhew <smayhew@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1831672

commit 0ab88ca4bcf18ba21058d8f19220f60afe0d34d8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Mar 22 15:07:11 2019 +0100

    nfsd: avoid uninitialized variable warning

    clang warns that 'contextlen' may be accessed without an initialization:

    fs/nfsd/nfs4xdr.c:2911:9: error: variable 'contextlen' is uninitialized when used here [-Werror,-Wuninitialized]
                                                                    contextlen);
                                                                    ^~~~~~~~~~
    fs/nfsd/nfs4xdr.c:2424:16: note: initialize the variable 'contextlen' to silence this warning
            int contextlen;
                          ^
                           = 0

    Presumably this cannot happen, as FATTR4_WORD2_SECURITY_LABEL is
    set if CONFIG_NFSD_V4_SECURITY_LABEL is enabled.
    Adding another #ifdef like the other two in this function
    avoids the warning.

    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: J. Bruce Fields <bfields@redhat.com>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>