[netdrv] mlx5e: Fix compilation error in TLS code
Message-id: <20191105095158.18958-161-ahleihel@redhat.com>
Patchwork-id: 283176
O-Subject: [RHEL8.2 BZ 1724336 160/335] net/mlx5e: Fix compilation error in TLS code
Bugzilla: 1724336
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1724336
Upstream: v5.3-rc1

commit c93dfec10f1d693a897bfd0d6e3a58a5ea7edc91
Author: Tariq Toukan <tariqt@mellanox.com>
Date:   Thu Jul 11 19:39:55 2019 +0000

    net/mlx5e: Fix compilation error in TLS code

    In the cited patch below, the Kconfig flags combination of:
    CONFIG_MLX5_FPGA is not set
    CONFIG_MLX5_TLS=y
    CONFIG_MLX5_EN_TLS=y

    leads to the compilation error:

    ./include/linux/mlx5/device.h:61:39: error: invalid application of
    sizeof to incomplete type struct mlx5_ifc_tls_flow_bits.

    Fix it.

    Fixes: 90687e1a9a50 ("net/mlx5: Kconfig, Better organize compilation flags")
    Signed-off-by: Tariq Toukan <tariqt@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
    CC: Mao Wenan <maowenan@huawei.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>