[tools] bpf: fix perf build error with uClibc (seen on ARC)
Message-id: <20191018135423.24316-191-yauheni.kaliuta@redhat.com>
Patchwork-id: 280353
O-Subject: [RHEL8.2 191/268] tools/bpf: fix perf build error with uClibc (seen on ARC)
Bugzilla: 1747615
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747615

commit ca31ca8247e2d3807ff5fa1d1760616a2292001c
Author: Vineet Gupta <Vineet.Gupta1@synopsys.com>
Date:   Thu May 2 08:56:50 2019 -0700

    tools/bpf: fix perf build error with uClibc (seen on ARC)

    When build perf for ARC recently, there was a build failure due to lack
    of __NR_bpf.

    | Auto-detecting system features:
    |
    | ...                     get_cpuid: [ OFF ]
    | ...                           bpf: [ on  ]
    |
    | #  error __NR_bpf not defined. libbpf does not support your arch.
        ^~~~~
    | bpf.c: In function 'sys_bpf':
    | bpf.c:66:17: error: '__NR_bpf' undeclared (first use in this function)
    |  return syscall(__NR_bpf, cmd, attr, size);
    |                 ^~~~~~~~
    |                 sys_bpf

    Signed-off-by: Vineet Gupta <vgupta@synopsys.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>