[cpufreq] thermal: cpu_cooling: Require thermal core to be compiled in
Message-id: <20191114025436.22894-74-ahs3@redhat.com>
Patchwork-id: 286711
O-Subject: [RHEL8.2 PATCH v2 073/210] thermal: cpu_cooling: Require thermal core to be compiled in
Bugzilla: 1739729 1725581
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1725581
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1739729
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24685852
Depends: bz1739728
Upstream Status: afa1f2ab43d48d0e1fa1bda524a0cf53e4cd6c87
Tested: bz1725581, bz1739729: ran CKI KT1 tests and basic s2idle, powertop,
 as well as suspend/resume, and tuned testing.  As this is very
 difficult to test, the broader the exposure to different platforms,
 the greater the confidence; partner testing (since their firmware
 affects the behavior of cpufreq most directly) is highly recommended.
 Regardless, these changes should not cause regressions.

commit afa1f2ab43d48d0e1fa1bda524a0cf53e4cd6c87
Author: Amit Kucheria <amit.kucheria@linaro.org>
Date:   Tue Jan 29 10:25:07 2019 +0530

    thermal: cpu_cooling: Require thermal core to be compiled in

    The CPU cooling driver (cpu_cooling.c) allows the platform's cpufreq
    driver to register as a cooling device and cool down the platform by
    throttling the CPU frequency. In order to be able to auto-register a
    cpufreq driver as a cooling device from the cpufreq core, we need access
    to code inside cpu_cooling.c which, in turn, accesses code inside
    thermal core.

    CPU_FREQ is a bool while THERMAL is tristate.  In some configurations
    (e.g. allmodconfig), CONFIG_THERMAL ends up as a module while
    CONFIG_CPU_FREQ is compiled in. This leads to following error:

    drivers/cpufreq/cpufreq.o: In function `cpufreq_offline':
    cpufreq.c:(.text+0x407c): undefined reference to `cpufreq_cooling_unregister'
    drivers/cpufreq/cpufreq.o: In function `cpufreq_online':
    cpufreq.c:(.text+0x70c0): undefined reference to `of_cpufreq_cooling_register'

    Given that platforms using CPU_THERMAL usually want it compiled-in so it
    is available early in boot, make CPU_THERMAL depend on THERMAL being
    compiled-in instead of allowing it to be a module.

    As a result of this change, get rid of the ugly (!CPU_THERMAL ||
    THERMAL) dependency in all cpufreq drivers using CPU_THERMAL.

    Suggested-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
    Signed-off-by: Amit Kucheria <amit.kucheria@linaro.org>
    Acked-by: Viresh Kumar <viresh.kumar@linaro.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
    (cherry picked from commit afa1f2ab43d48d0e1fa1bda524a0cf53e4cd6c87)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>