[netdrv] hinic: Fix l4_type parameter in hinic_task_set_tunnel_l4
Message-id: <1543417306-29041-3-git-send-email-txiaojun@redhat.com>
Patchwork-id: 233858
O-Subject: [RHEL8.0 BZ 1654207 2/7] hinic: Fix l4_type parameter in hinic_task_set_tunnel_l4
Bugzilla: 1654207
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: David S. Miller <davem@redhat.com>

From: Nathan Chancellor <natechancellor@gmail.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1654207
Build-Info: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=19278806
git repo: https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git
commit 6e29464b8a72e74ec7c3f816f53bfe46a43601bc

Clang warns:

drivers/net/ethernet/huawei/hinic/hinic_tx.c:392:34: error: implicit
conversion from enumeration type 'enum hinic_l4_tunnel_type' to
different enumeration type 'enum hinic_l4_offload_type'
[-Werror,-Wenum-conversion]
                hinic_task_set_tunnel_l4(task, TUNNEL_UDP_NO_CSUM,
                ~~~~~~~~~~~~~~~~~~~~~~~~       ^~~~~~~~~~~~~~~~~~
1 error generated.

It seems that hinic_task_set_tunnel_l4 was meant to take an enum of type
hinic_l4_tunnel_type, not hinic_l4_offload_type, given both the name of
the functions and the values used.

Fixes: cc18a7543d2f ("net-next/hinic: add checksum offload and TSO support")
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Xiaojun Tan <txiaojun@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>