mm: remove src/dst mm parameter in copy_page_range()
Conflicts: mm/memory.c - on ppc64le we get an unused variable error
	mm/memory.c: In function ‘copy_p4d_range’:
	mm/memory.c:1086:20: error: unused variable ‘dst_mm’ [-Werror=unused-variable]
  	struct mm_struct *dst_mm = dst_vma->vm_mm;
                    	^~~~~~
	so add __maybe_unused to the declaration of dst_mm

Bugzilla: http://bugzilla.redhat.com/1945442
Upstream status: linux

Both of the mm pointers are not needed after commit 7a4830c380f3
("mm/fork: Pass new vma pointer into copy_page_range()").

Jason Gunthorpe also reported that the ordering of copy_page_range() is
odd.  Since working at it, reorder the parameters to be logical, by (1)
always put the dst_* fields to be before src_* fields, and (2) keep the
same type of parameters together.

[peterx@redhat.com: further reorder some parameters and line format, per Jason]
  Link: https://lkml.kernel.org/r/20201002192647.7161-1-peterx@redhat.com
[peterx@redhat.com: fix warnings]
  Link: https://lkml.kernel.org/r/20201006200138.GA6026@xz-x1

Reported-by: Kirill A. Shutemov <kirill@shutemov.name>
Signed-off-by: Peter Xu <peterx@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Reviewed-by: Jason Gunthorpe <jgg@nvidia.com>
Acked-by: Kirill A. Shutemov <kirill.shutemov@linux.intel.com>
Link: https://lkml.kernel.org/r/20200930204950.6668-1-peterx@redhat.com
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit c78f463649d60f4ed12df97a32def4d77b583853)
Signed-off-by: Chris von Recklinghausen <crecklin@redhat.com>