[netdrv] phy: mdio-bcm-unimac: mark PM functions as __maybe_unused
Message-id: <224da02e5c0df3c7be1245ea46fddb566b26777c.1573676613.git.poros@redhat.com>
Patchwork-id: 286350
O-Subject: [RHEL8.2 PATCH 054/320] net: phy: mdio-bcm-unimac: mark PM functions as __maybe_unused
Bugzilla: 1772010
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1772010

Upstream commit(s):
commit 9b97123a584f60a5bca5a2663485768a1f6cd0a4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 26 15:14:10 2018 +0200

    net: phy: mdio-bcm-unimac: mark PM functions as __maybe_unused

    The newly added runtime-pm support causes a harmless warning
    when CONFIG_PM is disabled:

    drivers/net/phy/mdio-bcm-unimac.c:330:12: error: 'unimac_mdio_resume' defined but not used [-Werror=unused-function]
     static int unimac_mdio_resume(struct device *d)
    drivers/net/phy/mdio-bcm-unimac.c:321:12: error: 'unimac_mdio_suspend' defined but not used [-Werror=unused-function]
     static int unimac_mdio_suspend(struct device *d)

    Marking the functions as __maybe_unused is the easiest workaround
    and avoids adding #ifdef checks.

    Fixes: b78ac6ecd1b6 ("net: phy: mdio-bcm-unimac: Allow configuring MDIO clock divider")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>