[wireless] brcmfmac: Fix use after free in brcmf_sdio_readframes()
Message-id: <20200413203652.3431-463-jarod@redhat.com>
Patchwork-id: 301792
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 462/615] brcmfmac: Fix use after free in brcmf_sdio_readframes()
Bugzilla: 1807052
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1807052

commit 216b44000ada87a63891a8214c347e05a4aea8fe
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Tue Dec 3 12:58:55 2019 +0300

    brcmfmac: Fix use after free in brcmf_sdio_readframes()

    The brcmu_pkt_buf_free_skb() function frees "pkt" so it leads to a
    static checker warning:

        drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:1974 brcmf_sdio_readframes()
        error: dereferencing freed memory 'pkt'

    It looks like there was supposed to be a continue after we free "pkt".

    Fixes: 4754fceeb9a6 ("brcmfmac: streamline SDIO read frame routine")
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Acked-by: Franky Lin <franky.lin@broadcom.com>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>