[infiniband] rdma/siw: Add missing dependencies on LIBCRC32C and DMA_VIRT_OPS
Message-id: <20191029153151.25029-162-kheib@redhat.com>
Patchwork-id: 281607
O-Subject: [RHEL-8.2 PATCH 161/173] rdma/siw: Add missing dependencies on LIBCRC32C and DMA_VIRT_OPS
Bugzilla: 1725830 1720892
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Honggang Li <honli@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1720892
Bugzilla: http://bugzilla.redhat.com/1725830

commit b45305d777f2f9209dae5a3b8249ca03166a4df3
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Wed Jul 10 15:39:30 2019 +0200

    rdma/siw: Add missing dependencies on LIBCRC32C and DMA_VIRT_OPS

    If LIBCRC32C and DMA_VIRT_OPS are not enabled:

        drivers/infiniband/sw/siw/siw_main.o: In function `siw_newlink':
        siw_main.c:(.text+0x35c): undefined reference to `dma_virt_ops'
        drivers/infiniband/sw/siw/siw_qp_rx.o: In function `siw_csum_update':
        siw_qp_rx.c:(.text+0x16): undefined reference to `crc32c'

    Fix the first issue by adding a select of DMA_VIRT_OPS.  Fix the second
    issue by replacing the unneeded dependency on CRYPTO_CRC32 by a dependency
    on LIBCRC32C.

    Reported-by: noreply@ellerman.id.au (first issue)
    Fixes: c0cf5bdde46c ("rdma/siw: addition to kernel build environment")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Reviewed-by: Jason Gunthorpe <jgg@mellanox.com>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Kamal Heib <kheib@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>