[tools] tools: bpftool: fix crash with un-owned prog arrays
Message-id: <20190604085256.3304-535-yauheni.kaliuta@redhat.com>
Patchwork-id: 262539
O-Subject: [RHEL8.1 PATCH v2 535/627] tools: bpftool: fix crash with un-owned prog arrays
Bugzilla: 1700846
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1700846

commit 8c79b35693380d856dcbbc21629682a90f26ca62
Author: Jakub Kicinski <jakub.kicinski@netronome.com>
Date:   Mon Jan 28 10:01:21 2019 -0800

    tools: bpftool: fix crash with un-owned prog arrays

    Prog arrays don't have 'owner_prog_type' and 'owner_jited'
    fields in their fdinfo when they are created.  Those fields
    are set and reported when first program is checked for
    compatibility by bpf_prog_array_compatible().

    This means that bpftool cannot expect the fields to always
    be there.  Currently trying to show maps on a system with
    an un-owned prog array leads to a crash:

    $ bpftool map show
    389: prog_array  name tail_call_map  flags 0x0
    Error: key 'owner_prog_type' not found in fdinfo
    Error: key 'owner_jited' not found in fdinfo
           key 4B  value 4B  max_entries 4  memlock 4096B
           Segmentation fault (core dumped)

    We pass a NULL pointer to atoi().

    Remove the assumption that fdinfo keys are always present.
    Add missing validations and remove the p_err() calls which
    may lead to broken JSON output as caller will not propagate
    the failure.

    Fixes: 99a44bef5870 ("tools: bpftool: add owner_prog_type and owner_jited to bpftool output")
    Signed-off-by: Jakub Kicinski <jakub.kicinski@netronome.com>
    Reviewed-by: Quentin Monnet <quentin.monnet@netronome.com>
    Acked-by: Song Liu <songliubraving@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>