[powerpc] eeh: Fix build with STACKTRACE=n
Message-id: <20191122141408.20843-13-gduarte@redhat.com>
Patchwork-id: 287909
O-Subject: [RHEL8.2 PATCH BZ 1524642 12/18] powerpc/eeh: Fix build with STACKTRACE=n
Bugzilla: 1524642
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

BZ 1524642
Upstream Status: 1b7f3b6c43675ef2cfb9d8f48bde057794820f7c

commit 1b7f3b6c43675ef2cfb9d8f48bde057794820f7c
Author: Michael Ellerman <mpe@ellerman.id.au>
Date:   Fri Sep 13 23:32:13 2019 +1000

    powerpc/eeh: Fix build with STACKTRACE=n

    The build breaks when STACKTRACE=n, eg. skiroot_defconfig:

      arch/powerpc/kernel/eeh_event.c:124:23: error: implicit declaration of function 'stack_trace_save'

    Fix it with some ifdefs for now.

    Fixes: 25baf3d81614 ("powerpc/eeh: Defer printing stack trace")
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>