[usb] usb: mtu3: fix EXTCON dependency
Message-id: <20200407161320.17414-642-torez@redhat.com>
Patchwork-id: 300378
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH BZ1686205 641/983] usb: mtu3: fix EXTCON dependency
Bugzilla: 1686205
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1686205
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27787109
Testing: HP ZBook 15 G3/80D5

commit 3d54d10c6afed34fd45b852bf76f55e8da31d8ef
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 25 14:54:30 2019 +0100

    usb: mtu3: fix EXTCON dependency

    When EXTCON is a loadable module, mtu3 fails to link as built-in:

    drivers/usb/mtu3/mtu3_plat.o: In function `mtu3_probe':
    mtu3_plat.c:(.text+0x690): undefined reference to `extcon_get_edev_by_phandle'

    Add a Kconfig dependency to force mtu3 also to be a loadable module
    if extconn is, but still allow it to be built without extcon.

    Fixes: d0ed062a8b75 ("usb: mtu3: dual-role mode support")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: stable <stable@vger.kernel.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>