[infiniband] IB/mlx5: Use div64_u64 for num_var_hw_entries calculation
Message-id: <20200512105530.4207-55-ahleihel@redhat.com>
Patchwork-id: 306926
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1789382 054/124] IB/mlx5: Use div64_u64 for num_var_hw_entries calculation
Bugzilla: 1789382
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1789382
Upstream: v5.6-rc2

commit 685eff513183d6d64a5f413531e683d23b8b198b
Author: Jason Gunthorpe <jgg@mellanox.com>
Date:   Thu Feb 6 10:27:54 2020 -0400

    IB/mlx5: Use div64_u64 for num_var_hw_entries calculation

    On i386:

    ERROR: "__udivdi3" [drivers/infiniband/hw/mlx5/mlx5_ib.ko] undefined!
    ERROR: "__divdi3" [drivers/infiniband/hw/mlx5/mlx5_ib.ko] undefined!

    Fixes: f164be8c0366 ("IB/mlx5: Extend caps stage to handle VAR capabilities")
    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Reported-by: Alexander Lobakin <alobakin@dlink.ru>
    Signed-off-by: Jason Gunthorpe <jgg@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>