[tools] tools/bpf: add const qualifier to btf__get_map_kv_tids() map_name parameter
Message-id: <20190925141552.30691-73-yauheni.kaliuta@redhat.com>
Patchwork-id: 274599
O-Subject: [RHEL8.2 PATCH v2 073/214] tools/bpf: add const qualifier to btf__get_map_kv_tids() map_name parameter
Bugzilla: 1747341
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Hangbin Liu <haliu@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747341

commit a6c109a6b746509f5030d20d57b35e566cf3a04f
Author: Yonghong Song <yhs@fb.com>
Date:   Tue Feb 5 11:48:22 2019 -0800

    tools/bpf: add const qualifier to btf__get_map_kv_tids() map_name parameter

    Commit 96408c43447a ("tools/bpf: implement libbpf btf__get_map_kv_tids() API function")
    added the API function btf__get_map_kv_tids():
      btf__get_map_kv_tids(const struct btf *btf, char *map_name, ...)

    The parameter map_name has type "char *". This is okay inside libbpf library since
    the map_name is from bpf_map->name which also has type "char *".

    This will be problematic if the caller for map_name already has attribute "const",
    e.g., from C++ string.c_str(). It will result in either a warning or an error.

      /home/yhs/work/bcc/src/cc/btf.cc:166:51:
        error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
          return btf__get_map_kv_tids(btf_, map_name.c_str()

    This patch added "const" attributes to map_name parameter.

    Fixes: 96408c43447a ("tools/bpf: implement libbpf btf__get_map_kv_tids() API function")
    Signed-off-by: Yonghong Song <yhs@fb.com>
    Acked-by: Alexei Starovoitov <ast@kernel.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>