[net] bpf: Fix unused variable warning
Message-id: <20200924164430.191293-41-yauheni.kaliuta@redhat.com>
Patchwork-id: 327891
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 041/243] bpf: Fix unused variable warning
Bugzilla: 1874003
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874003

commit 449e14bfdb83bf772200840a7ac4dcc1d7cacf54
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 29 15:21:58 2020 +0200

    bpf: Fix unused variable warning

    Hiding the only using of bpf_link_type_strs[] in an #ifdef causes
    an unused-variable warning:

    kernel/bpf/syscall.c:2280:20: error: 'bpf_link_type_strs' defined but not used [-Werror=unused-variable]
     2280 | static const char *bpf_link_type_strs[] = {

    Move the definition into the same #ifdef.

    Fixes: f2e10bff16a0 ("bpf: Add support for BPF_OBJ_GET_INFO_BY_FD for bpf_link")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Link: https://lore.kernel.org/bpf/20200429132217.1294289-1-arnd@arndb.de

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>