[tools] sync bpf.h
Message-id: <20191018135423.24316-175-yauheni.kaliuta@redhat.com>
Patchwork-id: 280377
O-Subject: [RHEL8.2 175/268] tools: sync bpf.h
Bugzilla: 1747615
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747615

commit 4635b0ae4d26f87cf68dbab6740955dd1ad67cf4
Author: Matt Mullins <mmullins@fb.com>
Date:   Fri Apr 26 11:49:50 2019 -0700

    tools: sync bpf.h

    This adds BPF_PROG_TYPE_RAW_TRACEPOINT_WRITABLE, and fixes up the

            error: enumeration value BPF_PROG_TYPE_RAW_TRACEPOINT_WRITABLE not handled in switch [-Werror=switch-enum]

    build errors it would otherwise cause in libbpf.

    Signed-off-by: Matt Mullins <mmullins@fb.com>
    Acked-by: Yonghong Song <yhs@fb.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>