[kernel] sched/core: Annotate curr pointer in rq with __rcu
Message-id: <20200406151254.7457-27-pauld@redhat.com>
Patchwork-id: 299241
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 26/27] sched/core: Annotate curr pointer in rq with __rcu
Bugzilla: 1794398
RH-Acked-by: Daniel Bristot de Oliveira <bristot@redhat.com>
RH-Acked-by: Juri Lelli <juri.lelli@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Waiman Long <longman@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1794398
Upstream Status: linux
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=27668514
Tested:  With cki.kt1, stress/ltp-lite, and manual scheduler tests. Kernel perf
team ran a set of tests as noted in the bug.

commit 4104a562e0ca62e971089db9d3c47794a0d7d4eb
Author: Madhuparna Bhowmik <madhuparnabhowmik10@gmail.com>
Date:   Sat Feb 1 18:28:03 2020 +0530

    sched/core: Annotate curr pointer in rq with __rcu

    This patch fixes the following sparse warnings in sched/core.c
    and sched/membarrier.c:

      kernel/sched/core.c:2372:27: error: incompatible types in comparison expression
      kernel/sched/core.c:4061:17: error: incompatible types in comparison expression
      kernel/sched/core.c:6067:9: error: incompatible types in comparison expression
      kernel/sched/membarrier.c:108:21: error: incompatible types in comparison expression
      kernel/sched/membarrier.c:177:21: error: incompatible types in comparison expression
      kernel/sched/membarrier.c:243:21: error: incompatible types in comparison expression

    Signed-off-by: Madhuparna Bhowmik <madhuparnabhowmik10@gmail.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lkml.kernel.org/r/20200201125803.20245-1-madhuparnabhowmik10@gmail.com

Signed-off-by: Phil Auld <pauld@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>