[bluetooth] Bluetooth: btusb: Remove return statement in btintel_reset_to_bootloader
Message-id: <20200707102204.31859-32-gtiwari@redhat.com>
Patchwork-id: 321873
Patchwork-instance: patchwork
O-Subject: [RHEL8 BZ 1838924 031/165] Bluetooth: btusb: Remove return statement in btintel_reset_to_bootloader
Bugzilla: 1838924
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1838924

commit fae7548f25a41443f1f074fcc6d3fed220a42a34
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Fri Oct 18 15:29:24 2019 -0700

    Bluetooth: btusb: Remove return statement in btintel_reset_to_bootloader

    When building with Clang and CONFIG_BT_INTEL unset, the following error
    occurs:

    In file included from drivers/bluetooth/hci_ldisc.c:34:
    drivers/bluetooth/btintel.h:188:2: error: void function
    'btintel_reset_to_bootloader' should not return a value [-Wreturn-type]
            return -EOPNOTSUPP;
            ^      ~~~~~~~~~~~
    1 error generated.

    Remove the unneeded return statement to fix this.

    Fixes: b9a2562f4918 ("Bluetooth: btusb: Trigger Intel FW download error recovery")
    Link: https://github.com/ClangBuiltLinux/linux/issues/743
    Reported-by: <ci_notify@linaro.org>
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Reviewed-by: Nick Desaulniers <ndesaulniers@google.com>
    Signed-off-by: Marcel Holtmann <marcel@holtmann.org>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>