[scsi] scsi: target: sbitmap: add seq_file forward declaration
Message-id: <20181213071454.16332-2-ming.lei@redhat.com>
Patchwork-id: 235257
O-Subject: [RHEL8 001/153] scsi: target: sbitmap: add seq_file forward declaration
Bugzilla: 1655485
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: Mike Snitzer <snitzer@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

BZ: 1655485

commit 14b470b56840dbb093abd71f214e9d63770c87b8
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jul 6 22:19:07 2018 +0200

    scsi: target: sbitmap: add seq_file forward declaration

    The target core runs into a warning in the linux/sbitmap.h
    file in some configurations:

    In file included from include/target/target_core_base.h:7,
                     from drivers/target/target_core_fabric_lib.c:41:
    include/linux/sbitmap.h:331:46: error: 'struct seq_file' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
     void sbitmap_show(struct sbitmap *sb, struct seq_file *m);
                                                  ^~~~~~~~

    In general, headers should not depend on others being included first,
    so this fixes it with a forward declaration for that struct name, but
    we probably want to merge the patch through the scsi tree to help
    bisection.

    Fixes: 10e9cbb6b531 ("scsi: target: Convert target drivers to use sbitmap")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Bart Van Assche <bart.vanassche@wdc.com>
    Reviewed-by: Omar Sandoval <osandov@fb.com>
    Reviewed-by: Jens Axboe <axboe@kernel.dk>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Ming Lei <ming.lei@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>