[tools] kvm: selftests: use -pthread instead of -lpthread
Message-id: <20181021075629.16645-15-pbonzini@redhat.com>
Patchwork-id: 231211
O-Subject: [RHEL8 PATCH v2 14/62] kvm: selftests: use -pthread instead of -lpthread
Bugzilla: 1636610
RH-Acked-by: Andrew Jones <drjones@redhat.com>
RH-Acked-by: Vitaly Kuznetsov <vkuznets@redhat.com>

From: Lei Yang <Lei.Yang@windriver.com>

I run into the following error

testing/selftests/kvm/dirty_log_test.c:285: undefined reference to `pthread_create'
testing/selftests/kvm/dirty_log_test.c:297: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status

my gcc version is gcc version 4.8.4
"-pthread" would work everywhere

Signed-off-by: Lei Yang <Lei.Yang@windriver.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 6bd317d3c865ebcddcb287a424093fe4758c40ef)
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>