[tools] bpf: Print error message for bpftool cgroup show
Message-id: <20200608222925.282045-106-yauheni.kaliuta@redhat.com>
Patchwork-id: 318071
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 106/257] bpf: Print error message for bpftool cgroup show
Bugzilla: 1813372
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813372

commit 1162f844030ac1ac7321b5e8f6c9badc7a11428f
Author: Hechao Li <hechaol@fb.com>
Date:   Mon Dec 23 17:17:42 2019 -0800

    bpf: Print error message for bpftool cgroup show

    Currently, when bpftool cgroup show <path> has an error, no error
    message is printed. This is confusing because the user may think the
    result is empty.

    Before the change:

    $ bpftool cgroup show /sys/fs/cgroup
    ID       AttachType      AttachFlags     Name
    $ echo $?
    255

    After the change:
    $ ./bpftool cgroup show /sys/fs/cgroup
    Error: can't query bpf programs attached to /sys/fs/cgroup: Operation
    not permitted

    v2: Rename check_query_cgroup_progs to cgroup_has_attached_progs

    Signed-off-by: Hechao Li <hechaol@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/20191224011742.3714301-1-hechaol@fb.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>