[tools] libbpf: Fix strncat bounds error in libbpf_prog_type_by_name
Message-id: <20200529062245.152030-70-yauheni.kaliuta@redhat.com>
Patchwork-id: 315318
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 070/235] libbpf: Fix strncat bounds error in libbpf_prog_type_by_name
Bugzilla: 1813370
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813370

commit 58eeb2289ab9bd8acad41a589431bbdbf7622595
Author: KP Singh <kpsingh@google.com>
Date:   Wed Oct 23 17:40:38 2019 +0200

    libbpf: Fix strncat bounds error in libbpf_prog_type_by_name

    On compiling samples with this change, one gets an error:

     error: ‘strncat’ specified bound 118 equals destination size
      [-Werror=stringop-truncation]

        strncat(dst, name + section_names[i].len,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         sizeof(raw_tp_btf_name) - (dst - raw_tp_btf_name));
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    strncat requires the destination to have enough space for the
    terminating null byte.

    Fixes: f75a697e09137 ("libbpf: Auto-detect btf_id of BTF-based raw_tracepoint")
    Signed-off-by: KP Singh <kpsingh@google.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Link: https://lore.kernel.org/bpf/20191023154038.24075-1-kpsingh@chromium.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>