perf daemon: Fix compile error with Asan
Bugzilla: https://bugzilla.redhat.com/1944685

upstream
========
commit bd57a9f33abc0adede5bafa06b2f1af3de03190d
Author: Namhyung Kim <namhyung@kernel.org>
Date: Wed Feb 24 16:14:38 2021 +0900

description
===========
I'm seeing a build failure when build with address sanitizer.  It seems
we could write to the name[100] if the var is longer.

  $ make EXTRA_CFLAGS=-fsanitize=address
  ...
    CC       builtin-daemon.o
  In function ‘get_session_name’,
    inlined from ‘session_config’ at builtin-daemon.c:164:6,
    inlined from ‘server_config’ at builtin-daemon.c:223:10:
  builtin-daemon.c:155:11: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
    155 |  *session = 0;
        |  ~~~~~~~~~^~~
  builtin-daemon.c: In function ‘server_config’:
  builtin-daemon.c:162:7: note: at offset 100 to object ‘name’ with size 100 declared here
    162 |  char name[100];
        |       ^~~~

Fixes: c0666261ff38 ("perf daemon: Add config file support")

Signed-off-by: Michael Petlan <mpetlan@redhat.com>