[kernel] libceph: fix clang warning for CEPH_DEFINE_OID_ONSTACK
Message-id: <20191108140453.73236-114-jlayton@redhat.com>
Patchwork-id: 284313
O-Subject: [BZ#1767959 RHEL8.2 PATCH 113/264] libceph: fix clang warning for CEPH_DEFINE_OID_ONSTACK
Bugzilla: 1767959
RH-Acked-by: Zheng Yan <zyan@redhat.com>
RH-Acked-by: Ilya Dryomov <idryomov@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

clang complains about assigning a variable to itself during the
declaration:

fs/ceph/ioctl.c:187:26: error: variable 'oid' is uninitialized when used within its own initialization [-Werror,-Wuninitialized]
        CEPH_DEFINE_OID_ONSTACK(oid);
                                ^~~
include/linux/ceph/osdmap.h:122:52: note: expanded from macro 'CEPH_DEFINE_OID_ONSTACK'
        struct ceph_object_id oid = CEPH_OID_INIT_ONSTACK(oid)
                              ~~~                         ^~~
include/linux/ceph/osdmap.h:120:29: note: expanded from macro 'CEPH_OID_INIT_ONSTACK'
    ({ ceph_oid_init(&oid); oid; })
                            ^~~

We use this trick in other places, but it is completely unnecessary
here, as we can just use a regular struct initializer.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Ilya Dryomov <idryomov@gmail.com>
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit 0384892c2d839033566b53453be44b1f5812cd00)
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>