[wireless] mt76: fix LED link time failure
Message-id: <20200413203652.3431-330-jarod@redhat.com>
Patchwork-id: 301817
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 329/615] mt76: fix LED link time failure
Bugzilla: 1807052
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1807052

commit d68f4e43a46ff1f772ff73085f96d44eb4163e9d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Dec 16 14:18:42 2019 +0100

    mt76: fix LED link time failure

    The mt76_led_cleanup() function is called unconditionally, which
    leads to a link error when CONFIG_LEDS is a loadable module or
    disabled but mt76 is built-in:

    drivers/net/wireless/mediatek/mt76/mac80211.o: In function `mt76_unregister_device':
    mac80211.c:(.text+0x2ac): undefined reference to `led_classdev_unregister'

    Use the same trick that is guarding the registration, using an
    IS_ENABLED() check for the CONFIG_MT76_LEDS symbol that indicates
    whether LEDs can be used or not.

    Fixes: 36f7e2b2bb1d ("mt76: do not use devm API for led classdev")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Felix Fietkau <nbd@nbd.name>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>