[arm] ARM: module: fix modsign build error
Message-id: <20200527180156.23049-104-didoming@redhat.com>
Patchwork-id: 314638
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH BZ1781925 v2 103/106] ARM: module: fix modsign build error
Bugzilla: 1781925
RH-Acked-by: Bruno Meneguele <bmeneg@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1781925
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28848035

The asm/module.h header file can not be included standalone, which
breaks the module signing code after a recent change:

In file included from kernel/module-internal.h:13,
                 from kernel/module_signing.c:17:
arch/arm/include/asm/module.h:37:27: error: 'struct module' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 u32 get_module_plt(struct module *mod, unsigned long loc, Elf32_Addr val);

This adds a forward declaration of struct module to make it all work.

commit 4d58e7034d1971436d44f203cf69d2feb6b82e5c

Fixes: f314dfea16a0 ("modsign: log module name in the event of an error")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Russell King <rmk+kernel@armlinux.org.uk>
Signed-off-by: Jessica Yu <jeyu@kernel.org>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>