[x86] x86/boot: Provide KASAN compatible aliases for string routines
Message-id: <20200729075116.10882-4-lijiang@redhat.com>
Patchwork-id: 322955
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 3/7] x86/boot: Provide KASAN compatible aliases for string routines
Bugzilla: 1857528
RH-Acked-by: Pingfan Liu <piliu@redhat.com>
RH-Acked-by: Baoquan He <bhe@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1857528
Brew build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=30336198
Tested machine: intel-wildcatpass-06.khw.lab.eng.bos.redhat.com
Conflicts: None

commit c3ee82ce47af63eca2075d8af956d468f508942e
Author: Ard Biesheuvel <ard.biesheuvel@linaro.org>
Date:   Sat May 18 18:11:13 2019 +0200

    x86/boot: Provide KASAN compatible aliases for string routines

    The KASAN subsystem wraps calls to memcpy(), memset() and memmove()
    to sanitize the arguments before invoking the actual routines, which
    have been renamed to __memcpy(), __memset() and __memmove(),
    respectively. When CONFIG_KASAN is enabled for the kernel build but
    KASAN code generation is disabled for the compilation unit (which is
    needed for things like the EFI stub or the decompressor), the string
    routines are just #define'd to their __ prefixed names so that they
    are simply invoked directly.

    This does however rely on those __ prefixed names to exist in the
    symbol namespace, which is not currently the case for the x86
    decompressor, which may lead to errors like

      drivers/firmware/efi/libstub/tpm.o: In function `efi_retrieve_tpm2_eventlog':
      tpm.c:(.text+0x2a8): undefined reference to `__memcpy'

    So let's expose the __ prefixed symbols in the decompressor when
    KASAN is enabled.

    Signed-off-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>
    Acked-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
    Cc: Andrey Konovalov <andreyknvl@google.com>
    Cc: Borislav Petkov <bp@alien8.de>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Matthew Garrett <matthewgarrett@google.com>
    Cc: Peter Zijlstra <peterz@infradead.org>
    Cc: Thomas Gleixner <tglx@linutronix.de>
    Cc: linux-efi@vger.kernel.org
    Signed-off-by: Ingo Molnar <mingo@kernel.org>

Signed-off-by: Lianbo Jiang <lijiang@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>