[crypto] cxgb4/chcr: avoid -Wreturn-local-addr warning
Message-id: <20200701104937.29652-18-crecklin@redhat.com>
Patchwork-id: 321735
Patchwork-instance: patchwork
O-Subject: [RHEL 8.3 BZ1797945 v3 PATCH 17/18] cxgb4/chcr: avoid -Wreturn-local-addr warning
Bugzilla: 1797945
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

gcc-10 warns about functions that return a pointer to a stack
variable. In chcr_write_cpl_set_tcb_ulp(), this does not actually
happen, but it's too hard to see for the compiler:

drivers/crypto/chelsio/chcr_ktls.c: In function 'chcr_write_cpl_set_tcb_ulp.constprop':
drivers/crypto/chelsio/chcr_ktls.c:760:9: error: function may return address of local variable [-Werror=return-local-addr]
  760 |  return pos;
      |         ^~~
drivers/crypto/chelsio/chcr_ktls.c:712:5: note: declared here
  712 |  u8 buf[48] = {0};
      |     ^~~

Split the middle part of the function out into a helper to make
it easier to understand by both humans and compilers, which avoids
the warning.

Fixes: 5a4b9fe7fece ("cxgb4/chcr: complete record tx handling")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 071a43e660996d1517d02ea7724491cc5b93bb03)
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>