tracing: Annotate ftrace_graph_notrace_hash pointer with __rcu
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1941211

commit fd0e6852c407dd9aefc594f54ddcc21d84803d3b
Author: Amol Grover <frextrite@gmail.com>
Date:   Wed, 5 Feb 2020 11:27:02 +0530

    tracing: Annotate ftrace_graph_notrace_hash pointer with __rcu

    Fix following instances of sparse error
    kernel/trace/ftrace.c:5667:29: error: incompatible types in comparison
    kernel/trace/ftrace.c:5813:21: error: incompatible types in comparison
    kernel/trace/ftrace.c:5868:36: error: incompatible types in comparison
    kernel/trace/ftrace.c:5870:25: error: incompatible types in comparison

    Use rcu_dereference_protected to dereference the newly annotated pointer.

    Link: http://lkml.kernel.org/r/20200205055701.30195-1-frextrite@gmail.com

    Signed-off-by: Amol Grover <frextrite@gmail.com>
    Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>

Signed-off-by: Waiman Long <longman@redhat.com>