[kernel] sysctl: Fix unused function warning
Message-id: <20200924164430.191293-50-yauheni.kaliuta@redhat.com>
Patchwork-id: 327900
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 050/243] sysctl: Fix unused function warning
Bugzilla: 1874003
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874003

commit 5447e8e01e101ba19fe5b7551f02d37367156f6b
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue May 5 16:07:12 2020 +0200

    sysctl: Fix unused function warning

    The newly added bpf_stats_handler function has the wrong #ifdef
    check around it, leading to an unused-function warning when
    CONFIG_SYSCTL is disabled:

    kernel/sysctl.c:205:12: error: unused function 'bpf_stats_handler' [-Werror,-Wunused-function]
    static int bpf_stats_handler(struct ctl_table *table, int write,

    Fix the check to match the reference.

    Fixes: d46edd671a14 ("bpf: Sharing bpf runtime stats with BPF_ENABLE_STATS")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Reviewed-by: Luis Chamberlain <mcgrof@kernel.org>
    Acked-by: Martin KaFai Lau <kafai@fb.com>
    Acked-by: Song Liu <songliubraving@fb.com>
    Link: https://lore.kernel.org/bpf/20200505140734.503701-1-arnd@arndb.de

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>