[lib] kasan: turn off asan-stack for clang-8 and earlier
Message-id: <452f0b470d27610ee397c5d02773ebdff39bf345.1605724262.git@redhat.com>
Patchwork-id: 340035
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 bz1894223 PATCH 1/59] kasan: turn off asan-stack for clang-8 and earlier
Bugzilla: 1894223
RH-Acked-by: Waiman Long <longman@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

commit 6baec880d7a53cbc2841123e56ee31e830df9b49
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Feb 28 16:21:58 2019 -0800

    kasan: turn off asan-stack for clang-8 and earlier

    Building an arm64 allmodconfig kernel with clang results in over 140
    warnings about overly large stack frames, the worst ones being:

      drivers/gpu/drm/panel/panel-sitronix-st7789v.c:196:12: error: stack frame size of 20224 bytes in function 'st7789v_prepare'
      drivers/video/fbdev/omap2/omapfb/displays/panel-tpo-td028ttec1.c:196:12: error: stack frame size of 13120 bytes in function 'td028ttec1_panel_enable'
      drivers/usb/host/max3421-hcd.c:1395:1: error: stack frame size of 10048 bytes in function 'max3421_spi_thread'
      drivers/net/wan/slic_ds26522.c:209:12: error: stack frame size of 9664 bytes in function 'slic_ds26522_probe'
      drivers/crypto/ccp/ccp-ops.c:2434:5: error: stack frame size of 8832 bytes in function 'ccp_run_cmd'
      drivers/media/dvb-frontends/stv0367.c:1005:12: error: stack frame size of 7840 bytes in function 'stv0367ter_algo'

    None of these happen with gcc today, and almost all of these are the
    result of a single known issue in llvm.  Hopefully it will eventually
    get fixed with the clang-9 release.

    In the meantime, the best idea I have is to turn off asan-stack for
    clang-8 and earlier, so we can produce a kernel that is safe to run.

    I have posted three patches that address the frame overflow warnings
    that are not addressed by turning off asan-stack, so in combination with
    this change, we get much closer to a clean allmodconfig build, which in
    turn is necessary to do meaningful build regression testing.

    It is still possible to turn on the CONFIG_ASAN_STACK option on all
    versions of clang, and it's always enabled for gcc, but when
    CONFIG_COMPILE_TEST is set, the option remains invisible, so
    allmodconfig and randconfig builds (which are normally done with a
    forced CONFIG_COMPILE_TEST) will still result in a mostly clean build.

    Link: http://lkml.kernel.org/r/20190222222950.3997333-1-arnd@arndb.de
    Link: https://bugs.llvm.org/show_bug.cgi?id=38809
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Qian Cai <cai@lca.pw>
    Reviewed-by: Mark Brown <broonie@kernel.org>
    Acked-by: Andrey Ryabinin <aryabinin@virtuozzo.com>
    Cc: Dmitry Vyukov <dvyukov@google.com>
    Cc: Nick Desaulniers <ndesaulniers@google.com>
    Cc: Kostya Serebryany <kcc@google.com>
    Cc: Andrey Konovalov <andreyknvl@google.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Nico Pache <npache@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>