[kernel] timekeeping/vsyscall: Use __iter_div_u64_rem()
Message-id: <20201027003220.16553-88-longman@redhat.com>
Patchwork-id: 335451
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 087/213] timekeeping/vsyscall: Use __iter_div_u64_rem()
Bugzilla: 1548297
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1548297

commit 0df1c9868c3a1916198ee09c323ca5932a0b8a11
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed, 10 Jul 2019 15:01:53 +0200

    timekeeping/vsyscall: Use __iter_div_u64_rem()

    On 32-bit x86 when building with clang-9, the 'division' loop gets turned
    back into an inefficient division that causes a link error:

    kernel/time/vsyscall.o: In function `update_vsyscall':
    vsyscall.c:(.text+0xe3): undefined reference to `__udivdi3'

    Use the existing __iter_div_u64_rem() function which is used to address the
    same issue in other places.

    Fixes: 44f57d788e7d ("timekeeping: Provide a generic update_vsyscall() implementation")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Reviewed-by: Nathan Chancellor <natechancellor@gmail.com>
    Tested-by: Nathan Chancellor <natechancellor@gmail.com>
    Link: https://lkml.kernel.org/r/20190710130206.1670830-1-arnd@arndb.de

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>