[iommu] iommu/mediatek: Fix MTK_IOMMU dependencies
Message-id: <20210116012107.726851-134-jsnitsel@redhat.com>
Patchwork-id: 349526
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 133/449] iommu/mediatek: Fix MTK_IOMMU dependencies
Bugzilla: 1887546
RH-Acked-by: Mark Salter <msalter@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1887546
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=34307190

commit d1dcb7255c2b0ae77fbe297e4543c6cfff54e9b9
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Fri Apr 10 16:30:47 2020 +0200

    iommu/mediatek: Fix MTK_IOMMU dependencies

    If NO_DMA=y (e.g. Sun-3 all{mod,yes}-config):

	drivers/iommu/dma-iommu.o: In function `iommu_dma_mmap':
	dma-iommu.c:(.text+0x836): undefined reference to `dma_pgprot'

    IOMMU_DMA must not be selected, unless HAS_DMA=y.

    Hence fix this by making MTK_IOMMU depend on HAS_DMA.
    While at it, remove the dependency on ARM || ARM64, as that is already
    implied by the dependency on ARCH_MEDIATEK.

    Fixes: e93a1695d7fb5513 ("iommu: Enable compile testing for some of drivers")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Link: https://lore.kernel.org/r/20200410143047.19691-1-geert@linux-m68k.org
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit d1dcb7255c2b0ae77fbe297e4543c6cfff54e9b9)
Cc: Myron Stowe <myron.stowe@redhat.com>
Cc: Alex Williamson <alex.williamson@redhat.com>
Cc: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>