[sound] ALSA: soundwire: qcom: Fix build failure when slimbus is module
Message-id: <16118254255780022-59-patchset-jkysela@redhat.com>
Patchwork-id: 351408
Patchwork-instance: patchwork
O-Subject: [RHEL 8.4 PATCH 58/93] ALSA: soundwire: qcom: Fix build failure when slimbus is module
Bugzilla: 1783462
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Commit 5bd773242f75 ("soundwire: qcom: avoid dependency on
CONFIG_SLIMBUS") removed hard dependency on Slimbus for qcom driver but
it results in build failure when: CONFIG_SOUNDWIRE_QCOM=y
CONFIG_SLIMBUS=m

drivers/soundwire/qcom.o: In function `qcom_swrm_probe':
qcom.c:(.text+0xf44): undefined reference to `slimbus_bus'

Fix this by using IS_REACHABLE() in driver which is recommended to be
used with imply.

Fixes: 5bd773242f75 ("soundwire: qcom: avoid dependency on CONFIG_SLIMBUS")
Reported-by: kernel test robot <lkp@intel.com>
Tested-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Reviewed-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
Link: https://lore.kernel.org/r/20201125055155.GD8403@vkoul-mobl
Signed-off-by: Vinod Koul <vkoul@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 47edc0104c61d609b0898a302267b7269d87a6af)
Bugzilla: 1783462
Signed-off-by: Jan Stancek <jstancek@redhat.com>