[cdrom] gdrom: fix mistake in assignment of error
Message-id: <20181115124238.31964-84-ming.lei@redhat.com>
Patchwork-id: 232978
O-Subject: [RHEL8.0 083/169] gdrom: fix mistake in assignment of error
Bugzilla: 1638826
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Ewan Milne <emilne@redhat.com>

From: Jens Axboe <axboe@kernel.dk>

BZ: 1638826

commit 0a40a93524736c2ce01d82effe2f2bc34d5cf159
Author: Jens Axboe <axboe@kernel.dk>
Date:   Thu Oct 25 08:15:30 2018 -0600

    gdrom: fix mistake in assignment of error

    Apparently the kbuild bots missed this one originally, but at least
    it caught it now. Fix compilation error:

    All errors (new ones prefixed by >>):

       drivers/cdrom/gdrom.c: In function 'probe_gdrom':
    >> drivers/cdrom/gdrom.c:797:3: error: 'rc' undeclared (first use in this function)
          rc = PTR_ERR(gd.gdrom_rq);
          ^~
       drivers/cdrom/gdrom.c:797:3: note: each undeclared identifier is reported only once for each function it appears in

    Fixes: ad5fc6bb7221 ("gdrom: convert to blk-mq")
    Signed-off-by: Jens Axboe <axboe@kernel.dk>

Signed-off-by: Ming Lei <ming.lei@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>