[net] ipv6: remove dependency of nf_defrag_ipv6 on ipv6 module
Message-id: <440d148c44696a5828776018a34eaa6ec7461b1e.1556898167.git.gnault@redhat.com>
Patchwork-id: 253272
O-Subject: [RHEL8.1 net PATCH 02/13] ipv6: remove dependency of nf_defrag_ipv6 on ipv6 module
Bugzilla: 1660282
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Florian Westphal <fwestpha@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1660282
Upstream Status: commit 70b095c84326
Build Info: local build

Original problem could not occur, because RHEL8 doesn't have commit
a0ae2562c6c4 ("netfilter: conntrack: remove l3proto abstraction").
That is, we can't have NF_DEFRAG_IPV6=y with IPV6=m, because
DEFRAG_IPV6 is selected by NF_CONNTRACK_IPV6 which itself depends on
IPV6.

commit 70b095c84326640eeacfd69a411db8fc36e8ab1a
Author: Florian Westphal <fw@strlen.de>
Date:   Sat Jul 14 01:14:01 2018 +0200

    ipv6: remove dependency of nf_defrag_ipv6 on ipv6 module

    IPV6=m
    DEFRAG_IPV6=m
    CONNTRACK=y yields:

    net/netfilter/nf_conntrack_proto.o: In function `nf_ct_netns_do_get':
    net/netfilter/nf_conntrack_proto.c:802: undefined reference to `nf_defrag_ipv6_enable'
    net/netfilter/nf_conntrack_proto.o:(.rodata+0x640): undefined reference to `nf_conntrack_l4proto_icmpv6'

    Setting DEFRAG_IPV6=y causes undefined references to ip6_rhash_params
    ip6_frag_init and ip6_expire_frag_queue so it would be needed to force
    IPV6=y too.

    This patch gets rid of the 'followup linker error' by removing
    the dependency of ipv6.ko symbols from netfilter ipv6 defrag.

    Shared code is placed into a header, then used from both.

    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Guillaume Nault <gnault@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>