[drm] amd/display/dc/basics/logger.c: fix build error with CONFIG_FORTIFY_SOURCE=y
Message-id: <20180926134640.19637-2-herton@redhat.com>
Patchwork-id: 229326
O-Subject: [RHEL8 PATCH 1/2] [drm] drm/amd/display/dc/basics/logger.c: fix build error with CONFIG_FORTIFY_SOURCE=y
Bugzilla: 1548068
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1548068
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=18498206
Upstream Status: RHEL only

After trying to apply the config change, now on 4.18 kernel I'm getting the following
build error with CONFIG_FORTIFY_SOURCE=y:

In function 'memmove',
    inlined from 'append_entry' at drivers/gpu/drm/amd/amdgpu/../display/dc/basics/logger.c:258:2,
    inlined from 'dm_logger_append_va.part.5' at drivers/gpu/drm/amd/amdgpu/../display/dc/basics/logger.c:349:4:
./include/linux/string.h:356:4: error: call to '__read_overflow2' declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:317: drivers/gpu/drm/amd/amdgpu/../display/dc/basics/logger.o] Error 1

I didn't get such error when building with RHEL8 based on 4.17 kernel before, but this
now happens on current RHEL8 kernel tree based on 4.18.

This is a RHEL only patch, because logger.c was removed upstream and the code doesn't
exist anymore (see upstream commit e1cb3e4801e6 - "drm/amd/display: Convert remaining
loggers off dc_logger"). The same solution was also sent upstream by Jan Kosterec:
https://www.mail-archive.com/amd-gfx@lists.freedesktop.org/msg25438.html
But as I mentioned above, was turned down since logger.c was removed upstream after 4.18.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>