[tools] libbpf: Fix build by renaming variables
Message-id: <20200608222925.282045-69-yauheni.kaliuta@redhat.com>
Patchwork-id: 318040
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 069/257] libbpf: Fix build by renaming variables
Bugzilla: 1813372
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813372

commit a79ac2d1036a824abba982c33e938b717d1b659f
Author: Prashant Bhole <prashantbhole.linux@gmail.com>
Date:   Mon Dec 16 17:27:38 2019 +0900

    libbpf: Fix build by renaming variables

    In btf__align_of() variable name 't' is shadowed by inner block
    declaration of another variable with same name. Patch renames
    variables in order to fix it.

      CC       sharedobjs/btf.o
    btf.c: In function ‘btf__align_of’:
    btf.c:303:21: error: declaration of ‘t’ shadows a previous local [-Werror=shadow]
      303 |   int i, align = 1, t;
          |                     ^
    btf.c:283:25: note: shadowed declaration is here
      283 |  const struct btf_type *t = btf__type_by_id(btf, id);
          |

    Fixes: 3d208f4ca111 ("libbpf: Expose btf__align_of() API")
    Signed-off-by: Prashant Bhole <prashantbhole.linux@gmail.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Tested-by: Toke Høiland-Jørgensen <toke@redhat.com>
    Link: https://lore.kernel.org/bpf/20191216082738.28421-1-prashantbhole.linux@gmail.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>