[kernel] bpf: fix missing bpf_check_uarg_tail_zero in BPF_PROG_TEST_RUN
Message-id: <20191018135423.24316-86-yauheni.kaliuta@redhat.com>
Patchwork-id: 280199
O-Subject: [RHEL8.2 086/268] bpf: fix missing bpf_check_uarg_tail_zero in BPF_PROG_TEST_RUN
Bugzilla: 1747615
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1747615

commit c695865c5c9803f14eef2c99d8a49d9ad60a3383
Author: Stanislav Fomichev <sdf@google.com>
Date:   Thu Apr 11 09:12:02 2019 -0700

    bpf: fix missing bpf_check_uarg_tail_zero in BPF_PROG_TEST_RUN

    Commit b0b9395d865e ("bpf: support input __sk_buff context in
    BPF_PROG_TEST_RUN") started using bpf_check_uarg_tail_zero in
    BPF_PROG_TEST_RUN. However, bpf_check_uarg_tail_zero is not defined
    for !CONFIG_BPF_SYSCALL:

    net/bpf/test_run.c: In function bpf_ctx_init:
    net/bpf/test_run.c:142:9: error: implicit declaration of function bpf_check_uarg_tail_zero [-Werror=implicit-function-declaration]
       err = bpf_check_uarg_tail_zero(data_in, max_size, size);
             ^~~~~~~~~~~~~~~~~~~~~~~~

    Let's not build net/bpf/test_run.c when CONFIG_BPF_SYSCALL is not set.

    Reported-by: kbuild test robot <lkp@intel.com>
    Fixes: b0b9395d865e ("bpf: support input __sk_buff context in BPF_PROG_TEST_RUN")
    Signed-off-by: Stanislav Fomichev <sdf@google.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>