[scsi] scsi: ibmvscsis: Fix a stringop-overflow warning
Message-id: <20181128174629.20727-13-labbott@redhat.com>
Patchwork-id: 233880
O-Subject: [RHEL8.0 BZ 1626466 12/17] scsi: ibmvscsis: Fix a stringop-overflow warning
Bugzilla: 1582754
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1582754
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=19300249
Testing: Compile only

commit d792d4c4fc866ae224b0b0ca2aabd87d23b4d6cc
Author: Laura Abbott <labbott@redhat.com>
Date:   Tue Sep 11 12:22:25 2018 -0700

    scsi: ibmvscsis: Fix a stringop-overflow warning

    There's currently a warning about string overflow with strncat:

    drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c: In function 'ibmvscsis_probe':
    drivers/scsi/ibmvscsi_tgt/ibmvscsi_tgt.c:3479:2: error: 'strncat' specified
    bound 64 equals destination size [-Werror=stringop-overflow=]
      strncat(vscsi->eye, vdev->name, MAX_EYE);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Switch to a single snprintf instead of a strcpy + strcat to handle this
    cleanly.

    Signed-off-by: Laura Abbott <labbott@redhat.com>
    Suggested-by: Kees Cook <keescook@chromium.org>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Cc: Ewan D. Milne <emilne@redhat.com>
Cc: Laura Abbott <labbott@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>