selftests/bpf: Initialize duration in xdp_noinline.c
Bugzilla: http://bugzilla.redhat.com/1874006

commit cffcdbff70a3cf3cc4f42fa2e57012411b1c78a6
Author: Stanislav Fomichev <sdf@google.com>
Date:   Thu Oct 1 15:54:40 2020 -0700

    selftests/bpf: Initialize duration in xdp_noinline.c

    Fixes clang error:
    tools/testing/selftests/bpf/prog_tests/xdp_noinline.c:35:6: error: variable 'duration' is uninitialized when used here [-Werror,-Wuninitialized]
            if (CHECK(!skel, "skel_open_and_load", "failed\n"))
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Signed-off-by: Stanislav Fomichev <sdf@google.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Martin KaFai Lau <kafai@fb.com>
    Link: https://lore.kernel.org/bpf/20201001225440.1373233-1-sdf@google.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>