[netdrv] qed: reduce maximum stack frame size
Message-id: <1572516117-4404-21-git-send-email-mchopra@redhat.com>
Patchwork-id: 281944
O-Subject: [RHEL8.2 PATCH 20/39] qed: reduce maximum stack frame size
Bugzilla: 1720392
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1720392
RHEL-fixes: 86622ee75312 ("qed: Move statistics to L2 code")
Upstream: linux.git

commit 7c116e02a4a7575c8c62bfd2106e3e3ec8fb99dc
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jul 22 17:01:23 2019 +0200

    qed: reduce maximum stack frame size

    clang warns about an overly large stack frame in one function
    when it decides to inline all __qed_get_vport_*() functions into
    __qed_get_vport_stats():

    drivers/net/ethernet/qlogic/qed/qed_l2.c:1889:13: error: stack frame size of 1128 bytes in function '_qed_get_vport_stats' [-Werror,-Wframe-larger-than=]

    Use a noinline_for_stack annotation to prevent clang from inlining
    these, which keeps the maximum stack usage at around half of that
    in the worst case, similar to what we get with gcc.

    Fixes: 86622ee75312 ("qed: Move statistics to L2 code")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Manish Chopra <mchopra@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>