[char] ipmi: ipmb: don't allocate i2c_client on stack
Message-id: <20190918151314.27704-18-tcamuso@redhat.com>
Patchwork-id: 272431
O-Subject: [RHEL8.2 BZ 1752071 17/27] ipmi: ipmb: don't allocate i2c_client on stack
Bugzilla: 1752071
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzillas: https://bugzilla.redhat.com/show_bug.cgi?id=1752071
           https://bugzilla.redhat.com/show_bug.cgi?id=1725433
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=23542405
Testing:
    IPMI regression tests and full cki.test suite.
    https://beaker.engineering.redhat.com/jobs/?jobsearch-0.table=Whiteboard&jobsearch-0.operation=contains&jobsearch-0.value=cki%40gitlab%3A171332
        Overall result: PASSED
             Tests: OK

Cherry-picked from the following upstream commit.

commit 21feadd024e747123bc0aaba8d8cbef2b5eda058
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Jun 19 14:50:34 2019 +0200

    ipmi: ipmb: don't allocate i2c_client on stack

    The i2c_client structure can be fairly large, which leads to
    a warning about possible kernel stack overflow in some
    configurations:

    drivers/char/ipmi/ipmb_dev_int.c:115:16: error: stack frame size of 1032 bytes in function 'ipmb_write' [-Werror,-Wframe-larger-than=]

    There is no real reason to even declare an i2c_client, as we can simply
    call i2c_smbus_xfer() directly instead of the i2c_smbus_write_block_data()
    wrapper.

    Convert the ipmb_write() to use an open-coded i2c_smbus_write_block_data()
    here, without changing the behavior.

    It seems that there is another problem with this implementation;
    when user space passes a length of more than I2C_SMBUS_BLOCK_MAX
    bytes, all the rest is silently ignored. This should probably be
    addressed in a separate patch, but I don't know what the intended
    behavior is here.

    Fixes: 51bd6f291583 ("Add support for IPMB driver")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Message-Id: <20190619125045.918700-1-arnd@arndb.de>
    Acked-by: Asmaa Mnebhi <Asmaa@mellanox.com>
    [Broke up a line >80 characters on i2c_smbus_xfer().]
    Signed-off-by: Corey Minyard <cminyard@mvista.com>

Signed-off-by: Tony Camuso <tcamuso@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>