[net] netfilter: nf_flow_table_offload: Correct memcpy size for flow_overload_mangle()
Message-id: <9bc8215463d68133cbfc29cbcbdcd4ddb06355af.1589567677.git.mleitner@redhat.com>
Patchwork-id: 310010
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 091/146] netfilter: nf_flow_table_offload: Correct memcpy size for flow_overload_mangle()
Bugzilla: 1811193
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Phil Sutter <psutter@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1811193
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28605855

commit 7acd9378dc65296b2531758aa62ee9bcf55b371c
Author: Pablo Neira Ayuso <pablo@netfilter.org>
Date:   Sat Dec 7 18:38:12 2019 +0100

    netfilter: nf_flow_table_offload: Correct memcpy size for flow_overload_mangle()

    In function 'memcpy',
         inlined from 'flow_offload_mangle' at net/netfilter/nf_flow_table_offload.c:112:2,
         inlined from 'flow_offload_port_dnat' at net/netfilter/nf_flow_table_offload.c:373:2,
         inlined from 'nf_flow_rule_route_ipv4' at net/netfilter/nf_flow_table_offload.c:424:3:
    ./include/linux/string.h:376:4: error: call to '__read_overflow2' declared with attribute error: detected read beyond size of object passed as 2nd parameter
       376 |    __read_overflow2();
           |    ^~~~~~~~~~~~~~~~~~

    The original u8* was done in the hope to make this more adaptable but
    consensus is to keep this like it is in tc pedit.

    Fixes: c29f74e0df7a ("netfilter: nf_flow_table: hardware offload support")
    Reported-by: Laura Abbott <labbott@redhat.com>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Marcelo Ricardo Leitner <mleitner@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>