[netdrv] ethernet: dpaa: remove unused variables
Message-id: <97de2b53bf760a9a0767cd7eee88a44793420acc.1556881625.git.poros@redhat.com>
Patchwork-id: 253295
O-Subject: [RHEL8.1 net PATCH 14/27] net: ethernet: dpaa: remove unused variables
Bugzilla: 1691720
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1691720

Upstream commit(s):
commit 5e8cc3947d8f7b62ff964e58789677a81b20dfca
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Sep 26 15:12:13 2018 +0200

    net: ethernet: dpaa: remove unused variables

    The patch that removed the only users of the oldadv/newadv variables
    accidentally left the now-unused declarations behind:

    drivers/net/ethernet/freescale/dpaa/dpaa_ethtool.c: In function 'dpaa_set_pauseparam':
    drivers/net/ethernet/freescale/dpaa/dpaa_ethtool.c:185:14: error: unused variable 'oldadv' [-Werror=unused-variable]
    drivers/net/ethernet/freescale/dpaa/dpaa_ethtool.c:185:6: error: unused variable 'newadv' [-Werror=unused-variable]

    Fixes: 70814e819c11 ("net: ethernet: Add helper for set_pauseparam for Asym Pause")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Petr Oros <poros@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>