[net] sched: act_skbmod: validate the control action inside init()
Message-id: <20190610212005.12299-146-ivecera@redhat.com>
Patchwork-id: 264133
O-Subject: [RHEL-8.1 net PATCH 145/194] net/sched: act_skbmod: validate the control action inside init()
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 7c3d825d12c5e6056ea73c0a202cbdef9d9ab9e6
Author: Davide Caratti <dcaratti@redhat.com>
Date:   Wed Mar 20 15:00:12 2019 +0100

    net/sched: act_skbmod: validate the control action inside init()

    the following script:

     # tc qdisc add dev crash0 clsact
     # tc filter add dev crash0 egress matchall \
     > action skbmod set smac 00:c1:a0:c1:a0:00 pass index 90
     # tc actions replace action skbmod \
     > set smac 00:c1:a0:c1:a0:00 goto chain 42 index 90 cookie c1a0c1a0
     # tc actions show action skbmod

    had the following output:

     src MAC address <00:c1:a0:c1:a0:00>
     src MAC address <00:c1:a0:c1:a0:00>
     Error: Failed to init TC action chain.
     We have an error talking to the kernel
     total acts 1

             action order 0: skbmod goto chain 42 set smac 00:c1:a0:c1:a0:00
              index 90 ref 2 bind 1
             cookie c1a0c1a0

    Then, the first packet transmitted by crash0 made the kernel crash:

     BUG: unable to handle kernel NULL pointer dereference at 0000000000000000
     #PF error: [normal kernel read fault]
     PGD 800000002d5c7067 P4D 800000002d5c7067 PUD 77e16067 PMD 0
     Oops: 0000 [#1] SMP PTI
     CPU: 3 PID: 0 Comm: swapper/3 Not tainted 5.0.0-rc4.gotochain_crash+ #536
     Hardware name: Red Hat KVM, BIOS 0.5.1 01/01/2011
     RIP: 0010:tcf_action_exec+0xb8/0x100
     Code: 00 00 00 20 74 1d 83 f8 03 75 09 49 83 c4 08 4d 39 ec 75 bc 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 49 8b 97 a8 00 00 00 <48> 8b 12 48 89 55 00 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3
     RSP: 0018:ffff8987ffd83be0 EFLAGS: 00010246
     RAX: 000000002000002a RBX: ffff8987aeb68800 RCX: ffff8987fa263640
     RDX: 0000000000000000 RSI: ffff8987f51c8802 RDI: 00000000000000a0
     RBP: ffff8987ffd83c80 R08: ffff8987f939bac8 R09: 0000000000000000
     R10: 0000000000000000 R11: 0000000000000000 R12: ffff8987f5c77d00
     R13: ffff8987f5c77d08 R14: 0000000000000001 R15: ffff8987f0c29f00
     FS:  0000000000000000(0000) GS:ffff8987ffd80000(0000) knlGS:0000000000000000
     CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
     CR2: 0000000000000000 CR3: 000000007832c004 CR4: 00000000001606e0
     Call Trace:
      <IRQ>
      tcf_classify+0x58/0x120
      __dev_queue_xmit+0x40a/0x890
      ? ip6_finish_output2+0x369/0x590
      ip6_finish_output2+0x369/0x590
      ? ip6_output+0x68/0x110
      ip6_output+0x68/0x110
      ? nf_hook.constprop.35+0x79/0xc0
      mld_sendpack+0x16f/0x220
      mld_ifc_timer_expire+0x195/0x2c0
      ? igmp6_timer_handler+0x70/0x70
      call_timer_fn+0x2b/0x130
      run_timer_softirq+0x3e8/0x440
      ? tick_sched_timer+0x37/0x70
      __do_softirq+0xe3/0x2f5
      irq_exit+0xf0/0x100
      smp_apic_timer_interrupt+0x6c/0x130
      apic_timer_interrupt+0xf/0x20
      </IRQ>
     RIP: 0010:native_safe_halt+0x2/0x10
     Code: 56 ff ff ff 7f f3 c3 65 48 8b 04 25 00 5c 01 00 f0 80 48 02 20 48 8b 00 a8 08 74 8b eb c1 90 90 90 90 90 90 90 90 90 90 fb f4 <c3> 0f 1f 00 66 2e 0f 1f 84 00 00 00 00 00 f4 c3 90 90 90 90 90 90
     RSP: 0018:ffffa2a1c038feb8 EFLAGS: 00000246 ORIG_RAX: ffffffffffffff13
     RAX: ffffffffa94184f0 RBX: 0000000000000003 RCX: 0000000000000001
     RDX: 0000000000000001 RSI: 0000000000000087 RDI: 0000000000000003
     RBP: 0000000000000003 R08: 001123cfc2ba71ac R09: 0000000000000000
     R10: 0000000000000000 R11: 00000000000f4240 R12: 0000000000000000
     R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
      ? __sched_text_end+0x1/0x1
      default_idle+0x1c/0x140
      do_idle+0x1c4/0x280
      cpu_startup_entry+0x19/0x20
      start_secondary+0x1a7/0x200
      secondary_startup_64+0xa4/0xb0
     Modules linked in: act_skbmod veth ip6table_filter ip6_tables iptable_filter binfmt_misc ext4 crct10dif_pclmul crc32_pclmul ghash_clmulni_intel mbcache jbd2 snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hwdep snd_hda_core snd_seq snd_seq_device aesni_intel crypto_simd cryptd glue_helper snd_pcm joydev pcspkr virtio_balloon snd_timer snd i2c_piix4 soundcore nfsd auth_rpcgss nfs_acl lockd grace sunrpc ip_tables xfs ata_generic pata_acpi qxl drm_kms_helper syscopyarea sysfillrect virtio_net sysimgblt fb_sys_fops net_failover virtio_console ttm virtio_blk failover drm crc32c_intel serio_raw ata_piix virtio_pci libata virtio_ring virtio floppy dm_mirror dm_region_hash dm_log dm_mod
     CR2: 0000000000000000

    Validating the control action within tcf_skbmod_init() proved to fix the
    above issue. A TDC selftest is added to verify the correct behavior.

    Fixes: db50514f9a9c ("net: sched: add termination action to allow goto chain")
    Fixes: 97763dc0f401 ("net_sched: reject unknown tcfa_action values")
    Signed-off-by: Davide Caratti <dcaratti@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>