[fs] cifs: Silence uninitialized variable warning
Message-id: <20190509235548.8854-3-lsahlber@redhat.com>
Patchwork-id: 254543
O-Subject: [RHEL8.1 fs 002/276] cifs: Silence uninitialized variable warning
Bugzilla: 1708033
RH-Acked-by: Benjamin Coddington <bcodding@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>

From: Dan Carpenter <dan.carpenter@oracle.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1708033
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21579898

This is not really a runtime issue but Smatch complains that:

    fs/cifs/smb2ops.c:1740 smb2_query_symlink()
    error: uninitialized symbol 'resp_buftype'.

The warning is right that it can be uninitialized...  Also "err_buf"
would be NULL at this point and we're not supposed to pass NULLs to
free_rsp_buf() or it might trigger some extra output if we turn on
debugging.

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Reviewed-by: Paulo Alcantara <palcantara@suse.de>
Signed-off-by: Steve French <stfrench@microsoft.com>
(cherry picked from commit ff361fda55fda55031252aca1f8afef735fe057c)
Signed-off-by: Ronnie Sahlberg <lsahlber@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>