[tools] tools: PCI: Fix broken pcitest compilation
Message-id: <20200228153738.38543.93563.stgit@tak.stowe>
Patchwork-id: 295418
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 39/41] tools: PCI: Fix broken pcitest compilation
Bugzilla: 1793091
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1793091
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=26765111
Upstream Status: 8a5e0af240e07dd3d4897eb8ff52aab757da7fab

commit 8a5e0af240e07dd3d4897eb8ff52aab757da7fab
Author: Alan Mikhak <alan.mikhak@sifive.com>
Date:   Thu May 23 14:18:00 2019 -0700

    tools: PCI: Fix broken pcitest compilation

    pcitest is currently broken due to the following compiler error
    and related warning. Fix by changing the run_test() function
    signature to return an integer result.

    pcitest.c: In function run_test:
    pcitest.c:143:9: warning: return with a value, in function
    returning void
      return (ret < 0) ? ret : 1 - ret; /* return 0 if test succeeded */

    pcitest.c: In function main:
    pcitest.c:232:9: error: void value not ignored as it ought to be
      return run_test(test);

    Fixes: fef31ecaaf2c ("tools: PCI: Fix compilation warnings")
    Signed-off-by: Alan Mikhak <alan.mikhak@sifive.com>
    Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
    Reviewed-by: Paul Walmsley <paul.walmsley@sifive.com>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>