[iommu] iommu: Fix integer truncation
Message-id: <20190925153803.30733.62293.stgit@tak.stowe>
Patchwork-id: 274814
O-Subject: [RHEL8.2 PATCH 50/51] iommu: Fix integer truncation
Bugzilla: 1753749
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1753749
Build Info: https://brewweb.devel.redhat.com/taskinfo?taskID=23690407
Upstream Status: 29fcea8ce7f3c16ebd267f8cb2f4a07887530aa9

commit 29fcea8ce7f3c16ebd267f8cb2f4a07887530aa9
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jun 17 15:30:54 2019 +0200

    iommu: Fix integer truncation

    On 32-bit architectures, phys_addr_t may be different from dma_add_t,
    both smaller and bigger. This can lead to an overflow during an assignment
    that clang warns about:

    drivers/iommu/dma-iommu.c:230:10: error: implicit conversion from 'dma_addr_t' (aka 'unsigned long long') to
          'phys_addr_t' (aka 'unsigned int') changes value from 18446744073709551615 to 4294967295 [-Werror,-Wconstant-conversion]

    Use phys_addr_t here because that is the type that the variable was
    declared as.

    Fixes: aadad097cd46 ("iommu/dma: Reserve IOVA for PCIe inaccessible DMA address")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

Signed-off-by: Phillip Lougher <plougher@redhat.com>