[mm] mm/vmalloc.c: avoid bogus -Wmaybe-uninitialized warning
Message-id: <aa73fa973f8fc1e71e7059642c0c2cd25150c126.1605724261.git@redhat.com>
Patchwork-id: 340046
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 bz1894223 PATCH 12/59] mm/vmalloc.c: avoid bogus -Wmaybe-uninitialized warning
Bugzilla: 1894223
RH-Acked-by: Waiman Long <longman@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

commit 2c9292336a09f7bf019689580ceea9a2d116b999
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Jun 28 12:07:09 2019 -0700

    mm/vmalloc.c: avoid bogus -Wmaybe-uninitialized warning

    gcc gets confused in pcpu_get_vm_areas() because there are too many
    branches that affect whether 'lva' was initialized before it gets used:

      mm/vmalloc.c: In function 'pcpu_get_vm_areas':
      mm/vmalloc.c:991:4: error: 'lva' may be used uninitialized in this function [-Werror=maybe-uninitialized]
          insert_vmap_area_augment(lva, &va->rb_node,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           &free_vmap_area_root, &free_vmap_area_list);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      mm/vmalloc.c:916:20: note: 'lva' was declared here
        struct vmap_area *lva;
                          ^~~

    Add an intialization to NULL, and check whether this has changed before
    the first use.

    [akpm@linux-foundation.org: tweak comments]
    Link: http://lkml.kernel.org/r/20190618092650.2943749-1-arnd@arndb.de
    Fixes: 68ad4a330433 ("mm/vmalloc.c: keep track of free blocks for vmap allocation")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Uladzislau Rezki (Sony) <urezki@gmail.com>
    Cc: Joel Fernandes <joelaf@google.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Nico Pache <npache@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>