[iommu] iommu: spapr_tce: Disable compile testing to fix build on book3s_32 config
Message-id: <20210116012107.726851-133-jsnitsel@redhat.com>
Patchwork-id: 349521
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 132/449] iommu: spapr_tce: Disable compile testing to fix build on book3s_32 config
Bugzilla: 1887546
RH-Acked-by: Mark Salter <msalter@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: 1887546
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=34307190

commit 9dd124b63a2e03c85dab42cc009a6fd9b9e571a1
Author: Krzysztof Kozlowski <krzk@kernel.org>
Date:   Tue Apr 14 16:26:30 2020 +0200

    iommu: spapr_tce: Disable compile testing to fix build on book3s_32 config

    Although SPAPR_TCE_IOMMU itself can be compile tested on certain PowerPC
    configurations, its presence makes arch/powerpc/kvm/Makefile to select
    modules which do not build in such configuration.

    The arch/powerpc/kvm/ modules use kvm_arch.spapr_tce_tables which exists
    only with CONFIG_PPC_BOOK3S_64.  However these modules are selected when
    COMPILE_TEST and SPAPR_TCE_IOMMU are chosen leading to build failures:

	In file included from arch/powerpc/include/asm/book3s/64/mmu-hash.h:20:0,
			 from arch/powerpc/kvm/book3s_64_vio_hv.c:22:
	arch/powerpc/include/asm/book3s/64/pgtable.h:17:0: error: "_PAGE_EXEC" redefined [-Werror]
	 #define _PAGE_EXEC  0x00001 /* execute permission */

	In file included from arch/powerpc/include/asm/book3s/32/pgtable.h:8:0,
			 from arch/powerpc/include/asm/book3s/pgtable.h:8,
			 from arch/powerpc/include/asm/pgtable.h:18,
			 from include/linux/mm.h:95,
			 from arch/powerpc/include/asm/io.h:29,
			 from include/linux/io.h:13,
			 from include/linux/irq.h:20,
			 from arch/powerpc/include/asm/hardirq.h:6,
			 from include/linux/hardirq.h:9,
			 from include/linux/kvm_host.h:7,
			 from arch/powerpc/kvm/book3s_64_vio_hv.c:12:
	arch/powerpc/include/asm/book3s/32/hash.h:29:0: note: this is the location of the previous definition
	 #define _PAGE_EXEC 0x200 /* software: exec allowed */

    Fixes: e93a1695d7fb ("iommu: Enable compile testing for some of drivers")
    Reported-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>
    Link: https://lore.kernel.org/r/20200414142630.21153-1-krzk@kernel.org
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

(cherry picked from commit 9dd124b63a2e03c85dab42cc009a6fd9b9e571a1)
Cc: Myron Stowe <myron.stowe@redhat.com>
Cc: Alex Williamson <alex.williamson@redhat.com>
Cc: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>