scsi: lpfc: Fix gcc -Wstringop-overread warning
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1923762

commit ada48ba70f6b98b7e93eea56770d6e6932734783
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 22 17:02:47 2021 +0100

    scsi: lpfc: Fix gcc -Wstringop-overread warning

    gcc-11 warns about an strnlen with a length larger than the size of the
    passed buffer:

    drivers/scsi/lpfc/lpfc_attr.c: In function 'lpfc_nvme_info_show':
    drivers/scsi/lpfc/lpfc_attr.c:518:25: error: 'strnlen' specified bound 4095 exceeds source size 24 [-Werror=stringop-overread]
      518 |                         strnlen(LPFC_NVME_INFO_MORE_STR, PAGE_SIZE - 1)
          |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    In this case, the code is entirely valid, as the string is properly
    terminated, and the size argument is only there out of extra caution in
    case it exceeds a page.

    This cannot really happen here, so just simplify it to a sizeof().

    Link: https://lore.kernel.org/r/20210322160253.4032422-10-arnd@kernel.org
    Fixes: afff0d2321ea ("scsi: lpfc: Add Buffer overflow check, when nvme_info larger than PAGE_SIZE")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Dick Kennedy <dkennedy@redhat.com>