[tools] libbpf: Fix sym->st_value print on 32-bit arches
Message-id: <bbede54c8365ea684c814b43fdd62aa1eac306b8.1581600558.git.jbenc@redhat.com>
Patchwork-id: 294801
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 20/43] libbpf: Fix sym->st_value print on 32-bit arches
Bugzilla: 1802507
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1802507
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=26435624

This patch is a dependency for the next patch. We wouldn't need it
otherwise, we support only 64bit in RHEL.

commit 7c3977d1e80401b1a25efded698b05d60ee26e31
Author: Alexei Starovoitov <ast@kernel.org>
Date:   Wed Nov 27 17:46:56 2019 -0800

    libbpf: Fix sym->st_value print on 32-bit arches

    The st_value field is a 64-bit value and causing this error on 32-bit arches:

    In file included from libbpf.c:52:
    libbpf.c: In function 'bpf_program__record_reloc':
    libbpf_internal.h:59:22: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'Elf64_Addr' {aka 'const long long unsigned int'} [-Werror=format=]

    Fix it with (__u64) cast.

    Fixes: 1f8e2bcb2cd5 ("libbpf: Refactor relocation handling")
    Reported-by: Arnaldo Carvalho de Melo <acme@redhat.com>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>