dm zoned: select CONFIG_CRC32
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1949682

Hand-patched Kconfig because RHEL8 doesn't have upstream's
s/---help---/help/ churn.

Signed-off-by: Mike Snitzer <snitzer@redhat.com>

commit b690bd546b227c32b860dae985a18bed8aa946fe
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sun Jan 3 22:40:51 2021 +0100

    dm zoned: select CONFIG_CRC32

    Without crc32 support, this driver fails to link:

    arm-linux-gnueabi-ld: drivers/md/dm-zoned-metadata.o: in function `dmz_write_sb':
    dm-zoned-metadata.c:(.text+0xe98): undefined reference to `crc32_le'
    arm-linux-gnueabi-ld: drivers/md/dm-zoned-metadata.o: in function `dmz_check_sb':
    dm-zoned-metadata.c:(.text+0x7978): undefined reference to `crc32_le'

    Fixes: 3b1a94c88b79 ("dm zoned: drive-managed zoned block device target")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Damien Le Moal <damien.lemoal@wdc.com>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>