[scsi] scsi: qla2xxx: Simplify the functions for dumping firmware
Message-id: <20201029130752.15040-42-njavali@redhat.com>
Patchwork-id: 336088
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 v2 BZ 1887427 041/113] scsi: qla2xxx: Simplify the functions for dumping firmware
Bugzilla: 1887427
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Ewan Milne <emilne@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1887427

Tree: git://git.kernel.org/pub/scm/linux/kernel/git/mkp/scsi.git

commit 8ae178760b23e2055aecf8b8a54629cec7ccc58e
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Mon May 18 14:17:00 2020 -0700

    scsi: qla2xxx: Simplify the functions for dumping firmware

    Instead of passing an argument to the firmware dumping functions that tells
    these functions whether or not to obtain the hardware lock, obtain that
    lock before calling these functions. This patch fixes the following
    recently introduced C=2 build error:

      CHECK   drivers/scsi/qla2xxx/qla_tmpl.c
    drivers/scsi/qla2xxx/qla_tmpl.c:1133:1: error: Expected ; at end of statement
    drivers/scsi/qla2xxx/qla_tmpl.c:1133:1: error: got }
    drivers/scsi/qla2xxx/qla_tmpl.h:247:0: error: Expected } at end of function
    drivers/scsi/qla2xxx/qla_tmpl.h:247:0: error: got end-of-input

    Link: https://lore.kernel.org/r/20200518211712.11395-4-bvanassche@acm.org
    Fixes: cbb01c2f2f63 ("scsi: qla2xxx: Fix MPI failure AEN (8200) handling")
    Cc: Arun Easi <aeasi@marvell.com>
    Cc: Nilesh Javali <njavali@marvell.com>
    Cc: Himanshu Madhani <himanshu.madhani@oracle.com>
    Cc: Martin Wilck <mwilck@suse.com>
    Cc: Roman Bolshakov <r.bolshakov@yadro.com>
    Reviewed-by: Hannes Reinecke <hare@suse.de>
    Reviewed-by: Daniel Wagner <dwagner@suse.de>
    Signed-off-by: Bart Van Assche <bvanassche@acm.org>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Cc: Nilesh Javali <njavali@redhat.com>
Cc: Arun Easi <aeasi@redhat.com>
Cc: "Ewan D. Milne" <emilne@redhat.com>
Signed-off-by: Nilesh Javali <njavali@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>