[tools] tools, bpftool: Print correct error message when failing to load BTF
Message-id: <20200924164430.191293-144-yauheni.kaliuta@redhat.com>
Patchwork-id: 327991
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 144/243] tools, bpftool: Print correct error message when failing to load BTF
Bugzilla: 1874003
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874003

commit dc3ca5cf3e0be9fb73f4691247367d76a22bf30b
Author: Tobias Klauser <tklauser@distanz.ch>
Date:   Mon May 25 15:54:21 2020 +0200

    tools, bpftool: Print correct error message when failing to load BTF

    btf__parse_raw and btf__parse_elf return negative error numbers wrapped
    in an ERR_PTR, so the extracted value needs to be negated before passing
    them to strerror which expects a positive error number.

    Before:
      Error: failed to load BTF from .../vmlinux: Unknown error -2

    After:
      Error: failed to load BTF from .../vmlinux: No such file or directory

    Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/20200525135421.4154-1-tklauser@distanz.ch
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>