[tools] libbpf: Handle GCC built-in types for Arm NEON
Message-id: <20210113140908.457588-228-yauheni.kaliuta@redhat.com>
Patchwork-id: 348572
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 v2 228/291] libbpf: Handle GCC built-in types for Arm NEON
Bugzilla: 1874005
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874005

commit 702eddc77a905782083b14ccd05b23840675fd18
Author: Jean-Philippe Brucker <jean-philippe@linaro.org>
Date:   Wed Aug 12 16:39:10 2020 +0200

    libbpf: Handle GCC built-in types for Arm NEON

    When building Arm NEON (SIMD) code from lib/raid6/neon.uc, GCC emits
    DWARF information using a base type "__Poly8_t", which is internal to
    GCC and not recognized by Clang. This causes build failures when
    building with Clang a vmlinux.h generated from an arm64 kernel that was
    built with GCC.

            vmlinux.h:47284:9: error: unknown type name '__Poly8_t'
            typedef __Poly8_t poly8x16_t[16];
                    ^~~~~~~~~

    The polyX_t types are defined as unsigned integers in the "Arm C
    Language Extension" document (101028_Q220_00_en). Emit typedefs based on
    standard integer types for the GCC internal types, similar to those
    emitted by Clang.

    Including linux/kernel.h to use ARRAY_SIZE() incidentally redefined
    max(), causing a build bug due to different types, hence the seemingly
    unrelated change.

    Reported-by: Jakov Petrina <jakov.petrina@sartura.hr>
    Signed-off-by: Jean-Philippe Brucker <jean-philippe@linaro.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Link: https://lore.kernel.org/bpf/20200812143909.3293280-1-jean-philippe@linaro.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>