powerpc/maple: Fix declaration made after definition
Bugzilla: http://bugzilla.redhat.com/1924090
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37569338

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/

commit af6cf95c4d003fccd6c2ecc99a598fb854b537e7
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Mon Mar 23 15:27:29 2020 -0700

    powerpc/maple: Fix declaration made after definition

    When building ppc64 defconfig, Clang errors (trimmed for brevity):

      arch/powerpc/platforms/maple/setup.c:365:1: error: attribute declaration
      must precede definition [-Werror,-Wignored-attributes]
      machine_device_initcall(maple, maple_cpc925_edac_setup);
      ^

    machine_device_initcall expands to __define_machine_initcall, which in
    turn has the macro machine_is used in it, which declares mach_##name
    with an __attribute__((weak)). define_machine actually defines
    mach_##name, which in this file happens before the declaration, hence
    the warning.

    To fix this, move define_machine after machine_device_initcall so that
    the declaration occurs before the definition, which matches how
    machine_device_initcall and define_machine work throughout
    arch/powerpc.

    While we're here, remove some spaces before tabs.

    Fixes: 8f101a051ef0 ("edac: cpc925 MC platform device setup")
    Reported-by: Nick Desaulniers <ndesaulniers@google.com>
    Suggested-by: Ilie Halip <ilie.halip@gmail.com>
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20200323222729.15365-1-natechancellor@gmail.com
    Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>

Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>