[pinctrl] pinctrl: intel: mark intel_pin_to_gpio __maybe_unused
Message-id: <20200406171515.45972-74-darcari@redhat.com>
Patchwork-id: 299326
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1773772 073/108] pinctrl: intel: mark intel_pin_to_gpio __maybe_unused
Bugzilla: 1773772
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1773772

commit 55dac43747be98516a337285428806d177afaa3a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Sep 6 20:51:59 2019 +0200

    pinctrl: intel: mark intel_pin_to_gpio __maybe_unused

    The intel_pin_to_gpio() function is only called by the
    PM support functions and causes a warning when those are disabled:

    drivers/pinctrl/intel/pinctrl-intel.c:841:12: error: unused function 'intel_pin_to_gpio' [-Werror,-Wunused-function]

    Mark it __maybe_unused to suppress the warning.

    Suggested-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Chris Chiu <chiu@endlessm.com>
    Acked-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: Mika Westerberg <mika.westerberg@linux.intel.com>

Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>