[netdrv] net/mlx5e: CT: Fix stack usage compiler warning
Message-id: <20200519074934.6303-39-ahleihel@redhat.com>
Patchwork-id: 310541
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 BZ 1663246 38/63] net/mlx5e: CT: Fix stack usage compiler warning
Bugzilla: 1663246
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1663246
Upstream: v5.7-rc1

commit aded104d397c22a18b9040f5641309f426d6df27
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Mon Mar 16 15:47:03 2020 -0700

    net/mlx5e: CT: Fix stack usage compiler warning

    Fix the following warnings: [-Werror=frame-larger-than=]

    In function ‘mlx5_tc_ct_entry_add_rule’:
    drivers/net/ethernet/mellanox/mlx5/core/en/tc_ct.c:541:1:
    error: the frame size of 1136 bytes is larger than 1024 bytes

    In function ‘__mlx5_tc_ct_flow_offload’:
    drivers/net/ethernet/mellanox/mlx5/core/en/tc_ct.c:1049:1:
    error: the frame size of 1168 bytes is larger than 1024 bytes

    Fixes: 4c3844d9e97e ("net/mlx5e: CT: Introduce connection tracking")
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>
    Reviewed-by: Paul Blakey <paulb@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>