[x86] um: Fix header inclusion
Message-id: <20201027003220.16553-213-longman@redhat.com>
Patchwork-id: 335559
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH v2 212/213] um: Fix header inclusion
Bugzilla: 1548297
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Phil Auld <pauld@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1548297

commit 1c1a18b00d7e25d1bed3507880de2da07be704a2
Author: Vincenzo Frascino <vincenzo.frascino@arm.com>
Date:   Mon, 23 Mar 2020 12:41:09 +0000

    um: Fix header inclusion

    User Mode Linux is a flavor of x86 that from the vDSO prospective always
    falls back on system calls. This implies that it does not require any
    of the unified vDSO definitions and their inclusion causes side effects
    like this:

      In file included from include/vdso/processor.h:10:0,
                          from include/vdso/datapage.h:17,
                          from arch/x86/include/asm/vgtod.h:7,
                          from arch/x86/um/../kernel/sys_ia32.c:49:
      >> arch/x86/include/asm/vdso/processor.h:11:29: error: redefinition of 'rep_nop'
          static __always_inline void rep_nop(void)
                                      ^~~~~~~
         In file included from include/linux/rcupdate.h:30:0,
                          from include/linux/rculist.h:11,
                          from include/linux/pid.h:5,
                          from include/linux/sched.h:14,
                          from arch/x86/um/../kernel/sys_ia32.c:25:
         arch/x86/um/asm/processor.h:24:20: note: previous definition of 'rep_nop' was here
          static inline void rep_nop(void)

    Make sure that the unnecessary headers are not included when um is built
    to address the problem.

    Fixes: abc22418db02 ("x86/vdso: Enable x86 to use common headers")
    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Vincenzo Frascino <vincenzo.frascino@arm.com>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Link: https://lkml.kernel.org/r/20200323124109.7104-1-vincenzo.frascino@arm.com

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>