lockdep: Address clang -Wformat warning printing for %hd
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1954361

commit 6d48b7912cc72275dc7c59ff961c8bac7ef66a92
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon, 22 Mar 2021 12:55:25 +0100

    lockdep: Address clang -Wformat warning printing for %hd

    Clang doesn't like format strings that truncate a 32-bit
    value to something shorter:

      kernel/locking/lockdep.c:709:4: error: format specifies type 'short' but the argument has type 'int' [-Werror,-Wformat]

    In this case, the warning is a slightly questionable, as it could realize
    that both class->wait_type_outer and class->wait_type_inner are in fact
    8-bit struct members, even though the result of the ?: operator becomes an
    'int'.

    However, there is really no point in printing the number as a 16-bit
    'short' rather than either an 8-bit or 32-bit number, so just change
    it to a normal %d.

    Fixes: de8f5e4f2dc1 ("lockdep: Introduce wait-type checks")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Ingo Molnar <mingo@kernel.org>
    Link: https://lore.kernel.org/r/20210322115531.3987555-1-arnd@kernel.org

Signed-off-by: Waiman Long <longman@redhat.com>