scsi: qla2xxx: Remove unnecessary NULL check
Bugzilla: http://bugzilla.redhat.com/1925465

Tree: git://git.app.eng.bos.redhat.com/linux.git

commit c750a9c9c59a85843d447910a27da21c5bcf600a
Author: Dan Carpenter <dan.carpenter@oracle.com>
Date:   Thu Jan 21 09:08:41 2021 +0300

    scsi: qla2xxx: Remove unnecessary NULL check

    The list iterator can't be NULL so this check is not required.  Removing
    the check silences a Smatch warning about inconsistent NULL checking.

        drivers/scsi/qla2xxx/qla_dfs.c:371 qla_dfs_tgt_counters_show()
        error: we previously assumed 'fcport' could be null (see line 372)

    Link: https://lore.kernel.org/r/YAkaaSrhn1mFqyHy@mwanda
    Acked-by: Saurav Kashyap <skashyap@marvell.com>
    Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

Signed-off-by: Nilesh Javali <njavali@redhat.com>