[tools] bpftool: Skeleton should depend on libbpf
Message-id: <20200610045258.353158-94-yauheni.kaliuta@redhat.com>
Patchwork-id: 319412
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 094/235] bpftool: Skeleton should depend on libbpf
Bugzilla: 1845114
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1845114

commit 39be909c38a42543239de97087d3c93ea9272864
Author: Song Liu <songliubraving@fb.com>
Date:   Thu Mar 12 11:23:31 2020 -0700

    bpftool: Skeleton should depend on libbpf

    Add the dependency to libbpf, to fix build errors like:

      In file included from skeleton/profiler.bpf.c:5:
      .../bpf_helpers.h:5:10: fatal error: 'bpf_helper_defs.h' file not found
      #include "bpf_helper_defs.h"
               ^~~~~~~~~~~~~~~~~~~
      1 error generated.
      make: *** [skeleton/profiler.bpf.o] Error 1
      make: *** Waiting for unfinished jobs....

    Fixes: 47c09d6a9f67 ("bpftool: Introduce "prog profile" command")
    Suggested-by: Quentin Monnet <quentin@isovalent.com>
    Signed-off-by: Song Liu <songliubraving@fb.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Reviewed-by: Quentin Monnet <quentin@isovalent.com>
    Acked-by: John Fastabend <john.fastabend@gmail.com>
    Link: https://lore.kernel.org/bpf/20200312182332.3953408-3-songliubraving@fb.com

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>