[sound] ALSA: ASoC: msm8916-wcd-digital: Select REGMAP_MMIO to fix build error
Message-id: <15580872947136052-1263-patchset-jkysela@redhat.com>
Patchwork-id: 258478
O-Subject: [RHEL 8.1 PATCH 1262/2119] ALSA: ASoC: msm8916-wcd-digital: Select REGMAP_MMIO to fix build error
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Fix below build error:
ERROR: "__devm_regmap_init_mmio_clk" [sound/soc/codecs/snd-soc-msm8916-digital.ko] undefined!

Signed-off-by: Axel Lin <axel.lin@ingics.com>
Acked-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 5b86fa6d2903c41c3c3dbff4def76a5b8bbe0660)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>