[netdrv] e1000e: fix unused-function warning
Message-id: <20201021124652.115662-7-jkc@redhat.com>
Patchwork-id: 333755
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 BZ 1838750 06/13] e1000e: fix unused-function warning
Bugzilla: 1838750
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>
RH-Acked-by: Stefan Assmann <sassmann@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1838750

commit 880e6269fd6e60249c8f5f1b98295e9f7e56636d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 27 15:47:00 2020 +0200

    e1000e: fix unused-function warning

    The CONFIG_PM_SLEEP #ifdef checks in this file are inconsistent,
    leading to a warning about sometimes unused function:

    drivers/net/ethernet/intel/e1000e/netdev.c:137:13: error: unused function 'e1000e_check_me' [-Werror,-Wunused-function]

    Rather than adding more #ifdefs, just remove them completely
    and mark the PM functions as __maybe_unused to let the compiler
    work it out on it own.

    Fixes: e086ba2fccda ("e1000e: disable s0ix entry and exit flows for ME systems")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Tested-by: Aaron Brown <aaron.f.brown@intel.com>
    Signed-off-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>

Signed-off-by: Ken Cox <jkc@redhat.com>

Cc: Ken Cox <jkc@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>