[sound] ALSA: ASoC: simple-card-utils: fix build warning without CONFIG_OF
Message-id: <15580872947136052-1043-patchset-jkysela@redhat.com>
Patchwork-id: 257621
O-Subject: [RHEL 8.1 PATCH 1042/2119] ALSA: ASoC: simple-card-utils: fix build warning without CONFIG_OF
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

When CONFIG_OF is disabled, of_graph_parse_endpoint() does not
initialize 'info', and gcc can see that:

sound/soc/generic/simple-card-utils.c: In function 'asoc_simple_card_parse_graph_dai':
sound/soc/generic/simple-card-utils.c:284:13: error: 'info.port' may be used uninitialized in this function [-Werror=maybe-uninitialized]

It's probably best to check the return code anyway, and that also
takes care of the warning.

Fixes: b6f3fc005a2c ("ASoC: simple-card-utils: fixup asoc_simple_card_get_dai_id() counting")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit 2b320e046495e6cf02d1f0b1abf07042ac5635ea)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>