[security] security: export security_kernel_load_data function
Message-id: <20200527180156.23049-27-didoming@redhat.com>
Patchwork-id: 314579
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH BZ1781925 v2 26/106] security: export security_kernel_load_data function
Bugzilla: 1781925
RH-Acked-by: Bruno Meneguele <bmeneg@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1781925
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28848035

The firmware_loader can be built as a loadable module, which now
fails when CONFIG_SECURITY is enabled, because a call to the
security_kernel_load_data() function got added, and this is
not exported to modules:

ERROR: "security_kernel_load_data" [drivers/base/firmware_loader/firmware_class.ko] undefined!

Add an EXPORT_SYMBOL_GPL() to make it available here.

commit 83a68a06795fa47e77ea758f293a5946e9e02e84

Fixes: 6e852651f28e ("firmware: add call to LSM hook before firmware sysfs fallback")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: James Morris <james.morris@microsoft.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>