[kernel] mm/hmm: fix memremap.h, move dev_page_fault_t callback to hmm
Message-id: <20191126135817.19189-19-ddutile@redhat.com>
Patchwork-id: 289326
O-Subject: [PATCH RHEL-8.2 v3 18/45] mm/hmm: fix memremap.h, move dev_page_fault_t callback to hmm
Bugzilla: 1754737
RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>
RH-Acked-by: Baoquan He <bhe@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1754737

commit 063a7d1d3623db31ca5d2309cab6030ebf93b72f
Author: Dan Williams <dan.j.williams@intel.com>
Date:   Fri Dec 28 00:39:46 2018 -0800

    mm/hmm: fix memremap.h, move dev_page_fault_t callback to hmm

    The kbuild robot reported the following on a development branch that used
    memremap.h in a new path:

       In file included from arch/m68k/include/asm/pgtable_mm.h:148:0,
                         from arch/m68k/include/asm/pgtable.h:5,
                         from include/linux/memremap.h:7,
                         from drivers//dax/bus.c:3:
        arch/m68k/include/asm/motorola_pgtable.h: In function 'pgd_offset':
     >> arch/m68k/include/asm/motorola_pgtable.h:199:11: error: dereferencing pointer to incomplete type 'const struct mm_struct'
          return mm->pgd + pgd_index(address);
                   ^~

    The ->page_fault() callback is specific to HMM.  Move it to 'struct
    hmm_devmem' where the unusual asm/pgtable.h dependency can be contained in
    include/linux/hmm.h.  Longer term refactoring this dependency out of HMM
    is recommended, but in the meantime memremap.h remains generic.

    Link: http://lkml.kernel.org/r/154534090899.3120190.6652620807617715272.stgit@dwillia2-desk3.amr.corp.intel.com
    Fixes: 5042db43cc26 ("mm/ZONE_DEVICE: new type of ZONE_DEVICE memory...")
    Signed-off-by: Dan Williams <dan.j.williams@intel.com>
    Reviewed-by: "Jrme Glisse" <jglisse@redhat.com>
    Cc: Logan Gunthorpe <logang@deltatee.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Conflict: For (false) kabi reasons, have to DEPRECATE page_fault in dev_pagemap{}.
In order to DEPRECATE, must keep struct definition and pgtable include.

Signed-off-by: Donald Dutile <ddutile@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>