[char] tpm: Export tpm2_get_cc_attrs_tbl for ibmvtpm driver as module
Message-id: <20200505042623.220508-4-dgibson@redhat.com>
Patchwork-id: 306161
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 kernel virt PATCH 3/3] tpm: Export tpm2_get_cc_attrs_tbl for ibmvtpm driver as module
Bugzilla: 1781915
RH-Acked-by: Jerry Snitselaar <jsnitsel@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>

From: Stefan Berger <stefanb@linux.ibm.com>

This patch fixes the following problem when the ibmvtpm driver
is built as a module:

ERROR: modpost: "tpm2_get_cc_attrs_tbl" [drivers/char/tpm/tpm_ibmvtpm.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make: *** [Makefile:1298: modules] Error 2

Fixes: 18b3670d79ae ("tpm: ibmvtpm: Add support for TPM2")
Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
Reported-by: Sachin Sant <sachinp@linux.vnet.ibm.com>
Tested-by: Sachin Sant <sachinp@linux.vnet.ibm.com>
Reviewed-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
(cherry picked from commit 684c6bd806253bf65dbb64978fc113ff081b4aea)

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1781915

Signed-off-by: David Gibson <dgibson@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>