[wireless] ath10k: fix ath10k_pci struct layout
Message-id: <20201023173140.4030081-585-jarod@redhat.com>
Patchwork-id: 334665
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 PATCH 0584/1137] ath10k: fix ath10k_pci struct layout
Bugzilla: 1860496
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1860496

commit 32221df6765b3773ff1af37c77f8531ebc48f246
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Sat May 9 14:06:33 2020 +0200

    ath10k: fix ath10k_pci struct layout

    gcc-10 correctly points out a bug with a zero-length array in
    struct ath10k_pci:

    drivers/net/wireless/ath/ath10k/ahb.c: In function 'ath10k_ahb_remove':
    drivers/net/wireless/ath/ath10k/ahb.c:30:9: error: array subscript 0 is outside the bounds of an interior zero-length array 'struct ath10k_ahb[0]' [-Werror=zero-length-bounds]
       30 |  return &((struct ath10k_pci *)ar->drv_priv)->ahb[0];
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from drivers/net/wireless/ath/ath10k/ahb.c:13:
    drivers/net/wireless/ath/ath10k/pci.h:185:20: note: while referencing 'ahb'
      185 |  struct ath10k_ahb ahb[0];
          |                    ^~~

    The last addition to the struct ignored the comments and added
    new members behind the array that must remain last.

    Change it to a flexible-array member and move it last again to
    make it work correctly, prevent the same thing from happening
    again (all compilers warn about flexible-array members in the
    middle of a struct) and get it to build without warnings.

    Fixes: 521fc37be3d8 ("ath10k: Avoid override CE5 configuration for QCA99X0 chipsets")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/20200509120707.188595-2-arnd@arndb.de

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>