[netdrv] mlx5: FWTrace, Reduce stack usage
Message-id: <20191105095158.18958-311-ahleihel@redhat.com>
Patchwork-id: 283327
O-Subject: [RHEL8.2 BZ 1724336 310/335] net/mlx5: FWTrace, Reduce stack usage
Bugzilla: 1724336
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1724336
Upstream: v5.4-rc1

commit fa355bb1b0373e7fe087cfc830b1b0b9b6130388
Author: Saeed Mahameed <saeedm@mellanox.com>
Date:   Tue Sep 10 12:35:59 2019 -0700

    net/mlx5: FWTrace, Reduce stack usage

    Mark mlx5_tracer_print_trace as noinline as the function only uses 512
    bytes on the stack to avoid the following build warning:

    drivers/net/ethernet/mellanox/mlx5/core/diag/fw_tracer.c:660:13: error: stack frame size of 1032 bytes in function 'mlx5_fw_tracer_handle_traces' [-Werror,-Wframe-larger-than=]

    Fixes: 70dd6fdb8987 ("net/mlx5: FW tracer, parse traces and kernel tracing support")
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>