[powerpc] Fix compile issue with force DAWR
Message-id: <20201117152733.1509856-9-gkurz@redhat.com>
Patchwork-id: 339696
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 kernel virt PATCH 08/41] powerpc: Fix compile issue with force DAWR
Bugzilla: 1882796
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Michael Neuling <mikey@neuling.org>

If you compile with KVM but without CONFIG_HAVE_HW_BREAKPOINT you fail
at linking with:
  arch/powerpc/kvm/book3s_hv_rmhandlers.o:(.text+0x708): undefined reference to `dawr_force_enable'

This was caused by commit c1fe190c0672 ("powerpc: Add force enable of
DAWR on P9 option").

This moves a bunch of code around to fix this. It moves a lot of the
DAWR code in a new file and creates a new CONFIG_PPC_DAWR to enable
compiling it.

Fixes: c1fe190c0672 ("powerpc: Add force enable of DAWR on P9 option")
Signed-off-by: Michael Neuling <mikey@neuling.org>
[mpe: Minor formatting in set_dawr()]
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
(cherry picked from commit a278e7ea608bea5fe6df9b6ae91fa134655c5d2c)
Signed-off-by: Greg Kurz <gkurz@redhat.com>

Conflicts:
	arch/powerpc/Kconfig

Contextual conflicts because RHEL doesn't have upstream 2eac9c2dfb2b9
and 20f1b79d33590, and because downstream 7f2812180e718 moved ZONE_DMA
around to maintain kABI.

Signed-off-by: Jan Stancek <jstancek@redhat.com>