[net] netfilter: kconfig: nat related expression depend on nftables core
Message-id: <20200605143206.24398-23-fwestpha@redhat.com>
Patchwork-id: 317522
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 22/48] netfilter: kconfig: nat related expression depend on nftables core
Bugzilla: 1579145
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Guillaume Nault <gnault@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1579145
Upstream Status: commit e07584122089

commit e0758412208960be9de11e6d2350c81ffd88410f
Author: Florian Westphal <fw@strlen.de>
Date:   Sat Aug 25 01:14:46 2018 +0200

    netfilter: kconfig: nat related expression depend on nftables core

    NF_TABLES_IPV4 is now boolean so it is possible to set

    NF_TABLES=m
    NF_TABLES_IPV4=y
    NFT_CHAIN_NAT_IPV4=y

    which causes:
    nft_chain_nat_ipv4.c:(.text+0x6d): undefined reference to `nft_do_chain'

    Wrap NFT_CHAIN_NAT_IPV4 and related nat expressions with NF_TABLES to
    restore the dependency.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Fixes: 02c7b25e5f54 ("netfilter: nf_tables: build-in filter chain type")
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Acked-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>