[netdrv] dynamic_debug: provide dynamic_hex_dump stub
Message-id: <0b281bff6b399df1ae5eb2ba7e9d7805ae73785f.1588173512.git.jtoppins@redhat.com>
Patchwork-id: 305822
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL-8.3 v2 30/84] dynamic_debug: provide dynamic_hex_dump stub
Bugzilla: 1780645
RH-Acked-by: Vladis Dronov <vdronov@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Corinna Vinschen <vinschen@redhat.com>

The ionic driver started using dymamic_hex_dump(), but
that is not always defined:

drivers/net/ethernet/pensando/ionic/ionic_main.c:229:2: error: implicit declaration of function 'dynamic_hex_dump' [-Werror,-Wimplicit-function-declaration]

Add a dummy implementation to use when CONFIG_DYNAMIC_DEBUG
is disabled, printing nothing.

Fixes: 938962d55229 ("ionic: Add adminq action")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Shannon Nelson <snelson@pensando.io>
Signed-off-by: Jakub Kicinski <jakub.kicinski@netronome.com>
(cherry picked from commit 011c7289de619d76f82b0d9e9fec3f59d2fe57f7)
Bugzilla: 1780645
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28076826
Tested: partner and local testing show driver seems to work as expected
Signed-off-by: Jonathan Toppins <jtoppins@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>