[x86] kvm: x86/mmu: Avoid modulo operator on 64-bit value to fix i386 build
Message-id: <20201105180132.489350-1-vkuznets@redhat.com>
Patchwork-id: 337969
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 virt PATCH v2 331/340] KVM: x86/mmu: Avoid modulo operator on 64-bit value to fix i386 build
Bugzilla: 1882793
RH-Acked-by: Andrew Jones <drjones@redhat.com>
RH-Acked-by: Bandan Das <bsd@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

From: Sean Christopherson <sean.j.christopherson@intel.com>

Replace a modulo operator with the more common pattern for computing the
gfn "offset" of a huge page to fix an i386 build error.

  arch/x86/kvm/mmu/tdp_mmu.c:212: undefined reference to `__umoddi3'

In fact, almost all of tdp_mmu.c can be elided on 32-bit builds, but
that is a much larger patch.

Fixes: 2f2fad0897cb ("kvm: x86/mmu: Add functions to handle changed TDP SPTEs")
Reported-by: Daniel Daz <daniel.diaz@linaro.org>
Signed-off-by: Sean Christopherson <sean.j.christopherson@intel.com>
Message-Id: <20201024031150.9318-1-sean.j.christopherson@intel.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
(cherry picked from commit 764388ce598f0c3f5c7c39f45279104cb9e18be5)
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>