[fs] ovl: fix bogus -Wmaybe-unitialized warning
Message-id: <20200622192149.32365-11-mszeredi@redhat.com>
Patchwork-id: 321299
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 PATCH 10/73] ovl: fix bogus -Wmaybe-unitialized warning
Bugzilla: 1849770
RH-Acked-by: Vivek Goyal <vgoyal@redhat.com>
RH-Acked-by: Ian Kent <ikent@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1849770
Upstream status: Linus
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=29428465
Testing: xfstests -overlay

commit 1dac6f5b0ed2601be21bb4e27a44b0c3e667b7f4
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jun 17 14:39:29 2019 +0200

    ovl: fix bogus -Wmaybe-unitialized warning

    gcc gets a bit confused by the logic in ovl_setup_trap() and
    can't figure out whether the local 'trap' variable in the caller
    was initialized or not:

    fs/overlayfs/super.c: In function 'ovl_fill_super':
    fs/overlayfs/super.c:1333:4: error: 'trap' may be used uninitialized in this function [-Werror=maybe-uninitialized]
        iput(trap);
        ^~~~~~~~~~
    fs/overlayfs/super.c:1312:17: note: 'trap' was declared here

    Reword slightly to make it easier for the compiler to understand.

    Fixes: 146d62e5a586 ("ovl: detect overlapping layers")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>

Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>