[net] sk_msg: Don't use RCU_INIT_POINTER on sk_user_data
Message-id: <d36180cd09c1dae7518983eb13c3d4edaee28ebe.1589962818.git.sdubroca@redhat.com>
Patchwork-id: 312961
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 net 52/52] net, sk_msg: Don't use RCU_INIT_POINTER on sk_user_data
Bugzilla: 1819627
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1819627
Brew: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=28687932
Tested: sockmap + tls selftests

commit 7a1ca97269ee197ea967de2c9412d8e7e2274ee6
Author: Jakub Sitnicki <jakub@cloudflare.com>
Date:   Thu Apr 2 14:55:24 2020 +0200

    net, sk_msg: Don't use RCU_INIT_POINTER on sk_user_data

    sparse reports an error due to use of RCU_INIT_POINTER helper to assign to
    sk_user_data pointer, which is not tagged with __rcu:

    net/core/sock.c:1875:25: error: incompatible types in comparison expression (different address spaces):
    net/core/sock.c:1875:25:    void [noderef] <asn:4> *
    net/core/sock.c:1875:25:    void *

    ... and rightfully so. sk_user_data is not always treated as a pointer to
    an RCU-protected data. When it is used to point at an RCU-protected object,
    we access it with __sk_user_data to inform sparse about it.

    In this case, when the child socket does not inherit sk_user_data from the
    parent, there is no reason to treat it as an RCU-protected pointer.

    Use a regular assignment to clear the pointer value.

    Fixes: f1ff5ce2cd5e ("net, sk_msg: Clear sk_user_data pointer on clone if tagged")
    Reported-by: kbuild test robot <lkp@intel.com>
    Signed-off-by: Jakub Sitnicki <jakub@cloudflare.com>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Link: https://lore.kernel.org/bpf/20200402125524.851439-1-jakub@cloudflare.com

Signed-off-by: Sabrina Dubroca <sdubroca@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>