KVM: PPC: Make the VMX instruction emulation routines static
Bugzilla: http://bugzilla.redhat.com/1945745

commit 9236f57a9e51c72ce426ccd2e53e123de7196a0f
Author: Cédric Le Goater <clg@kaod.org>
Date:   Mon Jan 4 15:32:01 2021 +0100

    KVM: PPC: Make the VMX instruction emulation routines static

    These are only used locally. It fixes these W=1 compile errors :

    ../arch/powerpc/kvm/powerpc.c:1521:5: error: no previous prototype for ‘kvmppc_get_vmx_dword’ [-Werror=missing-prototypes]
     1521 | int kvmppc_get_vmx_dword(struct kvm_vcpu *vcpu, int index, u64 *val)
          |     ^~~~~~~~~~~~~~~~~~~~
    ../arch/powerpc/kvm/powerpc.c:1539:5: error: no previous prototype for ‘kvmppc_get_vmx_word’ [-Werror=missing-prototypes]
     1539 | int kvmppc_get_vmx_word(struct kvm_vcpu *vcpu, int index, u64 *val)
          |     ^~~~~~~~~~~~~~~~~~~
    ../arch/powerpc/kvm/powerpc.c:1557:5: error: no previous prototype for ‘kvmppc_get_vmx_hword’ [-Werror=missing-prototypes]
     1557 | int kvmppc_get_vmx_hword(struct kvm_vcpu *vcpu, int index, u64 *val)
          |     ^~~~~~~~~~~~~~~~~~~~
    ../arch/powerpc/kvm/powerpc.c:1575:5: error: no previous prototype for ‘kvmppc_get_vmx_byte’ [-Werror=missing-prototypes]
     1575 | int kvmppc_get_vmx_byte(struct kvm_vcpu *vcpu, int index, u64 *val)
          |     ^~~~~~~~~~~~~~~~~~~

    Fixes: acc9eb9305fe ("KVM: PPC: Reimplement LOAD_VMX/STORE_VMX instruction mmio emulation with analyse_instr() input")
    Signed-off-by: Cédric Le Goater <clg@kaod.org>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20210104143206.695198-19-clg@kaod.org

Signed-off-by: Greg Kurz <gkurz@redhat.com>