Avoid macro redefinition in compiler-{clang,gcc}.h
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1907271
Upstream Status: RHEL only
Tested: It builds, boots and fixes the bcc issue.

Commits ee3dd9f43eb5c and f2579a08a6f42 introduced macro redefinitions
in compiler-clang.h and compiler-gcc.h. The main issue is that the
order in which compiler-clang and compiler-gcc.h are included have
changed upstream (upstream commit 815f0ddb346c1) but the backport of
upstream commits 2bd926b439b4 and dfd402a4c4ba does not take that into
account and redefines __no_sanitize_address and
__no_sanitize_thread. The order of the headers is important since clang
also defines __GNUC__, and thus compiler-gcc.h is also included when
compiled with clang.
There is also an obvious redefinition of __no_sanitize_address in
compiler-gcc.h.

This issue causes multiple bcc tools to issue the following warning:
In file included from include/linux/compiler_types.h:78:
include/linux/compiler-clang.h:29:9: warning: '__no_sanitize_address' macro redefined [-Wmacro-redefined]
        ^
include/linux/compiler-gcc.h:339:9: note: previous definition is here
        ^
1 warning generated.

Fixes: ee3dd9f43eb5c and f2579a08a6f42

Signed-off-by: Jerome Marchand <jmarchan@redhat.com>