perf tools: Fix documentation of verbose options
Bugzilla: https://bugzilla.redhat.com/1944685

upstream
========
commit b55ff1d1456c86209ba28fd06b1b5fb0e05d92c3
Author: Ian Rogers <irogers@google.com>
Date: Fri Feb 26 10:31:44 2021 -0800

description
===========
Option doesn't take a value, make sure the man pages agree. For example:

  $ perf evlist --verbose=1
   Error: option `verbose' takes no value

Signed-off-by: Michael Petlan <mpetlan@redhat.com>