[tools] selftests/bpf: Build urandom_read with LDFLAGS and LDLIBS
Message-id: <20200608222925.282045-181-yauheni.kaliuta@redhat.com>
Patchwork-id: 318141
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.3 181/257] selftests/bpf: Build urandom_read with LDFLAGS and LDLIBS
Bugzilla: 1813372
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Toke Høiland-Jørgensen <toke@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1813372

commit 1222653cc0489fa9304a36f7d9593ecaeb51efe1
Author: Daniel Díaz <daniel.diaz@linaro.org>
Date:   Wed Jan 22 17:44:24 2020 +0100

    selftests/bpf: Build urandom_read with LDFLAGS and LDLIBS

    During cross-compilation, it was discovered that LDFLAGS and
    LDLIBS were not being used while building binaries, leading
    to defaults which were not necessarily correct.

    OpenEmbedded reported this kind of problem:

      ERROR: QA Issue: No GNU_HASH in the ELF binary [...], didn't pass LDFLAGS?

    Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Acked-by: John Fastabend <john.fastabend@gmail.com>

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>