kunit: tool: fix display of make errors
commit 1abdd39f14b25dd2d69096b624a4f86f158a9feb
Author: Daniel Latypov <dlatypov@google.com>
Date:   Wed Sep 30 11:31:51 2020 -0700

    kunit: tool: fix display of make errors

    CalledProcessError stores the output of the failed process as `bytes`,
    not a `str`.

    So when we log it on build error, the make output is all crammed into
    one line with "\n" instead of actually printing new lines.

    After this change, we get readable output with new lines, e.g.
    >   CC      lib/kunit/kunit-example-test.o
    > In file included from ../lib/kunit/test.c:9:
    > ../include/kunit/test.h:22:1: error: unknown type name ‘invalid_type_that_causes_compile’
    >    22 | invalid_type_that_causes_compile errors;
    >       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    > make[3]: *** [../scripts/Makefile.build:283: lib/kunit/test.o] Error 1

    Secondly, trying to concat exceptions to strings will fail with
    > TypeError: can only concatenate str (not "OSError") to str
    so fix this with an explicit cast to str.

    Signed-off-by: Daniel Latypov <dlatypov@google.com>
    Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
    Tested-by: Brendan Higgins <brendanhiggins@google.com>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1939309
Signed-off-by: Nico Pache <npache@redhat.com>