[net] sched: act_bpf: validate the control action inside init()
Message-id: <20190610212005.12299-134-ivecera@redhat.com>
Patchwork-id: 264121
O-Subject: [RHEL-8.1 net PATCH 133/194] net/sched: act_bpf: validate the control action inside init()
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit 4e1810049c267c203c19130301203d0591174535
Author: Davide Caratti <dcaratti@redhat.com>
Date:   Wed Mar 20 15:00:00 2019 +0100

    net/sched: act_bpf: validate the control action inside init()

    the following script:

     # tc filter add dev crash0 egress matchall \
     > action bpf bytecode '1,6 0 0 4294967295' pass index 90
     # tc actions replace action bpf \
     > bytecode '1,6 0 0 4294967295' goto chain 42 index 90 cookie c1a0c1a0
     # tc action show action bpf

    had the following output:

     Error: Failed to init TC action chain.
     We have an error talking to the kernel
     total acts 1

             action order 0: bpf bytecode '1,6 0 0 4294967295' default-action goto chain 42
             index 90 ref 2 bind 1
             cookie c1a0c1a0

    Then, the first packet transmitted by crash0 made the kernel crash:

     RIP: 0010:tcf_action_exec+0xb8/0x100
     Code: 00 00 00 20 74 1d 83 f8 03 75 09 49 83 c4 08 4d 39 ec 75 bc 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 49 8b 97 a8 00 00 00 <48> 8b 12 48 89 55 00 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3
     RSP: 0018:ffffb3a0803dfa90 EFLAGS: 00010246
     RAX: 000000002000002a RBX: ffff942b347ada00 RCX: 0000000000000000
     RDX: 0000000000000000 RSI: ffffb3a08034d038 RDI: ffff942b347ada00
     RBP: ffffb3a0803dfb30 R08: 0000000000000000 R09: 0000000000000000
     R10: 0000000000000000 R11: ffffb3a0803dfb0c R12: ffff942b3b682b00
     R13: ffff942b3b682b08 R14: 0000000000000001 R15: ffff942b3b682f00
     FS:  00007f6160a72740(0000) GS:ffff942b3da80000(0000) knlGS:0000000000000000
     CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
     CR2: 0000000000000000 CR3: 00000000795a4002 CR4: 00000000001606e0
     Call Trace:
      tcf_classify+0x58/0x120
      __dev_queue_xmit+0x40a/0x890
      ? ip_finish_output2+0x16f/0x430
      ip_finish_output2+0x16f/0x430
      ? ip_output+0x69/0xe0
      ip_output+0x69/0xe0
      ? ip_forward_options+0x1a0/0x1a0
      ip_send_skb+0x15/0x40
      raw_sendmsg+0x8e1/0xbd0
      ? sched_clock+0x5/0x10
      ? sched_clock_cpu+0xc/0xa0
      ? try_to_wake_up+0x54/0x480
      ? ldsem_down_read+0x3f/0x280
      ? _cond_resched+0x15/0x40
      ? down_read+0xe/0x30
      ? copy_termios+0x1e/0x70
      ? tty_mode_ioctl+0x1b6/0x4c0
      ? sock_sendmsg+0x36/0x40
      sock_sendmsg+0x36/0x40
      __sys_sendto+0x10e/0x140
      ? do_vfs_ioctl+0xa4/0x640
      ? handle_mm_fault+0xdc/0x210
      ? syscall_trace_enter+0x1df/0x2e0
      ? __audit_syscall_exit+0x216/0x260
      __x64_sys_sendto+0x24/0x30
      do_syscall_64+0x5b/0x180
      entry_SYSCALL_64_after_hwframe+0x44/0xa9
     RIP: 0033:0x7f615f7e3c03
     Code: 48 8b 0d 90 62 2c 00 f7 d8 64 89 01 48 83 c8 ff c3 66 0f 1f 44 00 00 83 3d 9d c3 2c 00 00 75 13 49 89 ca b8 2c 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 34 c3 48 83 ec 08 e8 4b cc 00 00 48 89 04 24
     RSP: 002b:00007ffee5d8cc28 EFLAGS: 00000246 ORIG_RAX: 000000000000002c
     RAX: ffffffffffffffda RBX: 000055a4f28f1700 RCX: 00007f615f7e3c03
     RDX: 0000000000000040 RSI: 000055a4f28f1700 RDI: 0000000000000003
     RBP: 00007ffee5d8e340 R08: 000055a4f28ee510 R09: 0000000000000010
     R10: 0000000000000000 R11: 0000000000000246 R12: 0000000000000040
     R13: 000055a4f28f16c0 R14: 000055a4f28ef69c R15: 0000000000000080
     Modules linked in: act_bpf veth ip6table_filter ip6_tables iptable_filter binfmt_misc ext4 mbcache crct10dif_pclmul jbd2 crc32_pclmul snd_hda_codec_generic ghash_clmulni_intel snd_hda_intel snd_hda_codec snd_hwdep snd_hda_core snd_seq snd_seq_device snd_pcm aesni_intel crypto_simd cryptd glue_helper pcspkr joydev virtio_balloon snd_timer snd i2c_piix4 soundcore nfsd auth_rpcgss nfs_acl lockd grace sunrpc ip_tables xfs ata_generic pata_acpi qxl drm_kms_helper virtio_blk virtio_net virtio_console net_failover failover syscopyarea sysfillrect sysimgblt fb_sys_fops ttm drm crc32c_intel ata_piix serio_raw libata virtio_pci virtio_ring virtio floppy dm_mirror dm_region_hash dm_log dm_mod
     CR2: 0000000000000000

    Validating the control action within tcf_bpf_init() proved to fix the
    above issue. A TDC selftest is added to verify the correct behavior.

    Fixes: db50514f9a9c ("net: sched: add termination action to allow goto chain")
    Fixes: 97763dc0f401 ("net_sched: reject unknown tcfa_action values")
    Signed-off-by: Davide Caratti <dcaratti@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>