[net] netfilter: nf_tables: allow lookups in dynamic sets
Message-id: <20191007145252.6034-6-fwestpha@redhat.com>
Patchwork-id: 276920
O-Subject: [RHEL8.2 net 5/5] netfilter: nf_tables: allow lookups in dynamic sets
Bugzilla: 1759074
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1759074
Upstream Status: commit acab71317737

commit acab713177377d9e0889c46bac7ff0cfb9a90c4d
Author: Florian Westphal <fw@strlen.de>
Date:   Thu Sep 19 16:56:44 2019 +0200

    netfilter: nf_tables: allow lookups in dynamic sets

    This un-breaks lookups in sets that have the 'dynamic' flag set.
    Given this active example configuration:

    table filter {
      set set1 {
        type ipv4_addr
        size 64
        flags dynamic,timeout
        timeout 1m
      }

      chain input {
         type filter hook input priority 0; policy accept;
      }
    }

    ... this works:
    nft add rule ip filter input add @set1 { ip saddr }

    -> whenever rule is triggered, the source ip address is inserted
    into the set (if it did not exist).

    This won't work:
    nft add rule ip filter input ip saddr @set1 counter
    Error: Could not process rule: Operation not supported

    In other words, we can add entries to the set, but then can't make
    matching decision based on that set.

    That is just wrong -- all set backends support lookups (else they would
    not be very useful).
    The failure comes from an explicit rejection in nft_lookup.c.

    Looking at the history, it seems like NFT_SET_EVAL used to mean
    'set contains expressions' (aka. "is a meter"), for instance something like

     nft add rule ip filter input meter example { ip saddr limit rate 10/second }
     or
     nft add rule ip filter input meter example { ip saddr counter }

    The actual meaning of NFT_SET_EVAL however, is
    'set can be updated from the packet path'.

    'meters' and packet-path insertions into sets, such as
    'add @set { ip saddr }' use exactly the same kernel code (nft_dynset.c)
    and thus require a set backend that provides the ->update() function.

    The only set that provides this also is the only one that has the
    NFT_SET_EVAL feature flag.

    Removing the wrong check makes the above example work.
    While at it, also fix the flag check during set instantiation to
    allow supported combinations only.

    Fixes: 8aeff920dcc9b3f ("netfilter: nf_tables: add stateful object reference to set elements")
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>