[net] ip6_vti: use IS_REACHABLE to avoid some compile errors
Message-id: <9f87f90e717b0c6dc5f97ed87f0cd61398594ae3.1595405604.git.lxin@redhat.com>
Patchwork-id: 322405
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net PATCH 16/16] ip6_vti: use IS_REACHABLE to avoid some compile errors
Bugzilla: 1840976 1835075
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Brew Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=30221458
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1840976
          https://bugzilla.redhat.com/show_bug.cgi?id=1835075
Upstream Status: ipsec-next.git commit 96a20829
Tested: CKI and bug reproducer

commit 96a208295040c00c85d022720c10ec1a751b9bdb
Author: Xin Long <lucien.xin@gmail.com>
Date:   Fri Jul 17 15:03:14 2020 +0800

    ip6_vti: use IS_REACHABLE to avoid some compile errors

    Naresh reported some compile errors:

      arm build failed due this error on linux-next 20200713 and  20200713
      net/ipv6/ip6_vti.o: In function `vti6_rcv_tunnel':
      ip6_vti.c:(.text+0x1d20): undefined reference to `xfrm6_tunnel_spi_lookup'

    This happened when set CONFIG_IPV6_VTI=y and CONFIG_INET6_TUNNEL=m.
    We don't really want ip6_vti to depend inet6_tunnel completely, but
    only to disable the tunnel code when inet6_tunnel is not seen.

    So instead of adding "select INET6_TUNNEL" for IPV6_VTI, this patch
    is only to change to IS_REACHABLE to avoid these compile error.

    Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
    Fixes: 08622869ed3f ("ip6_vti: support IP6IP6 tunnel processing with .cb_handler")
    Signed-off-by: Xin Long <lucien.xin@gmail.com>
    Signed-off-by: Steffen Klassert <steffen.klassert@secunet.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>