[net] sched: act_mirred: validate the control action inside init()
Message-id: <20190610212005.12299-138-ivecera@redhat.com>
Patchwork-id: 264126
O-Subject: [RHEL-8.1 net PATCH 137/194] net/sched: act_mirred: validate the control action inside init()
Bugzilla: 1688236 1687456
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1688236
Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1687456

Upstream commit(s):
commit ff9721d32b1aba8bf46a06df20827d0a5d52ec48
Author: Davide Caratti <dcaratti@redhat.com>
Date:   Wed Mar 20 15:00:04 2019 +0100

    net/sched: act_mirred: validate the control action inside init()

    the following script:

     # tc qdisc add dev crash0 clsact
     # tc filter add dev crash0 egress matchall \
     > action mirred ingress mirror dev lo pass
     # tc actions replace action mirred \
     > ingress mirror dev lo goto chain 42 index 90 cookie c1a0c1a0
     # tc actions show action mirred

    had the following output:

     Error: Failed to init TC action chain.
     We have an error talking to the kernel
     total acts 1

             action order 0: mirred (Ingress Mirror to device lo) goto chain 42
             index 90 ref 2 bind 1
             cookie c1a0c1a0

    Then, the first packet transmitted by crash0 made the kernel crash:

     Mirror/redirect action on
     BUG: unable to handle kernel NULL pointer dereference at 0000000000000000
     #PF error: [normal kernel read fault]
     PGD 0 P4D 0
     Oops: 0000 [#1] SMP PTI
     CPU: 3 PID: 47 Comm: kworker/3:1 Not tainted 5.0.0-rc4.gotochain_crash+ #533
     Hardware name: Red Hat KVM, BIOS 0.5.1 01/01/2011
     Workqueue: ipv6_addrconf addrconf_dad_work
     RIP: 0010:tcf_action_exec+0xb8/0x100
     Code: 00 00 00 20 74 1d 83 f8 03 75 09 49 83 c4 08 4d 39 ec 75 bc 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3 49 8b 97 a8 00 00 00 <48> 8b 12 48 89 55 00 48 83 c4 10 5b 5d 41 5c 41 5d 41 5e 41 5f c3
     RSP: 0018:ffffa772404b7ad0 EFLAGS: 00010246
     RAX: 000000002000002a RBX: ffff9c5afc3f4300 RCX: 0000000000000000
     RDX: 0000000000000000 RSI: ffff9c5afdba9380 RDI: 0000000000029380
     RBP: ffffa772404b7b70 R08: ffff9c5af7010028 R09: ffff9c5af7010029
     R10: 0000000000000000 R11: ffff9c5af94c6a38 R12: ffff9c5af7953000
     R13: ffff9c5af7953008 R14: 0000000000000001 R15: ffff9c5af7953d00
     FS:  0000000000000000(0000) GS:ffff9c5afdb80000(0000) knlGS:0000000000000000
     CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
     CR2: 0000000000000000 CR3: 000000007c514004 CR4: 00000000001606e0
     Call Trace:
      tcf_classify+0x58/0x120
      __dev_queue_xmit+0x40a/0x890
      ? ndisc_next_option+0x50/0x50
      ? ___neigh_create+0x4d5/0x680
      ? ip6_finish_output2+0x1b5/0x590
      ip6_finish_output2+0x1b5/0x590
      ? ip6_output+0x68/0x110
      ip6_output+0x68/0x110
      ? nf_hook.constprop.28+0x79/0xc0
      ndisc_send_skb+0x248/0x2e0
      ndisc_send_ns+0xf8/0x200
      ? addrconf_dad_work+0x389/0x4b0
      addrconf_dad_work+0x389/0x4b0
      ? __switch_to_asm+0x34/0x70
      ? process_one_work+0x195/0x380
      ? addrconf_dad_completed+0x370/0x370
      process_one_work+0x195/0x380
      worker_thread+0x30/0x390
      ? process_one_work+0x380/0x380
      kthread+0x113/0x130
      ? kthread_park+0x90/0x90
      ret_from_fork+0x35/0x40
     Modules linked in: act_mirred veth ip6table_filter ip6_tables iptable_filter binfmt_misc ext4 crct10dif_pclmul snd_hda_codec_generic crc32_pclmul snd_hda_intel snd_hda_codec mbcache ghash_clmulni_intel jbd2 snd_hwdep snd_hda_core snd_seq snd_seq_device snd_pcm aesni_intel snd_timer snd crypto_simd cryptd glue_helper soundcore virtio_balloon joydev pcspkr i2c_piix4 nfsd auth_rpcgss nfs_acl lockd grace sunrpc ip_tables xfs ata_generic pata_acpi qxl drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops virtio_net ttm virtio_blk net_failover virtio_console failover drm ata_piix crc32c_intel virtio_pci serio_raw libata virtio_ring virtio floppy dm_mirror dm_region_hash dm_log dm_mod
     CR2: 0000000000000000

    Validating the control action within tcf_mirred_init() proved to fix the
    above issue. For the same reason, postpone the assignment of tcfa_action
    and tcfm_eaction to avoid partial reconfiguration of a mirred rule when
    it's replaced by another one that mirrors to a device that does not
    exist. A TDC selftest is added to verify the correct behavior.

    Fixes: db50514f9a9c ("net: sched: add termination action to allow goto chain")
    Fixes: 97763dc0f401 ("net_sched: reject unknown tcfa_action values")
    Signed-off-by: Davide Caratti <dcaratti@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>

Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>