[fpga] fpga-manager: altera-ps-spi: Fix build error
Message-id: <20200602160015.1206517-69-lgoncalv@redhat.com>
Patchwork-id: 316159
Patchwork-instance: patchwork
O-Subject: [RHEL-8.3 BZ 1494701 V3 068/109] fpga-manager: altera-ps-spi: Fix build error
Bugzilla: 1689274 1660310 1494701 1494699
RH-Acked-by: Clark Williams <williams@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Tom Rix <trix@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1494699
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1494701
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1689274
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1660310

Upstream Status: Linus tree, from v5.6.13.
Brew Build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=28984697
Testing: Basic manual testing on the available HW.

commit 3d139703d397f6281368047ba7ad1c8bf95aa8ab
Author: YueHaibing <yuehaibing@huawei.com>
Date: Mon, 8 Jul 2019 15:13:56 +0800

    fpga-manager: altera-ps-spi: Fix build error

    If BITREVERSE is m and FPGA_MGR_ALTERA_PS_SPI is y,
    build fails:

    drivers/fpga/altera-ps-spi.o: In function `altera_ps_write':
    altera-ps-spi.c:(.text+0x4ec): undefined reference to `byte_rev_table'

    Select BITREVERSE to fix this.

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: fcfe18f885f6 ("fpga-manager: altera-ps-spi: use bitrev8x4")
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Cc: stable <stable@vger.kernel.org>
    Acked-by: Moritz Fischer <mdf@kernel.org>
    Link: https://lore.kernel.org/r/20190708071356.50928-1-yuehaibing@huawei.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Luis Claudio R. Goncalves <lgoncalv@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>