refperf: Work around 64-bit division
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1941211

commit 7c944d7c67daee84e3c756bb74ad2f32b28c41cf
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri, 29 May 2020 14:36:26 -0700

    refperf: Work around 64-bit division

    A 64-bit division was introduced in refperf, breaking compilation
    on all 32-bit architectures:

    kernel/rcu/refperf.o: in function `main_func':
    refperf.c:(.text+0x57c): undefined reference to `__aeabi_uldivmod'

    Fix this by using div_u64 to mark the expensive operation.

    [ paulmck: Update primitive and format per Nathan Chancellor. ]
    Fixes: bd5b16d6c88d ("refperf: Allow decimal nanoseconds")
    Reported-by: kbuild test robot <lkp@intel.com>
    Reported-by: Valdis Klētnieks <valdis.kletnieks@vt.edu>
    Acked-by: Randy Dunlap <rdunlap@infradead.org> # build-tested
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Paul E. McKenney <paulmck@kernel.org>

Signed-off-by: Waiman Long <longman@redhat.com>