[mm] mm/kasan/common.c: fix compile error
Message-id: <df0ca3e921cc4b82d7288f109c2dcc51294b8cc7.1605724261.git@redhat.com>
Patchwork-id: 340057
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 bz1894223 PATCH 23/59] mm/kasan/common.c: fix compile error
Bugzilla: 1894223
RH-Acked-by: Waiman Long <longman@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

commit 2e7d31704c7fe9141b0b27ec1ece254d9993fe2d
Author: zhong jiang <zhongjiang@huawei.com>
Date:   Wed Dec 4 16:49:43 2019 -0800

    mm/kasan/common.c: fix compile error

    I hit the following compile error in arch/x86/

       mm/kasan/common.c: In function kasan_populate_vmalloc:
       mm/kasan/common.c:797:2: error: implicit declaration of function flush_cache_vmap; did you mean flush_rcu_work? [-Werror=implicit-function-declaration]
         flush_cache_vmap(shadow_start, shadow_end);
         ^~~~~~~~~~~~~~~~
         flush_rcu_work
       cc1: some warnings being treated as errors

    Link: http://lkml.kernel.org/r/1575363013-43761-1-git-send-email-zhongjiang@huawei.com
    Fixes: 3c5c3cfb9ef4 ("kasan: support backing vmalloc space with real shadow memory")
    Signed-off-by: zhong jiang <zhongjiang@huawei.com>
    Reviewed-by: Andrew Morton <akpm@linux-foundation.org>
    Reviewed-by: Daniel Axtens <dja@axtens.net>
    Cc: Mark Rutland <mark.rutland@arm.com>
    Cc: Mark Rutland <mark.rutland@arm.com>
    Cc: Vasily Gorbik <gor@linux.ibm.com>
    Cc: Andrey Ryabinin <aryabinin@virtuozzo.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Nico Pache <npache@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>