[arm64] arm64: arch_timer: avoid unused function warning
Message-id: <1576692571-326-3-git-send-email-jlinton@redhat.com>
Patchwork-id: 292086
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 BZ1757828 v4 02/13] arm64: arch_timer: avoid unused function warning
Bugzilla: 1757828
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Mark Langsdorf <mlangsdo@redhat.com>
RH-Acked-by: Mark Salter <msalter@redhat.com>

bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1757828
brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=25241293
Tested: N1 SDP, kernel self test
Upstream status: mainline, the last three are merged to arm64/for-next/core

commit 040f340134751d73bd03ee92fabb992946c55b3d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 2 23:11:44 2018 +0200

arm64_1188873_read_cntvct_el0() is protected by the correct
CONFIG_ARM64_ERRATUM_1188873 #ifdef, but the only reference to it is
also inside of an CONFIG_ARM_ARCH_TIMER_OOL_WORKAROUND section,
and causes a warning if that is disabled:

drivers/clocksource/arm_arch_timer.c:323:20: error: 'arm64_1188873_read_cntvct_el0' defined but not used [-Werror=unused-function]

Since the erratum requires that we always apply the workaround
in the timer driver, select that symbol as we do for SoC
specific errata.

Fixes: 95b861a4a6d9 ("arm64: arch_timer: Add workaround for ARM erratum 1188873")
Acked-by: Marc Zyngier <marc.zyngier@arm.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
Signed-off-by: Jeremy Linton <jlinton@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>