[netdrv] mlxsw: spectrum_buffers: Add extack messages for invalid configurations
Message-id: <20191113174919.6852-28-ivecera@redhat.com>
Patchwork-id: 286180
O-Subject: [RHEL-8.2 PATCH 027/127] mlxsw: spectrum_buffers: Add extack messages for invalid configurations
Bugzilla: 1737368
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Petr Oros <poros@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1737368

Upstream commit(s):
commit 8f6862065d8be320ba45a52c8a361b580722fc18
Author: Ido Schimmel <idosch@mellanox.com>
Date:   Mon Apr 22 12:08:41 2019 +0000

    mlxsw: spectrum_buffers: Add extack messages for invalid configurations

    Add extack messages to better communicate invalid configuration to the
    user.

    Example:

    # devlink sb pool set pci/0000:01:00.0 pool 0 size 104857600 thtype dynamic
    Error: mlxsw_spectrum: Exceeded shared buffer size.
    devlink answers: Invalid argument

    Signed-off-by: Ido Schimmel <idosch@mellanox.com>
    Acked-by: Jiri Pirko <jiri@mellanox.com>
    Reviewed-by: Petr Machata <petrm@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>