[x86] x86/mce: Add notifier_block forward declaration
Message-id: <20190723143645.552171906@redhat.com>
Patchwork-id: 267095
O-Subject: [RHEL8 PATCH 01/19] x86/mce: Add notifier_block forward declaration
Bugzilla: 1485543 1482412
RH-Acked-by: Dean Nelson <dnelson@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

BZ#1485543
BZ#1482412
brew: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=22664488
Tested: Sanity testing only

commit 704ae091b061082b37a9968621af4c290c641d50
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Aug 17 12:01:36 2018 +0200

    x86/mce: Add notifier_block forward declaration

    Without linux/irq.h, there is no declaration of notifier_block, leading to
    a build warning:

    In file included from arch/x86/kernel/cpu/mcheck/threshold.c:10:
    arch/x86/include/asm/mce.h:151:46: error: 'struct notifier_block' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]

    It's sufficient to declare the struct tag here, which avoids pulling in
    more header files.

    Fixes: 447ae3166702 ("x86: Don't include linux/irq.h from asm/hardirq.h")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
    Cc: Nicolai Stange <nstange@suse.de>
    Cc: "H. Peter Anvin" <hpa@zytor.com>
    Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
    Cc: Borislav Petkov <bp@suse.de>
    Link: https://lkml.kernel.org/r/20180817100156.3009043-1-arnd@arndb.de

Signed-off-by: Phillip Lougher <plougher@redhat.com>