[tools] perf strbuf: Match va_{add,copy} with va_end
Message-id: <befba06421a63986dd22981b9cb9d3a472015a52.1559304074.git.mpetlan@redhat.com>
Patchwork-id: 261434
O-Subject: [RHEL8.1 BZ1709243 137/217] perf strbuf: Match va_{add, copy} with va_end
Bugzilla: 1709243
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: 1709243
https://bugzilla.redhat.com/show_bug.cgi?id=1709243

upstream
========
commit ce49d8436cffa9b7a6a5f110879d53e89dbc6746
Author: Sanskriti Sharma <sansharm@redhat.com>
Date: Tue Oct 2 10:29:10 2018 -0400

description
===========
Ensure that all code paths in strbuf_addv() call va_end() on the
ap_saved copy that was made.

Fixes the following coverity complaint:

  Error: VARARGS (CWE-237): [#def683]
  tools/perf/util/strbuf.c:106: missing_va_end: va_end was not called
  for "ap_saved".

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>