mm, memcg: rework remote charging API to support nesting
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1937825
Conflicts:
 1) A merge conflict in fanotify.c due to missing a number of upstream
    f[as]notify commits.
 2) A fuzz in inotify_fsnotify.c due to missing upstream commit
    c8f3446c66d8 ("inotify: report both events on parent and child with
    single callback")

commit b87d8cefe43c7f22e8aa13919c1dfa2b4b4b4e01
Author: Roman Gushchin <guro@fb.com>
Date:   Sat, 17 Oct 2020 16:13:40 -0700

    mm, memcg: rework remote charging API to support nesting

    Currently the remote memcg charging API consists of two functions:
    memalloc_use_memcg() and memalloc_unuse_memcg(), which set and clear the
    memcg value, which overwrites the memcg of the current task.

      memalloc_use_memcg(target_memcg);
      <...>
      memalloc_unuse_memcg();

    It works perfectly for allocations performed from a normal context,
    however an attempt to call it from an interrupt context or just nest two
    remote charging blocks will lead to an incorrect accounting.  On exit from
    the inner block the active memcg will be cleared instead of being
    restored.

      memalloc_use_memcg(target_memcg);

      memalloc_use_memcg(target_memcg_2);
        <...>
        memalloc_unuse_memcg();

        Error: allocation here are charged to the memcg of the current
        process instead of target_memcg.

      memalloc_unuse_memcg();

    This patch extends the remote charging API by switching to a single
    function: struct mem_cgroup *set_active_memcg(struct mem_cgroup *memcg),
    which sets the new value and returns the old one.  So a remote charging
    block will look like:

      old_memcg = set_active_memcg(target_memcg);
      <...>
      set_active_memcg(old_memcg);

    This patch is heavily based on the patch by Johannes Weiner, which can be
    found here: https://lkml.org/lkml/2020/5/28/806 .

    Signed-off-by: Roman Gushchin <guro@fb.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Reviewed-by: Shakeel Butt <shakeelb@google.com>
    Cc: Johannes Weiner <hannes@cmpxchg.org>
    Cc: Dan Schatzberg <dschatzberg@fb.com>
    Link: https://lkml.kernel.org/r/20200821212056.3769116-1-guro@fb.com
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Signed-off-by: Waiman Long <longman@redhat.com>