[netdrv] net: hns: make hns_dsaf_roce_reset non static
Message-id: <20190418081419.22501-3-txiaojun@redhat.com>
Patchwork-id: 250441
O-Subject: [RHEL8.1 BZ 1661885 v2 02/21] net: hns: make hns_dsaf_roce_reset non static
Bugzilla: 1661885
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Neil Horman <nhorman@redhat.com>

From: YueHaibing <yuehaibing@huawei.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1661885
Build-Info: http://brewweb.devel.redhat.com/brew/taskinfo?taskID=21205999
git repo: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
commit ff7b91262b3ad31dfe1461dace0314a773b0fa55

hns_dsaf_roce_reset is exported and used in hns_roce_hw_v1.c
In commit 336a443bd9dd ("net: hns: Make many functions static") I make
it static wrongly.

drivers/infiniband/hw/hns/hns_roce_hw_v1.o: In function `hns_roce_v1_reset':
hns_roce_hw_v1.c:(.text+0x37ac): undefined reference to `hns_dsaf_roce_reset'
hns_roce_hw_v1.c:(.text+0x37cc): undefined reference to `hns_dsaf_roce_reset'

Fixes: 336a443bd9dd ("net: hns: Make many functions static")
Signed-off-by: YueHaibing <yuehaibing@huawei.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Xiaojun Tan <txiaojun@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>