[x86] x86/speculation/l1tf: Unbreak !__HAVE_ARCH_PFN_MODIFY_ALLOWED architectures
Message-id: <1534368137-6548-29-git-send-email-longman@redhat.com>
Patchwork-id: 227105
O-Subject: [RHEL8 PATCH 53/75] x86/speculation/l1tf: Unbreak !__HAVE_ARCH_PFN_MODIFY_ALLOWED architectures
Bugzilla: 1616046
CVE: CVE-2018-3620 CVE-2018-3646
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Christoph von Recklinghausen <crecklin@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1616046
CVE: CVE-2018-3620, CVE-2018-3646 (L1TF, Foreshadow)

commit 6c26fcd2abfe0a56bbd95271fce02df2896cfd24
Author: Jiri Kosina <jkosina@suse.cz>
Date:   Sat Jul 14 21:56:13 2018 +0200

    x86/speculation/l1tf: Unbreak !__HAVE_ARCH_PFN_MODIFY_ALLOWED architectures

    pfn_modify_allowed() and arch_has_pfn_modify_check() are outside of the
    !__ASSEMBLY__ section in include/asm-generic/pgtable.h, which confuses
    assembler on archs that don't have __HAVE_ARCH_PFN_MODIFY_ALLOWED (e.g.
    ia64) and breaks build:

        include/asm-generic/pgtable.h: Assembler messages:
        include/asm-generic/pgtable.h:538: Error: Unknown opcode `static inline bool pfn_modify_allowed(unsigned long pfn,pgprot_t prot)'
        include/asm-generic/pgtable.h:540: Error: Unknown opcode `return true'
        include/asm-generic/pgtable.h:543: Error: Unknown opcode `static inline bool arch_has_pfn_modify_check(void)'
        include/asm-generic/pgtable.h:545: Error: Unknown opcode `return false'
        arch/ia64/kernel/entry.S:69: Error: `mov' does not fit into bundle

    Move those two static inlines into the !__ASSEMBLY__ section so that they
    don't confuse the asm build pass.

    Fixes: 42e4089c7890 ("x86/speculation/l1tf: Disallow non privileged high MMIO PROT_NONE mappings")
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>
    Signed-off-by: Thomas Gleixner <tglx@linutronix.de>

Signed-off-by: Waiman Long <longman@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>