[scsi] lpfc: Fix pointer checks and comments in
Message-id: <20201014120050.20873-245-gtiwari@redhat.com>
Patchwork-id: 331432
Patchwork-instance: patchwork
O-Subject: [RHEL-8.4 V2 PATCH 244/247] lpfc: Fix pointer checks and comments in
Bugzilla: 1857052 1857051 1853231
RH-Acked-by: David Milburn <dmilburn@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Ewan Milne <emilne@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1793190
Bugzilla: http://bugzilla.redhat.com/1857052
Bugzilla: http://bugzilla.redhat.com/1853231
Bugzilla: http://bugzilla.redhat.com/1857051

commit fcdd14b86f6b891b5e894bf1dbeaf02cc79bdbce
Author: James Smart <jsmart2021@gmail.com>
Date:   Wed May 20 11:59:27 2020 -0700

    lpfc: Fix pointer checks and comments in LS receive refactoring

    Additional testing encountered null pointers that weren't fully qualified
    in lpfc_nvmet_xmt_ls_abort_cmp() and lpfc_nvmet_unsol_issue_abort().

    The same error was detected and reported by static checker reporting:
      drivers/scsi/lpfc/lpfc_sli.c:2905 lpfc_nvme_unsol_ls_handler()
      error: we previously assumed 'phba->targetport' could be null
        (see line 2837)

    Fix by making phba->nvmet_support and phba->targetport validity checks
    in lpfc_nvmet_xmt_ls_abort_cmp() and lpfc_nvmet_unsol_issue_abort().

    Fixes: 3a8070c567aaa (“lpfc: Refactor NVME LS receive handling”)
    Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Paul Ely <paul.ely@broadcom.com>
    Signed-off-by: James Smart <jsmart2021@gmail.com>
    Reviewed-by: Dan Carpenter <dan.carpenter@oracle.com>
    Signed-off-by: Christoph Hellwig <hch@lst.de>

Signed-off-by: Gopal Tiwari <gtiwari@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>