[net] flow_dissector: work around stack frame size warning
Message-id: <a1712e5a25aea30fb80fbc4469f5fb2912c6bf65.1608233888.git.gnault@redhat.com>
Patchwork-id: 346246
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net PATCH 3/6] flow_dissector: work around stack frame size warning
Bugzilla: 1814836
RH-Acked-by: Antoine Tenart <atenart@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1814836
Upstream Status: linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33800834
Tested: LNST + CKI net
        + test script from bz: https://bugzilla.redhat.com/show_bug.cgi?id=1814836#c4
Conflicts: (context) Upstream commit 5923b8f7fa21 ("net/sched:
           cls_flower: Add hash info to flow classification") already
           backported to RHEL (as commit dc027c4a83be):
           we have an extra skb_flow_dissect_hash() call in
           fl_classify().

commit 0af413bd3e2de73bcf0742ed556be4af83c71964
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri May 29 22:13:58 2020 +0200

    flow_dissector: work around stack frame size warning

    The fl_flow_key structure is around 500 bytes, so having two of them
    on the stack in one function now exceeds the warning limit after an
    otherwise correct change:

    net/sched/cls_flower.c:298:12: error: stack frame size of 1056 bytes in function 'fl_classify' [-Werror,-Wframe-larger-than=]

    I suspect the fl_classify function could be reworked to only have one
    of them on the stack and modify it in place, but I could not work out
    how to do that.

    As a somewhat hacky workaround, move one of them into an out-of-line
    function to reduce its scope. This does not necessarily reduce the stack
    usage of the outer function, but at least the second copy is removed
    from the stack during most of it and does not add up to whatever is
    called from there.

    I now see 552 bytes of stack usage for fl_classify(), plus 528 bytes
    for fl_mask_lookup().

    Fixes: 58cff782cc55 ("flow_dissector: Parse multiple MPLS Label Stack Entries")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Cong Wang <xiyou.wangcong@gmail.com>
    Acked-by: Guillaume Nault <gnault@redhat.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Guillaume Nault <gnault@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>