powerpc/pseries/eeh: Make pseries_send_allow_unfreeze() static
Bugzilla: http://bugzilla.redhat.com/1924090
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=37569338

Upstream Status: https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/

commit 22f1de2e13b066921dedf6a00d2cc414f3cbab05
Author: Cédric Le Goater <clg@kaod.org>
Date:   Mon Jan 4 15:32:06 2021 +0100

    powerpc/pseries/eeh: Make pseries_send_allow_unfreeze() static

    Only used locally. It fixes this W=1 compile error :

    ../arch/powerpc/platforms/pseries/eeh_pseries.c:697:5: error: no previous prototype for ‘pseries_send_allow_unfreeze’ [-Werror=missing-prototypes]
      697 | int pseries_send_allow_unfreeze(struct pci_dn *pdn,
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~

    Signed-off-by: Cédric Le Goater <clg@kaod.org>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
    Link: https://lore.kernel.org/r/20210104143206.695198-24-clg@kaod.org
    Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>

Signed-off-by: Gustavo Walbon <gwalbon@redhat.com>