[s390] s390: use __u{16, 32, 64} instead of uint{16, 32, 64}_t in uapi header
Message-id: <20191007163743.11940-12-prudo@redhat.com>
Patchwork-id: 276955
O-Subject: [RHEL8.2 PATCH 11/30] [s390] s390: use __u{16, 32, 64} instead of uint{16, 32, 64}_t in uapi header
Bugzilla: 1726416
RH-Acked-by: Cornelia Huck <cohuck@redhat.com>
RH-Acked-by: Herbert Xu <herbert.xu@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: 1726416
Upstream Status: kernel/git/torvalds/linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=23859706
Tested: by IBM
Conflicts: None

commit 061c996239490a402aa31cd116f71a8bf9db1d8c
Author: Masahiro Yamada <yamada.masahiro@socionext.com>
Date:   Sun Jul 21 23:20:08 2019 +0900

    s390: use __u{16,32,64} instead of uint{16,32,64}_t in uapi header

    When CONFIG_UAPI_HEADER_TEST=y, exported headers are compile-tested to
    make sure they can be included from user-space.

    Currently, zcrypt.h is excluded from the test coverage. To make it
    join the compile-test, we need to fix the build errors attached below.

    For a case like this, we decided to use __u{8,16,32,64} variable types
    in this discussion:

      https://lkml.org/lkml/2019/6/5/18

    Build log:

      CC      usr/include/asm/zcrypt.h.s
    In file included from <command-line>:32:0:
    ./usr/include/asm/zcrypt.h:163:2: error: unknown type name ‘uint16_t’
      uint16_t cprb_len;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:168:2: error: unknown type name ‘uint32_t’
      uint32_t source_id;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:169:2: error: unknown type name ‘uint32_t’
      uint32_t target_id;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:170:2: error: unknown type name ‘uint32_t’
      uint32_t ret_code;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:171:2: error: unknown type name ‘uint32_t’
      uint32_t reserved1;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:172:2: error: unknown type name ‘uint32_t’
      uint32_t reserved2;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:173:2: error: unknown type name ‘uint32_t’
      uint32_t payload_len;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:182:2: error: unknown type name ‘uint16_t’
      uint16_t ap_id;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:183:2: error: unknown type name ‘uint16_t’
      uint16_t dom_id;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:198:2: error: unknown type name ‘uint16_t’
      uint16_t  targets_num;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:199:2: error: unknown type name ‘uint64_t’
      uint64_t  targets;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:200:2: error: unknown type name ‘uint64_t’
      uint64_t  weight;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:201:2: error: unknown type name ‘uint64_t’
      uint64_t  req_no;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:202:2: error: unknown type name ‘uint64_t’
      uint64_t  req_len;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:203:2: error: unknown type name ‘uint64_t’
      uint64_t  req;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:204:2: error: unknown type name ‘uint64_t’
      uint64_t  resp_len;
      ^~~~~~~~
    ./usr/include/asm/zcrypt.h:205:2: error: unknown type name ‘uint64_t’
      uint64_t  resp;
      ^~~~~~~~

    Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
    Signed-off-by: Heiko Carstens <heiko.carstens@de.ibm.com>

Signed-off-by: Philipp Rudo <prudo@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>