[tools] selftests: timestamping: Fix SIOCGSTAMP undeclared build failure
Message-id: <20201020034703.1081610-8-haliu@redhat.com>
Patchwork-id: 333561
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 net PATCH 07/22] selftests: timestamping: Fix SIOCGSTAMP undeclared build failure
Bugzilla: 1861175
RH-Acked-by: Andrea Claudi <aclaudi@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1861175
Brew: https://brewweb.devel.redhat.com/taskinfo?taskID=32170705
Upstream Status: net.git commit 877d53c29549

commit 877d53c295498c16a1977e591b7fc2838f8d8daf
Author: Shuah Khan <skhan@linuxfoundation.org>
Date:   Thu Jun 27 16:39:35 2019 -0600

    selftests: timestamping: Fix SIOCGSTAMP undeclared build failure

    Add missing linux/sockios.h include to fix the following SIOCGSTAMP
    undeclared build error. In addition, remove the local defines for
    SIOCGSTAMPNS and SIOCSHWTSTAMP and pick them up from linux/sockios.h.

    timestamping.c:249:19: error: SIOCGSTAMP undeclared
       if (ioctl(sock, SIOCGSTAMP, &tv))

    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: Hangbin Liu <haliu@redhat.com>
Signed-off-by: Andrea Claudi <aclaudi@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>