[fs] SUNRPC: use cmpxchg64() in gss_seq_send64_fetch_and_inc()
Message-id: <9c6afef99a96d98e9c0a82223c520a3324df4b13.1570027539.git.bcodding@redhat.com>
Patchwork-id: 276122
O-Subject: [RHEL8.2 fs PATCH v3 147/394] SUNRPC: use cmpxchg64() in gss_seq_send64_fetch_and_inc()
Bugzilla: 1732409
RH-Acked-by: Steve Dickson <SteveD@redhat.com>
RH-Acked-by: J. Bruce Fields <bfields@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

https://bugzilla.redhat.com/show_bug.cgi?id=1732409

commit 21924765862a0871908a35cb0e53e2e1c169b888
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Tue Oct 2 22:57:46 2018 +0200

    SUNRPC: use cmpxchg64() in gss_seq_send64_fetch_and_inc()

    The newly introduced gss_seq_send64_fetch_and_inc() fails to build on
    32-bit architectures:

    net/sunrpc/auth_gss/gss_krb5_seal.c:144:14: note: in expansion of macro 'cmpxchg'
       seq_send = cmpxchg(&ctx->seq_send64, old, old + 1);
                  ^~~~~~~
    arch/x86/include/asm/cmpxchg.h:128:3: error: call to '__cmpxchg_wrong_size' declared with attribute error: Bad argument size for cmpxchg
       __cmpxchg_wrong_size();     \

    As the message tells us, cmpxchg() cannot be used on 64-bit arguments,
    that's what cmpxchg64() does.

    Fixes: 571ed1fd2390 ("SUNRPC: Replace krb5_seq_lock with a lockless scheme")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Trond Myklebust <trond.myklebust@hammerspace.com>

Signed-off-by: Phillip Lougher <plougher@redhat.com>