[net] bpf: Fix net/core/filter build errors when INET is not enabled
Message-id: <20210113140908.457588-55-yauheni.kaliuta@redhat.com>
Patchwork-id: 348395
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 v2 055/291] bpf: Fix net/core/filter build errors when INET is not enabled
Bugzilla: 1874005
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874005

commit 6b207d66aa9fad0deed13d5f824e1ea193b0a777
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Tue Jun 30 10:29:10 2020 -0700

    bpf: Fix net/core/filter build errors when INET is not enabled

    Fix build errors when CONFIG_INET is not set/enabled.

    (.text+0x2b1b): undefined reference to `tcp_prot'
    (.text+0x2b3b): undefined reference to `tcp_prot'

    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Signed-off-by: Alexei Starovoitov <ast@kernel.org>
    Acked-by: Yonghong Song <yhs@fb.com>
    Link: https://lore.kernel.org/bpf/b1a858ec-7e04-56bc-248a-62cb9bbee726@infradead.org

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>