[include] gpio: merrifield: Fix build err without CONFIG_ACPI
Message-id: <20191110173746.26019-254-ahs3@redhat.com>
Patchwork-id: 284955
O-Subject: [RHEL8.2 PATCH v5 253/299] gpio: merrifield: Fix build err without CONFIG_ACPI
Bugzilla: 1754787 1739728 1730098 1721297 1664185
RH-Acked-by: Jeremy Linton <jlinton@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664185
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1721297
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1730098
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1739728
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1754787
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24584640
Upstream Status: fe066621c7966fe47fa17c6be6fd81adb3c0509f
Tested: multiple BZs are covered by this patch set:

 bz1664185: this requires an ACPI HMAT table plus the hardware that it
 describes.  For full testing, PartnerQA is recommended.  Barring
 that, does an HMAT table exist, and are there sysfs entries for
 it showing up?

 bz1721297: this requires the latest ACPI PPTT tables in firmware, and
 the hardware that reflects it, so PartnerQA is required.  NB:
 there are additional patches for SPE that will need to be added
 -- see bz1504978 -- but these are the ACPI patches required for
 the SPE patches.

 bz1730098: same as bz1664185, but different partner.

 bz1739728: basic kernel testing and running of the kernel CI tests; in
 general, if a system boots and runs with all known hardware active
 and usable, the ACPI subsystem is behaving.  Re-ran CKI tests for
 v2.

 bz1754787: Windows 2018 string for _OSI, needs confirmation from the
 partner, also.

Conflicts:
    drivers/gpio/gpio-merrifield.c

    This part of the patch may be needed as part of a separate
    repair; in this instance, we only took the ACPI portions
    that define acpi_dev_put().

commit fe066621c7966fe47fa17c6be6fd81adb3c0509f
Author: YueHaibing <yuehaibing@huawei.com>
Date:   Fri Apr 12 23:19:11 2019 +0800

    gpio: merrifield: Fix build err without CONFIG_ACPI

    When building CONFIG_ACPI is not set
    gcc warn this:

    drivers/gpio/gpio-merrifield.c: In function mrfld_gpio_get_pinctrl_dev_name:
    drivers/gpio/gpio-merrifield.c:388:19: error: dereferencing pointer to incomplete type struct acpi_device
       put_device(&adev->dev);
                       ^~

    Reported-by: Hulk Robot <hulkci@huawei.com>
    Fixes: d00d2109c367 ("gpio: merrifield: Convert to use acpi_dev_get_first_match_dev()")
    Suggested-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Reviewed-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
    Acked-by: Linus Walleij <linus.walleij@linaro.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
    (cherry picked from commit fe066621c7966fe47fa17c6be6fd81adb3c0509f)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>