[netdrv] mlxsw: core: mlxsw: core: avoid -Wint-in-bool-context warning
Message-id: <20190607192438.30003-474-ivecera@redhat.com>
Patchwork-id: 263663
O-Subject: [RHEL-8.1 PATCH 473/486] mlxsw: core: mlxsw: core: avoid -Wint-in-bool-context warning
Bugzilla: 1680241
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1680241

Upstream commit(s):
commit 7442c483b963dbee7d1b655cbad99c727c047828
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Mar 18 17:35:11 2019 +0100

    mlxsw: core: mlxsw: core: avoid -Wint-in-bool-context warning

    A recently added function in mlxsw triggers a harmless compiler warning:

    In file included from drivers/net/ethernet/mellanox/mlxsw/core.h:17,
                     from drivers/net/ethernet/mellanox/mlxsw/core_env.c:7:
    drivers/net/ethernet/mellanox/mlxsw/core_env.c: In function 'mlxsw_env_module_temp_thresholds_get':
    drivers/net/ethernet/mellanox/mlxsw/reg.h:8015:45: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
     #define MLXSW_REG_MTMP_TEMP_TO_MC(val) (val * 125)
                                            ~~~~~^~~~~~
    drivers/net/ethernet/mellanox/mlxsw/core_env.c:116:8: note: in expansion of macro 'MLXSW_REG_MTMP_TEMP_TO_MC'
       if (!MLXSW_REG_MTMP_TEMP_TO_MC(module_temp)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~

    The warning is normally disabled, but it would be nice to enable
    it to find real bugs, and there are no other known instances at
    the moment.

    Replace the negation with a zero-comparison, which also matches
    the comment above it.

    Fixes: d93c19a1d95c ("mlxsw: core: Add API for QSFP module temperature thresholds reading")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Jiri Pirko <jiri@mellanox.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>