[net] Use __kernel_clockid_t in uapi net_stamp.h
Message-id: <99b25ec060e5273c3f3823cd08bd68feaeacb746.1545043346.git.dcaratti@redhat.com>
Patchwork-id: 235913
O-Subject: [RHEL8.0 net] net: Use __kernel_clockid_t in uapi net_stamp.h
Bugzilla: 1638022
RH-Acked-by: Stefano Brivio <sbrivio@redhat.com>
RH-Acked-by: Timothy Redaelli <tredaelli@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1638022
Upstream Status: not upstream yet, waiting for acceptance, needed urgently
on RHEL to fix up UAPI after 80b14dee2bea ("net: Add a new socket option for a
future transmit time.")

Tested: locally, using reproducer program that includes net_tstamp.h
Conflicts: none

Herton reports the following error when building a userspace program that
includes net_stamp.h:

 In file included from foo.c:2:
 /usr/include/linux/net_tstamp.h:158:2: error: unknown type name
 'clockid_t'
   clockid_t clockid; /* reference clockid */
   ^~~~~~~~~

Fix it by using __kernel_clockid_t in place of clockid_t.

Signed-off-by: Davide Caratti <dcaratti@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>