[kernel] rcu/tree: Export rcu_idle_{enter, exit} to modules
Message-id: <20201223180920.3240723-150-ahs3@redhat.com>
Patchwork-id: 346869
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 PATCH 149/235] rcu/tree: Export rcu_idle_{enter, exit} to modules
Bugzilla: 1865698 1851555
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1865698
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1851555
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33918986
Upstream Status: 3ad1c8ef083bef96ec922688966484be1039e6b5
Tested: Ran through the kernel CKI KT1 test suite multiple times to ensure the
 results were consistent, that we hit multiple platforms, and that they
 were successful.

commit 3ad1c8ef083bef96ec922688966484be1039e6b5
Author: Borislav Petkov <bp@suse.de>
Date:   Mon Sep 21 12:31:36 2020 +0200

    rcu/tree: Export rcu_idle_{enter,exit} to modules

    Fix this link error:

      ERROR: modpost: "rcu_idle_enter" [drivers/acpi/processor.ko] undefined!
      ERROR: modpost: "rcu_idle_exit" [drivers/acpi/processor.ko] undefined!

    when CONFIG_ACPI_PROCESSOR is built as module. PeterZ says that in light
    of ARM needing those soon too, they should simply be exported.

    Fixes: 1fecfdbb7acc ("ACPI: processor: Take over RCU-idle for C3-BM idle")
    Reported-by: Sven Joachim <svenjoac@gmx.de>
    Suggested-by: Peter Zijlstra <peterz@infradead.org>
    Signed-off-by: Borislav Petkov <bp@suse.de>
    Reviewed-by: Paul E. McKenney <paulmckrcu@kernel.org>
    Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
    (cherry picked from commit 3ad1c8ef083bef96ec922688966484be1039e6b5)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>