[usb] usb: typec: add dependency for TYPEC_HD3SS3220
Message-id: <20201216155447.212357-262-torez@redhat.com>
Patchwork-id: 345402
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 1900751 0261/1059] usb: typec: add dependency for TYPEC_HD3SS3220
Bugzilla: 1900751 1856683 1838295 1837563 1783493
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: David Arcari <darcari@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Bugzilla: https://bugzilla.redhat.com/1900751
Bugzilla: https://bugzilla.redhat.com/1837563
Bugzilla: https://bugzilla.redhat.com/1856683
Bugzilla: https://bugzilla.redhat.com/1853229
Bugzilla: https://bugzilla.redhat.com/1838295
Bugzilla: https://bugzilla.redhat.com/1836895
Bugzilla: https://bugzilla.redhat.com/1798825
Bugzilla: https://bugzilla.redhat.com/1789257
Bugzilla: https://bugzilla.redhat.com/1783493

Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33777895
Upstream Status: da4b5d18dd949abdda7c8ea76c9483b5edd49616

Tested: HP ZBook 15 G5/80D5 Laptop
 TGL-U(QS) Laptop
 Dell Customer: onsite team in China via TGL-U(QS) and RKL-S(ES2) CPU

commit da4b5d18dd949abdda7c8ea76c9483b5edd49616
Author: Mao Wenan <maowenan@huawei.com>
Date:   Wed Oct 9 09:47:07 2019 +0800

usb: typec: add dependency for TYPEC_HD3SS3220

If CONFIG_TYPEC_HD3SS3220=y, CONFIG_USB_ROLE_SWITCH=m, below errors
can be found:
drivers/usb/typec/hd3ss3220.o: In function `hd3ss3220_remove':
hd3ss3220.c:(.text+0x64): undefined reference to `usb_role_switch_put'
drivers/usb/typec/hd3ss3220.o: In function `hd3ss3220_dr_set':
hd3ss3220.c:(.text+0x154): undefined reference to `usb_role_switch_set_role'
drivers/usb/typec/hd3ss3220.o: In function `hd3ss3220_set_role':
hd3ss3220.c:(.text+0x294): undefined reference to `usb_role_switch_set_role'
hd3ss3220.c:(.text+0x2f4): undefined reference to `usb_role_switch_set_role'
hd3ss3220.c:(.text+0x348): undefined reference to `usb_role_switch_set_role'
hd3ss3220.c:(.text+0x390): undefined reference to `usb_role_switch_set_role'
drivers/usb/typec/hd3ss3220.o: In function `hd3ss3220_probe':
hd3ss3220.c:(.text+0x5e8): undefined reference to `fwnode_usb_role_switch_get'
hd3ss3220.c:(.text+0x8a4): undefined reference to `usb_role_switch_put'
make: *** [vmlinux] Error 1

This patch add dependency USB_ROLE_SWITCH for TYPEC_HD3SS3220.

Fixes: 1c48c759ef4b ("usb: typec: driver for TI HD3SS3220 USB Type-C DRP port controller")
Reported-by: Hulk Robot <hulkci@huawei.com>
Signed-off-by: Mao Wenan <maowenan@huawei.com>
Reviewed-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Reviewed-by: Biju Das <biju.das@bp.renesas.com>
Link: https://lore.kernel.org/r/20191009014707.38716-1-maowenan@huawei.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Torez Smith <torez@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>