[tools] tools, bpftool: Correctly evaluate $(BUILD_BPF_SKELS) in Makefile
Message-id: <20210113140908.457588-24-yauheni.kaliuta@redhat.com>
Patchwork-id: 348365
Patchwork-instance: patchwork
O-Subject: [PATCH RHEL8.4 v2 024/291] tools, bpftool: Correctly evaluate $(BUILD_BPF_SKELS) in Makefile
Bugzilla: 1874005
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1874005

commit 9d9d8cc21e3827b89e414f990016836290de3038
Author: Tobias Klauser <tklauser@distanz.ch>
Date:   Tue Jun 23 12:37:10 2020 +0200

    tools, bpftool: Correctly evaluate $(BUILD_BPF_SKELS) in Makefile

    Currently, if the clang-bpf-co-re feature is not available, the build
    fails with e.g.

      CC       prog.o
    prog.c:1462:10: fatal error: profiler.skel.h: No such file or directory
     1462 | #include "profiler.skel.h"
          |          ^~~~~~~~~~~~~~~~~

    This is due to the fact that the BPFTOOL_WITHOUT_SKELETONS macro is not
    defined, despite BUILD_BPF_SKELS not being set. Fix this by correctly
    evaluating $(BUILD_BPF_SKELS) when deciding on whether to add
    -DBPFTOOL_WITHOUT_SKELETONS to CFLAGS.

    Fixes: 05aca6da3b5a ("tools/bpftool: Generalize BPF skeleton support and generate vmlinux.h")
    Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Reviewed-by: Quentin Monnet <quentin@isovalent.com>
    Acked-by: Andrii Nakryiko <andriin@fb.com>
    Link: https://lore.kernel.org/bpf/20200623103710.10370-1-tklauser@distanz.ch

Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>