[netdrv] qed: Fix -Wmaybe-uninitialized false positive
Message-id: <1572516117-4404-18-git-send-email-mchopra@redhat.com>
Patchwork-id: 281941
O-Subject: [RHEL8.2 PATCH 17/39] qed: Fix -Wmaybe-uninitialized false positive
Bugzilla: 1720392
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jonathan Toppins <jtoppins@redhat.com>
RH-Acked-by: Kamal Heib <kheib@redhat.com>

From: Arnd Bergmann <arnd@arndb.de>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1720392
Upstream: linux.git

commit 815deee0e34503dee7e74fb5ba4ea4a9b3a56750
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Jun 17 15:04:49 2019 +0200

    qed: Fix -Wmaybe-uninitialized false positive

    A previous attempt to shut up the uninitialized variable use
    warning was apparently insufficient. When CONFIG_PROFILE_ANNOTATED_BRANCHES
    is set, gcc-8 still warns, because the unlikely() check in DP_NOTICE()
    causes it to no longer track the state of all variables correctly:

    drivers/net/ethernet/qlogic/qed/qed_dev.c: In function 'qed_llh_set_ppfid_affinity':
    drivers/net/ethernet/qlogic/qed/qed_dev.c:798:47: error: 'abs_ppfid' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      addr = NIG_REG_PPF_TO_ENGINE_SEL + abs_ppfid * 0x4;
                                         ~~~~~~~~~~^~~~~

    This is not a nice workaround, but always initializing the output from
    qed_llh_abs_ppfid() at least shuts up the false positive reliably.

    Fixes: 79284adeb99e ("qed: Add llh ppfid interface and 100g support for offload protocols")
    Fixes: 8e2ea3ea9625 ("qed: Fix static checker warning")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Michal Kalderon <michal.kalderon@marvell.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Manish Chopra <mchopra@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>