[netdrv] mlx5e: Allow dissector meta key in tc flower
Message-id: <20191017191655.16967-6-ivecera@redhat.com>
Patchwork-id: 279825
O-Subject: [RHEL-8.2 net PATCH 5/5] net/mlx5e: Allow dissector meta key in tc flower
Bugzilla: 1762861
RH-Acked-by: Neil Horman <nhorman@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Davide Caratti <dcaratti@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: http://bugzilla.redhat.com/show_bug.cgi?id=1762861

Upstream commit(s):
commit 3d144578c91a2db417923ba905ce7a84ce0c274b
Author: Vlad Buslov <vladbu@mellanox.com>
Date:   Thu Jul 11 13:03:48 2019 +0300

    net/mlx5e: Allow dissector meta key in tc flower

    Recently, fl_flow_key->indev_ifindex int field was refactored into
    flow_dissector_key_meta field. With this, flower classifier also sets
    FLOW_DISSECTOR_KEY_META flow dissector key. However, mlx5 flower dissector
    validation code rejects filters that use flow dissector keys that are not
    supported. Add FLOW_DISSECTOR_KEY_META to the list of allowed dissector
    keys in __parse_cls_flower() to prevent following error when offloading
    flower classifier to mlx5:

    Error: mlx5_core: Unsupported key.

    Fixes: 8212ed777f40 ("net: sched: cls_flower: use flow_dissector for ingress ifindex")
    Signed-off-by: Vlad Buslov <vladbu@mellanox.com>
    Reviewed-by: Roi Dayan <roid@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Ivan Vecera <ivecera@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>