[acpi] ACPI/IORT: Fix build when CONFIG_IOMMU_API=n
Message-id: <20191110173746.26019-126-ahs3@redhat.com>
Patchwork-id: 284843
O-Subject: [RHEL8.2 PATCH v5 125/299] ACPI/IORT: Fix build when CONFIG_IOMMU_API=n
Bugzilla: 1754787 1739728 1730098 1721297 1664185
RH-Acked-by: Jeremy Linton <jlinton@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664185
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1721297
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1730098
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1739728
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1754787
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=24584640
Upstream Status: 6b68835b5af4feb2a3f31592a52a1a68d7c1b1f3
Tested: multiple BZs are covered by this patch set:

 bz1664185: this requires an ACPI HMAT table plus the hardware that it
 describes.  For full testing, PartnerQA is recommended.  Barring
 that, does an HMAT table exist, and are there sysfs entries for
 it showing up?

 bz1721297: this requires the latest ACPI PPTT tables in firmware, and
 the hardware that reflects it, so PartnerQA is required.  NB:
 there are additional patches for SPE that will need to be added
 -- see bz1504978 -- but these are the ACPI patches required for
 the SPE patches.

 bz1730098: same as bz1664185, but different partner.

 bz1739728: basic kernel testing and running of the kernel CI tests; in
 general, if a system boots and runs with all known hardware active
 and usable, the ACPI subsystem is behaving.  Re-ran CKI tests for
 v2.

 bz1754787: Windows 2018 string for _OSI, needs confirmation from the
 partner, also.

commit 6b68835b5af4feb2a3f31592a52a1a68d7c1b1f3
Author: Qian Cai <cai@lca.pw>
Date:   Mon Jan 7 16:42:07 2019 +0000

    ACPI/IORT: Fix build when CONFIG_IOMMU_API=n

    Commit 8097e53eaba2 ("ACPI/IORT: Use helper functions to access
    dev->iommu_fwspec") changed by mistake the iort_fwspec_iommu_ops() stub
    definition (compiled in when CONFIG_IOMMU_API=n), that caused the
    following compilation failure:

    drivers/acpi/arm64/iort.c:880:1: error: expected identifier or
    '(' before '{' token
     { return NULL; }
     ^
    drivers/acpi/arm64/iort.c:879:39: warning: 'iort_fwspec_iommu_ops'
    used but never defined
     static inline const struct iommu_ops *iort_fwspec_iommu_ops(struct device *dev);
                                           ^~~~~~~~~~~~~~~~~~~~~

    Fix it.

    Fixes: 8097e53eaba2 ("ACPI/IORT: Use helper functions to access dev->iommu_fwspec")
    Signed-off-by: Qian Cai <cai@lca.pw>
    [lorenzo.pieralisi@arm.com: updated tags and log]
    Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
    Acked-by: Hanjun Guo <hanjun.guo@linaro.org>
    Cc: Will Deacon <will.deacon@arm.com>
    Cc: Sudeep Holla <sudeep.holla@arm.com>
    Cc: Catalin Marinas <catalin.marinas@arm.com>
    Cc: Joerg Roedel <jroedel@suse.de>
    Signed-off-by: Will Deacon <will.deacon@arm.com>
    (cherry picked from commit 6b68835b5af4feb2a3f31592a52a1a68d7c1b1f3)

Signed-off-by: Al Stone <ahs3@redhat.com>
Signed-off-by: Phillip Lougher <plougher@redhat.com>