[wireless] rtw88: avoid unused function warnings
Message-id: <20200604193030.27246-14-jarod@redhat.com>
Patchwork-id: 317097
Patchwork-instance: patchwork
O-Subject: [RHEL8 PATCH 13/17] rtw88: avoid unused function warnings
Bugzilla: 1844129
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Steve Best <sbest@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1844129

commit f4025026992d374fbfbceaedb9ed23a6e8637931
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 8 20:53:51 2020 +0200

    rtw88: avoid unused function warnings

    commit 7dc7c41607d192ff660ba4ea82d517745c1d7523 upstream.

    The rtw88 driver defines emtpy functions with multiple indirections
    but gets one of these wrong:

    drivers/net/wireless/realtek/rtw88/pci.c:1347:12: error: 'rtw_pci_resume' defined but not used [-Werror=unused-function]
     1347 | static int rtw_pci_resume(struct device *dev)
          |            ^~~~~~~~~~~~~~
    drivers/net/wireless/realtek/rtw88/pci.c:1342:12: error: 'rtw_pci_suspend' defined but not used [-Werror=unused-function]
     1342 | static int rtw_pci_suspend(struct device *dev)

    Better simplify it to rely on the conditional reference in
    SIMPLE_DEV_PM_OPS(), and mark the functions as __maybe_unused to avoid
    warning about it.

    I'm not sure if these are needed at all given that the functions
    don't do anything, but they were only recently added.

    Fixes: 44bc17f7f5b3 ("rtw88: support wowlan feature for 8822c")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/20200408185413.218643-1-arnd@arndb.de
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

Signed-off-by: Jarod Wilson <jarod@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>