[tools] kunit: Fix TabError, remove defconfig code and handle when there is no kunitconfig
Message-id: <f8a3c50585d607d4022f59faa73a179b8835f449.1610738985.git@redhat.com>
Patchwork-id: 349935
Patchwork-instance: patchwork
O-Subject: [RHEL8.4 V2 bz1900119 PATCH 67/90] kunit: Fix TabError, remove defconfig code and handle when there is no kunitconfig
Bugzilla: 1900119
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1900119
commit 01397e822af42f8485e876ba9d1309b63646d886
Author: Vitor Massaru Iha <vitor@massaru.org>
Date:   Fri May 29 16:28:45 2020 -0300

    kunit: Fix TabError, remove defconfig code and handle when there is no kunitconfig

    The identation before this code
    (`if not os.path.exists(cli_args.build_dir):``)
    was with spaces instead of tabs after fixed up merge conflits,
    this commit revert spaces to tabs:

    [iha@bbking linux]$ tools/testing/kunit/kunit.py run
      File "tools/testing/kunit/kunit.py", line 247
        if not linux:
                    ^
    TabError: inconsistent use of tabs and spaces in indentation

    [iha@bbking linux]$ tools/testing/kunit/kunit.py run
    Traceback (most recent call last):
      File "tools/testing/kunit/kunit.py", line 338, in <module>
        main(sys.argv[1:])
      File "tools/testing/kunit/kunit.py", line 215, in main
        add_config_opts(config_parser)

    [iha@bbking linux]$ tools/testing/kunit/kunit.py run
    Traceback (most recent call last):
      File "tools/testing/kunit/kunit.py", line 337, in <module>
        main(sys.argv[1:])
      File "tools/testing/kunit/kunit.py", line 255, in main
        result = run_tests(linux, request)
      File "tools/testing/kunit/kunit.py", line 133, in run_tests
        request.defconfig,
    AttributeError: 'KunitRequest' object has no attribute 'defconfig'

    Handles when there is no .kunitconfig, the error due to merge conflicts
    between the following:

    commit 9bdf64b35117 ("kunit: use KUnit defconfig by default")
    commit 45ba7a893ad8 ("kunit: kunit_tool: Separate out
            config/build/exec/parse")

    [iha@bbking linux]$ tools/testing/kunit/kunit.py run
    Traceback (most recent call last):
      File "tools/testing/kunit/kunit.py", line 335, in <module>
        main(sys.argv[1:])
      File "tools/testing/kunit/kunit.py", line 246, in main
        linux = kunit_kernel.LinuxSourceTree()
      File "../tools/testing/kunit/kunit_kernel.py", line 109, in __init__
        self._kconfig.read_from_file(kunitconfig_path)
      File "t../ools/testing/kunit/kunit_config.py", line 88, in read_from_file
        with open(path, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '.kunit/.kunitconfig'

    Signed-off-by: Vitor Massaru Iha <vitor@massaru.org>
    Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>

Signed-off-by: Nico Pache <npache@redhat.com>
Signed-off-by: Jan Stancek <jstancek@redhat.com>