[kvm] x86: kvm: avoid unused variable warning
Message-id: <20190109204059.12206-6-drjones@redhat.com>
Patchwork-id: 237071
O-Subject: [RHEL-8.0 PATCH v4 05/51] x86: kvm: avoid unused variable warning
Bugzilla: 1659491
RH-Acked-by: Wei Huang <wei@redhat.com>
RH-Acked-by: Paolo Bonzini <pbonzini@redhat.com>
RH-Acked-by: Vitaly Kuznetsov <vkuznets@redhat.com>
RH-Acked-by: Auger Eric <eric.auger@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1659491

Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon, 20 Aug 2018 23:37:50 +0200

    x86: kvm: avoid unused variable warning

    Removing one of the two accesses of the maxphyaddr variable led to
    a harmless warning:

    arch/x86/kvm/x86.c: In function 'kvm_set_mmio_spte_mask':
    arch/x86/kvm/x86.c:6563:6: error: unused variable 'maxphyaddr' [-Werror=unused-variable]

    Removing the #ifdef seems to be the nicest workaround, as it
    makes the code look cleaner than adding another #ifdef.

    Fixes: 28a1f3ac1d0c ("kvm: x86: Set highest physical address bits in non-present/reserved SPTEs")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Cc: stable@vger.kernel.org # L1TF
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

(cherry picked from commit 7288bde1f9df6c1475675419bdd7725ce84dec56)
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>