[net] mptcp: Fix incorrect IPV6 dependency check
Message-id: <20200515101824.19445-30-fwestpha@redhat.com>
Patchwork-id: 309895
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 29/38] mptcp: Fix incorrect IPV6 dependency check
Bugzilla: 1835796
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1835796
Upstream Status: commit 8e1974a2a02b

commit 8e1974a2a02bf5b77831c686f01761163ea0cd3e
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Wed Jan 29 19:01:17 2020 +0100

    mptcp: Fix incorrect IPV6 dependency check

    If CONFIG_MPTCP=y, CONFIG_MPTCP_IPV6=n, and CONFIG_IPV6=m:

        net/mptcp/protocol.o: In function `__mptcp_tcp_fallback':
        protocol.c:(.text+0x786): undefined reference to `inet6_stream_ops'

    Fix this by checking for CONFIG_MPTCP_IPV6 instead of CONFIG_IPV6, like
    is done in all other places in the mptcp code.

    Fixes: 8ab183deb26a3b79 ("mptcp: cope with later TCP fallback")
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Reviewed-by: Mat Martineau <mathew.j.martineau@linux.intel.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>