[extcon] axp288: Add a depends on ACPI to the Kconfig entry
Message-id: <20191114232800.14205-30-lyude@redhat.com>
Patchwork-id: 287350
O-Subject: [RHEL8.2 drm v3 29/39] extcon: axp288: Add a depends on ACPI to the Kconfig entry
Bugzilla: 1731110
RH-Acked-by: Karol Herbst <kherbst@redhat.com>
RH-Acked-by: Ben Skeggs <bskeggs@redhat.com>
RH-Acked-by: Dave Airlie <airlied@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1731110
Upstream: since v5.2

commit fa3c098c2d52a268f6372fa053932e11f50cecb1
Author:     YueHaibing <yuehaibing@huawei.com>
AuthorDate: Thu Apr 4 22:17:48 2019 +0800
Commit:     Chanwoo Choi <cw00.choi@samsung.com>
CommitDate: Fri Apr 12 08:23:24 2019 +0900

    extcon: axp288: Add a depends on ACPI to the Kconfig entry

    As Hans de Goede pointed, using this driver without ACPI
    makes little sense, so add ACPI dependency to Kconfig entry
    to fix a build error while CONFIG_ACPI is not set.

    drivers/extcon/extcon-axp288.c: In function 'axp288_extcon_probe':
    drivers/extcon/extcon-axp288.c:363:20: error: dereferencing pointer to incomplete type
        put_device(&adev->dev);

    Fixes: 0cf064db948a ("extcon: axp288: Convert to use acpi_dev_get_first_match_dev()")
    Reported-by: Hulk Robot <hulkci@huawei.com>
    Suggested-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: YueHaibing <yuehaibing@huawei.com>
    Reviewed-by: Hans de Goede <hdegoede@redhat.com>
    Reviewed-by: Mukesh Ojha <mojha@codeaurora.org>
    Signed-off-by: Chanwoo Choi <cw00.choi@samsung.com>

Signed-off-by: Lyude Paul <lyude@redhat.com>
Signed-off-by: Bruno Meneguele <bmeneg@redhat.com>