[tools] perf ui helpline: Use strlcpy() as a shorter form of strncpy() + explicit set nul
Message-id: <0b1c5885cfb10dfa0ba953d3deaf7ecc2d8b9098.1560250176.git.mpetlan@redhat.com>
Patchwork-id: 265008
O-Subject: [RHEL8.1 BZ1715507 102/234] perf ui helpline: Use strlcpy() as a shorter form of strncpy() + explicit set nul
Bugzilla: 1715507
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Olsa <jolsa@redhat.com>

Bugzilla: 1715507
https://bugzilla.redhat.com/show_bug.cgi?id=1715507

upstream
========
commit 4d0f16d059ddb91424480d88473f7392f24aebdc
Author: Arnaldo Carvalho de Melo <acme@redhat.com>
Date: Thu Dec 6 11:41:03 2018 -0300

description
===========
The strncpy() function may leave the destination string buffer
unterminated, better use strlcpy() that we have a __weak fallback
implementation for systems without it.

In this case we are actually setting the null byte at the right place,
but since we pass the buffer size as the limit to strncpy() and not
it minus one, gcc ends up warning us about that, see below. So, lets
just switch to the shorter form provided by strlcpy().

This fixes this warning on an Alpine Linux Edge system with gcc 8.2:

  ui/tui/helpline.c: In function 'tui_helpline__push':
  ui/tui/helpline.c:27:2: error: 'strncpy' specified bound 512 equals destination size [-Werror=stringop-truncation]
    strncpy(ui_helpline__current, msg, sz)[sz - 1] = '\0';
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Fixes: e6e904687949 ("perf ui: Introduce struct ui_helpline")
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>