[sound] ALSA: ASoC: wcd9335: Fix missing regmap requirement
Message-id: <15580872947136052-1901-patchset-jkysela@redhat.com>
Patchwork-id: 258557
O-Subject: [RHEL 8.1 PATCH 1900/2119] ALSA: ASoC: wcd9335: Fix missing regmap requirement
Bugzilla: 1683051
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

wcd9335.c: undefined reference to 'devm_regmap_add_irq_chip'

Signed-off-by: Marc Gonzalez <marc.w.gonzalez@free.fr>
Signed-off-by: Mark Brown <broonie@kernel.org>

Signed-off-by: Jaroslav Kysela <jkysela@redhat.com>
(cherry picked from commit ac71317e6be01812cc0c54d8be6d3c1139c8380b)
Bugzilla: 1683051
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>