[netdrv] bnxt_en: avoid string overflow for record->system_name
Message-id: <20190508140250.9014-19-sxavier@redhat.com>
Patchwork-id: 254009
O-Subject: [RHEL8.1 PATCH BZ 1664477 018/107] bnxt_en: avoid string overflow for record->system_name
Bugzilla: 1664477
RH-Acked-by: John Linville <linville@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664477
Upstream: 3d46eee5a5f2f22ca04e2139e8c9a16b81d16073
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=21351388
Test: Smoke testing with traffic passed.

commit 3d46eee5a5f2f22ca04e2139e8c9a16b81d16073
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Aug 13 23:26:54 2018 +0200

    bnxt_en: avoid string overflow for record->system_name

    The utsname()->nodename string may be 64 bytes long, and it gets
    copied without the trailing nul byte into the shorter record->system_name,
    as gcc now warns:

    In file included from include/linux/bitmap.h:9,
                     from include/linux/ethtool.h:16,
                     from drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c:13:
    In function 'strncpy',
        inlined from 'bnxt_fill_coredump_record' at drivers/net/ethernet/broadcom/bnxt/bnxt_ethtool.c:2863:2:
    include/linux/string.h:254:9: error: '__builtin_strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]

    Using strlcpy() at least avoids overflowing the destination buffer
    and adds proper nul-termination. It may still truncate long names
    though, which probably can't be solved here.

    Fixes: 6c5657d085ae ("bnxt_en: Add support for ethtool get dump.")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Michael Chan <michael.chan@broadcom.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Selvin Xavier <sxavier@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>