[netdrv] net/mlx5e: E-Switch, Add peer miss rules
Message-id: <20190611125818.20321-124-ahleihel@redhat.com>
Patchwork-id: 264766
O-Subject: [RHEL8.1 BZ 1691236 v2 123/238] net/mlx5e: E-Switch, Add peer miss rules
Bugzilla: 1691236 1663230 1663207
RH-Acked-by: Kamal Heib <kheib@redhat.com>
RH-Acked-by: Don Dutile <ddutile@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Tony Camuso <tcamuso@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1691236
Bugzilla: http://bugzilla.redhat.com/1663207
Bugzilla: http://bugzilla.redhat.com/1663230
Upstream: v5.0-rc1
Conflicts:
 - drivers/net/ethernet/mellanox/mlx5/core/eswitch_offloads.c:
   Saw same compilation error as in upstream when HEAD points to this patch:
   drivers/net/ethernet/mellanox/mlx5/core/eswitch_offloads.c:566:13: error: ‘struct <anonymous>’ has no member named ‘vhca_id_valid’
   So, in order to fix incremental build, I took a hunk from commit:
   04de7dda7394 ("net/mlx5e: Infrastructure for duplicated offloading of TC flows")
   --> vhca_id_valid was replaced by flags.

commit ac004b8321281b9da7d9a99674241e60e49ffc8a
Author: Roi Dayan <roid@mellanox.com>
Date:   Sun Nov 11 17:50:16 2018 +0200

    net/mlx5e: E-Switch, Add peer miss rules

    In the sriov offloads mode, packets that are not matched by any
    other rule are sent towards the e-switch vport manager for further
    processing.

    Under upcoming patches (e.g for uplink LAG), packets sent from VF
    vports belonging to esw0 (e-switch related to PF0) might end up in
    esw1 (e-switch related to PF1) due to muxing logic applied by the
    FW.

    In such a case we still want the missed packet to be sent to the
    "base" esw manager vport in order to present the control plane a
    consistent view of the source (VF reresentor) port.

    Signed-off-by: Roi Dayan <roid@mellanox.com>
    Signed-off-by: Aviv Heller <avivh@mellanox.com>
    Signed-off-by: Shahar Klein <shahark@mellanox.com>
    Signed-off-by: Saeed Mahameed <saeedm@mellanox.com>

Signed-off-by: Alaa Hleihel <ahleihel@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>