ath11k: fix link error when CONFIG_REMOTEPROC is disabled
Bugzilla: http://bugzilla.redhat.com/1937053

commit 5c0ec012ca7f7771f4a2dc9e41333411dd2693bc
Author: Kalle Valo <kvalo@codeaurora.org>
Date:   Thu Sep 10 07:20:59 2020 +0000

    ath11k: fix link error when CONFIG_REMOTEPROC is disabled

    If CONFIG_REMOTEPROC was disabled the linking failed with:

    ERROR: modpost: "rproc_get_by_phandle" [drivers/net/wireless/ath/ath11k/ath11k.ko] undefined!

    Compile tested only.

    Reported-by: Randy Dunlap <rdunlap@infradead.org>
    Fixes: 1ff8ed786d5d ("ath11k: use remoteproc only with AHB devices")
    Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
    Link: https://lore.kernel.org/r/0101017476e38f40-c4168ac4-c00a-4220-a032-fe17e4a157cb-000000@us-west-2.amazonses.com

Signed-off-by: Jarod Wilson <jarod@redhat.com>