[net] netfilter: nat: fix icmp id randomization
Message-id: <20200605143206.24398-10-fwestpha@redhat.com>
Patchwork-id: 317509
Patchwork-instance: patchwork
O-Subject: [RHEL8.3 net 09/48] netfilter: nat: fix icmp id randomization
Bugzilla: 1579145
RH-Acked-by: Marcelo Leitner <mleitner@redhat.com>
RH-Acked-by: Ivan Vecera <ivecera@redhat.com>
RH-Acked-by: Guillaume Nault <gnault@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1579145
Upstream Status: commit 5bdac418f33f

commit 5bdac418f33f60b07a34e01e722889140ee8fac9
Author: Florian Westphal <fw@strlen.de>
Date:   Tue Apr 9 14:45:20 2019 +0200

    netfilter: nat: fix icmp id randomization

    Sven Auhagen reported that a 2nd ping request will fail if 'fully-random'
    mode is used.

    Reason is that if no proto information is given, min/max are both 0,
    so we set the icmp id to 0 instead of chosing a random value between
    0 and 65535.

    Update test case as well to catch this, without fix this yields:
    [..]
    ERROR: cannot ping ns1 from ns2 with ip masquerade fully-random (attempt 2)
    ERROR: cannot ping ns1 from ns2 with ipv6 masquerade fully-random (attempt 2)

    ... becaus 2nd ping clashes with existing 'id 0' icmp conntrack and gets
    dropped.

    Fixes: 203f2e78200c27e ("netfilter: nat: remove l4proto->unique_tuple")
    Reported-by: Sven Auhagen <sven.auhagen@voleatech.de>
    Signed-off-by: Florian Westphal <fw@strlen.de>
    Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>

Signed-off-by: Florian Westphal <fwestpha@redhat.com>
Signed-off-by: Timothy Redaelli <tredaelli@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>